### ISSUE TITLE
[誠徵] 不血汗之嗡嗡嗡前端工程師

### ISSUE THREAD

**Issue by amouro** [f2etw/jobs#1]
## 應徵條件：
1. 熟悉 HTML / CSS / jQuery / Javascript 等網頁技術，且具網頁跨瀏覽器相容性開發能力
2. 具 SCSS / SASS 經驗

## 加分條件:
1. 具 Git 使用經驗
2. 具 RWD 實作經驗
3. 使用過PHP框架：Smarty, Twig, Liquid 等等
4. 流利的英語溝通能力

## About Us  - 賦格創意
* 主要服務：提供包含規劃、設計、前端、乃至於平台網站整合開發服務。
* 服務對象：除國內企業與非營利團體外，目前客戶也遍及世界各地，包含巴西、澳洲及美國等地。
One Company, One Family：我們的規模很小，所以我們很挑。我們不一定在意你的過去 (學歷、背景或做過什麼偉大的專案)，但我們很在意你的現在 (是不是與我們志同道合)以及你的未來 (是不是願意與我們一起開創更寬廣的世界)。正因為小，我們希望找到正直、忠誠、像家人一樣的夥伴，一起航向偉大的航道。
* 夥伴待遇：NT$ 40,000 ~ NT$ 70,000，這是我們現在可以提供的薪資範圍，但絕對不是未來的薪資上限!
* 夥伴福利："Work Smart, Play Hard"，因此我們極少下班時間到了還要大家嗡嗡嗡；三不五時來份下午茶，偶爾一起聚聚餐，我們更愛驚喜慶生嚇嚇又老一歲的壽星；一年7天休假不嫌少，多個幾天特休剛剛好。
* 休假日數：優於勞基法規定 7 天
* 公司地點：台北市重慶北路一段 （近台北車站、中山捷運站）

## Apply Information
請將你的過去(履歷、作品集等)寄至：design[at]laconique.com.tw 
並於主旨註明應徵的職務名稱。

**Comment by tesshsu** [comment]
Looks attractive!!

**Comment by amouro** [comment]
@yutin1987 裡面本來有寫到休假了，補上一條專門說明好了。
另，目前暫時關閉職缺

**Comment by yutin1987** [comment]
感謝^^
