### ISSUE TITLE
[外商] 樂天市場亞洲區開發職缺 - 前端工程師 Front End Engineer

### ISSUE THREAD

**Issue by jaydenlin** [f2etw/jobs#10]
1.基於Rakuten Global E-Commerce Platform開發新服務，提供未來亞洲區各國(新加坡，印尼，馬來西亞，泰國等等)使用
2.設計與開發具彈性且可擴充的前端頁面元件，供Desktop以及Mobile使用
3.自動化部署與測試(Unit test, Functional test, Integration Test)
4.此工作職缺為跨團隊、跨國合作機會，適合想挑戰自我能力與未來發展機會，參與樂天全球化的腳步一起邁向世界！

月薪 5萬元 至 6萬元起  (強者薪資不在此限！歡迎大家前來挑戰！)
* 年終+績效獎金: 2月(視情況調整)

上班地點：
台北市中山區民生東路三段49號11樓

基本條件:
1. 熟悉JavaScript 物件導向開發
2. 具有一年以上前端開發經驗
3. 具有前端頁面效能調校能力
4. 有主動學習的熱忱與問題解決能力。
5. 願意接受挑戰及跨國專案系統開發。

加分條件:
1. 使用JavaScript Framework開發經驗(例如React.js , Ext.js , Backbone.js , Angular.js ) 
2. 串接API JSON資料於網頁呈現開發經驗
3. React.js開發經驗尤佳
4. 熟悉自動化測試(Mocha, Jasmine)
5. 熟悉Node.js
6. 使用 SASS/LESS 開發經驗

現場將準備小型筆試

聯絡方式：
http://www.104.com.tw/job/?jobno=38fer&jobsource=104_hotorder

**Comment by Rplus** [comment]
請問 @jaydenlin ，
這是跟 #10 不一樣的職缺嗎?

**Comment by CYBAI** [comment]
@Rplus 應該是想打 #11 ?

**Comment by jaydenlin** [comment]
@Rplus 您好，是不一樣職等的職缺．
另一個是Senior的職缺．想請問一下有需要合併開在一起嗎？

**Comment by appleboy** [comment]
@Rplus 可以用標籤區隔 ...

**Comment by Rplus** [comment]
@CYBAI 
哈  切分頁切到忘記是哪一頁了 :p 
已修改

@appleboy 
目前有在考慮多加幾個 label 來增加分類的便利性
不過還在確認要擺哪些 label
前輩有建議的種類嗎？

**Comment by appleboy** [comment]
@Rplus 我看 @jaydenlin  說是不一樣職等的缺，乾脆用兩個 Label 來代表 Senior or Junior?這樣使用者進來大致上也可以知道自己需要找資深或資淺工作了。

**Comment by Rplus** [comment]
@appleboy
目前想說針對 senior 再加註，
這樣應該能達到區分較進階的職缺訊息~

**Comment by appleboy** [comment]
@Rplus :+1:

**Comment by jf423** [comment]
請問還有junior的職缺嗎？

**Comment by jaydenlin** [comment]
Hi @jf423,
Please see the new job opening here.
https://github.com/f2etw/jobs/issues/105
