### ISSUE TITLE
【徵才】可在家遠程辦公資深主程級Go開發工程師 （15-20萬新台幣月薪+獎金）

### ISSUE THREAD

**Issue by wlinna22** [f2etw/jobs#1019]
聯絡方式：
人資部LINE ID：lina663
人資部Telegram：@w4262

團隊簡介：
我們是一家經營區塊鏈、棋牌等各類遊戲開發等發展包網集團，目前為行業知名獨角獸企業，亞洲頂尖區塊鏈及遊戲研發包網公司，產業鏈遍佈全球。
目前研發中心在於新加坡及大馬KLCC，集團總部命名大樓位於首爾市中心核心位置。

工作地點：
星加坡或大馬KLCC（目前公司政策可選擇在台居家遠程辦公）

工作內容：
1、負責GRPC和大廳業務；
2、負責需求評審、大廳框架搭建、規劃和設計；負責解決方案、架構優化方案；
3、負責代碼編寫、規範和標準設定；
4、負責大數據、高並發、高承載設計；
5、負責棋牌遊戲、休閑遊戲維護叠代升級
6、負責公司後端架構的搭建和優化，持續優化服務的可用性、伸縮性、穩定性；

能力需求：
精通遊戲服務器邏輯框架、系統架構、腳本引擎、內存管理、性能分析、測試、安全性等技術？
有RPC服務器開發經驗
有GRPC和大廳業務經驗
1、精通Golang語言，五年以上golang經驗，其中2年架構經驗；
2、精通數據結構和算法，深入理解多線程、net/http等相關技術；
3、具備良好的編碼習慣，結構清晰，命名規範，邏輯性強，代碼冗余率低；
4、精通Golang常用框架，深入了解框架提供的特性及其實現原理細節；
5、有大規模分布式系統的設計和開發經驗，能獨立完成系統的設計及開發；
6、精通MySQL數據庫，熟練MySQL索引優化、查詢優化的能力；
7、精通多種非關系型數據庫，如Redis, Mencached，理解其使用場景及限製；
8、精通分布式系統，掌握多種服務框架和消息中間件，了解其實現原理；
9、精通Internet常用協議，如HTTP、TCP/IP和RESTful、RESTAPI規範；
10、精通Golang微服務、Docker部署、有RPC服務器開發經驗；
11、精通遊戲服務器邏輯框架、系統架構、腳本引擎、內存管理、性能分析、測試、安全性等技

薪資範圍：
15-20萬新台幣月薪+獎金

工時/特休：
8小時、大小休6.5天

福利/推薦項：
每月固定職位補貼、每月獎金池獎金、年終獎、節假日紅包、面試補貼等

**Comment by Vdragon** [comment]
**注意：** 此份以及其他由相同帳號發布的相關職缺被發現於 Telegram 非關主題群組大量違規投放廣告，請求職人注意相關職缺的合法性！

![證據截圖](https://user-images.githubusercontent.com/1192163/206259198-a98b8d5c-cf7b-46e4-9218-20aca16ee92d.png "證據截圖")

**Comment by wlinna22** [comment]
投放廣告宣傳企業很正常！Telegram社群有機器人檢測刪廣告大家都是知道，何必在這妖言惑眾說我們不合法？我們20年行業大公司

**Comment by Jacky-lctech** [comment]
這不是前端職缺
