### ISSUE TITLE
【徵才】Bindo POS - 前端工程師

### ISSUE THREAD

**Issue by mrjumpy** [f2etw/jobs#102]
## 團隊簡介/地點
https://bindopos.com/zh-tw/
Based on Hong Kong/Taiwan, Bindo is the one-stop retail solution for local retailers. Our iPad/iPhone point-of-sale (POS) system makes it incredibly easy for merchants to add and manage inventory in the cloud, enabling in-store purchases to be processed with greater efficiency and speed.
工作地點：捷運忠孝復興站SOGO附近

## 工作內容
We are looking for an outstanding Front-end developer to join web app team to lead the development of high performing, modular and pixel perfect web applications. As a senior FED in our team you will work closely with product managers and web designer to build our high end web applications that are used by our customer.

## 能力需求
- Experience developing rich, large-scale web applications.
- Knowledge of JavaScript design patterns.
- Proficient knowledge in front-end design patterns.
- Experience with modern front-end technologies like Angular, React or ES2015.
- Familiar with modern development tools including SASS/LESS, Grunt/Gulp, Bower, Npm.
- Experience working with RESTful web services and other API's.

### 加分
- Experience with front-end unit testing frameworks

## 薪資範圍
60K~100K+
12 month

## 工時/特休
- 9 AM ~ 6 PM
- 10 days Annual leave

## 福利/推薦項
- Modern software development environment
- Open mind to new technologies.
- Develop product, not client work.

## 聯絡方式
will.you@antcosa.com

**Comment by Clementtang** [comment]
wow 關注一陣子沒想到來台灣徵才了 :P

**Comment by mrjumpy** [comment]
昨天的mail怪怪的，換了一個
如果已經send的再麻煩了

**Comment by Shyam-Chen** [comment]
:+1:

**Comment by winwu** [comment]
請問 有找到人了嗎 ?

**Comment by Rplus** [comment]
@mrjumpy ，請問是已徵得嗎？還是僅職缺關閉？

**Comment by mrjumpy** [comment]
@Rplus 職缺關閉

**Comment by Rplus** [comment]
@mrjumpy 如果是已徵得，會幫忙加另外的 label
：)
