### ISSUE TITLE
【徵才】可在家遠程辦公資深DBA資料庫管理工程師 （20-25萬新台幣月薪+獎金）

### ISSUE THREAD

**Issue by wlinna22** [f2etw/jobs#1020]
聯絡方式：
人資部LINE ID：lina663
人資部Telegram：@w4262

薪資範圍：
20-25萬新台幣月薪+獎金

工作地點：
星加坡或大馬KLCC（目前公司政策可選擇在台居家遠程辦公）

公司簡介：
我們是一家經營區塊鏈、棋牌等各類遊戲開發等發展包網集團，目前為行業知名獨角獸企業，亞洲頂尖區塊鏈及遊戲研發包網公司，產業鏈遍佈全球。
目前研發中心在於新加坡及大馬KLCC，集團總部命名大樓位於首爾市中心核心位置。

工作內容：

1、負責管理和維護MySQL、Mongo、Redis、ES、Tidb數據庫實例；
2、設計和開發數據庫運維管理工具、製定緩存系統的使用方案；
3、持續改進數據庫和緩存系統方案，保障數據庫的可靠、穩定、高效地運行。
4、處理數據庫的日常維護工作，及出現重大問題時的應急恢復；
5、提供數據庫開發支持，根據業務需求進行索引優化和調優 
6、定期進行系統的健康檢查，並對性能問題進行定位和排查。
7、配合開發同事完成數據庫一系列優化工作。
8、熟練執行數據庫性能調優、監控、備份、異常處理、故障恢復 
9、熟悉數據庫的高可用和動態擴展方案 
10、能提供良好的讀寫分離方案（IO讀/寫）

能力需求：

✅ 熟悉MySQL架構 & 了解MySQL數據庫基礎知識
✅ 熟悉Redis、MongoDB, Elasticsearch管理，數據備份，優化
✅ 有NoSQL的管理、優化經驗
✅ 需要ES、TiDB經驗
✅ 熟練使用Shell、Python腳本編寫工具
✅ 熟悉Zabbix監控系統
✅ 了解Archery

1、5年以上Linux平臺數據庫管理經驗；
2、從事Mysql技術方面的支持和維護實際工作經驗在5年以上；
3、精通MySQL管理，數據備份，優化；
4、有NoSQL的管理、優化經驗, 熟悉Redis、MongoDB, Elasticsearch管理，數據備份，優化；
5、精通MySQL數據庫引擎原理，深入理解數據庫引擎的實現機製，能根據相關機製優化數據庫；
6、善於學習總結，關註數據庫技術發展，了解新技術；
7、具備較強的責任心，良好的溝通能力，積極分享，帶頭提升整個團隊的技術水平；
8、接觸過千萬級數據庫的處理經驗
9、有災難性故障處理經驗
10、熟悉Tidb實例管理，備份與優化的優先

工時/特休：
8小時、大小休6.5天

福利/推薦項：
每月固定職位補貼、每月獎金池獎金、年終獎、節假日紅包、面試補貼等

**Comment by Vdragon** [comment]
**注意：** 此份以及其他由相同帳號發布的相關職缺被發現於 Telegram 非關主題群組大量違規投放廣告，請求職人注意相關職缺的合法性！

![證據截圖](https://user-images.githubusercontent.com/1192163/206259198-a98b8d5c-cf7b-46e4-9218-20aca16ee92d.png "證據截圖")
