### ISSUE TITLE
【远程】可在家办公资深DBA数据库管理工程师 （35-60+奖金,可在谈）

### ISSUE THREAD

**Issue by wlinna22** [f2etw/jobs#1021]
联系方式：
人事部Telegram：@w4262
人事部LINE ID：lina663

薪资范围：
35-50K人民币+奖金（可在谈）

工作地点：
新加坡或大马KLCC（目前公司政策可选择在台居家远程办公）

公司简介：
我们是一家主营区块链、棋牌等各类游戏开发等发展包网集团，目前为行业知名独角兽企业，亚洲顶尖区块链及游戏研发包网公司，产业链遍佈全球。
目前研发中心在于新加坡及大马KLCC，集团总部命名大楼位于首尔市中心核心位置。

工作内容：

1、负责管理和维护MySQL、Mongo、Redis、ES、Tidb数据库实例；
2、设计和开发数据库运维管理工具、制定缓存系统的使用方案；
3、持续改进数据库和缓存系统方案，保障数据库的可靠、稳定、高效地运行。
4、处理数据库的日常维护工作，及出现重大问题时的应急恢复；
5、提供数据库开发支持，根据业务需求进行索引优化和调优 
6、定期进行系统的健康检查，并对性能问题进行定位和排查。
7、配合开发同事完成数据库一系列优化工作。
8、熟练执行数据库性能调优、监控、备份、异常处理、故障恢复 
9、熟悉数据库的高可用和动态扩展方案 
10、能提供良好的读写分离方案（IO读/写）

能力需求：

✅ 熟悉MySQL架构 & 了解MySQL数据库基础知识
✅ 熟悉Redis、MongoDB, Elasticsearch管理，数据备份，优化
✅ 有NoSQL的管理、优化经验
✅ 需要ES、TiDB经验
✅ 熟练使用Shell、Python脚本编写工具
✅ 熟悉Zabbix监控系统
✅ 了解Archery

1、5年以上Linux平台数据库管理经验；
2、从事Mysql技术方面的支持和维护实际工作经验在5年以上；
3、精通MySQL管理，数据备份，优化；
4、有NoSQL的管理、优化经验, 熟悉Redis、MongoDB, Elasticsearch管理，数据备份，优化；
5、精通MySQL数据库引擎原理，深入理解数据库引擎的实现机制，能根据相关机制优化数据库；
6、善于学习总结，关注数据库技术发展，了解新技术；
7、具备较强的责任心，良好的沟通能力，积极分享，带头提升整个团队的技术水平；
8、接触过千万级数据库的处理经验
9、有灾难性故障处理经验
10、熟悉Tidb实例管理，备份与优化的优先

工时/特休：
8小时、大小休6.5天

福利/推荐项：
每月固定职位补贴、每月奖金池奖金、年终奖、节假日红包、面试补贴等

**Comment by Vdragon** [comment]
**注意：** 此份以及其他由相同帳號發布的相關職缺被發現於 Telegram 非關主題群組大量違規投放廣告，請求職人注意相關職缺的合法性！

![證據截圖](https://user-images.githubusercontent.com/1192163/206259198-a98b8d5c-cf7b-46e4-9218-20aca16ee92d.png "證據截圖")
