### ISSUE TITLE
【徵才】產品經理 負責APP直播項目,有過博弈經驗不排擠

### ISSUE THREAD

**Issue by wlinna22** [f2etw/jobs#1025]
聯絡方式：
人資部LINE ID：lina663
人資部Telegram：@w4262

薪資範圍：
12-15萬新台幣月薪+獎金（可在談）

工時/特休：
工時8小時、月休八天+台灣假期

福利/推薦項：
每季度項目盈利獎金、固定13薪起、年終獎、節假日紅包、面試補貼等

公司簡介：
我們是一家主營區塊鏈、遊戲等各類等各類程式開發台資控股集團，目前為行業知名老牌獨角獸企業，亞洲頂尖區塊鏈及遊戲研發公司，產業鏈遍佈台灣、歐洲、北美、新馬泰、菲律賓等國，也是全球首家擁有合法博弈牌照經營公司。20年的發展我們堅信能夠在行業越做越強！

工作地點：
歐美、新加坡、台灣、菲律賓（目前職位為菲律賓公司需求）

工作內容：
1、負責平台整體產品規劃
2、與運營和技術溝通跟進並把控整體項目進度
3、理解產品和交互設計<熟悉原則及合理性>
4、負責具有高易用性設計、易維護性的自動化測試框架
5、具有綜合型遊戲產業經驗

崗位需求：
1、熟悉使用Axure設計
2、有較豐富APP產品經驗可優先考慮
3、善於溝通協作，邏輯性強，有大局觀的同時關註細節
4、優秀的結構化思維和抽象能力,從實際業務場景歸納分析並解決問題
5、熟悉HTTP,MYSQL,LINUX及使用經驗可優先考慮

加分條件：
1、對於python語言能運用以及有基礎的代碼能力可優先考慮
2、熟悉HTTP,MYSQL,LINUX及使用經驗可優先考慮"

**Comment by Vdragon** [comment]
**注意：** 此份以及其他由相同帳號發布的相關職缺被發現於 Telegram 非關主題群組大量違規投放廣告，請求職人注意相關職缺的合法性！

![證據截圖](https://user-images.githubusercontent.com/1192163/206259198-a98b8d5c-cf7b-46e4-9218-20aca16ee92d.png "證據截圖")
