### ISSUE TITLE
【聘棋牌市场经理】老牌双休台资 50-100K底薪人民币可在谈,接受第三国到菲

### ISSUE THREAD

**Issue by wlinna22** [f2etw/jobs#1026]
有兴趣联系人事部Telegram：@w4262

ＪＤ如下：
"岗位职责：
1、 承担公司业绩目标，并为实现业绩目标提供可行性策略；
2、分析市场需求，依据公司品牌和产品特点，制定短中长期营销计划，落实市场营销工作；
3、线上整体营销活动的策划与组织实施，精通互联网产品、模式和营销方法，对网络产品策划、推广、运营流程有深入了解和成功实践经验；
4、市场营销数据的整理、分析，品牌推广及营销活动的效果监控；
5、负责口碑营销推广工作，保证口碑推广的有效执行；
6、公司网站品牌宣传与有效推广；
7、市场营销部日常管理工作，制定相关的管理制度与工作规范。

岗位要求：
1、统招专科以上学历市场营销、电子商务、信息管理等相关专业。
2、对互联网市场具有敏感洞察力和良好的商业理念，有丰富的市场营销、互联网营销策划经验，有一定的网络及媒体资源；
3、熟悉品牌运作机理，有深厚的文案策划功底，极强的策划创意能力，全面的组织协调管理能力 ；
4、具有较强的团队管理能力、人际沟通协调能力、计划与执行能力；
5、有迎接各种业务挑战和压力的心理承受能力；
6、认同公司企业文化，高度的敬业精神和职业道德操守；"

**Comment by Vdragon** [comment]
**注意：** 此份以及其他由相同帳號發布的相關職缺被發現於 Telegram 非關主題群組大量違規投放廣告，請求職人注意相關職缺的合法性！

![證據截圖](https://user-images.githubusercontent.com/1192163/206259198-a98b8d5c-cf7b-46e4-9218-20aca16ee92d.png "證據截圖")
