### ISSUE TITLE
【遠端／前端】甜甜外商公司徵才－Vue

### ISSUE THREAD

**Issue by mini79103** [f2etw/jobs#1031]
## 團隊簡介/地點

總公司在泰國，在台灣建置團隊，所以你的同事都是台灣人
分工細，不監控
線上打卡報到
任務結束就不干涉，自由度高
需要自律且有責任心的人

## 能力需求
1. 有多年 vue 開發經驗
2. 有 React 專案維護經驗
3. 前端效能優化經驗
4. 具備後端JAVA經驗佳
5. 至少需要具備2年彩票的經驗

## 薪資範圍

80-110K

## 工時/特休

國定假日休(見紅休)
09:00 - 18:00

## 福利/推薦項

13薪/三節獎金/季獎金

## 聯絡方式

LINE ID ：wealthy0016
Telegram：@wealthy_0016
Linkedln：https://www.linkedin.com/in/winnie-chen-540674244/

**Comment by Rplus** [comment]
dup. with #1029
