### ISSUE TITLE
【遠程職位】【資深前端工程師】

### ISSUE THREAD

**Issue by SSU-HAN** [f2etw/jobs#1033]
## 工作內容
職位描述:
1.在工作中具有主動性，具備快速開發效率，並勇於承擔任務，具備團隊合作
精神。
3.精通 HTML5、CSS3，JavaScript 等前端技術，熟悉常用資料結構、演算法、
設計模式，具有良好的編碼風格。
4.精通 React 或 Vue.js 等主流開發框架。
5.熟悉基本的電腦網路概念，熟悉 HTTP/HTTPS 協定及其他 Web 標準規範。
6.對 web 前端的效能優化以及 web 常見漏洞有一定的理解和相關實踐。
7.較強的邏輯思維能力，較高的學習意願與自驅力，英語良好者優先，抗壓性
高，願意一起開創，一起收穫未來。
8.有獨當一面的開發能力，帶領團隊能力; 過去的專案請提前分享。

## 能力需求
任職要求：：
1. 有 5 年以上經驗。
2. 須提供相關作品供參考。
3. 必須能中文流利溝通

### 加分
英語流利加分

## 薪資範圍
面議

## 工時/特休
早九晚六, 按照所在國家時區工作及休假

## 聯絡方式
Line : ringle869
Telegram : @Han869 
Skype : live:.cid.3f9db9ac54272104

**Comment by regchiu** [comment]
不好意思，為什麼要在 38 歲以內呢？ 🤔

**Comment by dca** [comment]
性別及年齡限制，不符合台灣當地法規
