### ISSUE TITLE
【遠端／台中】Cloud Latitude Software／夢幻體育／資深遊戲系統前端工程師 | Senior Front-End Developer |

### ISSUE THREAD

**Issue by sharlenechou** [f2etw/jobs#1036]
**大家好，我們是Cloud Latitude Software緯雲，我們立志於實踐軟體技術及創造更優質的夢幻體育遊戲。**

在2023年，緯雲持續進行組織擴編！我們的遠端團隊及辦公室團隊現正如火如荼招募中，您可以選擇加入您所習慣的工作模式團隊。而在2023下半年我們將遷移至新辦公室，讓同仁能夠享受更加優質的工作環境。（別擔心！遠端團隊將不受影響）
​
若您對於軟體工程充滿熱情，並且有志在提升職涯里程碑，都歡迎您成為團隊一份子！

​
## 【招募職缺】

- 資深遊戲系統前端工程師－遠端團隊 x 2名
- 資深遊戲系統前端工程師－辦公室團隊(台中市西區) x 1名
​
## 【職務內容】

- 設計與撰寫遊戲網頁（含單元測試）
- 串接後端 API
- Code Review 同事的程式
- 自動化部署與維護

## 【職務要求】
Must Have

- 三年以上軟體開發經驗
- 熟悉 VueJS、ReactJS、AngularJS 任一框架（目前產品使用ReactJS，歡迎到職後學習！）
- 了解版控工具，如 Git

Nice to Have

- 有單元測試經驗
- 使用過 Docker 與 CI/CD工具

​
## 【薪資待遇】
辦公室團隊及遠端團隊略有不同，但不變的是我們追求公平性及更優質的員工福利！

辦公室團隊－
- 薪資：65~80K/Month（另有三節、分紅及績效獎金，共14個月）。
- 福利：享有辦公室團隊完整福利（參照104頁面）。
- 保障：皆有完整符合薪資級距之勞健保及勞退保障。
- 軟硬體設備：由公司發放軟硬體設備(Macbook Pro + 23”螢幕 + JetBrains all products pack)。

​
遠端團隊－
- 薪資：70~85K/Month（另有三節、分紅及績效獎金，共14個月）。
- 福利：此為遠端工作package，故福利部分將計算至每月月薪內加成10%。
- 保障：皆有完整符合薪資級距之勞健保及勞退保障。
- 軟硬體設備：到職第一個月提供硬體設備補助(65,000元)，及每年度JetBrains all products pack軟體補助(8,000元)。

​
## 【了解我們】
公司網站：[https://www.cloud-latitude.com/](https://www.cloud-latitude.com/?fbclid=IwAR0P11k6FlyF3buJvBSf1Hmdhrm30pHsfcnoJJDJVA6_7L1Dbcuh-aKWB5E)
LinkedIn：[https://www.linkedin.com/company/cloudlatitudesoftware/](https://www.linkedin.com/company/cloudlatitudesoftware/?fbclid=IwAR13M27ZtDbjXpMH-W1wJZkgqjqNtvt2MhrFUdRxvx6bZb6TmG8-d5ozXtg)
104招募頁面：[https://www.104.com.tw/company/1a2x6blkuu](https://www.104.com.tw/company/1a2x6blkuu?fbclid=IwAR0GcMRnqHUGToHLuP2WFU1zMzw9Z3hPzWSh0ihmScnAvKzxilHcCQP28gQ)
​
​
**若有興趣或想了解更多，請直接私訊或寄送至sharlene@cloud-latitude.com，將竭誠為您回答😄**

**Comment by lu7766lu7766** [comment]
請問遠端團隊還有在徵人嗎？我在104上面沒有看到
