### ISSUE TITLE
【徵才】Fliegen – 前後端工程師

### ISSUE THREAD

**Issue by amouro** [f2etw/jobs#104]
## 團隊簡介/地點
![Fliegen Logo](https://www.fliegen.com.tw/sites/default/files/logo_h2x.png)
賦格創意科技是富有設計背景的內容網站開發公司，自 2010 年起為海內外客戶開發了多個網站與服務。
在業務發展之餘，亦支持開源軟體，鼓勵工作夥伴參加社群活動，貢獻開源程式。

公司地點位於台北市重慶南路一段，鄰近北門站與寧夏夜市

## 工作職缺
- Jr. / Sr. PHP Developer
- Jr. / Sr. Front-end Developer

## 工作內容及能力需求

> Full Job Description is also available in English at [Fliegen Career](https://www.fliegen.com.tw/career)

#### PHP 工程師、資深 PHP 工程師

我們正在尋找有效率、自我要求、視程式開發為工藝的 PHP 工程師！您將和我們的團隊從設計討論、程式開發到部署上線等階段，一起參與網站開發。

- 職責
    - 負責各系列網站後端模組開發與維護
    - 與前端溝通並提供支援
    - 解決問題、測試以及維護產品網站及資料庫，確保功能與效能最佳化

- 條件
    - 具有 PHP 開發經驗
    - 專精 OOP 程式設計
    - 具一種或以上的 PHP Framework 的開發經驗，如 Symphony 、 Lavarel
    - 熟悉 Composer
    - 瞭解 GIT 版本控制工具
    - 具 Scrum 經驗
    - 使用外部 APIs 開發之經驗，如 Google, Facebook, Paypal 等
    - 追求優良的程式碼，勇於提出各種大膽想法

> 應徵者至少須符合上述三項以上的條件；
> 應徵資深後端 PHP 工程師者，歡迎提出更多或未列於條件中的相關經驗與證明

````
````
#### 前端工程師、資深前端工程師

我們正在徵求前端工程師，將負責網站開發、執行創新設計以及網站版型製作 您將和我們的團隊從設計討論、程式開發到部署上線等階段，一起參與網站開發。

- 職責
    - 使用標準 HTML/CSS 開發網站版面與使用者介面
    - 整合並呈現來自後端或第三方提供 APIs 資料
    - 與設計師及後端工程師一同解決問題，滿足產品網站前端需求

- 條件
    - 對於 HTML/CSS 有深入了解
    - 專精 JavaScript 及瞭解至少一項其他 JS library，如 jQuery、AngularJS, ReactJS 等
    - 瞭解 GIT 版本控制工具
    - 熟悉且有能力解決瀏覽器相容問題，尤其是行動瀏覽器
    - 瞭解一種版型語法，如 Liquid 、 Twig 或 Nunjucks
    - 瞭解 RESTful 及 HTML5 API
    - 具 Scrum 經驗
    - 追求優良的程式碼，勇於提出各種大膽想法

> 應徵者至少須符合上述三項以上的條件；
> 應徵資深前端工程師者，歡迎提出更多或未列於條件中的相關經驗與證明

## 薪資福利
- NT$40,000 - NT$70,000，視經驗與能力面議
- 每年保障薪資 13 個月，另視表現發放績效獎金
- 加班費依勞基法規定發放
- 工作相關之書籍/社群活動/研討會經費補助

## 休假資訊
- 優於勞基法，試用期滿即享有 7 天特休(依在職比例計算)
- 依人事行政局公告之行事曆休假，但是補班日不一定會補班!

## 聯絡方式
請連同您的履歷寄至 jobs@fliegen.com.tw 
信件主旨請載明 [ 職位名稱 ]_[ 應徵者姓名 ]

**Comment by Rplus** [comment]
恭喜搶到 104 XDD

**Comment by amouro** [comment]
寫完才發現～
下一個大概是 #123 或是 #1111 吧...

**Comment by amouro** [comment]
已結束徵才活動，感謝來投履歷的優秀工程師們
