### ISSUE TITLE
[求職][高雄/台南] Jr. Vue 前端工程師

### ISSUE THREAD

**Issue by Linlaose** [f2etw/jobs#1045]
## 簡歷

工作經歷 3 年，學習前端程式設計已有 1 年，因前產業發展較為侷限，進而積極思考其他職涯發展，隨後在嘗試前端開發後得到許多成就感，便自發性尋找更多學習資源並持續投入前端開發的領域。

擅長使用 Vue 作為前端開發框架，作品為自行發想至開發完成。
具備自學能力並時時關注新技術與趨勢，擁有多年跨部門溝通、團隊合作及危機處理經驗，擅於審慎分析、整合資訊達成多方共識以解決問題。

### Vue.js | JavaScript
1. 使用 Vue3, Pinia, JavaScript ES6 開發 SPA。
2. 採用 SFC 方式拆分元件並確保資料架構易讀性。
3. 善用 Vee-validate 套件製作表單驗證。

### Bootstrap | Tailwind css
1. 使用 Bootstrap5 作為 CSS 框架時，會直接修改 utilities、variables 樣式。
2. 使用 Tailwind css 作為 CSS 框架時，會善用 JIT 以及修改 config 設定樣式。

### HTML5 | CSS3
1. 使用 HTML5 標準語意化的標籤。
2. 熟悉 RWD 網站建構方式，會使用 Sass/Scss ，自我要求固定的樣式排序，重視樣式的易讀性。
3. RWD 實作時，會根據設計稿提供的版型，決定要 mobile first 或 PC first。
4. 使用 Sass 時，檔案結構遵循 7-1 patterns，確保各類樣式分門別類。
5. 清楚知道 CSS weight 的問題，不輕易使用 important，重視後續維護。
6. 在不藉助 CSS 框架的情況下，可純手刻具 RWD 的版面。

### Front-end workflow
1. 使用 Git 版本管控，熟悉 branch、merge 等基本指令。
2. 使用 Source Tree 作為 Git 輔助。
3. 具使用 Gulp 前端自動化工具的經驗。
4. Vue 專案採用 Vite 進行環境建構。
5. 使用 json-server-auth 模擬資料庫，作為後端資料尚未成形時的 RESTful API 串接測試。

### RentRide - Vue 專案
發想：本身喜歡重機，又想練習 Vue3 的技術，於是開發
RentRide 租車網作品。

實踐過程
1. 題目發想
 - 以重機為思想出發點，尋找可發揮的方向。
2. Figma 繪製設計稿。
3. json-server-auth 模擬資料庫實作 JWT 會員驗證。
4. Vue-router 設定路由以及相關動態路由。
5. Pinia 狀態管理。
6. tailwindcss 搭配 daisyUI 製作 RWD 版型，GSAP、Vue-kinesis 製作網頁動態效果。
7. axios 串接模擬資料。
8. V-calendar 製作日期選擇器。
9. Vee-validate 表單、註冊驗證。
10. ESlint(Airbnb)、Prettier 程式碼風格與排版管理。
11. Render 部署模擬資料庫。

專案詳細說明請看 README
https://github.com/Linlaose/RentRide#rent-ride

### MyResume - JavaScript 專案
發想：想讓自己練習如何使用 Editor 及 Draggable，並以
cakeresume 作為範本

實踐過程
1. 題目發想
 - 思考出自己感興趣又剛好可以作為技術訓練的主題。
2. Whimsical 繪製線稿
3. 與設計師合作取得設計稿
4. json-server-auth 模擬資料庫實作 JWT 會員驗證。
5. Bootstrap5 製作 RWD 版型。
6. axios 串接模擬資料。
7. SortableJS 完成拖拉功能，搭配 TinyMCE 完善 editor。
8. html2pdf、html2canvas 實作下載履歷功能。
9. Vercel 部署模擬資料庫。

專案詳細說明請看 README
https://github.com/Linlaose/Project_MyResume#myresume

### 金艾甲鹽水雞 - 切版專案
發想：想幫助新開小吃舖的家人製作商家形象網站 。

實踐過程
1. 題目發想
 - 從身邊的題材做發想方向。
2. Whimsical 線稿繪製
 - 參考不同切版風格的網站。
3. 與設計師合作取得設計稿
 - 有問題及時提出與設計師討論。
4. tailwindcss 製作 RWD 版型。
5. axios 串接 API 實作會員註冊/登入。

專案詳細說明請看 README
https://reurl.cc/o0XpQl

## 2022 鐵人賽
2022 年 9 月，參加第 14 屆 iThome 鐵人賽

- 組成團隊 「死線衝鋒 Deadline Squad」，並為隊長，督促隊員全員完賽。
- 文章主題「【Tailwind】你聽過尾巴風嗎 ? CSS 框架 tailwind 的新手入門指南」
以 Tailwind css 為主題進行鐵人賽文章撰寫
完賽！鐵人練成

參賽目的：希望透過文章撰寫將自己已經學會的技巧再度熟悉，而自己尚未使用的技巧進行探索學習

完賽心得：透過文章的撰寫的確讓自己對於 Tailwind css 的掌握度更上一層，且發現自己尚未使用的技巧並學習吸收是非常有成就感的！
https://ithelp.ithome.com.tw/users/20152251/ironman

## 期望薪資
1. 月薪 4 萬以上

## 補充說明
1. 非本科生，自學途徑主要是線上學習平台和書籍。
2. 擅長 Vue 開發，若有需要 React 開發也非常願意學習。
3. 上述資料如有不足之處，歡迎來信或留言詢問更多，謝謝。

## 聯絡方式
aa0900144903@gmail.com
若願意詳談或給予面試機會，請以上述信箱聯絡，感謝！

## 其他
104 履歷：https://pda.104.com.tw/profile/share/8rqxmHrN1V4kwzBwbcfGrSqpLXiBIaOG

**Comment by regchiu** [comment]
嗨，提醒您，104 的連結會有有效期限，所以會過期。

**Comment by Linlaose** [comment]
> 嗨，提醒您，104 的連結會有有效期限，所以會過期。

感謝您的提醒！

**Comment by PurrgisHong** [comment]
你好，我這邊有信息給您email，您這邊如果考慮的話可以恢復一下我的信息哦

感謝
