### ISSUE TITLE
[Hiring]Fluv - Pet care platform | Software Engineering Intern

### ISSUE THREAD

**Issue by amychen99999** [f2etw/jobs#1048]
## Introduction

Fluv (毛小愛) is the top one pet sitting platform based in Taipei, Taiwan.
Our team has 14 years of professional pet sitting experience. Since 2019, 3,124
pet sitters have provided 46,945 hours of service to 90,842 users through our
platform.

Our engineering team has 17 years of professional experience and a JSDC and
COSCUP speaker. Our engineering team is distributed in Taiwan.

Our technology stack includes AWS, Docker, Firebase, Next.js, React Native,
TypeScript, etc. For more, please visit: https://stackshare.io/fluv/engineering

## Culture

We are a team full of love, very chill working environment. We encourage
everyone to express their ideas, no matter how wild the ideas are.

Fluv does not discriminate in employment on the basis of race, color, religion,
sex (including pregnancy and gender identity), political affiliation, sexual
orientation, marital status, disability, genetic information, age, membership
in an employee organization, retaliation, parental status, military service, or
other non-merit factor.

At Fluv, we commit to provide a workplace free of:

1.  Harassment, including sexual harassment
2.  Open or hidden verbal abuse (including offensive language)
3.  Hidden verbal abuse (intended to harm your reputation)
4.  Acts or deliberate inactions which demean or isolate you, or undermine you and your work
5.  Threats or intimidation
6.  Physical assault
7.  Damaging or destroying property
8.  Concealing or using a weapon

## Job Description

Most of your time will be spent on the following tasks.

1. Join our daily standup at 12:00
2. Estimate story points for tickets with engineers
3. Write and maintain documents
4. Write and maintain react components
5. Write and maintain typescript modules
6. Write unit tests
7. Write E2E tests
8. Make atomic commits into git
9. Design and implement database schema
10. Design and implement database migration
11. Review other team members’ code
12. Automate processes
13. Deploy to staging and production
14. Create demo screencasts
15. Communicated with ticket owners
16. Ask questions, small or big

## Soft Requirements

As long as you are willing to learn them, it's OK to not know all of them.

1. AWS
2. CSS
3. Docker
4. English
5. Expo
6. Git
7. GitLab
8. Firebase
9. Google Maps
10. JavaScript
11. Jest
12. Next.js
13. RWD
14. React
15. React Native
16. macOS, Linux (Any distribution) or BSD (Any distribution)
17. TypeScript
18. bash
19. sh

### Bonus

The following are technologies we plan to adopt in the future.

1. Apollo GraphQL
2. Cypress
3. Elixir
4. GraphQL
5. MariaDB/MySQL
6. MongoDB
7. Nx
8. OpenAPI/Swagger
9. PWA
10. Phoenix Framework
11. PostgreSQL
12. Redis
13. Rust
14. SEO

## Salary Range

$176 to $185 twd/hour.

## Working Hours and PTO

20 to 40 hours per week. (Work overtime needs to be approved in advance.)

PTO is identical to Labor Standards Act.

Scheduled leaves needs to be approved in advance.

## Benefit

1. A macOS laptop
2. An external monitor
3. Remote working
4. Pet friendly working space
5. Child friendly working space
6. Free healthy food
7. Nintendo Switch

## Interview Process

1. Review CV (1-2 workdays)
2. Review questionnaire (1-2 workdays)
3. Technical and HR interview (4 working hours)
4. Homework assignment based on result of 2 or 3 (7 workdays)

## Contact

1. Prepare a cover letter
2. Remove your photo from your CV (application with your photo will be rejected silently as a small test for attention to detail)
3. Send the cover letter and your CV to hiring@fluv.com
4. Subject: Fluv 2023 Engineering Intern - Your English Name (e.g. Fluv 2023 Engineering Intern - John Doe)

**Comment by rukuboy1997** [comment]
I will love to be part of this journey. I've recently applied!
