### ISSUE TITLE
【徵才】Rakuten Taiwan - Front-end Application Engineer - Mall (Junior/Senior) (Dev)

### ISSUE THREAD

**Issue by CYBAI** [f2etw/jobs#105]
## 團隊簡介/地點

身為全球電商龍頭之一, 樂天市場專注於良好系統的開發並持續改善來滿足使用者及消費者. 
我們提供穩定的系統服務 
我們持續使用新的前端及網頁相關技術來假設 實驗 驗證並且實作於我們系統之上 

We are looking for engineer candidates who can develop consumer services with flexible idea and speed. 

樂天市場 Mall 團隊的前端應用工程師負責規劃, 開發, 維護樂天市場全球 Shopping Mall 系統 
我們的主要的服務有 
1. Rakuten Ichiba Navigation (Top page, Event Page, Recommend Page, Browsing history.. etc） 
2. Item Search page 
3. Item Page 
4. Shopping cart 
5. Smart phone applications 
## 工作內容
- Shopping Mall 系統設計, 開發, 測試及品質維護 
- 前端系統設計, 開發, 測試, 改善, 維護
## 能力需求
- 有過下列任一之開發經驗： RoR , Java, PHP, Node.js 
- 有過 React JS, Angular JS 或任一 JS framework 開發經驗 
- 熟悉 HTML, CSS, JavaScript 
- 檢附英文履歷 
### 語言能力
- 商用英文溝通能力
### 加分
- TOEIC 600+ 或同等級成績證明 
- 使用過 CI 相關工具 (Jenkins, Docker) 
- 前端測試框架經驗 (Mocha, Jasmine etc.) 
- 開發及維護大型系統經驗 
## 薪資範圍

NTD. 40K ~ 80K ( Depend on skills )
## 工時/特休
- 平日平均工時8~9小時
- 趕專案時需加班，有加班費
- 週休二日
## 福利/推薦項
- 享勞健保、勞退新制退休金、團保、週休2日、優於勞基法之年假制度(到職第1年可按比例享有年假，第2年起10天)、生日假1天、年度員工健康檢查、員工教育訓練、海外進修機會、職工福利委員會福利項目(三節獎金、每季員工活動、婚喪喜慶補助)等等
- 女性生理假每年12天
## 聯絡方式

請將您的簡歷或作品資料 寄至 tw-dev-f2e@rakuten.com (English resume must attach into email)

**Comment by konekoya** [comment]
不好意思，借一下討論串
@Rplus 不知道有沒有可能加一個工作地點的Label呢？

**Comment by Rplus** [comment]
@konekoya
討論可到 gitter 唷
https://gitter.im/f2etw/jobs
> 我等下補到 README 好了

**Comment by CYBAI** [comment]
請從 [104](https://www.104.com.tw/job/?jobno=5253f&jobsource=) 投遞，謝謝。
