### ISSUE TITLE
remoted 遠端工作機會

### ISSUE THREAD

**Issue by PurrgisHong** [f2etw/jobs#1050]
提供履歷面試：
郵件：purrgis-hrd@skvip.org
賴號：PURRGIS

【IOS開發】（可遠程辦公）

薪資範圍：100K-150K 新台币（根據能力進行調整）
工作時間：9小時（包含休息時間）
月休：6天（固定週一二，大小周輪休）

崗位要求：

1、高中職畢業以上學歷，三年以上iOS手機應用實際開發經驗，熟悉iPhone各個版本之間的差異，並且能夠提供良好的解決方案，參加過完整的商業級手機應用開發項目；
2、精通iOS平台UI相關開發、Objective-C、Swift、熟悉Runtime、KVO有頁面性能優化經驗的優先；
3、精通多線程開發，消息隊列、熟悉常用的設計模式、算法和數據結構、網絡編程、SQLite編程、熟練使用WDBC進行本地消息緩存；
4、熟悉即時通訊消息機制、消息透傳、多端消息同步；
5、熟悉TCP/IP協議、熟悉HTTP/Socket工作原理，有客戶端弱網性能優化經驗的優先；
6、能夠獨立承擔任務，具備優秀的分析和解決問題能力；
7、思路清晰，喜歡思考，較強的自學能力，溝通能力，能夠指導他人工作；
8、良好的代碼習慣，對事情追求極致，熟悉git等代碼管理工具；
9、工作積極主動，有強烈的

責任感和嚴謹的工作作風，對移動產品有濃厚興趣。

-加分項:
1、有GitHub開源項目或個人技術博客；
2、有Instrument工具性能調優經驗；
3、基於Cocoapods的模塊化開發經驗；
4、對Git理解深刻，知曉git pull --rebase原理。

崗位職責:

1、負責即時通訊APP研發維護，編寫高質量的代碼；
2、根據產品需求，高質量完成iOS客戶端開發；
3、對所負責的業務模塊進行持續的性能和體驗優化。

電 - 報 頻道：@HR_PURR
聯繫方式：@HR_PURRGIS

**Comment by tix123** [comment]
要求很多錢很少，且低於台灣法定最低底薪，有違法之虞。

**Comment by PurrgisHong** [comment]
你好，是25k RMB哦， 不是新台币
