### ISSUE TITLE
【徵才】Rakuten Taiwan - Front-end Application Engineer - Internal business system (Dev)

### ISSUE THREAD

**Issue by CYBAI** [f2etw/jobs#107]
## 團隊簡介/地點
We are seeking a software engineer to build applications for business staff who manage Taiwan and Japan Rakuten Ichiba.

You will develop a front-end web application for supporting business operations (ex. Order Management, Campaign Management, Call Center, Shop Management).

Our service is based on Ruby on Rails, AngularJS, Java, MySQL, Oracle and Hadoop.
In addition, we always strive to improve our services using cutting-edge technology.
We have a front-end team to develop web-based applications and a back-end team to develop platforms using Hadoop, etc.
You will join a front-end team. There will be many chances to learn from each other.

After joining our group you will become part of a development team as a software engineer.
We will arrange for a position that best suits you based on your preferences and skills.
We have multiple locations (Taipei, Tokyo, Osaka) and work as ＂one team＂. You will get global experience.

## 工作內容
- Design, develop for, and operate a 24/7/365 system.
- Understand business needs and define the best architecture.
- Lead a team in terms of engineering and developing processes.
- Programming and development skills are also required.
- Plan and execute projects with engineers in your team and other product/project managers.

## 能力需求
- Experience in software development (Design, Development, Test, Release, Operation)
- Programming experience in one of following: RoR , Java, PHP, Node.js
- Programming experience in HTML, CSS, Javascript
- Experience in Linux or Unix
- Coordinate work flexibly with multiple stakeholders

### 語言能力
- English: Business Level

### 加分
- Experience with large-scale systems
- Experience with offshore development
- Experience with i18n system
- Experience of Engineer Leader
- Experience with Jenkins, Docker, Rundeck
- Experience with Scala

## 薪資範圍
暫定面議 (有🍌資訊時補上)

## 工時/特休
- 平日平均工時8~9小時
- 趕專案時需加班，有加班費
- 週休二日

## 福利/推薦項
- 享勞健保、勞退新制退休金、團保、週休2日、優於勞基法之年假制度(到職第1年可按比例享有年假，第2年起10天)、生日假1天、年度員工健康檢查、員工教育訓練、海外進修機會、職工福利委員會福利項目(三節獎金、每季員工活動、婚喪喜慶補助)等等
- 女性生理假每年12天

## 聯絡方式
[請至104投履歷](https://www.104.com.tw/job/?jobno=4zhlu&jobsource=)
需附英文履歷

**Comment by dylandy** [comment]
請問有研發替代役的缺嗎？

**Comment by CYBAI** [comment]
@dylandy 抱歉，目前沒有研發替代役的缺
