### ISSUE TITLE
#無限休假 #100%遠端 #在海邊上班 #前端 #全端 #每年調薪 #美商 #Fintech

### ISSUE THREAD

**Issue by ghost** [f2etw/jobs#1088]
### 公司介紹
我們是一家美商金融公司，提供房地產、保險、投資、稅務、貸款、教育等一站式全方位服務，公司穩健持續成長，即使在過去疫情期間，營運也都維持良好，反而擴大規模，目前正為未來上市準備，目前有200多位員工。由於同業競爭等原因，我們不方便公開公司名稱，面試時會告知詳情。

這是一份100%的遠端工作，工作時間與地點很有彈性，上班不用打卡，也不會像大部分遠端工作要監控員工電腦與手機狀態和位置，你可以在家、咖啡店、圖書館、山上、海邊，甚至國外上班，只要能達成工作目標都行。

### 職責
1) 新網站的前端開發
2) 現有網站的前端維護
3) 執行主管交辦與網站相關的工作

### 必備
1) 一年以上的React/Next.js或類似架構開發經驗
2) 熟悉JavaScript/CSS/HTML
3) 用過Git控管版本
4) 工作認真負責，願意積極與團隊合作、配合公司發展方向
5) 遇到問題能自主學習找到適合方案

### 加分
1) 用過Tailwind CSS或Python
2) 開發過以API與其他系統連結的程式
3) 做過後端程式設計，熟悉資料庫基本概念
4) 用過CRM或ERP系統
5) 願意學習後端FastAPI等技術，朝向Jamstack全端工程師邁進

### 勞保、健保、休假
1) 比照台灣勞基法
2) 上班時間自由分配
3) 休假日數？時間那麼自由，還希望有日數限定嗎？ :smile:

### 聯繫
[請在104寄送履歷](https://www.104.com.tw/job/7t1rm)

**Comment by ghost** [comment]
@Rplus 可否標籤加上[F] React, [F] Next.js ？香蕉資訊是什麼意思？

**Comment by Jacky-lctech** [comment]
香蕉資訊就是指薪資

**Comment by regchiu** [comment]
@cerenoD  香蕉是薪水的意思。
