### ISSUE TITLE
「求職」Rplus：Front-end Web Developer

### ISSUE THREAD

**Issue by Rplus** [f2etw/jobs#110]
## 簡介
我是 [Rplus Chen](//fb.me/RplusTW), 朋友間常用 `R+` 稱呼
喜歡在社群分享及討論前端資訊 [[1](https://www.facebook.com/groups/f2e.tw/search/?query=Rplus "go to see inteeraction of Rplus in F2ETW group")] [[2](https://twitter.com/search?f=tweets&q=%23f2etw%20from%3Arplustw "go to see tech notes in frontend from Rplus on Twitter")]
之前從 KKTIX 與 PIXNET 畢業後，目前放長假中
個性偏網路宅，不過天氣好時會出門玩玩 [POI](http://www.youtube.com/results?q=sock+poi "go to watch sock poi videos on YouTube")

## 能力
[Rplus on GitHub](https://github.com/Rplus "go to Rplus' github page")：可以直接在個人的 GitHub 上看到所有程式碼內容及撰寫風格

* 我喜歡語義化結構良好的 HTML
  > 但有些細節並沒那麼熟，所以滿喜歡去掀掀其它網站怎麼設計的 [[3](https://github.com/Rplus/rplus.github.io/issues/6 "go to see Rplus' note for input:file tag format in different websites")]

* 再套用穩健的 CSS 處理大部份的呈現
  > CSS 是我偏愛的項目，可以在 [我的 CodePen](https://codepen.io/Rplus/pens/popular/ 'go To Rplus CodePen page') 上看到平常的練習作品

* 最後寫些 JavaScript 增加元件互動性。
  > 我的 JS 能力並不算特別突出，也幾乎都沒在使用 JS Framewwork，對於 application 等級的 JS 較沒經驗；不過因為互動上的需求，對於 JS 大部份的 API 操作都還能應付

### 工具
* Sublime Text 3
* Git with command line
* 用 npm scripts / gulp 處理專案自動化流程
* OS: Xubuntu(個人用) / Windows(工作用) / Mac OS(工作用)

## 期望薪資
期望有 70w+ / year

## 聯絡方式
<Rplus.tw@gmail.com>
歡迎有志同道合的來信聊聊~ :wink:
會另外投遞履歷應徵

**Comment by floydwch** [comment]
大大是否有點破壞行情... XD

**Comment by Rplus** [comment]
@floydwch 其實我不常在外面走跳，也不知道什麼行不行情的… Orz

**Comment by floydwch** [comment]
@Rplus 這版不是經常有一堆徵人文嗎... XD

我認為你值得 100~120w+ / year

**Comment by Rplus** [comment]
@floydwch
你太看得起我了~
我 react 不會，angular 也不熟吶 
拿那麼多錢感覺要做好多事 XDD

**Comment by floydwch** [comment]
你練個一個月應該就會了... 除非你不太會寫 JS XD

**Comment by floydwch** [comment]
而且就算不拿那麼多錢，也還是有可能要做好多事的... XD

**Comment by WendellLiu** [comment]
這樣應該大家都不敢po了 XD

**Comment by Rplus** [comment]
@WendellLiu ，大家不要這樣呀呀 XDDD

**Comment by kerkerj** [comment]
大大!!!

**Comment by Rplus** [comment]
@kerkerj 我小小…

**Comment by gordenliao** [comment]
標題:大大求職，業界震撼彈!

**Comment by Daniel54088** [comment]
大大你這樣猛才開70+  我...

**Comment by justin3737** [comment]
大大... 應該100+ 以上 0.0+++

**Comment by ChenHom** [comment]
大大...我們可以理解您的想法。
但是您要為後進們想想啊~

您是有經驗的即戰力，就算有不了解也可以快速的進入狀況
而這樣的戰力只值70+...

後進們不就要....

我可以理解您謙虛的表達自己，但您的一言一行都會被拿來當標竿
提高大家的就業環境是需要大家一起努力

所以求業前，請先爬下文...!!

**Comment by Rplus** [comment]
啊… 其實我都不曉得該怎麼回了
怎麼看大家的回應都好像跟我共事過的樣子，
我沒那麼強，所以也不是過度自謙呀… XDD

還請各位夥伴，再介紹介紹相符的優質職缺！ 甘溫~ :heart:
