### ISSUE TITLE
[新竹/竹科] [月薪 10 萬起] [年薪 200 萬] 聯發科技前端工程師 (Senior and Junior)

### ISSUE THREAD

**Issue by appleboy** [f2etw/jobs#1105]
## 工作地點

新竹科學工業園區篤行一路 2 號 (聯發科總部 V 棟)

## 團隊簡介

* 聯發科技專注於使用 AI, BigData, Process Automation 技術提升公司各部門團隊生產力，及改善 IC Design Flow
* 擁抱產品及數據思維，以數據驅動產品功能之開發決策
* 以使用者故事 (user story) 作為開發依據，採用敏捷式開發 (Agile development) 快速迭代產品
* 重視團隊成員能力成長及團隊向心力，每月由不同成員定期做軟硬技術分享 (AI / BigData / Process Automation)，進而達成組織目標
* 自動化測試部署確保軟體品質及提升工作效率減少時間浪費

## 基本條件

- 熟悉 React / Angular / Vue 任一框架 (我們用 React)
- 熟悉 HTML5 / CSS3 / ES6+
- 熟悉 Git 版控
- 能獨立作業完成專案
- 編寫乾淨、可擴展和可維護的代碼
- 能夠指導團隊合作整體設計和程式碼架構，並不斷努力改進它，能夠為團隊編寫風格指南以供遵循。
- 三年以上相關軟體開發經驗，資工/電機相關科系畢業

很多會問，什麼條件才能成為資深軟體工程師，請直接參考這篇文章『[如何才有資格稱為資深工程師](https://jaceju.net/be-a-senior-engineer/)』

## 工作內容

- 負責 Web 前端元件開發並完成交付
- 與 UI/UX designer 合作，制定使用者介面
- 與 PM 確認系統需求與操作流程，以實作商業邏輯
- 與 Backend engineer 合作，進行 API 整合與開發
- 構建可重用的組件和前端 library 以供未來使用
- Agile 開發方式，每週定期更新、回報實作進度

## 加分項目

- React hooks
- GraphQL (Apollo)
- Typescript
- Material UI / Tailwind
- Jest 單元測試
- Cypress E2E testing
- Next.js
- RWD
- 熟悉瀏覽器行為
- 有網站效能優化經驗
- 善於溝通與團隊合作
- 熟悉 CI/CD 工具

## 團隊技術

1. 使用 [Gitea][10] 進行版本控制及審核
2. 使用 Jira 及 Confluence 控管專案進度及文件
3. 使用 [Gitea Action][11] 打造自動化部署系統
4. 使用 Go, Python, Node.JS 語言開發微服務架構
5. 使用 Restful API, GraphQL 或 gRPC 進行服務溝通
6. 資料庫使用 SQLite, Postgres 或 MySQL
7. 雲平台使用 Azure, AWS 或 GCP
8. 透過 [Terraform][12], [Pulumi][13] 管理 Infrastructure
9. 使用 Grafana + Prometheus + Loki 監控各種服務狀態
10. 使用 Kubernetes 部署服務
 
[10]: https://about.gitea.com/
[11]: https://docs.gitea.com/usage/actions/overview
[12]: https://www.terraform.io/
[13]: https://www.pulumi.com/

## 薪資福利

年薪百萬起跳 100k/month（依據資歷能力給薪）

* 年終兩個月(依照到職比例)
* 健康檢查 (6500 元)、聚餐補助
* 旅遊補助 16000 (每年) 可以買任何產品
* 午餐跟晚餐補助 65 元 (分開補助)
* 每個月 200 元餐點補助 (7-11, 星巴克購物)

## 工時/特休

比照勞基法

## 聯絡方式

請將履歷夾帶於附件 (PDF)，寄信至 Bo-Yi.Wu@mediatek.com，標題註明『`應徵聯發科技前端工程師 - XXX`』(其中 XXX 為姓名)， 我們將會與您聯絡

**Comment by SidStraw** [comment]
你好
不好意思打擾了
相信這段時間應該收到了非常多的履歷
想冒昧請問一下回覆的週期

因為投遞履歷已有數天的時間
會希望了解是尚在處理中、已被篩選掉，又或者是投遞失敗並沒有收到
我的寄件地址是 sid@sid.tw

當然如果方便的話，若是已被篩選掉也希望能提示緣由
以便得知更明確的改進方向

感謝

**Comment by appleboy** [comment]
@SidStraw 歡迎直接來信詢問。

**Comment by regchiu** [comment]
Cool!

**Comment by appleboy** [comment]
已經找到人才了，感謝大家幫忙

**Comment by appleboy** [comment]
Hi All,

多新增一個缺，歡迎大家加入

**Comment by AmeMizuki** [comment]
請問一下還有在缺人嗎?

**Comment by appleboy** [comment]
已招募完畢，未來有缺會再開放
