### ISSUE TITLE
[徵才][台北/遠端] Frontend/Full-stack Engineer / UIUX designer

### ISSUE THREAD

**Issue by z20240** [f2etw/jobs#1116]
## 工作內容
我們是一家新創的遊戲公司，目前公司積極擴張團隊。我們正在尋找一位熟悉 Vue3 框架的前端工程師或全端工程師加入我們的團隊，專注於完善我們的後台網站（back-office website）。這個職位提供一個充滿挑戰和成長機會的環境，您將主要我一起合作，完善公司的 back-office 平台。

由於公司目前還在起步階段（但是已經有產品上線），因此我們會更加仰賴您在 UI/UX 上的設計與經驗(我們也在尋找 UI/UX 的合作夥伴，如有興趣也歡迎聯繫)。

### 關於這個職位
由於公司目前規模不大，因此我們期待每個 Engineer 都具有一定的即戰力。
關於 Frontend Engineer, 我們期待您具有豐富的 back-office website design & implementation 經驗。
關於 Full-stack (Backend) Engineer, 您將與我一起更加完善除了 back-office 以外的公司業務。

## 能力需求
- 熟悉 Vue3 框架，具備 Vue.js 開發經驗
- 具備 HTML5、CSS3、JavaScript 的深厚知識
- 了解 RESTful API 與前後端聯動
- 具備良好的代碼風格和版本控制經驗
- 優秀的問題解決能力和溝通技巧

### 加分
有全端開發經驗

## 薪資範圍
80~120k/mo
(但由於工作內容相對多樣，我們通常提供更加優於一般性的薪資，因此有機會可以再高。)

## 工時/特休
週休二日

## 福利/推薦項
- 工時彈性
- 一般性薪資高於市場行情
- 優於勞基法的特休天數

## 聯絡方式
- les.lee@intergamerdynamics.com

**Comment by regchiu** [comment]
嗨，請問是哪一家公司，能方便透露嗎？
