### ISSUE TITLE
「求職」Shyam：Front-End (HTML5) 或 Back-end (Node.js) 工程師

### ISSUE THREAD

**Issue by Shyam-Chen** [f2etw/jobs#112]
嗨，我是陳彥澄，是個應屆畢業生，在找一些 Front-end (HTML5) 或 Back-end (Node.js) 的正職工作機會。熱愛開放原始碼的技術，個性宅宅，冷靜冷沉，喜歡看書和寫作紀錄學習，閒暇之餘會嘗試去做和開放原始碼有關聯的專案。

履歷位址: https://www.cakeresume.com/shyam-chen

**Comment by Shyam-Chen** [comment]
有實習的報到通知了 ☺

**Comment by Rplus** [comment]
@Shyam-Chen 需要幫你調^整 label 嗎？

**Comment by Shyam-Chen** [comment]
好，謝謝

**Comment by Shyam-Chen** [comment]
沒 Node.js 實習 :sweat:

**Comment by Shyam-Chen** [comment]
挖哩，滿滿的都是 React 的工作，React 報到了
