### ISSUE TITLE
後端工程師招募（全遠端工作） 🧑‍💻

### ISSUE THREAD

**Issue by workavancevl** [f2etw/jobs#1128]
### 關於我們
我們是一家位於矽谷的金融科技初創軟件公司，由斯坦福和麻省理工學院的校友共同創立。我們的創始人、投資者和顧問團隊在科技行業、金融和管理諮詢方面都擁有豐富的經驗。我們致力於創造非凡的軟件，為全球用戶解決問題！
簡介
我們正在尋找一位才華橫溢的前端工程師加入我們充滿活力的團隊！
🍏 歡迎新畢業生申請！我們有適合各種經驗水平的職位，並有輪崗計劃，允許初級團隊成員根據興趣轉換工作角色。
🇺🇸 歡迎非英語母語的團隊成員。只需具備基本的英語閱讀能力。
💡 資深工程師可免考試：被選中的候選人將有機會與我們的聯合創始人/高級管理人員進行一對一討論，或約見喝咖啡。
💰 具有競爭力的薪資範圍：每年32,000 - 150,000美元，根據經驗水平而定：

新畢業生：32,000美元
助理：47,000美元
高級：63,000美元
主管：78,000美元
首席：94,000美元
總監：110,000美元
C級：150,000美元

### 職位概述
作為我們的前端工程師，您將為我們的網絡應用產品開發引人入勝、直觀且視覺上吸引人的用戶界面。您將與設計師、後端工程師和營銷團隊密切合作，將設計模型、用戶故事和線框圖轉化為高質量代碼，確保沉浸式和無縫的用戶體驗。
您作為前端工程師的旅程

使用我們的前端生態系統：

TypeScript
React 和 Material UI (MUI)
React Native 用於移動前端開發

使用 Figma 實現像素級完美的設計
在整個開發週期中與跨職能團隊協作
參與代碼審查
編寫乾淨、可重用和可測試的代碼
與各個團隊合作創建令用戶欣喜的功能
與我們的設計團隊合作解決用戶痛點
推動工程標準、工具和流程的改進
為內部團隊開發新工具
對您的工作負責並承擔責任
將 API 與前端框架集成
有效地構建、管理和重用 UI 組件
對現有軟件系統進行故障排除和調試
參與定期推出新市場、功能或產品

### 您需要具備的條件

信息技術、計算機工程或相關領域的學位
五年或以上的編碼經驗或類似角色的實習經驗
精通網絡開發框架，特別是 JavaScript、React 和 Material UI (MUI)
有使用 PostgreSQL 和 SQL Server 等數據庫的經驗
熟悉使用 QUnit、Mocha、Jasmine 或 RSpec 等工具進行質量控制測試

### 為什麼您會喜歡這個職位

享受全職工作的靈活性
完全遠程工作，無需通勤
在充滿活力的矽谷創業文化中茁壯成長
根據您的經驗水平提供具有競爭力的薪資

### 如何申請
https://linktr.ee/growaha
我們期待與您相見！

**Comment by tzurae** [comment]
又是Aha. 很像人頭 收集履歷的公司. 有人真的有面試過?
