### ISSUE TITLE
【徵才】Bloomon - Full Stack Developer

### ISSUE THREAD

**Issue by touhonoob** [f2etw/jobs#113]
## 團隊簡介

BLOOMON 
http://www.bloomon.co.uk/

Bloomon是一家藉由線上訂閱服務為歐洲花卉產業
帶來革命性影響的新創公司，我們在一年內成長
至10000名用戶，擴張到4個歐盟國家，並在台北
成立RD Center。除此之外，我們在第一輪募資就
獲得了1.4億台幣的資金。
## 工作地點
- 捷運善導寺站 Keep Working 工作空間 https://www.facebook.com/keepworkingtaipei/
- Remote: 如非台北人可遠端工作
## 工作內容
- LAMP Stack開發維護
- Angular/Require.js開發維護
- React/Redux/Webpack開發維護
## 能力需求
- Business Level English
- 後端
  - PHP Laravel
  - MySQL
  - Redis
  - Ubuntu Linux
- 前端
  - React/Redux/Webpack
  - Angular.js/Require.js
  - Node.js
### 加分
- React Native或其他Mobile開發經驗
- CI/CD經驗
  - Travis CI
  - Docker
- 自動化測試經驗
  - PHPUnit/Behat
  - Mocha/Nightwatch
## 薪資範圍

60k ~ 80k \* 13個月
## 工時/特休
- 9:00 AM ~ 18:00 AM (午休一小時)
- 10天特休 & 有薪病假
## 福利/推薦項
- company lunch
- 無限咖啡零食供應
## 聯絡方式

請將英文履歷寄至 peter.chung@bloomon.nl

**Comment by ShinyChang** [comment]
@Rplus 是不是可以多個 `Remote` label，有遠端需求的會比較好找

**Comment by appleboy** [comment]
推 @ShinyChang

**Comment by Rplus** [comment]
抱歉看漏了
我只看到很多零食 ( 遮臉 XD

**Comment by touhonoob** [comment]
最近公司找了專業的HR負責，有興趣的人請洽詢
http://jobs.bloomon.com/o/sr-fullstack-web-developer
