### ISSUE TITLE
「求職」接案網頁設計師 YM

### ISSUE THREAD

**Issue by ymcheung** [f2etw/jobs#118]
### 簡介

我是 YM，致力於打造有用又優雅的網站。
### 作品集

請見：[ymcheung.tw](http://ymcheung.tw)
### 技術能力
- Sketch: 用於網站/app UI 規劃。
- CSS3 (Sass): 熟悉響應式網頁設計。
- Javascript:  GSAP 動畫所用到的簡單語法。
- Illustrator
- Photoshop
### 開發環境
- OSX
- Vagrant 
- Git
### 社群貢獻

[Intersection 設計翻譯](https://intersection.tw)讓好文章有好的中文翻譯，目前平均每個月 5,500 點閱數。
### 期望酬勞

歡迎來信，一起討論您想在網路呈現的形象。
ymcheung.tw@gmail.com

**Comment by Rplus** [comment]
@ymcheung 作品集的網址要寫完整的網址唷~
