### ISSUE TITLE
【徵才】進階前端工程師 Front-End Developer, Staff II

### ISSUE THREAD

**Issue by jawayang** [f2etw/jobs#122]
### 團隊簡介/地點

Cloud-Interactive

Cloud Interactive is a design and engineering consulting firm. We provide highly customized solutions for leading enterprise and medical companies. Cloud Interactive is headquartered in Taipei, Taiwan. For more information on Cloud Interactive please visit www.cloud-interactive.com

地址：台北市大安區忠孝東路3段10巷10號 （忠孝新生捷運站 3 號出口) 
### 工作內容
- 負責 Javascript 開發
- 國際性專案
- 協助SA、PM釐清專案需求
- 與設計師討論互動方式，與後端串API
- 與QA完成除錯與修正
### 能力需求
- 專精於 Javascript、HTML、CSS
- 熟悉 jquery 與 require.js 
- 能模組化程式碼
- 能評估自己的開發所需的時間
- 具備 git 操作技能
- 具備前端開發工具的使用經驗
- 能駕馭 HTML 與 CSS 具備切版經驗
- 熟悉 web application 開發
### 加分項目
- 能撰寫測試程式
- 能設計及開發前端元件
- 能漸進優化、提升程式碼的可用性、可讀性及維護
- 熟悉行動網頁排版
- 熟悉常見的 Javascript Framework 如： React.js、Vue.js、D3.js … 
- 熟悉前端工具 gulp 、 nodejs、 sass ... 
- 具備 refactoring 能力
### 人格特質
- 對前端技術有強烈的熱愛與興趣
- 關注前端技術及網路發展趨勢
- 重視程式碼的可讀性與維護性
- 願意溝通討論，並能與團隊一起解決問題
- 能夠主動學習並自我要求
### 薪資範圍
- 月薪 4萬元 ～ 5萬元 
### 工時/特休
- 週休二日
- 9 : 30 ~ 18 : 30 (午休一小時)
### 福利/推薦項
- 三節獎金 / 年終 (視績效)
- 免費供應飲料、咖啡、點心、零食
- 每月部門員工聚餐與慶生會
- 每月最後一週 週五點心時間
- 不扣薪病假
### 聯絡方式
- email : james@cloud-interactive.com

**Comment by appleboy** [comment]
`webpack` ?

**Comment by jawayang** [comment]
@appleboy 公司有用 webpack 
但是用的不多，會根據專案本身的需求決定用或不用

**Comment by appleboy** [comment]
@jawayang 我只是想說你是不是忘記列了 `webpack` 👍
