### ISSUE TITLE
【徵才】Positive Grid強力徵求 Senior Front-end Engineer

### ISSUE THREAD

**Issue by AllieChen412** [f2etw/jobs#124]
## 團隊簡介/地點(彈性工作地點)

[POSITIVE GRID](https://www.positivegrid.com.tw/)在2010年在美國矽谷成立，2013年在台灣成立分公司，我們由來自美國史丹佛大學喜愛音樂的團隊所創辦。有世界最先進的音訊處理技術團隊，基於團隊對音樂的熱情、精實和注重細節的態度，我們的產品在短短一年內，在超過40個國家的App store排行榜位居音樂類NO.1，並獲得市場高度關注與App Store及多方媒體一致推薦。已成為行動音樂的領域的領導品牌，並藉由JamUp, BIAS等產品，年年營收皆呈倍數成長。

辦公室據點：臺北市中正區
## 工作內容
- 利用 WebView 開發支援跨平台桌面產品的 UI，搭配御用設計師，手刻酷炫的介面。
- 與 C++ 工程師共同制定 command spec，將使用者的操作結果從前端透過 bridge 傳遞至 native 底層進行音訊處理。
- 開發 SPA web app 並實作 cross-origin communication。
- 專職前端開發，不需要兼後端、設計、手機開發等等。
## 能力需求
- 熟悉 JavaScript、CSS3、HTML5 和 JQuery，並有 Angular.js 與 React 相關開發經驗
- 有使用 Gulp.js 、Grunt 或 Webpack 等相關經驗
- 熟悉並暸解 Scrum 或 Kanban 等敏捷開發法
- 熟悉使用 3rd Party Libraries 進行快速開發
- 能寫出架構乾淨並與標準相容並跨瀏覽器的程式碼
- 需熟悉物件導向軟體開發 (Object-Oriented Development) 及軟體設計模式 (Design Pattern) 等概念
- 卓越的最佳化能力，以及對相關技術知識細節的了解，並有卓越的除錯能力
- 卓越的溝通能力，在與產品經理及客戶緊密配合，規劃開發快速測試原型
## 薪資範圍
- 900,000~1,200,000
## 工時/特休
- 週休二日
- 09:00-18:00 (上班時間保持skype暢通，可即時處理e-mail即可)
## 福利/推薦
- 提供 Macbook pro成為你上班的好夥伴。 
- 舒服的辦公室環境，就好像在咖啡廳培養文青。 
- 冰箱無限量供應啤酒、可樂、ZERO、綠茶，記得上班不要喝醉囉。 
- 無限量供應餅乾、零食、小點心，隨時填飽你的肚子。 
- LIRIKA咖啡機每天讓辦公室飄咖啡香，除了美式、義式還有拿鐵多樣化選擇。 
- 每週五下午茶開心吃開心喝，互相分享與學習這週彼此的成長。 
- 第一年就有特休是基本的，我們還有給薪病假(但我們希望最好不要用到...) 
- 同時還有給薪的家庭照顧假讓每個人可以兼顧家庭，第一年就有26天給薪假讓你運用。 
- 不定期提供健康檢查的服務，關心自己與關心家人的身體。 
- 上班氣氛很歡樂，希望你不介意有時候比較吵鬧的辦公室。 
- 開車來嗎？ 我們還有停車費補助唷。 
- 跟一群優秀的人一起工作是最棒的福利！其他還有更多，等你來體驗！
## 聯絡方式

Allie Chen
E-mail: allie.chen@positivegrid.com
Skype: ting8489qq

**Comment by Rplus** [comment]
@AllieChen412 
想請問 26 天給薪假 是包含哪些？
因為我不確定要不要加上「無特休」的 label
另外可以的話補一下給薪範圍(下限或上限皆可)

**Comment by AllieChen412** [comment]
嗨嗨~~我們第一年就有特休
26天的給薪假包含特休、病假、家庭照顧假
薪資範圍已經更新囉:)
