### ISSUE TITLE
【徵才】Positive Grid強力徵求 Staff Front-End Engineer

### ISSUE THREAD

**Issue by AllieChen412** [f2etw/jobs#128]
## 團隊簡介/地點(彈性工作地點)

[POSITIVE GRID](https://www.positivegrid.com.tw/)在2010年在美國矽谷成立，2013年在台灣成立分公司，我們由來自美國史丹佛大學喜愛音樂的團隊所創辦。有世界最先進的音訊處理技術團隊，基於團隊對音樂的熱情、精實和注重細節的態度，我們的產品在短短一年內，在超過40個國家的App store排行榜位居音樂類NO.1，並獲得市場高度關注與App Store及多方媒體一致推薦。已成為行動音樂的領域的領導品牌，並藉由JamUp, BIAS等產品，年年營收皆呈倍數成長。

辦公室據點：臺北市中正區
## 工作內容
- 帶領前端開發團隊，搭配產品經理及設計師，開發支援跨平台桌面產品。
- 與部門主管制定團隊目標，並負全責與成員合作達成。
- 與 C++ 工程師共同制定 command 規格，將使用者的操作結果傳遞至 native 底層進行音訊處理。
- 開發 SPA web app 並實作即時跨域 (cross-origin) 通訊。
- 與產品經理、設計師、後端工程師頻繁溝通，協助專案分配人力，提供技術指導與培訓。
- 設計產品前端架構，制定核心介面規格。
## 能力需求
- 至少兩年帶領五人以上開發團隊，主導大型網站的前端架構設計、建置和開發的經驗
- 非常了解 JavaScript、CSS 和 HTML，並熟悉各種前端的技術、工具和趨勢，例如：Angular.js、React 、 Vue.js 或 Webpack 、PostCSS 等等
- 熟悉 SASS、 LESS 或是 Stylus 任一 CSS preprocessor
- 熟悉 Unit-Test 和自動化測試，並能寫出可測試性與可維護性高的程式碼架構
- 熟悉前端效能優化的方法，並能寫出與標準相容且兼容各種瀏覽器的程式碼
- 熟悉各種設計模式 (Design Pattern)，並能設計出良好的大型軟體架構
- 熟悉並暸解 Scrum 或 Kanban 等敏捷開發法
- 卓越的分析能力，能夠有效且快速的除錯和解決問題
- 卓越的最佳化能力，以及對相關技術知識細節的了解
- 卓越的溝通能力，在與產品經理及客戶緊密配合，規劃開發快速測試原型
## 加分加分
- 熟悉C++開發。
- 熟悉並了解函數式程式設計 (Functional Programming)
- 熟悉 ES6、ES7 或 TypeScript
## 薪資範圍
- 1.2 M~1.4 M
## 工時/特休
- 週休二日
- 09:00-18:00 (彈性上班時間保持skype暢通，可即時處理e-mail即可)
## 福利/推薦
- 提供 Macbook pro成為你上班的好夥伴。 
- 舒服的辦公室環境，就好像在咖啡廳培養文青。 
- 冰箱無限量供應啤酒、可樂、ZERO、綠茶，記得上班不要喝醉囉。 
- 無限量供應餅乾、零食、小點心，隨時填飽你的肚子。 
- LIRIKA咖啡機每天讓辦公室飄咖啡香，除了美式、義式還有拿鐵多樣化選擇。 
- 每週五下午茶開心吃開心喝，互相分享與學習這週彼此的成長。 
- 第一年就有特休是基本的，我們還有給薪病假(但我們希望最好不要用到...) 
- 同時還有給薪的家庭照顧假讓每個人可以兼顧家庭，第一年就有26天給薪假讓你運用。 
- 不定期提供健康檢查的服務，關心自己與關心家人的身體。 
- 上班氣氛很歡樂，希望你不介意有時候比較吵鬧的辦公室。 
- 開車來嗎？ 我們還有停車費補助唷。 
- 跟一群優秀的人一起工作是最棒的福利！其他還有更多，等你來體驗！
## 聯絡方式

Allie Chen
E-mail: allie.chen@positivegrid.com
Skype: ting8489qq

**Comment by Rplus** [comment]
@AllieChen412 ， 重覆發嗎？ #124

**Comment by AllieChen412** [comment]
Hiiii~~
不一樣唷!! 一個是Senior, 一個是Staff。
謝謝你:)
