### ISSUE TITLE
【徵才】Frontend Engineer – 前端工程師 – Accupass.com 活動通

### ISSUE THREAD

**Issue by tzuwenlo** [f2etw/jobs#141]
【工作內容】
負責依照產品功能需求開發前端網頁程式，並且根據視覺設計需求完成CSS切版，搭配完成交互體驗、質感、性能等兼備俱佳的網頁。

【職位要求】
- 2+年軟體設計開發工作經驗，能夠分析、設計、實做產品，且有網站專案上線經驗；
- 能夠使用 CSS 框架語言，如：LESS、SASS 或其他輔助工具；
- 熟悉前端JS開發工具與架構，如：jQuery、AngularJS 或其它；
- 對 UI/UX 設計敏感度佳；
- 具有串接第三方 API 經驗；
- 具有與後端、設計師合作經驗；
- 具有前端程式碼測試與品質控制經驗；
- 對Open Source接受度高；
- 願意持續主動精進開發技術。

【加分項目】
- 具有設計背景的相關經驗；
- 具有對Grunt, gulp, webpack的使用經驗；
- 對React, Redux有興趣；
- 線上有相關專案作品。

【薪資範圍】
NT$45k-95k，優秀工程師另外面議。

【公司介紹】
盈科泛利股份有限公司 (Accuvally Inc.) 的主營業務為「活動通Accupass」，是台灣最廣受信賴的自主活動票券平台。除了為各式活動主辦單位與個人提供雲端化的自助報名和售票服務，更有完善的推廣和社交機制供主辦單位維護客戶關係，深受各界客戶信賴。在亞洲，我們是市場上少數的開拓先鋒，被公認為最具發展潛力與市場商機的創業公司，擁有堅強的品牌實力與聲譽。「活動通Accupass」更與中國的姊妹站「活动行」 攜手締造佳績，成為在亞洲每月最多活動數與主辦單位數的自主網路售票平台，更是國際頂級資本投資公司：軟銀賽富(Softbank Asia Infrastructure Fund)、DCM、高通資本(Qualcomm Ventures)唯一在台灣投資的網路創業公司！為台灣最具潛力的創業之星！加入我們，為人們創造更多故事與回憶！

【文化特色】
- 自主自律的團隊文化，第一年即享帶薪年假（七天）、無限飲料供應，採彈性上下班制，週休二日；
- 高度目標導向，鼓勵成員參與建立團隊文化、完成目標；
- 保證年薪13個月，若公司達成目標另有其他獎金。

【聯繫方式】
請將您的 Github 帳號、resume 寄至 careers.tw@accuvally.com。

**Comment by Rplus** [comment]
其實比較建議由開發人員來張貼
畢竟你們都特別標註「對 Open Source 接收度高」，
那就直接看張貼者對 Open Source 有哪些互動就更加瞭解所謂的接收度高是需要到哪個範圍。

個人淺見~ ：)
