### ISSUE TITLE
【徵才】「痞客邦 PIXNET」 - 前端工程師

### ISSUE THREAD

**Issue by afutseng** [f2etw/jobs#147]
![PIXNET Logo](https://pixnethackathon2016.events.pixnet.net/img/co-pixnet.png)
![PIXNET office](https://pic.pimg.tw/emkt/1469774579-1218109191_n.jpg?v=1469775264)

# 公司名稱

「痞客邦 PIXNET」
https://www.pixnet.net/
# 公司簡介

優像數位媒體科技股份有限公司（「痞客邦 PIXNET」）創立於 2003 年，並於 2007 年加入城邦媒體控股集團。目前為台灣最重要的網路公司之一，同時亦是全台流量最高的本土網路社群（Alexa全球排名85）。
![PIXNET number](http://i.imgur.com/HxCtRIN.png)
資料時間：2016 年 12 月 8 日

目前，「痞客邦 PIXNET」為台灣最大內容社群，匯聚全台最多原創內容，儼然已是全民生活的資料庫平台。藉由長期觀察多樣化內容，深度了解社群行為面貌後，將雲端海量資料分析（Big Data）導入社群服務，於2014年成立社群大數據系統 <PIXinsight> 聚合轉化社群口碑影響力！

「痞客邦 PIXNET」將所有的數據彙整、分析、歸納後重新應用，衍生出了站內系統的廣告推送、行銷活動、社群商務...各種面向，致力於創造出最好最精準的服務，真實量化反映來自網路世界最真實的聲音，並且提供滿足生活中產生的需求。

同時間「痞客邦 PIXNET」亦致力發展行動網路應用，透過各種社交工具進行擴散與分享，以發揮社群行銷最大值，同時配合行動裝置的發展，除了不斷嘗試將桌機與行動進行結合外，並且將各種使用情境的需求直接獲得滿足，讓使用者在任何時間地點皆能隨心所欲使用「痞客邦PIXNET」旗下所有的服務。

# 服務簡介：
## < 痞客邦 >
全台最大內容社群 <痞客邦>，匯聚全台最廣泛的興趣社群、最豐富的原創內容、最具影響力的口碑評價，透過深入理解社群行為，持續優化內容服務，致力為使用者提供多樣化社群服務。面對充滿無限可能性的網路社群，<痞客邦> 將持續發展各種服務，讓使用者獲得更好的體驗。

## < PIXstyleMe >
全台最大美妝時尚內容社群 < styleMe >，提供最全面的美妝話題、知識、教學，解答所有美妝時尚相關問題。匯集百萬人氣意見領袖實用的保養彩妝資訊與技巧，帶給使用者最新的流行情報。此外，每月推出的「千萬口碑美妝賞」已成為最具影響力的美妝指標，引領台灣美妝市場的潮流方向。

## < PIXinsight >
社群大數據系統 < PIXinsight >，以獨家的語意分析及使用者行為交叉分析技術，廣泛蒐集、彙整、分析來自各社群、新聞、論壇等不同屬性之平台資料，包括 <痞客邦> 站內 6.5 億篇以上原創內容，從大數據的量化思維，預先洞察產業趨勢，發掘更多消費潛能，為品牌企業主精確解決 5W1H (who、what、why、where、when、how) 的各項難題。

# 團隊目前技術框架
* 前端：jQuery, Angular 1, React, Vue.js 2
    * [前端程式碼準則](https://pixnet.github.io/frontend-guideline/)
    * [產品開發瀏覽器支援原則](https://github.com/pixnet/frontend-guideline/wiki/%E7%94%A2%E5%93%81%E9%96%8B%E7%99%BC%E7%80%8F%E8%A6%BD%E5%99%A8%E6%94%AF%E6%8F%B4%E5%8E%9F%E5%89%87)
* 後端：PHP (90%+), Perl, Python, Node.js, Golang

# 日常工作內容
- 開發與維護痞客邦 PIXNET 旗下產品服務，您的研發成果可讓每日 770 萬名不重複訪客體驗
- HTML5 / CSS3 Layout / Performance tuning
- jQuery/AngularJS/React.js/Vue.js/Node.js 應用程式開發維護
- 與前端組同事共同引入新技術或工具，持續改良工作流程跟產品
- 鼓勵員工學習，會定期舉辦技術分享會，[可參考歷年前端內部技術分享簡報](https://github.com/pixnet/frontend-guideline/wiki/%E5%89%8D%E7%AB%AF%E5%9C%98%E9%9A%8A%E6%8A%80%E8%A1%93%E5%88%86%E4%BA%AB)，歡迎對技術學習有熱情的朋友加入

# 基本要求
- 二年以上網站前端工作經驗，可獨立作業。
- 熟悉 HTML/CSS/JavaScript
- 熟悉任一前端框架（AngularJS, React.js, Vue.js)
- 具備 Bootstrap/jQuery 使用經驗
- 具備 Responsive Web Design 網站製作經驗
- 具備 RESTful API 介接經驗
- 具備 Git 版本控制系統使用經驗

# 加分項目
- 具備跨瀏覽器相容性開發能力
- 具備 Sass/SCSS/PostCSS 開發經驗
- 具備前端效能調校經驗 (RAIL model, DevTools, PRPL Pattern, etc.)
- 具備 Progressive Web App 開發經驗
- 具備前端自動化測試開發經驗
- 暸解 Web Security
- 具備任何一種後端語言開發經驗 (PHP/Node.js/Python/Golang 等，PHP 尤佳)

# 薪資獎金
- 月薪 NTD $50,000 ~ $75,000 
- 績效獎金依每年兩次績效考核發放

# 休假
- 試用期滿即享有特休年假 12 天，逐年遞增一天
- 半薪病假

# 公司福利
- 員工旅遊 (2014-上海杭州、2015-馬來西亞、2016-越南、2017-美國舊金山)
- 國內外技術研討會門票、機票住宿補助
- 三節獎金
- 旅遊暨健康檢查補助
- 每週三免費下午茶點心
- 威秀電影票優惠
- 城邦集團旗下出版刊物優惠

# 需求人數
1 人

# 工作設備
- Macbook Pro 2016 
- DELL 可直立旋轉螢幕 22" x 1 (亦可申請外接兩顆螢幕，含筆電共三螢幕）

# 工作時間
彈性上下班，08:30 - 10:00 至 17:30 -19:30

# 工作地點
台北市中山區民生東路二段 149 號 3 樓
行天宮捷運站 1 號出口左轉步行約 300 公尺

# 應徵方式
請將履歷與作品集寄到 applyjob AT pixnet.tw，並附上常用的網路服務帳號 (GitHub/Twitter/LinkedIn/SlideShare/Speaker Deck, etc)

**Comment by appleboy** [comment]
Golang 用在哪部分？

**Comment by afutseng** [comment]
@appleboy 

目前只有 Slack Bot 用到 Golang；我們主管蠻看好 Golang 的，未來的獨立新專案有可能用 Golang 開發。

**Comment by afutseng** [comment]
更新工作設備螢幕的補充、新增前端程式碼準則、產品開發瀏覽器支援原則、前端組歷年內部技術分享簡報

**Comment by appleboy** [comment]
@afutseng 不錯的團隊

> 鼓勵員工學習，會定期舉辦技術分享會，[可參考歷年前端內部技術分享簡報](https://github.com/pixnet/frontend-guideline/wiki/%E5%89%8D%E7%AB%AF%E5%9C%98%E9%9A%8A%E5%85%A7%E9%83%A8%E6%8A%80%E8%A1%93%E5%88%86%E4%BA%AB)，歡迎對技術學習有熱情的朋友加入

**Comment by afutseng** [comment]
新人已通過試用期，關。
