### ISSUE TITLE
【徵才】幫你優 BoniO-前端工程師 

### ISSUE THREAD

**Issue by betty0114** [f2etw/jobs#151]
**【關於我們】**
BoniO Inc.(幫你優股份有限公司) 為開發「PaGamO」(台語：打Game學) 全球首創結合教學的線上遊戲公司. 在2014年12月獲得華頓商學院 Wharton 跟全球大學評比機構 QS 合作舉辦全球第一屆的教學創新大獎. 2015年獲得鴻海資金挹注. 現在招募Ruby on Rails專家, 歡迎對寓教於樂有興趣的精英加入!

**【榮獲獎項】**
2014年12月甫獲得華頓商學院 Wharton 跟全球大學評比機構 QS 合作舉辦全球第一屆的教學創新大獎肯定！歡迎加入我們一起繼續進步!!

**【工作內容】**
(一)	Must Have 
1.	基本使用 Git 能力
2.	熟悉 HTML5 、CSS3、ES6+ 語法
3.	使用過 React.js
4.	Flux/Redux or 任何與React搭配的state management
5.	SASS or postCSS
6.	不依賴css framework切版的能力
7.	Responsive Web Design 網站製作經驗
8.	jQuery 使用經驗

(二)	Nice to Have
1.	Webpack使用/設定經驗
2.	熟悉前端測試
3.	對後端有一定了解，Ruby on Rails尤佳
4.	瞭解scrum流程
5.	具備 RESTful API 介接經驗

**【薪資與工時】**
1.50K起-面議 (視所具備能力與測驗結果而訂)
2.彈性工時/加班依勞基法規定辦理
3.特休: 第一年7天 / 第二年14天

**【福利制度】**
1.工作氣氛融洽、環境自由
2.獎金/禮品類 :年終獎金、三節獎金/禮品
3.保險類:勞保、健保
4.休閒類:國內旅遊、部門聚餐、慶生會
5.制度類:完整的教育訓練
6.請/休假制度 :週休二日、特休/年假、生日假、陪產假、不扣薪病假、女性同仁生理假、女性同仁育嬰假
7.提供早餐與吃不完的零食、包子點心與咖啡等飲料

**【聯絡我們】**
E-mail: betty.tsai@bonio.com.tw
**來信請標註** 
1.應徵職務名稱與您的大名
2.檢附履歷/Github/作品集
3.從何處得知此職缺廣告

感謝各位的來信囉~

**Comment by erwaiyang** [comment]
已有特彈休資訊囉
> 3.特休: 第一年7天 / 第二年14天

可否幫忙把[缺特/彈休資訊]label 拿掉呢 謝謝
