### ISSUE TITLE
【徵才】[食我/Eatgether] Full Stack Developer - 網站全端工程師 

### ISSUE THREAD

**Issue by magicsky0831** [f2etw/jobs#153]
## 團隊簡介/地點

我們相信，一頓飯可以連結全世界。

《食我餐飲顧問股份有限公司》是一個成立自2014年的新創公司，致力於透過網路科技創新應用服務，「創造更美好的用餐體驗」。分別於2014年與2016年完成種子與天使輪投資，分別來自於聯合報系與多位業界知名天使投資人。公司主要的產品為2015年上線的餐飲優惠APP《EatMe食我》，以及自2016年上線就獲得廣大好評的聚餐交友APP《Eatgether》。

目前團隊成員約十人，是個平均年齡近30歲，同時具備年輕活力與技能經驗的團隊。動靜分明是我們的團隊文化，彈性自律是我們的工作風格，在這裡沒有太多的規範，上下班不打卡，也可自行安排工作時間，高度的自律搭配目標導向的管理模式，成就了一個快而精實的新創團隊。目前整個團隊都聚焦在開發Eatgether，朝著打造一個來自台灣的國際化餐飲社交平台而努力。我們認為新創公司的人才就是一切，每個加入的人都會改變這個團隊與產品，非常期待有你的加入！

公司地址：台北市中正區忠孝西路一段50號22f-9  (台北車站正對面，捷運出口10秒到)
公司官網：https://eatgether.com/
媒體報導：https://eatgether.com/news/4

## 工作內容

**Full Stack Developer - 網站全端工程師** 
- 規劃與開發Eatgether網站版前後端平台
- 與網站設計師合作開發優異的前端介面
- 與後段工程師溝通Api與資料庫串接
- 網站專案以外的後端資料庫與演算法開發

## 能力需求

- 具備實際的網站前後端開發經驗與作品
- 熟悉 JavaScript (ES6), ReactJS or VueJS 前端模組化開發技術
- 熟悉 Git 協作
- 熟悉 CSS3, RWD, Sass 前端設計技巧
- 熟悉 PHP + Laravel or NodeJS + Koa2
- 具備使用 UI Framework 經驗
- 熟悉後端技術(etc. AWS)

### 加分

- 提供 GitHub 或作品參考
- 具備串接 RESTful 或 WebSocket API 經驗

## 薪資範圍

年薪60萬-85萬

## 工時/特休

週休二日，表定9:30-18:30，彈性上下班不打卡
比照勞基法，國定假日見紅就放

## 福利/推薦項

外部進修課程與購書補助
每月團隊聚餐

## 聯絡方式

履歷與相關作品請寄至 jobs@eatme.tw

**Comment by SimonSun1988** [comment]
你好，這個 issue 可以 close 了，麻煩版主了
