### ISSUE TITLE
【徵才】[Cepave] 前端工程師(Junior/Senior)

### ISSUE THREAD

**Issue by CApopsicle** [f2etw/jobs#158]
<p align="center">
<img src="https://cloud.githubusercontent.com/assets/890063/22111325/ed85401e-de99-11e6-9067-fb9354eb69c2.png" />
</p>

Hi 大家好，我是 Cepave 的前端工程師 Kelly，希望可以找到**神隊友**一起教學相長 :)

以下是公司簡介與職務工作內容，有興趣者歡迎發送簡歷至: `rwu@cepave.com`

## [Cepave.com](http://cepave.com) 香港商翱鶚股份有限公司
Cepave 於 2015 年成立，是一家新型態網路科技公司，專注於開發大規模的網路應用系統。以直覺、人性化的操作介面來管理網路設備，提供智慧平台分析網路趨勢。母集團是 NASDAQ 上市公司，代號：[VNET](http://finance.yahoo.com/quote/VNET?ltr=1)。

我們要找的是有野心、有膽識、有創業想法、勇於自我挑戰、喜歡 Hackathon、熱愛學習新技術的人才。學歷不拘，只要有能力、態度良好、肯學，學歷不是問題。
對於 Cloud Computing / Big Data / Open Source 有興趣的您，Cepave 每日要處理的的資料量是好幾十 TB，是能讓您大展身手的極佳平台，歡迎加入我們！

## 工作內容
- 打造 `UI 組件庫`，擁抱開源
- 數百萬量級監控系統前端開發
- 大數據與資料視覺化

## 能力需求
**無**，我們並不會有特定的要求要對某一框架精通，理由是：
> 前端是個日新月異的職業，每天都在求新求變，永遠都有層出不窮的最佳解決方案出現，框架一個比一個潮

在這裡更不會用學歷來衡量你的價值
 - 對於 Junior 同仁，我們看重的是你的`潛能`與`發展力`。
 - 對於 Senior 同仁，我們看重的是你的`解決問題`能力，與技術有沒有深厚的基底。

#### Core
- [Vue](https://github.com/vuejs/vue) + [Vuex](https://github.com/vuejs/vuex)

#### Router System
- [Vue Router](https://github.com/vuejs/vue-router) 

#### Build system
- [webpack](https://webpack.js.org)
- [gulp](http://gulpjs.com)

#### Data Visualization
- [highcharts.js](http://www.highcharts.com/)
- [echart.js](http://echarts.baidu.com/)

#### CSS Preprocessor
- [sass/scss](https://github.com/sass/node-sass) (請放心是 node 版的 `node-sass`)
- [postcss](http://postcss.org)

#### ES6 / ES7 Compiler
- [babel](https://babeljs.io)

#### Coding Lint
- [eslint](https://eslint.org/docs/rules/)

#### Testing / Coverage
- [jest](https://github.com/facebook/jest)

#### E2E Testing
- [Nightwatch.js](http://nightwatchjs.org/) (Selenium based)

因為我們玩開源，所以程式碼品質的掌控是非常重要的，團隊有 Code Review 機制，也會嚴格要求每個人寫出易於測試的程式碼。

### 加分
若能提供以下資料會有很大的加分：
- 個人網站或部落格
- Stackoverflow 帳號
- Github 帳號
- LinkedIn 帳號

## 公司文化
我們崇尚 F.L.A.G. 的工程師文化，鼓勵獨到的見解、激發創意。透過最有效率的溝通、以及最少的管理來完成團隊任務。所以期待來挑戰的您與我們一樣，對於技術充滿熱情，能自動自發，持續在能力上精進，和我們一起挑戰技術上的難題。
我們沒有規定上下班時間，不用打卡，可以依照個人狀況自由地調整上下班時間與地點以得到最高的產出。
我們的組織非常扁平，每個人可以依據公司目標、工作優先順序、個人專長和興趣，主動參與討論並自行決定工作內容。期許每位人對自己的工作負責，在工作進行中充分和同伴進行討論。在專案上注重敏捷式開發 (Scrum + Kanban)，迅速並確實地完成工作。

## 團隊
不用支援 IE 不用支援 IE 不用支援 IE，沒有舊包袱，我們 Team 的 Slogan 是 用最潮的技術打造最威的監控系統，如果沒有意外，我們的 depend packages 也都是跟到最新版，所以來到這裡請你拋棄舊時的技術觀念。

團隊不死守當紅技術，我們也會持續關注其他業界新技術，希望可以解決目前開發上的一些痛點。
前端團隊內部技術分享與學習氛圍非常好，希望你也可以保持愛分享與學習的心 😃

### 團隊可以帶給你什麼
- 與一流的設計/工程團隊共同打造超體驗的滿滿大平台
- 走在業界前沿的 Work Flow，專業開源專案的 Git Flow 工作流程，並持續集成 CI 自動化測試/部署
- 每星期輪流固定技術分享，練習說話也吸收新知 :)

## 薪酬與福利
在 Cepave 中，即便是剛畢業的工程師，全年底薪也會至少新台幣 70 萬以上（以 14 個月計算）；資深工程師全年底薪至少百萬。我們的團隊文化新創、工作效率新創，但是待遇不新創。我們用盡可能高的待遇爭取人才，因為我們相信：在新創公司打拚，薪水不必委屈！

具體薪資依據能力以及各種條件而定，等您來挑戰上限！

* 免費的零食及飲料
* 鼓勵 BYOD，還有公司高額的補助
* 每週一次的 TGIF 下午茶大會，鼓勵大家暢所欲言，盡情表達自己的創意和想法
* 不定期的聚餐與電影欣賞
* 公司鼓勵您利用上班時間參與技術聚會/黑客松/研討會
* 為了提高運動風氣，公司還提供每人每月定额運動津貼，可用於健身房、馬拉松、單車比賽...等等
* 用餐補助、員工分紅、三節獎金、績效獎金
* 不定期文康活動
* 年度員工健康檢查
* 勞、健保及退休金提撥：凡新進人員報到後即辦理勞、健保投保及退休金提撥

## 工時/特休
* 我們沒有規定上下班時間，不用打卡，可以依照個人狀況自由地調整上下班時間與地點以得到最高的產出。
* 遇彈性放假例且假日須補班時，不用補班
* 提供優於勞基法規定的特休天數，並依社會年資給予7日以上特休。

## 聯絡方式
有興趣者歡迎發送簡歷至: `rwu@cepave.com`

**Comment by Rplus** [comment]
公司網址要調整一下唷
被辨認為網址了 :P

**Comment by CApopsicle** [comment]
👌 已修改! 感謝提醒!

**Comment by iamken1204** [comment]
eslint、babel、postcss、gulp、webpack 的連結可能要修改一下，被歸類到本頁底下了 :/

**Comment by h091237557** [comment]
可以remote work 嗎~?  或是一星期去個一兩天降~

**Comment by CApopsicle** [comment]
@h091237557 
因為目前團隊還很年輕需要磨合，公司規定每星期可以有 1 天 remote，但是我們未來也希望朝向最終大家都可以 remote 的方向前進 😃
