### ISSUE TITLE
【徵才】17 Media - Senior/Junior 前端工程師

### ISSUE THREAD

**Issue by eason17** [f2etw/jobs#159]
# 【徵才】17 Media - Senior/Junior 前端工程師

## 最新資訊與更新記錄
 - 2017/05/10: 由於編制有調整，更新紀錄不易描述清楚，因此將重開一篇徵才資訊
 - 2017/04/24: 更新 headcount
 - 2017/04/07: 更新 headcount
 - 2017/04/06: 更新 headcount
 - 2017/03/25: 更新 Senior headcount，由 3 位改為 2 位
 - 2017/03/23: 我們要再一次擴編了，將繼續邀約面試。更新 Junior headcount，由 0 位改為 2 位；更新 Senior headcount，由 1 位改為 3 位
 - 2017/03/19: 更新 Senior headcount，由 2 位改為 1 位
 - 2017/03/15: 更新 Junior headcount，由 1 ~ 2 位改為 0 位；更新職務內容：活動頁
 - 2017/03/09: 近一個月的時間，我們邀請了十幾位 candidate 面試，目前正在等待錄取者答覆意願，因此近期會暫停邀約面試。若錄取者答覆後仍有 headcount，我們將會繼續邀請面試，謝謝。
 - 2017/02/18: 更新 Senior headcount，由 2 ~ 3 位改為 2 位
 - 2017/02/17: 新增 Q&A 1、2

## 公司簡介
17 Media (英屬維京群島商麻吉一七股份有限公司臺灣分公司) 創立於 2015 年，旗下最知名產品「17 直播」，是一個能夠讓明星藝人、各領域名人、網紅與素人進行直播、錄製節目，以及分享生活點滴的應用程式與社交平台，讓全世界的人即時觀看並參與互動。

## 工作內容
:warning: **此職務橫跨前後端開發，若與您職涯方向不同，請勿花費您的時間閱讀內文，謝謝**
此工作涵蓋的技術範圍，包含強度較大的前端與輕量的後端，實質為偏重前端的全端工程師，但後端經驗為非必要，主要仍是考量前端能力。若您希望在精進前端的同時，跨足後端逐漸發展為全端工程師，請給我們一個機會認識您。
 - 與 17 app 團隊協同合作，提供技術支援並執行戰術，一同達成整體戰略目標
 - 開發 17 Web app、官方網站和各種大小型活動頁
 - 開發 17 app 後台管理系統
 - 開發內部 slackbot、維運和監控系統
 - 協助各部門開發各種小工具，加速整體公司運作效率

## 招募人數與能力需求
團隊目前有 9 位成員(含 4 位準備報到)，還需要 1 位工程師，分配可能性請見下方範圍

> Senior 1 位 (總共 6 位，已找到 5 位)
##### Must have
 - 精通 JavaScript、CSS、HTML、瀏覽器運作
 - 相容主流瀏覽器的前端整合開發經驗
 - 前端 framework/library 的使用或開發經驗
 - 模組化開發經驗
 - 團隊溝通與合作經驗
 - git
##### Nice to have
 - ES6、React.js、Sass、Webpack
 - Node.js、MySQL、MongoDB
 
> Junior 0 位 (總共 2 位，已找到 2 位)
##### Must have
 - 1 年以上前端相關工作經驗
 - 熟悉 JavaScript、CSS、HTML
 - 前端 framework/library 的使用經驗
 - 團隊溝通與合作經驗
##### Nice to have
 - ES6、React.js、Sass、Webpack

## 薪資範圍
 - Senior：年薪 100 萬新台幣以上
 - Junior：年薪 70 萬新台幣以上

## 工時與休假
 - 彈性上下班，09:00 ~ 10:00 至 18:00 ~ 19:00
 - 週休二日，依國定假日休假
 - 特休極優於勞基法
 - 不扣薪病假 12 天 / 年 (女性同仁生理假)
 - 生日假

## 福利制度
 - iMac / MacBook Pro 擇一
 - 公司提供免費午餐、健康零食、咖啡、飲料
 - 年終獎金保證 2 個月，以全薪計；中秋、端午禮金
 - 每月運動健身補助最高 3,000 新台幣
 - 年度職能進修補助最高 30,000 新台幣
 - 年度健康檢查補助 2,000 新台幣
 - 年度員工旅遊
 - 員工聚餐
 - 麻吉大哥帶你去看 M17 戰隊的電競比賽
 - 不需支援連 Flexbox 都不能用的瀏覽器

## 工作地點
台北市信義區

## 面試流程
> 第一階段：Front-end team lead，約 2 ~ 5 個小時

 - 向您介紹公司、團隊、工作內容
 - 您介紹自己與工作經驗，盡情展現您有多棒
 - 由數個實務中常見的實作題目，挑選至少 2 個做上機 live coding
 - 給定一段程式碼，請您進行 code review
 - 依照前面的討論內容，延伸前端相關技術問答
 - 向您介紹 17 Media 的文化、優缺點
 - 由您提問

> 第二階段：HR，約 0.5 小時

 - 向您介紹公司制度、福利
 - 自我介紹
 - 解答您對 17 Media 的各種問題

> 第三階段：HR

 - 1 ~ 7 個工作日內通知面試結果
 - 錄取的後續聯繫：說明 offer、可答覆時間、報到時間、設備選擇

## 聯絡方式
 1. 您的履歷中，除了姓名、連絡電話和 email，請盡量不要提供與學經歷無關的個人資訊，例如照片、性別、生日、身高、婚姻家庭狀況等，謝謝您
 1. 若您白天不便請假，面試時間也可以選擇平日晚上
 1. 請將您的履歷寄至 [careers.f2e@17.media](mailto:careers.f2e@17.media)

## Q&A
 1. 是否有招募實習或研發替代役？
    - 無
 1. 履歷怎麼篩選？
    - 每一封履歷都會由 Front-end team lead 親自看過，並回覆 HR 是否邀約面試

**Comment by eason17** [comment]
感謝這個平台讓我們可以發佈徵才資訊，也謝謝 @Rplus 幫忙加 label。
由於敝社前端團隊編制有更進一步的調整，
需要更多工程師，因此關閉此篇後將重新發一篇徵才。
謝謝！

**Comment by Rplus** [comment]
手補更新記錄好棒 (:+1)

**Comment by eason17** [comment]
@Rplus 哈哈～謝謝！我想說持續更新資訊，
可以讓謀職者在一兩個月後看到這篇文章時，
知道我們仍在徵才。 👨‍💻 👩‍💻
