### ISSUE TITLE
Client Engineer(外商遊戲公司)

### ISSUE THREAD

**Issue by LoveRelax** [f2etw/jobs#16]
工作內容：
開發手機遊戲的Native Client
iOS / android平台遊戲開發

需求條件：
•Confortable using C++  (at least 2 years experience)
•English(Conversation level)

candice.lin@tw-rising.com

**Comment by kidwm** [comment]
話說我個人認為廣義上來說原生平台也是一種前端啦。

**Comment by Rplus** [comment]
要廣義的話，所有人機介面都可以說是前端 XDD
但目前社團應該主要針對 web front-end.
所以我認為這邊還不太適合發 app 的職缺。

**Comment by LoveRelax** [comment]
喔~抱歉！！第一次使用或許在分類上不是那麼熟悉~還請多包涵！！
