### ISSUE TITLE
【徵才】Positive Grid- Senior/ Junior Front-End Engineer

### ISSUE THREAD

**Issue by AllieChen412** [f2etw/jobs#164]
## 團隊簡介/地點(彈性工作地點)

我們正在積極招募菁英加入我們在台灣的技術團隊，一起打造更多世界一流的高品質音樂產品！
用你的能力，做出令人驚艷的產品
用你的創意，重新定義世界創作音樂的方式
和我們一起站上世界的舞台
驕傲地向全世界說：這是我做的產品！

辦公室據點：臺北市中正區(未來會搬新家唷~~)

## 工作內容
- 參與世界級的數位音樂產品的開發與維護，並加以改善與優化
- 打造 Webview 為介面的跨平台桌機軟體，以 Mac 與 Windows 為主
- 採用 Webkit 作為主要渲染引擎，不需維護 IE 與 Firefox 等跨瀏覽器問題
- 搭配 Scrum 執行專案，每天與各領域的高手同事緊密合作
- 主動發掘工作上的問題，並提出解決問題的方法
- 持續關注與分享網頁前端技術新知，推動團隊成長和進步

## 能力需求
- 我們不注重年資，但如果你有參與過大型專案開發，且為主要開發者更加分
- 熟悉 JavaScript、CSS、HTML 和 jQuery
- 熟悉至少一項前端框架，例如：Angular.js、React.js 或 Vue.js 等
- 熟悉並使用過 Gulp、Grunt 或 Webpack 等前端開發工具
- 熟悉前端網頁效能的優化方法，打造出高效的使用者介面
- 撰寫過自動化單元測試和整合測試的經驗
- 具備良好的編程習慣，並能夠快速除錯和解決問題的能力
- 瞭解敏捷開發思維，有參與過 Scrum 開發經驗
- 樂於分享，並具備良好的溝通能力以及團隊合作的精神
- 對前端技術有熱枕，能夠持續地吸收新知，自我成長

## 薪資範圍
- 700K-1.2M 或依能力面議 (來挑戰吧)

## 工時/特休
- 週休二日
- 09:00-18:00 (彈性上班時間保持slack暢通，可即時處理e-mail即可)

## 福利/推薦
自由靈魂的標準配備：
●蘋果咬一口-用了MacBook Pro，你就是Pro!
●咦？零食盒怎麼會自己裝滿？-上升的體重 上升的工作靈感
●誰喝咖啡這麼香？無限供應的咖啡豆，我的一天，從喝了咖啡才開始
●零食配汽水才是王道？汽水啤酒給你最經典的搭配
●PG跟你一起慶生！生日小禮快遞到你家！
●每年教育訓練補助讓你自我成長累積經驗

和Positive Grid一起對自己好一點：
●進公司第1天就有特休，每多一年加2天，絕對不會低於法令規定，還有給薪家庭假&病假讓你運用
●覺得腦累、心累、身體累？自我放逐假讓你遠離塵囂
●不定期提供健康檢查的服務．Positive Grid關心你．
●光找停車位就一肚子火了？-別怕！！我們有停車費補助讓你消消氣

看不見但很重要的：
●溫馨的team building，開心吃喝，互相學習與成長
●上班氣氛很歡樂，吵鬧的辦公室也可能是你靈感的來源
●跟一群優秀的人一起工作是最棒的福利！其他還有更多，等你來體驗！

## 面試流程
- 全程使用skype/zoom 語音面試，只需要有穩定的網路，免去你的舟車勞頓
- 我們會有這些過程: 1st skill interview--> HR和你聊聊天--> 2nd co-founder interview--> 和老闆聊聊天(視情況給作業或是邀請你到公司看看環境)
- 所有的履歷都會經由HR轉給Team leader，討論是否要約面試，一定都會給回覆，如果沒有收到，可以直接問問我

## 聯絡方式
Allie Chen
E-mail: allie.chen@positivegrid.com
Skype: ting8489qq
[職缺點我！]([https://www.positivegrid.com.tw/join-us/])

**Comment by sharils** [comment]
@AllieChen412 Is this still open?
