### ISSUE TITLE
【徵才】Front-End Engineer  前端工程師 – 思樂科技

### ISSUE THREAD

**Issue by christan0612** [f2etw/jobs#166]
## 團隊簡介/地點
我們是思樂科技，提供雲端表單服務。 
有別於市場上的產品，思樂(G-Sailors)更專注於介面、流程及貼心的專屬服務！ 
期望企業或商家能用最實惠的價格，合適的工具，提昇其整體經營績效及服務水準！ 
上班地點：
台北市中正區近古亭站8號出口
## 工作內容
1.公司產品前、後台的功能開發與維運： 
(1)依據需求評估可行性 
(2)前端功能的開發與維護 
(3)與後端工程師API的串接 
(4)協助改善產品，埋設追蹤碼 

2.官方網站開發與維運： 
(1)與設計師合作，依據設計師所提供的圖檔進行討論、RWD切版 
(2)官網功能開發 
(3)SEO優化，提升自然搜尋排名

## 能力需求
1. HTML5\CSS3 的運用 
2. SASS 或 SCSS 的編寫 
3. RWD 切版 
4. Javascript 編寫 
5. jQuery 的使用 ( 非必要 ) 
6. 解決跨瀏覽器問題 
7. API 的串接 
8. 瀏覽器 devTools 的使用 
9. 良好的編碼習慣(註解的使用、class的命名、變數的命名) 
10. 前端框架的使用(AngularJS\ReactJS\VueJS)，VueJS 尤佳 
11. GA \ PIXEL 等追蹤碼的埋設，有辦法依據需求埋設相關事件追蹤碼 
12. 視覺化圖表製作，D3.js 或是其他製作圖表相關工具的使用
### 加分
1. SEO 優化相關經驗 
2. 網站效能優化調校
## 薪資範圍
NT$40,000 - NT$55,000
保障年薪13個月
## 福利/推薦項
-符合並優於勞基法相關規定
-彈性休假制度及上班時間 
-附設健身房、spa及蒸氣室等設施
-免費室內機車停車位
-吃不完的零食，喝不完的飲料
-不定期團膳(老闆、同事下廚)
-定期聚餐
-獎金制度
1. 年終獎金
2. 三節禮金
3. 電腦補助

## 工時/特休
彈性上下班大約 9:30 - 19:00 左右
休假的部分，是彈性休假，也就是只要提前說，並且不影響進度時程，都可以休，不扣薪！
所以平日的研討會只要不影響工作進度的情況下都可以請假參加不扣薪！
## 聯絡方式
張先生
scottie@gsailors.com

**Comment by YamiOdymel** [comment]
請問解決跨瀏覽器問題有包含 Edge 或 Internet Explorer 嗎？

**Comment by christan0612** [comment]
您好，關於跨瀏覽器的部分，目前需支援到ie10，感謝詢問!

2017年3月10日 上午1:04於 "Yami Odymel" <notifications@github.com>寫道：
