### ISSUE TITLE
【徵才】Positive Grid- Web Developer 網頁開發工程師

### ISSUE THREAD

**Issue by AllieChen412** [f2etw/jobs#170]
## 團隊簡介/地點
[POSITIVE GRID](https://www.positivegrid.com.tw/)在2010年在美國矽谷成立，2013年在台灣成立分公司，我們由來自美國史丹佛大學喜愛音樂的團隊所創辦。我們顛覆傳統音樂思維，開發多款軟體/硬體數位吉他效果器！我們的產品很好玩，當然也是一間非常有趣的公司，隨時有Live Band的演出~~
我們不斷研發新產品，當然也會不斷地更新公司網頁，讓我們的產品可以在第一時間被大家看見。
當然，有堅強的技術團隊，我們也有堅強的福利做後盾！

辦公室據點：臺北市中正區(未來會搬新家唷~~)
## 工作內容
我們的Web developer 在開發與維護各占 50/50，除了新功能開發外，還有新設計要套用，也有既有功能的重新設計。最重要的是跟Marketing一起合作Growth hacking和行為資料分析。如果你有興趣，Backend/I.T.也有很多事情可以讓你嘗試
- 開發官網、eCommerce、會員中心、Help center 
- 針對不同平台的頁面瀏覽體驗最佳化 
- 訪客行為分析 
- 與Marketing緊密合作，Growth hacking
## 能力需求
- 3年以上 PHP 經驗
- 熟悉 Javascript, CSS, HTML, MySQL等關連式資料庫
- PHP & JS Framework 經驗
- Google AdWords/Analytics 經驗
- 串接 RESTful API 經驗
## 加分加分
- 精通 WordPress Plugin
- Git-flow
- Node.js 
- 有自己開發作品
## 如果你具備這些更好
- 對於Growth hacking有熱情
- 具備英語讀寫能力
- 具備獨立開發與解決問題的能力、高執行力
## 薪資範圍
- TWD 60,000 - 80,000/月，或依能力&經驗討論薪資
## 工時/休假
- 週休二日
- 09:00-18:00 (彈性上班時間保持slack暢通，可即時處理e-mail即可)
## 福利/推薦
- 讓Macbook pro成為你的好夥伴
- 不會見底的零食盒，滿足動腦過後咕嚕嚕的肚子
- 裝滿滿的冰箱，提供啤酒、汽水、茶類(別醉，這是真的)
- 星巴克早餐豆讓公司飄滿咖啡香
- 進公司第1天就有7天特休，每多一年加2天，絕對不會低於法令規定，還有給薪家庭照顧假&病假讓你運用
- 不定期提供健康檢查的服務，關心自己與關心家人的身體 
- 溫馨 team building 讓你開心吃喝，互相學習與成長
- 開車來公司嗎？我們提供停車費補助喔！
- 上班氣氛很歡樂，希望你不介意有時候比較吵鬧的辦公室 
- 跟一群優秀的人一起工作是最棒的福利！其他還有更多，等你來體驗！
## 面試流程
- 全程使用skype/zoom 語音面試，只需要有穩定的網路，免去你的舟車勞頓
- 我們會有這些過程: skill interview--> HR和你聊聊天--> co-founder interview--> 和CEO聊聊天
- 所有的履歷都會經由HR轉給Team leader，討論是否要約面試
- 大家都有「知」的權利，我一定會通知你要不要安排面試或是有沒有下一階段，如果沒有收到，可以直接問問我
## 聯絡方式

Allie Chen
E-mail: allie.chen@positivegrid.com
Skype: ting8489qq

**Comment by AllieChen412** [comment]
嗨嗨~~特休資訊我有放唷 :)

**Comment by CodinCat** [comment]
沒寫天數吧

**Comment by AllieChen412** [comment]
嗨~~已經更新天數
進公司第1天就有7天特休，每多一年加2天，絕對不會低於法令規定，還有給薪家庭照顧假&病假讓你運用
感謝唷~~
