### ISSUE TITLE
【徵才】Suiqui 網頁前端工程師 Front-End Engineer 

### ISSUE THREAD

**Issue by yinshenchao** [f2etw/jobs#174]
## 團隊簡介/地點

瑞思是 2016 年成立的早期的新創公司。主要產品在提供人性化、符合直覺的雲端服務，幫助企業管理大量照片檔案與工作事項。地點在南港後山埤站附近。

創辦人之一在美國有十一年軟體公司工作的經驗，其中八年在紐約的 Google 擔任軟體工程師。

## 工作內容

創造符合直覺、清爽乾淨的網站，讓用戶在桌機與手機均可以有良好的使用體驗。

## 能力需求

1. 3 年以上前端程式開發經驗
2. 熟悉 AngularJS 或 React JS 的架構
3. 熟悉 CSS/HTML5
4. 熟悉 Responsive Web Design
5. 有獨立工作與解決問題能力

### 加分

1. 有使用 Django / Django Template 的經驗
2. 對 UI/UX 有基本概念
3. 對 Python  有些了解

## 薪資範圍

月薪 70K - 90k，保證 13 個月

## 工時/特休

1. 周休二日、第一年特休 10 天，第二年 12 天，之後皆優於法律規定。
2. 彈性上下班，09:00 ~ 10:00 至 18:00 ~ 19:00

## 福利/推薦項

1. 公司提供大螢幕
2. 辦公室提供飲料與零食
3. 定期聚餐
4. 健身房

## 聯絡方式

yinshen@suiqui.com

**Comment by yinshenchao** [comment]
已加上公司訊息，麻煩把移除"公司資訊未明"，謝謝。

**Comment by Rplus** [comment]
請問公司是這間嗎？
因為沒看到網址，Google 搜尋又沒找到相似連結
所以掃了一下商業司資料想確認一下 ：）
![image](https://cloud.githubusercontent.com/assets/1808835/24792535/fc79224e-1bb0-11e7-8cce-3079605db2c9.png)

**Comment by yinshenchao** [comment]
是的，謝謝。

**Comment by yinshenchao** [comment]
@Rplus  能麻煩幫我把公司資訊留言移除嗎? 我希望版面能乾淨一點，謝謝。
