### ISSUE TITLE
正法寶藏 前端工程師

### ISSUE THREAD

**Issue by kmsheng** [f2etw/jobs#175]
## 公司簡介
「正法寶藏工作室」是一個非營利組織。 致力推動西藏文化之經典、古籍研究及保存，提升西藏文化之知識教育，促進國際西藏文化學術之交流。

目標：
 - 西藏經典、古籍的現代化，以符合現代閱讀習慣，方便更多人閱讀
 - 經典資料之收集、整理及發佈於各平台，包括網頁、手機與平板
 - 為達以上目標，研發相關技術、工具與流程

https://www.youtube.com/watch?v=xngG85QPoUE

## 工作內容
開發與維護正法寶藏產品

## 基本需求
 - 二年以上網站前端工作經驗，可獨立作業
 - 精通 HTML / CSS / JavaScript
 - 熟悉任一前端框架 ( AngularJS / React.js / Backbone / Ember.js )
 - 熟悉 Node.js
 - 具備 RESTful API 介接經驗
 - 熟悉跨瀏覽器相容性開發
 - 熟悉 Git 版本控制系統
 - 瞭解 Web Security

### 加分條件
 - 熟悉任一後端語言
 - 用過 MySQL
 - 用過 Electron
 - 用過 ElasticSearch
 - 用過 AWS

### 招募人數
團隊目前有 2 位成員，還需要 2 位工程師。

## 薪資範圍
NTD $45,000 ~ $55,000 / 月

## 工時與休假 
10:00 ~ 18:00
週休二日，依國定假日休假
特休比照勞基法規定

## 福利
 - 可遠端在家工作，開會時才需進公司
 - 研討會門票公司幫你出, 但是去完需要做內部分享
 - 可提議購書清單, 公司幫你出
 - 不定期員工聚餐

## 我們希望你
 - 能自我學習，持續進步

## 公司地點
台北市信義區信義路四段 401 號 9 樓

## 面試流程

第一階段: 
用 Google Hangouts 遠端面試, 約 1 ~ 2 小時
 - 確認你的技術能力
 - 向你介紹正法寶藏的產品與團隊的合作方式
 - 聊聊你過去的工作經歷
 - 由你發問

第二階段:
到台北信義辦公室與法海師面談, 約 1 小時
 - 由師父確認你的人格特質
 - 確認辦公室環境
 

## 聯絡方式
請將履歷寄到 kmsh3ng AT gmail.com

2017/5/22 已徵到兩位前端工程師，暫時沒有招募需求

**Comment by yutin1987** [comment]
好猛的面試流程
