### ISSUE TITLE
【徵才】IBM Front-End Engineer, Interactive Experience

### ISSUE THREAD

**Issue by lilingh0922** [f2etw/jobs#180]
## 團隊簡介/地點
台北市信義區松仁路7號3樓
## 工作內容
1. Collaborate on all layers of development 
1. Work closely with business, design and engineering teams to craft delightful user experience from front end design 
1. Have strong interest and contribute to user experience design 
1. Innovate with evolving customer experience in terms of applying new technologies

## 能力需求
1. Familiar with front end development languages of JavaScript, HTML5, CSS
1. At least 2 years＋dedicated experience in Front-End Development 
1.  Experience with all browser compatibility (including mobile browser)
1. Proactive, good interpersonal and problem-solving skill
1. Strong attention to detail 
1. Team player and able to work independently
### 加分
1. Familiar with gitlab, webpack, version control software
1. JS and CSS frameworks like Sass, Less, Bootstrap 

## 薪資範圍
面議
## 工時/特休
* 09:00-18:00, 週休二日, 無打卡
* 第一年即享年假10天及當年度彈性休假
* 給薪休假共約17天(視當年度彈性休假多寡而異)

## 福利
年假、彈性休假、員工福利津貼、進修補助、健康人生福利、疾病及事故支付福利、自願體檢福利、人身意外傷害保險、旅遊意外保險、職工福利委員會、股票認股計劃。

## 教育訓練
1. 基礎技能訓練: 完整的新進人員在職訓練，為期四個月，與兩岸三地的同仁共同上課。
1. 專業技能訓練: 幫助員工根據自己的專業領域找到適當的課程，來提升專業技能，創造寬廣無限的職涯 
1. 管理階層訓練: 理論與實務並重，媲美 EMBA，奔向成功之巔。 包括新任主管、中階主管、高階主管、未來主管的培訓計畫 
1. 電子學習訓練: 這一系列豐富多彩的學習方式都就是利用技術和網路，為員工提供及時的 學習機會。內容豐富，包括所有的相關課程並有認證考試與線上測試等試題，讓學習者瞭解自己的學習程度

## 聯絡方式
Send your Chinese/English CV to cmlai@tw.ibm.com

**Comment by appleboy** [comment]
缺香蕉

**Comment by SeanChen01** [comment]
版主，這位同仁已離職，可以撤掉此職缺了，謝謝！
