### ISSUE TITLE
【徵才】 t,mot 集界科技

### ISSUE THREAD

**Issue by yutin1987** [f2etw/jobs#181]
![image](https://cloud.githubusercontent.com/assets/2505934/25473536/6e7d9c1a-2b62-11e7-831e-a1bf79018ed1.png)
穿搭有個性、玩音樂或滑板、騎單車、曾經出國旅遊、手做乾燥花、習慣用鋼筆寫字、玩當個創世神 Minecraft

以下針對工程師與設計師，如果你是行銷市場達人也歡迎 email 聯繫。

# 工作內容：
### 工程師：
- 用 React 開發 Web
- 用 ReactNative 開發 App
- 用 Jest 搭 Enzyme 寫測試
- 用 GraphQL 串接 Server 與 Client
### <del>設計師：</del>
- <del>用 Sketch 設計 UI guideline</del>
- <del>用 紙筆 規劃 App / Web flow</del>
- <del>用 Photoshop 或 Illustrator 製作行銷視覺</del>
- <del>用 Adobe After Effects 製作產品介紹（非必要）</del>

# 基本條件：
### 工程師
熟悉 Slack 與 Github、擁有正版 的 Sketch、熟悉 Linux Shell、擁抱開源。
### <del>設計師</del>
<del>熟悉 Slack 與 Github、擁有正版 的 Sketch、熟悉 快速架站平台 (Wix / Strikingly, etc)。</del>

# 加分項目：
穿搭有個性、玩音樂或滑板、騎單車、曾經出國旅遊、手做乾燥花、習慣用鋼筆寫字、玩當個創世神 Minecraft

# 工時與休假：
- 上下班時段，通常上午 10點開始有人進公司，然後下午 5點開始有人離開公司。

- 工作不一定需要在公司（請在 `Slack @channel` 告知在何處工作即可）

- 週休二日，依國定假日休假（休假期間 `Slack` 與 `Email` 無需理會）

- 特休／病假／產假／生理假／失戀假／照顧家庭假 / 技術聚會假，不扣薪全年無上限（請在 `Slack @channel` 告知不想工作），如需長時間休假可討論留職停薪。

> 注意：會配合「成員提案」或「營運團隊」去制定階段性目標，並依個人優勢分派任務，消極的工作態度，不排除會有「例行性資遣」。

# 員工福利：
- 沒有吃不完的零食：垃圾食物吃多對健康不好，我們寧可把這些預算作為伙食津貼轉入員工的薪資帳戶，讓你依個人喜好用餐公司附近生活機能極佳。也有提供微波爐與冰箱，自行做菜更健康，或者購買許多義美食品與大家分享。

- 沒有開不完的會議：每一位成員的時間都是寶貴的，請沒事不要找其他人開會，每週最多一次分享會，有需要請兩三人成組討論，並請善用非同步（Slack）方式進行討論。

- 沒有極限值的空間：工作空間的使用以不打擾到其他成員為主（ex 吃臭豆腐），可以邊工作邊喝啤酒，只要覺得這樣比較有效率即可，會安排固定的座位，但依舊可以依個人喜好或躺或趴或站著。空間內提供四間浴室不用搶也可以洗澡，24小時開放要過夜也不是問題。

設備採購補助每2年最高 30k，你可以用來買 MacBook Pro。

# 年薪：
Senior：年薪 100 萬新台幣以上
Junior：年薪 60 萬新台幣以上

# 應徵方式：
1. 請寫 **255以內的字** 說明**自己與眾不同的地方**，並附上常用的 Social Network 網址 (GitHub / Twitter / Linkedin / SlideShare / Instagram / Behance / Medium, etc)，Email 至 yutin_liu@tmotx.com 與mike_chen@tmotx.com （收到 email 後 3日內會與你聯繫）
2. 使用 Skype ／Zoom / LINE / Messenger 暸解工作習慣，聊聊興趣與夢想 （通話中會與你討論可面試時間）
3. 公司面談時會給一段**程式碼**或**介面流程**，請現場 review 發表看法，聊聊公司文化並討論薪資福利等。 （3 日內會通知你結果）
4. 與公司所有成員同仁聊聊天，並討論 offer 與 可報到時間。

# 公司簡介：
公司簡介 t,mot 是我們的名字，代表的是 together & moment - 把握當下，珍惜人與人之間每次的相遇! 我們利用QR Code, NFC, RFID等介面，建構背後的營銷平台切入市場，想要借此大膽的一探物聯網 (IoT)在線下結合線上的各種創新營銷手法的可能性，也想要透過這樣的過程進入社交領域。

# 經營理念：
我們不喜歡官僚主義，崇尚極簡、透明、對事以真、對人以和的公司文化 我們認為讀萬卷書不如行萬里路，出國、出差、旅行是公司必要投資的費用 我們重視效率，快速的自我學習能力、自律時間管理加上有效產出是自我衡量的標準 我們不提供免費食物，但是鼓勵大家運動及取得家庭生活的平衡 創業的路上陪伴的是恐懼與孤獨，唯有源源不斷的好奇心才能夠支撐大家前進。海賊王裡的索隆說：「人生中有些事你不竭盡所能去做，你永遠不知道你自己有多出色」，歡迎加入 t,mot 的世界。

# 產品簡介：
主要商品／服務項目：tmot marketing platform (tmot MP)，tmot APP (企業微工具與社群軟體)，相關物聯網 (IOT)營銷模式。

![image](https://cloud.githubusercontent.com/assets/2505934/25473596/a2b2b7c2-2b62-11e7-90d9-00865756d6e5.png)
![image](https://cloud.githubusercontent.com/assets/2505934/25473609/ab2c6dbc-2b62-11e7-9d08-67e7c2b41a1f.png)

更新 Log：

5/3 
由於 設計師 投履歷的量有點高，因此回覆會開始有些慢，還請見諒 <_ _>
設計師履歷只收到這週末 5/7（日）。
對 React Native 有研究的工程師，持續歡迎。 🏄 🏄‍♀️ 

5/6 
停止收 設計師 的履歷，並加上刪除線

**Comment by CodinCat** [comment]
基本條件是自備 Sketch？

**Comment by yutin1987** [comment]
@CodinCat 是的!! Sketch 就如同 Sublime 一樣，是熱愛這份工作的人會有的家常工具，購買正版支持一下開發團隊似乎是常有的習慣。

**Comment by CodinCat** [comment]
不是支不支持正版的問題，支持正版是當然的。但這些工具是公司要用來產出賺錢的，怎麼會是叫員工自己先掏腰包買？四海遊龍會叫員工自備鍋鏟嗎？照這樣如果要用 Highcharts 之類的東西是不是也抓個衰小的員工叫他出錢買 licence

Sketch 可以大量買也有折扣，對公司來說不會是多大的負擔吧

**Comment by yutin1987** [comment]
@CodinCat 你好!!! 公司設有「設備採購補助每2年最高 30k」。

這種「家常工具」，自由開發者/社群 時常在團購，開發者通常已經有一套公司再買一套似乎有些多餘。

而 開發流程上配合團隊需要非家常的工具，像是 TravisCi, Github Group, Codecov, Adobe CC, Atlassian... 等，全數公司皆已經購買正版授權。

就大大的舉例，也就是說四海遊龍不會要「員工自備鍋鏟」，但工作流程上需要安裝App，因此工作基本條件就會是「請自備智慧型手機」，沒必要員工帶著兩支智慧型手機跑來跑去。

**Comment by yutin1987** [comment]
@CodinCat  另 補充，當然而公司可以立馬採購更多的 Sketch 授權。
但 「基本條件」 就是，我們想要跟已經參與「自由開發者/社群 團購」的熱血開發者共事。 😄 🔥

**Comment by htchien** [comment]
工具沒有分什麼家常不家常的，工作上如果有用到，那公司就應該購買給員工使用，這跟你想要跟誰共事是兩回事。

如果只因為你想要共事的對象是比較可能會自購 Sketch 軟體的自由開發者/社群參與者，而想要便宜行事讓自己公司省下這一筆費用，那也大概讓人家知道你公司的文化如何。

我其實還蠻想知道您這樣會吸引到怎樣的所謂自由開發者/社群參與者的。

**Comment by justin3737** [comment]
我自己是Sketch 跟 Sublime都有購買...
因為平時就會想自幹一些side project來玩一下
畢竟Sketch 購買成本已經比Adobe系列便宜很多了

**Comment by yutin1987** [comment]
@htchien 這樣說好了！ 😄 
某人表示熱愛開源貢獻，但 github 上的貢獻紀錄 零，我大概只能猜測他的貢獻在不同地方（這當然也有可能）
某人表示熱愛設計UI或前端，但為曾參與過 Sketch 團購，我大概只能猜測 他有不同的開發習慣。（並定熱血開發者有時候會開發非公司的專案）

又或者說 開發者表示 沒有電腦，我大概只能猜測 他是用 Raspberry Pi 開發？（我真的有遇過）

家常不家常的定義其實很簡單：就是社群中是否有一群開發者發起團購過。我不基本條件不會有 Adobe CC

至於能夠吸引到什麼類型的人... 說真的我不確定，但我是一個已團購 Sketch 跟 Sublime 的開發者，而且討厭公司配發員工電腦的人。

**Comment by htchien** [comment]
@yutin1987 基本上你上面的這個回應跟你公司買不買 Sketch 是沒有關係的 XD

**Comment by yutin1987** [comment]
@htchien 是的 😄 👍  你抓到重點了!! 文中並沒有說「開發軟體需員工自備」而是「條件」是「一種習慣」

就像加分條件一樣： 穿搭有個性、玩音樂或滑板、騎單車、曾經出國旅遊、手做乾燥花、習慣用鋼筆寫字、玩當個創世神 Minecraft

這些習慣 可能會讓我們一起工作很愉快。

另補充： 不家常軟體 unity 公司也有買正版授權。

**Comment by zhengda** [comment]
![oj3sdgc](https://cloud.githubusercontent.com/assets/352349/25495036/597a0b5e-2bae-11e7-96e8-f1fa3ca59a1a.jpg)

**Comment by irvin** [comment]
有買個人版 CC 的人其實還應該不少⋯⋯ 
CC 沒有團購是因為團購（企業授權？）比個人版貴不少XD

**Comment by yutin1987** [comment]
@irvin 的確，CC 用量肯定不低，平面設計 與 視覺設計 需求度很高，至於會不會有個人去買個人版就不確定哩。
但就「UI 設計師」的角色來看，就如同這篇討論串的結果 Sketch 應該在 CC 之上
https://www.facebook.com/groups/TaiwanUIUXDesigners/permalink/932342030241314/

**Comment by judewang** [comment]
四間浴室好狂😄

**Comment by yutin1987** [comment]
樓上專業 是重點

**Comment by yutin1987** [comment]
更新資訊：
由於 設計師 投履歷的量有點高，因此回覆會開始有些慢，還請多多包涵 <_ _> 設計師履歷只收到這週末 5/7（日）。
對 React Native 有研究的工程師，持續歡迎。 🏄 🏄‍♀️

**Comment by kmsheng** [comment]
看起來還不錯, 祝早日徵到人才囉 👍

**Comment by cchuang0425** [comment]
話說回來，我是寫 Java 的，我也蠻希望自己能買一套 Intellij IDEA UE。但它可以在 Mac、Win、Linux 上執行，而 Sketch 只能在 Mac 上執行。若限定 Sketch 為工具，換句話說你們其實也隱含著限定員工一定要自備 Mac，排除了使用 Win 或 Linux 的工作人員。當然，設計師用 Linux 就像叫貓戴上狗鍊一樣，但 Win 上應也有為數不少的設計人才，這層過濾，你們也考慮過了嗎？

**Comment by kidwm** [comment]
@cchuang0425 我同意你說的，不應限定平台，但請不要歧視使用 Linux 的設計從業人員 Orz

**Comment by cchuang0425** [comment]
抱歉，我不是歧視 Linux 上的設計師，我是抱怨 Linux 的工具非常不利設計...XD

**Comment by Rplus** [comment]
這樣的徵才廣度固然狹隘了些
但我覺得以公司角度來限定平台並無不可
他們團隊的開發循環或許就是希望多加利用這些軟體來幫助溝通協調
不然連熟 PhotoShop 或 Sketch 都可以討論很久了是不 XD

**Comment by ssmlee04** [comment]
"熟悉 Slack 與 Github、擁有正版 的 Sketch、熟悉快速架站平台 (Wix / Strikingly, etc)" 這些很合理這沒什麼好討論的啊。DOS工程師也是可以去應征 Designer 只是政治正確浪費大家時間也沒有意義。

**Comment by yutin1987** [comment]
Re: @cchuang0425  cc. @Rplus @kidwm @ssmlee04
Sorry!!! 沒注意到留言，遲回應。
感謝大大們的寶貴意見，https://www.jetbrains.com/idea/ 是個好工具。

先談談 win, mac, linux ，別管「Sketch」了！
工程師的工作內容是：React, React Native (Android, iOS)。
單就這一項工作內容，可能就已經限定 MacOS 了。至於「自備 Mac」還是老話一句，公司規劃 2年3萬的設備補助，至於社會新鮮人會配 1台 MBPR。
至於設計師使用 win @@? 那他肯定沒在怕 WannaCry 的!!!
另一個問題就是 我們現在工程與設計團隊都適用 Sketch 設計 UI 耶 (=^ ^=) 大大們不要強迫我們用 Adobe 吧 QQ

最後關於 Linux 的問題，在未來徵才的工作內容是不需要 React Native 時，絕對歡迎 Linux 愛好者!!! 用 Raspberry Pi 來 coding 的我會愛上你 🥇

**Comment by yutin1987** [comment]
已徵到人，感謝大家 🙏
