### ISSUE TITLE
大麻新創 誠徵Frontend developer

### ISSUE THREAD

**Issue by peterlulu** [f2etw/jobs#193]
## 團隊簡介/地點
知道大毒梟Pablo Escobar嗎？ 想過大麻合法後會帶來什麼樣子的風暴嗎？ 隨著美國以及加拿大2018開始合法大麻, 開啟新時代的商場, 加拿大新創Hyer Technology Inc. 創立於2017 年大麻法案通過後, 我們目標成為北美大麻界的Uber Eat. 誠徵有經驗以及想賺大錢的前端工程師，共同參與這百年難得一見的國際大事

## 工作內容
Senior front end developer 
前端網頁製作 react.js,
前端手機製作 react native
邏輯好, 容易溝通, 需要長期配合

## 能力需求
熟悉 Javascript ES 6，CSS3，HTML5 技術 
對 React 有實戰經驗(若沒有我們願意指導)
對 NPM，Webpack 編譯執行或打包有經驗
對於 RESTful API 有串接經驗
了解 Git 並有實戰經驗
3年以上前端開發的資歷

### 加分
中英文精通

## 薪資範圍
40k 配股，60k+ 不配股 

## 工時/特休
全職，在家工作
## 福利/推薦項
配公司股票
## 聯絡方式
0903340446 Peter

**Comment by Rplus** [comment]
dup. with #192.
close this item.
