### ISSUE TITLE
[台北] 蹦點科技 誠徵 React 前端工程師

### ISSUE THREAD

**Issue by tungsheng** [f2etw/jobs#196]
## 團隊簡介

2016年蹦點科技成立，主要產品為滿房寶旅宿管理系統，讓民宿、旅店輕鬆快速管理房間、訂單及旅客，整合訂房網頁、房間庫存管理、客戶管理、財務報表統計和金流系統。蹦點科技致力提供最強大、好用的旅宿管理工具，也將延伸到各項能改善旅宿營運與生活的事情。

在 Popup，我們努力工作，集思廣益，打破拘泥的想法與心胸。
在 Popup，一起腦力激盪，最棒的點子每天蹦出。
我們堅信樂觀正面的信念、共享互助的態度、加上資訊科技的力量，必能改善台灣的觀光旅遊業，更能對社會有所助益。

數位時代採訪文：https://www.bnext.com.tw/article/46997/full-house-treasure
勇於挑戰、喜愛創新、充滿熱忱、勇於承擔、對人性關懷的您，請加入我們！

## 地點

台北市中山區林森北路575號4樓之10

## 產品

滿房寶旅宿管理系統： https://room.fullinn.tw/

## 工作內容

- 維護現有系統與系統後台前端的開發
- 設計良好使用者體驗的前端 
- 頁面的樣式調整
- 與後端工程師溝通並串接 GraphQL

## 具備能力

- 擁有開發前端的經驗，並瞭解 JavaScript （Function Scope、ES6 module、Event Loop ）
- 自行閱讀英文技術文件（MDN、Can I Use 等）的能力
- 使用過前端任一框架：React.js、Vue.js 或是 AngularJS（我們使用 React.js）
- 熟悉 Git 或是 SVN

## 加分能力

- 瞭解 GraphQL
- 使用過 Apollo GraphQL Client
- 瞭解 Webpack
- 寫過前端 Testing
- 懂的如何運用 HTML tag 及 JSON-LD 等相關技術加強 SEO

## 薪資範圍

月薪 5萬 到 7萬

## 工時/特休

- 上班時間：9:00～18:00 

- 午間休息：12:30～13:30
- 週休二日
- 國定假日比照政府機關休假

## 福利/推薦項

- 滿一年享有特休 7天假期
- 三節獎金（依公司盈餘與績效發給）
- 與頂尖的夥伴們共事、激盪與成長
- 我們持續成長茁壯，提供最好的學習環境和舞台發揮

## 聯絡方式

李先生
tony@popup.com.tw

**Comment by tungsheng** [comment]
此職缺地點改在台北，感謝！

**Comment by Rplus** [comment]
@tungsheng 有需要更改什麼 tag 嗎？

**Comment by tungsheng** [comment]
可以拿掉 work remotely 感謝！

**Comment by tungsheng** [comment]
職位更新，重新Po！
