### ISSUE TITLE
[誠徵] 普奇科技 (ZK)  前端工程師

### ISSUE THREAD

**Issue by jumperchen** [f2etw/jobs#20]
公司: 普奇科技 (ZK or Quire.io) 
職稱: Front End Software Engineer (2+ year)
英文能力: toeic 750+ (佳) or coding 能力強也行，那英文能力就不那麼重要了。
薪資(年薪): 70萬~110萬
人數: 2+
履歷寄到: jobs@potix.com

HARD SKILLS & QUALIFICATIONS:
• 2+ years experience in building world class, public facing web applications. Please provide a portfolio of sites/applications you have built.
• Deep understanding of OOP and event-driven programming
• Proficient in HTML5, CSS3, the DOM, Object Oriented JavaScript and JS libraries, W3C standards
• Experience in ZK, Java, or other server side scripting and compiled languages

SOFT SKILLS:
• Excellent teamwork skills. Flexibility and collaboration with cross functional groups.
• Excellent visual, verbal, and written communication skills in English
• Proactively guide, mentor and help other team members

額外福利:
 * 可配 Macbook Pro 13吋 16 GB RAM
 * 可在家工作

Reference: 104 page
http://www.104.com.tw/job/?jobno=3ff71&jobsource

**Comment by Rplus** [comment]
請問是已徵到了嗎? : ]

**Comment by jumperchen** [comment]
Yes.

**Comment by Rplus** [comment]
恭喜～ :+1:
