### ISSUE TITLE
【徵才】Full Stack Software Developer/ 總部與研發中心位於台北的新創社會企業

### ISSUE THREAD

**Issue by migotalent** [f2etw/jobs#205]
## 公司簡介

Migo (www.migo.tv) is a consumer focused innovation company addressing the digital divide in emerging markets, with over 200 Imagineers in Taipei and Manila. Headquartered in Taipei with primary operations in the Philippines, Migo is a one-of-a-kind service that harnesses technical innovation to deliver accessible and affordable entertainment and education to billions of consumers who live on $5-$10 a day, in markets such as the Philippines, Indonesia and Africa. Migo's technology, a combination of hardware and software developed in-house, is designed specifically for the unique infrastructure and economic challenges that exist in our markets. We have designed, built, and tested which is uniquely capable of serving the most price- sensitive consumer by cutting the costs of delivering data by 100 times.

Migo is led by Barrett Comiskey, inducted into the U.S. National Inventors Hall of Fame as one of the fathers of E Ink (the technology behind the Amazon Kindle), which he developed as an undergraduate at MIT. He holds an M.B.A. from Stanford University. Barrett is a proven entrepreneur with a track record of success. He has been living in Asia for the last 15 years, and Migo is the culmination of decades of thought and experience.

We are a young, ambitious, and innovative company pursuing a transformative mission. We are currently expanding operations in the Philippines and preparing to scale in the region.

Migo 熱鬧點科技是一間外資新創社會企業，全球研發暨營運總部位於台北，以獨特的商業模式創造了一個專為新興市場的消費者客製化的服務及內容平台，並計畫從東南亞地區出發，逐漸拓展到全球的新興市場。

Migo致力於解决開發中國家(如菲律賓，印尼，印度等) 三十億消費者對於娛樂及教育資訊不易取得的窘境。相較身處台灣，取得光纖與第四台有線電視的服務就像打開水龍頭一般自然，這些市場往往基礎建設落後，網路普及率低，購買力也較不足， 多數民眾難以獲取在先進國家的豐富數位資訊與內容。目前Migo已深入菲律賓市場，以獨創的技術與硬體設備，讓消費者以親近的價格於我們佈設的熱點下載影音內容，並能夠於行動裝置上離線觀看，不再受到網路的限制。

公司的創辦人兼執行長，Barrett Comiskey 畢業於美國麻省理工學院（MIT），擁有史丹福（Stanford）商學院的企管碩士（MBA）。今年Comiskey因發明電子墨水(E-Ink) ：驅動亞馬遜的Kindle和市面上其他品牌電子書的核心科技入選美國專利商標局國家發明家名人堂。過去的得主包括2012年入選的賈伯斯以及2015年入選的諾貝爾獎得主中村修二。 Comiskey是至今還在世的百位發明家中最年輕的一位。他定居於亞洲有近十五年的時間，是一位成功且經驗豐富的創業家。

目前Migo在台灣和馬尼拉有超過200位Imagineer，分別來自台灣，菲律賓及美國的各個科系和不同的背景，其中有工程與企業管理背景，也有來自哲學與生物系的團隊成員，十分多元及國際化。

小知識：什麼是社會企業？「社會企業」指的是一個用商業模式來解決某一個社會或環境問題的組織，例如提供具社會責任或促進環境保護的產品/服務，為邊緣族群創造就業機會等。其組織可以以營利公司或非營利組織之型態存在，並且有營收與盈餘。其盈餘主要用來投資社會企業本身，繼續解決該社會或環境問題，而非為出資人或所有者謀取最大的利益。
## 團隊簡介/地點

Location: Taipei, Taiwan (business trips to Manila, Philippines required) 

Migo is a global team of Imagineers – and the team is growing. 

As Imagineers, we are deeply committed to and bound together by our mission: bringing entertainment and education to everyone through innovation. In this endeavor, we pursue the constant improvement of ourselves, our teammates, our organization, and the lives of the people we serve. We are seeking new Imagineers who yearn for the opportunity to work with a purpose, devoting their days to creating & delivering solutions to the world's most pressing problems. We value potential over experience, character over résumé, and curiosity over knowledge. 

In a typical week at Migo, an Imagineer stretches and builds many different muscles: working closely with other Imagineers across the company through cross-functional teams, developing new abilities, and having targeted discussions with peers and leaders to deliver ever greater results. Every week, Imagineers strive to produce world-class output while learning, following their strongest passions, and discovering new ones. Migo is where they pursue their life's work. 

Imagineering at Migo is the opportunity to pursue meaningful work, to be at the top of your game, and to build a company which will transform the lives of the next generation of emerging market consumers.

Migo招募人才的條件與一般企業不同，徵才的先決條件並非學歷，經驗與技能，而是人才的態度，價值觀與思維模式。我們相信能力和專業知識能夠在公司裡透過執行中學習，因此在Migo有大量資源投入人才培訓的計畫，幫助Imagineer學習如何解決問題，思考以及研究，以培養出全方位跨領域的人才。

Migo認為應該賦予人才等同的機會發掘自我和其可能性，而不是被過去的學歷和背景限制。在Migo，所有成員共用 Imagineer這個職稱，為了打破傳統組織架構及職務分配模式，每位Imagineer都需要縱觀全局，清楚了解他們在公司不同階段所扮演的角色，體認大家是一個團隊，共同朝著一致的目標前進。 Imagineer的每一項工作內容與日常決定都能直接影響公司長期的發展。

Imagineer的工作內容以問題作為導向，公司鼓勵思考 “how could we?”，利用跳脫框架的思維模式大膽假設，勇於嘗試 ，透過實作的過程中學習。Migo塑造了一個鼓勵不斷學習的環境，也提供一個無邊際的空間讓Imagineer發揮與成長，而成長並不會被職務分配及工作資歷所限制。成長的機會是以每個人的成長曲線所決定，當Imagineer無法從工作中繼續學習，導師會協助找尋更有挑戰性的工作，其方法有擴大工作範圍或將一個不熟悉領域的問題交給Imagineer解決。

## 工作內容

The Software Engineering function is part of the greater Product team comprised of Imagineers from a diverse range of backgrounds in engineering, science, and design. We all share a profound understanding of customer needs and the ability to synthesize those needs with business objectives and technology solutions. Innovation doesn't happen on its own, and we're at the forefront of it doing real research and development to solve problems that don't have answers. We apply interdisciplinary engineering knowledge and user-centered design principles within local market contexts to design and build holistic experience ecosystems that bridge the technology and infrastructure gaps present in Migo's markets. We participate in the full product development process from conception of new product ideas through analysis of business viability through development into real products, all while maintaining close collaboration with teams across the organization and our customers.

•	Architect, design and implement highly available and scalable consumer facing and enterprise solutions on a highly decentralized service platform. 
•	Full stack service and application level architecture design, development and implementation: from front end user experience to building a robust platform service 
•	Daily involvement in agile software development life cycle with close collaboration with cross-functional teams 
•	Continuously discover, evaluate, and implement best practices and tools to maximize development efficiency

## 能力需求
•	Strong analytical skills required to perform high frequency decision making during development cycle 
•	Comfortable with ambiguity to form living specs and learning through rapid experimentation and readings
•	Is customer-centric and passionate about building high quality, scalable software
•	Strong growth mindset and a desire to evolve into a well-rounded interdisciplinary thinker 
•	1-5 years of experience in software development 

### 加分

Exposure and expertise in one of the following domain knowledge is a plus (not must have):
•	Data manipulation and processing with relational database or NoSQL
•	Android/iOS mobile app development
•	Server side backend frameworks such as Node.js, Ruby on Rails, Java Spring, Python Django, etc.
•	Modern frontend framework such as Bootstrap, AngularJS, ReactJS, etc
  
## 薪資範圍

580K-1.3M/year (fixed 13 month salary)

## 工時/特休

Responsibility/Trust based. Unlimited leaves. 

## 福利/推薦項

• Health/Labor Insurance 
• Company Issued Laptop & Mobile Phone 
• Flexible Vacation Leaves 
• Free Snacks and Drinks (Free beer every Friday!) 
• Company parties to celebrate special events or holidays (Halloween, Christmas, End of Year etc.)

【Our Number One Benefit】 
The number one benefit at Migo is the responsibility, trust and limitless opportunity for growth we give each Imagineer. Leaders focus on insight and results, not process or policies.

Imagineers at Migo are working on a first-in-the-world service and technology, a vision, that is big enough to change the lives of billions of underserved people in the world. Migo is committed to helping Imagineers reach their unlimited potential. Curiosity and Learning is at the core of our values.

We have a structured Imagineer training which will teach Imagineers the Migo way of thinking and doing. We only hire people that are intrinsically motivated to learn and grow. We are committed to providing the resources our Imagineers need to be the best, not just in Taiwan, but globally.

##應徵/ 聯絡方式

Apply through our company website www.migo.tv/join by clicking the "Join Us" button at the top right corner.  

If you have any questions please email cecilia@migo.tv

**Comment by migotalent** [comment]
[Migo_Software Development_20170710.pdf](https://github.com/f2etw/jobs/files/1164290/Migo_Software.Development_20170710.pdf)

**Comment by iamken1204** [comment]
580K- ...130K？

**Comment by migotalent** [comment]
@iamken1204  thank you for catching the mistake!
