### ISSUE TITLE
【Eatgether 食我】React.JS 網站前端工程師 Frontend Developer

### ISSUE THREAD

**Issue by magicsky0831** [f2etw/jobs#208]
**公司介紹**

《食我餐飲顧問股份有限公司》是一個成立自2014年的新創公司，致力於透過網路科技創新應用服務，「創造更美好的用餐體驗」。分別於2014年與2016年完成種子與天使輪投資，分別來自於聯合報系與多位業界知名天使投資人。公司主要的產品為自2016年上線就獲得廣大好評的聚餐交友 APP《Eatgether》

目前團隊成員約十人，是個平均年齡近30歲，同時具備年輕活力與技能經驗的團隊。動靜分明是我們的團隊文化，彈性自律是我們的工作風格，在這裡沒有太多的規範，上下班不打卡，也可自行安排工作時間，高度的自律搭配目標導向的管理模式，成就了一個快而精實的新創團隊。

目前整個團隊都聚焦在開發 Eatgether，朝著打造一個來自台灣的國際化餐飲社交平台而努力。我們認為新創公司的人才就是一切，每個加入的人都會改變這個團隊與產品，非常期待有你的加入！

詳細內容可參考Yourator徵才頁面
https://www.yourator.co/companies/Eatgether/jobs/2696

# 工作內容

協助團隊開發與管理Eatgether網站版，功能會與APP版本相同， 
因此正在進行大改版中，目前是以React.JS為前端架構做開發。

1. 開發與維護Eatgether網站版 
2. 與後端協作開發新功能與系統 
3. 若有後端能力會視情況參與其他專案

**條件要求**

具備實際的網站開發經驗與作品 
熟悉 JavaScript (ES6), ReactJS or VueJS 前端模組化開發技術 
熟悉 CSS3, RWD, Sass 前端設計技巧 
具備使用 UI Framework 經驗 
請提供 GitHub 或作品參考 
熟悉 Git 協作

---加分（如會後端技能更好） 
會用 Next.js 
熟悉一點後端運作

**公司福利**

．彈性上下班與請假制度 
．合夥與配股機會 
．外部進修課程與購書補助 
．每月團隊聚餐

**薪資範圍**

NT$600,000 - NT$850,000(年薪)

應徵方式：
1. 直接寄送履歷到 jobs@eatme.tw
2. 直接從Yourator應徵：https://www.yourator.co/companies/Eatgether/jobs/2696

**Comment by SimonSun1988** [comment]
你好，這個 issue 可以 close 了，麻煩版主了
