### ISSUE TITLE
舒服美數位隱形矯正徵 Javascript 工程師 (無經驗新人可)

### ISSUE THREAD

**Issue by jackypan1989** [f2etw/jobs#211]
## 團隊簡介/地點
舒服美(SOV)是目前台灣最知名的數位隱形牙套團隊，藉由電腦軟體輔助3D診斷、設計、製造等系統，生產出一套專屬於客戶的SOV數位隱形矯正牙套。團隊工作地點在南京重慶交叉口(建成圓環)，目前成員已達30人，期待有興趣的新人加入

## 工作內容
資訊系統開發 (內控/醫療/3D模型)

## 能力需求
1. 會使用 git
2. 會使用 vim/sublime text/atom/VS code 其一
3. javascript 基礎知識

### 加分
1. 玩過 Vue, Angular, React 其一
2. 對 haskell, clojure, purescript 等函數式編程有高度興趣

## 薪資範圍
年薪 60 to 100萬 (無經驗 to senior)

## 工時/特休
彈性上下班 (0930~0630

## 福利/推薦項
1. 生日禮金
2. 三節禮金
3. 吃不完的零食
4. 配全新mac book pro retina
5. 配29吋寬螢幕
6. 健身補助
7. 員工旅遊
8. 公司男女比優良 (很多帥哥美女)

## 聯絡方式
jackypan1989@gmail.com

**Comment by Rplus** [comment]
官網是這個嗎？ http://www.sovmedcare.com/

**Comment by goden** [comment]
您好，我有興趣，該怎麼連絡呢?
