### ISSUE TITLE
[徵才] 圖特科技(台中) - Front-end Engineer (Senior/Junior)

### ISSUE THREAD

**Issue by yuri-wang** [f2etw/jobs#212]
## 團隊簡介/公司地點
圖特科技有限公司創立於 2017 年，總部位於台灣台中市南屯區，源自於一群熱愛程式、富有創造力的熱血青年共同成立。主要以研發科技娛樂及其附加產品為基礎，期盼能提昇人們的生活品質，並將歡樂帶給每位使用者。公司追求的目標不僅是將創意投入於現有已開發的產品，更要不斷求新求變開發不同於市場之新穎產品，以及致力於將產品推向符合國際標準認定的層級，未來將不斷追求技術的創新與提昇，並將產品市場定位於國際

 上班地點：台中市南屯區
公司統編：61845749

## 工作內容
* 配合後端 API 文件製作功能介面
* 針對公司現行系統功能擴充及維護以及新專案功能開發
* 專案管理採 scrum + kanban
* 與團隊成員合作完成以上任務 

## 能力需求
* 工作經歷：前端開發經驗 1 年以上
* 熟悉 JavaScript(ES5/ES6)、HTML、CSS(SCSS)
* 擁有任一 JavaScript framework 開發經驗，如 Angular、React、Backbone、Vue 等 (我們使用 Vue)
* 使用 GIT 版本控制(Gitlab)
* 具有團隊溝通能力且共同協作能力
* 具備自我學習能力

## 加分
* 了解 WebSocket(socket.io) 運作並且會運用

## 薪資範圍
月薪 40000元~60000元

## 工時/特休
※ 彈性上班 9:00 ~ 10:00，工作滿八小時後下班
 ※ 週休二日&國定假日比照政府機關休假
※ 特休依勞基法規定

## 福利/推薦項
※ 年薪保障 14 個月 
 ※ 公司配有義大利 Delonghi 全自動咖啡機，與提供高級咖啡豆，不愛咖啡公司也有提供茶包 
※ 每週補滿零食、飲料櫃
※ 每週有一小時的 Happy hour 
※ 每月有部門活動，聚餐或是遊戲 
※ 年度員工旅遊、尾牙 
※ 提供教育訓練補助，參加技術相關活動能請公假

## 聯絡方式
聯絡人：Yuri
E-mail： yuri@pharaoh-gaming.com

**Comment by Rplus** [comment]
沒官網的話可以附註商業司資料或統一編號唷

公司基本資料
* 統一編號  61845749
* 公司狀況  核准設立   (備註)
* 公司名稱  圖特科技有限公司
* 資本總額(元) 1,000,000
* 代表人姓名 張雅婷
* 公司所在地 臺中市南屯區文心路一段186號20樓
* 登記機關  臺中市政府
* 核准設立日期  106年07月20日
http://gcis.nat.gov.tw/pub/cmpy/cmpyInfoAction.do?method=detail&banNo=61845749

**Comment by yuri-wang** [comment]
@Rplus 
已修改附上統編 感謝 😄 

歡迎投履歷
