### ISSUE TITLE
【徵才】PHP 工程師 - 無名雲端科技有限公司

### ISSUE THREAD

**Issue by HugoUno** [f2etw/jobs#226]
## 團隊簡介/地點
我們是一間新創遊戲軟體開發公司，主要開發項目為Web遊戲平台，我們的公司成員都是充滿幹勁的年輕人，誠摯歡迎您加入一起打拼！

工作地點：台北市信義區東興路

## 工作內容
1. 產品需求開發
2. 產品重構，目前產品沒有使用 framework , 期望導入 Laravel

## 能力需求
1. 熟悉 PHP 開發
2. Linux 基礎
3. 熟悉 Git 版本控管系統
4. HTML / CSS / JavaScript 的排版運用
5. 使用至少一個 PHP framework (Laravel, Yii, CodeIgniter...)
6. JavaScript

### 加分
1. 對 DevOps 有一定了解
2. 使用過 Jenkins 或 gitlab CI 等等 CI 工具
3. 了解 Docker 操作

## 薪資範圍
50,000~80,000
年終兩個月(保證 14 個月薪水)

## 工時/特休
9:00~18:00 彈性上下班

## 福利/推薦項
每月員工聚餐
每月零食補給 (可自選)
週休二日、年假(依勞基法)

## 聯絡方式
cv.wuming@gmail.com

**Comment by Rplus** [comment]
是前後端都寫嗎？
不然怎麼一直 PO ？ #225
