### ISSUE TITLE
凌典科技徵 RoR＋前端工程師

### ISSUE THREAD

**Issue by duncanhsieh** [f2etw/jobs#23]
# 公司簡介：
* 公司為小型新創公司，不用太拘束自在一點。
* 除會議討論以辦公室為討論地點，其餘時間自由選擇工作地點時間 
( 大家很討厭被綁住的感覺、然後夜貓子很多) 
* 這間公司沒有不會coding的員工，最爛的大概是老闆 ( 只會寫前端而已 )

# 主要產品：
* RFID感應式會員系統
* Ibeacon資訊推播工具

# 薪資條件
4萬/月

# 地點：Futureward Coworking Space ( 近民權西路捷運站 )
* 空間內有很多maker的相關工具 雷切機 / 3D Printer / CNC / 電焊室 / 攝影棚
* 隔壁公司很友善，有時會大家互請零食
* 空間營運方本身很多相關活動，每逢佳節都有社群聚會和小party
	
# 技能需求：
* ROR
* JS

# 工作內容項目：
* D3.JS
* API撰寫、串接
* ROR系統開發
* APi / 系統設計文件撰寫

# 相關開發工具：
* fire.app
* bootstrap
* github
* amazon ec2

# 需要資料：
* 個人Github
* 過去執行的ROR實作案例 ( 網址 , 連結 ) 

# 聯絡方式：
* chn894 [at] gmail.com
* 0 9 3 1 6 2 1 3 1 3
* 劉先生

**Comment by duncanhsieh** [comment]
放好久該關掉了

**Comment by Rplus** [comment]
請問是已徵到了嗎？
