### ISSUE TITLE
【徵才】公共電視迎向全媒體，誠徵前端工程師

### ISSUE THREAD

**Issue by liaoppj** [f2etw/jobs#233]
## 團隊簡介/地點
公共電視是屬於大家的電視台，近來公視除了在傳統媒體提供優質的節目外，也積極朝向新媒體發展，10月將推出OTT影音平台【公視+】，更挑戰更多數位媒體。我們期待有程式高手加入我們的團隊，一起來做有意義的事。
## 工作內容
1.網頁前端程式及Mobile Web前端程式開發及維護，優化前端設計，並與企劃及其他程式同仁溝通協調。
2.互動式圖表、報表或互動遊戲網頁程式撰寫
3.相關程式專案執行。
4.不斷創新研究相關技術
## 能力需求
1.熟悉HTML5/CSS3/Javascript 或jQuery，且至少熟悉一套JS Framework。
2.至少須了解一種後端程式，如php或asp。
3.熟悉跨裝置與跨瀏覽器相容技術
4.具有美術相關技能及美感者 優先考量
5.對UX領域及新媒體保持熱誠者
6.需具要有高度溝通能力，能與企劃及後端人員協同合作，並樂於技術分享者。
### 加分
* 具網站/手機平台前端開發經驗者尤佳
* .具獨自完成開發專案經驗
* .具備 Responsive Web Design 經驗
以上有2年以上相關經驗尤佳。
## 薪資範圍
5萬~6萬。
## 工時/特休
按照勞基法，不虧待勞工，要不然我們會被罰錢。
## 福利/推薦項
* 有為全民服務的榮譽感。
* 基本上有一個月的年終獎金。
* 績效看表現。
(以上內容完全據實以報)
## 聯絡方式
如果有個人履歷、自傳或照片的電子檔，請註明應徵職務後E-mail至公共電視 新媒體部互動媒體組廖小姐liaoj@mail.pts.org.tw

**Comment by liaoppj** [comment]
目前仍積極徵才中。請大家多多支持(前一陣子正忙一個OTT專案，很多問題剛解決)未來還亟需大家共同協助。

**Comment by liaoppj** [comment]
目前仍積極徵才中。請大家多多支持（前一陣子正忙一個OTT專案，很多問題剛解決）未來還亟需大家共同協助。

**Comment by liaoppj** [comment]
我們已經找到人才了，謝謝！

**Comment by Rplus** [comment]
若已徵得，可以關 issue 唷
