### ISSUE TITLE
【徵才】樂思互動徵 後端工程師

### ISSUE THREAD

**Issue by christiehsu** [f2etw/jobs#235]
## 團隊簡介/地點 台北市松山區
Virtual Joy Interactive co., ltd.成立於2017年，據點在臺北，爲一新創APP軟體研發  
科技公司，主要爲美國/全球直播平臺做系統開發，目前已運作的系統已經在市場取得成   
績，未來將面向全球展開，我們將會與全球各地運營商接軌，我們的願景是成爲在各特定  
領域中，成爲全球最好的直播服務提供商。

## 能力需求
Job responsibility:
- Develop and operate scalable, reliable and maintainable service-based softwares and related components. 
- Cowork with team members to design system architecture, choose proper technologies and plan development. 
- Responsible for laying the foundation for the platform as well as proposing solutions to ease software development, monitoring of software, etc. 
- Profiling and performance tuning of critical components 
- Deploy system to production and monitor service health.

Requirements:
- Ability to build web services on Linux. 
- Good at any of the listed language: Python / C / C++ / Scala / Go. 
- Good knowledge of Network API Design ( e.g. REST or GraphQL).
- Good understanding of any SQLSQL database (MySQL / MongoDB / Redis / etc.) 
- Familiar with git. 
- Team player and able to work independently. 
- 4+ years of experience in Internet Industry. 
- Good at profiler and debugging tools. 
- High performance network service on Linux. 
- Design and architect large scale distributed system. 
- Design and implement distributed algorithm and data structure. 
- Familiar with HTML and Javascript. 
- Familiar with Nginx / HAProxy. 
- Familiar with operation automation tool (such as Ansible). 
- Familiar with continuous integration / continuous deployment 
- Familiar with monitoring and alert system (Prometheus / Nagios). 
- Familiar with Amazon Web Service or Google Compute Engine.
- Deep understanding of the technological landscape, ranging from DNS, HTTP, CDN

## 薪資範圍
80k - 120k 以上

## 工時/特休
每日八小時，週休二日

## 福利/推薦項
年終獎金 (到職滿一年，未滿按比例計算)
三節禮金/禮品 (同上)

## 聯絡方式
christie@funs.cool

**Comment by appleboy** [comment]
@christiehsu 需要 Go 語言專長的話，可以來這邊發布

https://github.com/golangtw/jobs/issues
