### ISSUE TITLE
【徵才】 Carousell 旋轉拍賣徵求 前端工程師

### ISSUE THREAD

**Issue by happyselina** [f2etw/jobs#246]
## 公司簡介
Carousell 旋轉拍賣為社群拍賣平台，2012 年在新加坡上線後，已拓展至台灣、香港、印尼、馬來西亞、菲律賓、澳洲等國家。現有超過 6,500 萬件刊登商品，為全球成長最快及最大的行動拍賣平台之一，在新加坡、台灣與香港均於手機購物應用程式排名中名列前茅。

## 技術介紹
後端目前為 Python & Django，資料庫是 PostgreSQL，未來後端會使用 GoLang (現已逐漸轉移中) 並搭配 Microservices ，前端是 NodeJS, ReactJS and Fluxible (也在轉移到 Redux 中)，我們的伺服器皆架設在 Google Cloud Platform ，每個團隊都跑 Scrum，以上是 Engineering team 的技術簡介～

## 工作內容
- Build new and key features for the Carousell web platform by working closely with the product and design teams.
- Analyze and optimize performance and reliability of the web app.
- Build a high performance dynamic web application with technologies such as React, Flux, Webpack, ES6, Node.js, etc.
- Take full ownership of projects from design (collaborate with the design team) to implementation and deployment.

## 能力需求
- Commanding grasp of HTML, CSS and JavaScript
- Experience with modern JavaScript libraries and tooling
- Familiarity with all aspects of MVC web applications (especially those built on Django/Flask)
- Proven ability to ship beautiful, stable and high-performance desktop and mobile web applications from start to finish
- Experience with automated testing framework
- Strong Computer Science background

## 薪資範圍
- NTD$ 77,000-154,000/月 (約新幣 3.5-7K)

## 工時/特休
- 彈性工時不打卡 (10:00 - 19:00)
- 週休二日，依國定假日休假
- 特休優於勞基法
- 加班制度依勞基法

## 福利制度
- 全額補助參加技術年會
- 超佛心員工認股權 (管理職可再議)
- Apple 電腦、外接雙螢幕與舒適座椅
- 免費開放零食櫃，歡迎許願你想吃什麼
- 每週五免費午餐，溫馨 Family Friday 讓我們更認識彼此
- 第一年即享 14 天年假，還可在任一旋轉拍賣海外辦公室 remote work

## 工作地點
- 臺北市中山區南京東路一段92號4樓（新辦公室）

## 申請方式
- Software Engineer, Frontend Web http://grnh.se/5e2wjf1

## 面試流程
1. 請透過上述連結(http://grnh.se/5e2wjf1) 申請、提交“英文履歷”
2. 通過履歷審核者，將與 Technology Recruiter 進行第一階段線上面談
3. 通過線上面談者，將會收到一份 coding challenge (請於 7 天內完成)
4. 通過 coding challenge 者，將安排線上面談 (先與工程師、後與創辦人) 
備註：面試皆以英文進行

## 聯絡方式
若有任何疑問，歡迎來信 carol.lin@thecarousell.com 詢問，謝謝！

**Comment by happyselina** [comment]
@Rplus 麻煩請幫我加 label:

- Flexible working time 
- [B] Python 
- [F] React 
- 年薪百萬 
- 求才
- nodejs
- scrum
- GIT
- senior

麻煩了，謝謝 😊

**Comment by Rplus** [comment]
看起來應該不是 `Flexible working time`，只是上下班有個緩衝時間對吧？

**Comment by happyselina** [comment]
@Rplus 謝謝您的詢問！
嗯嗯，我們的工時基本上很彈性，也提供大家一週一次work from home，希望的是大家能依據自己最有效率的時段工作！不過因為和新加坡產品團隊的接觸的頻率蠻高的，因此還是需要訂一個大家統一的工作時間，但自行調整和安排工作時間的空間還是蠻大的哦！謝謝您！ 😄
