### ISSUE TITLE
【徵才】Front-End Engineer 前端工程師 – Accupass活動通

### ISSUE THREAD

**Issue by Jakevin** [f2etw/jobs#253]
## 團隊簡介/地點
盈科泛利股份有限公司 (Accuvally Inc.) 的主營業務為「Accupass活動通」，是亞太地區最具影響力的活動SaaS平台。除了為各式活動主辦單位與個人提供辦活動及售票的服務，也有完善的行銷推廣功能可供主辦單位使用，深受各界客戶信賴。

「Accupass活動通」與中國的姊妹站「活动行」 攜手締造佳績，成為在亞太地區每月活動數與主辦單位數最多的活動SaaS平台，於2014年獲得軟銀賽富、DCM、高通資本A輪投資，在今年2017年完成數億元的A+輪融資，公司估值突破15億元，本輪融資包括日本最大人資網站Recruit、中國大陸騰訊及共享辦公業者UrWork三方共同參與。

我們接下來將整合多方資源，快速擴展到亞洲各國，這是一段艱辛及困難的旅程，我們需要更多的夥伴，在這條路上和我們一起奮鬥。
現在就加入Accupass活動通，和我們一起為人們創造更多故事與回憶！讓每個人的生活都能因活動而生動！

地址：[台北市中山區民權東路一段45號3樓](https://www.google.com.tw/maps/place/10491%E5%8F%B0%E5%8C%97%E5%B8%82%E4%B8%AD%E5%B1%B1%E5%8D%80%E6%B0%91%E6%AC%8A%E6%9D%B1%E8%B7%AF%E4%B8%80%E6%AE%B545%E8%99%9F/@25.0629296,121.5225481,17z/data=!3m1!4b1!4m5!3m4!1s0x3442a944bac52587:0xda28ada1fb8c2b7c!8m2!3d25.0629296!4d121.5247368?sa=X&ved=0ahUKEwiQ-tXbn_zWAhUHmpQKHSrzCs0Q8gEIJDAA)

公司：盈科泛利股份有限公司
網站：[Accupass-活動通](https://www.accupass.com)

## 工作內容
負責依照產品功能需求開發前端網頁程式，並且根據視覺設計需求完成CSS切版，搭配完成交互體驗、質感、性能等兼備俱佳的網頁。

## 能力需求

- 2+年軟體設計開發工作經驗，能夠分析、設計、實做產品，且有網站專案上線經驗
- 熟悉Babel, Webpack等 Modern JavaScript的開發工具
- 熟悉ES2015+語法
- 熟悉CSS3, RWD
- 熟悉GA, GTM, Facebook pixel等電子商務追蹤工具
- 熟悉網站SEO觀念
- 了解使用React, Redux的SPA開發手法
- 了解Angular1
- 具有串接第三方 API 經驗
- 具有GitHub或Bitbucket使用經驗
- 具有前端程式碼測試與品質控制經驗
- 對Open Source接受度高

### 加分

1. 具有設計背景的相關經驗，對 UI/UX 設計敏感度佳
2. 有SCRUM, Agile開發經驗
3. 線上有相關專案作品

## 工時/特休
周休二日

## 薪資範圍
工作待遇    月薪 45000元~90000元

## 聯絡方式
disneyhuang@accuvally.com

**Comment by Rplus** [comment]
看起來跟 #141 同一家，需要幫你調整嗎？

**Comment by Jakevin** [comment]
@Rplus 
感謝您！會是這篇為主，謝謝您
