### ISSUE TITLE
【台達電子徵才】Java 資深軟體工程師_台北內湖

### ISSUE THREAD

**Issue by MandyYao** [f2etw/jobs#256]
# 團隊簡介
台達知識管理部, 負責台達集團知識蒐集、分析、與活用的工作。

在知識經濟的時代，許多商業上的成功，都和善用企業無形資產有關，而企業中最重要的無形資產之一便是人才，尤其是長久待在企業的老員工，他們身經百戰，擁有豐富的經驗，如果這些知識經驗能夠傳承，不因為員工的離開而丟失，那麼便可奠定企業長久獲利、永續經營的基石。透過我們搭建的企業的知識平台，有效蒐集、累積、運用這些知識經驗，突破資訊與知識的藩籬，讓複雜的工作，可以輕鬆完成，進而提高 ROI，增加獲利能力。

## 工作內容
1.SA/SD文件撰寫
2.程式開發
3.新技術研究、推廣
## 能力需求
1.具軟體專案五年以上開發經驗(含JAVA EE相關專案三年以上開發經驗)
2.熟悉Spring framework
 3.熟悉物件導向分析與設計要領
4.熟悉MongoDB相關程式開發
5.熟悉多執行緒運算、分散式運算
6.樂觀、積極、樂於團隊合作，並願意主動積極幫助同事與分享經驗
7.具閱讀英文技術文章能力 
### 加分
1.熟悉Design Pattern
 2.熟悉Solr search engine
 3.熟悉SSO機制
4.熟悉Test-driven development
 5.瞭解CI/CD並有相關經驗
6.熟悉MQ機制與程式開發
7.熟悉Linux系統管理
8.熟悉OpenStack
 9.參與軟體產品開發經驗
## 薪資範圍
年終獎金固定2個月 + 績效獎金2個月(表現前90%者) + 現金分紅(依營運狀況與個人績效)
## 工時/特休
8:30-17:30
週休二日，依國定假日休假
 每年黃金旅遊週
## 福利/推薦項
1.新人訓練
2.專業/職能訓練：研發及工程、行銷/銷售、財務/管理、進出口/採購、資訊科技等專業訓練
3.管理才能訓練：基層、中階及高階管理訓練
4.通識教育訓練：公司價值觀、顧客滿意、品質、安全及衛生
5.專案導向訓練：企業議題討論會/研討會
6.自我發展訓練：語言課程、數位學習

## 聯絡方式
mandy.wl.yao@deltaww.com

**Comment by kidwm** [comment]
You can post it here: https://github.com/twjug/jobs/issues
