### ISSUE TITLE
【徵才】Software Architect ( React.js + Node.js/Python Preferred )

### ISSUE THREAD

**Issue by ryanhanwu** [f2etw/jobs#263]
## 團隊簡介/地點
地點：紐約
EdLab: 我們是一個位於哥大的研究開發單位，專精於研究與探索未來的教育產業，以下僅列出部份重點，詳情請點最底下連結。

## 工作內容
   - 2/3 研究與開發，1/3 規劃與架構
   - 參與整個敏捷開發流程
   - 教育與領導資淺團員成長
   - Dev Team 人數: 5~7 ，Research 以及 UIX 另計

## 能力需求
- 對教育有熱忱
- 有獨力解決問題能力
- 有以下相關知識與經驗
  - SPA 開發
  - API 設計、規劃與實作
  - SEO (Google)
  - 資料庫設計與拓展
  - 程式碼重構
  - 軟體部署開發管理

## 加分
- 熟我們現在的 [Stack](http://go.tc.edu/stack) 或者你可以把它變更好
- 熟 Node.js, React.js, Python, MySQL, Docker, and AWS
- 有 AI, ML 或 Recommendation System 經驗

## 薪資範圍
- 面議，過去經驗是十萬鎂+/年 
- 紐約目前禁止公司在招聘過程中詢問應徵者過去的薪酬紀錄，有能力者歡迎來挑戰

## 工時/特休
- 美國時間很多，7 hrs/day
- 休假也還可以，15 days/year

## 福利/推薦項
- 在美國該有的保險都有 (Health, Dental, Vision...etc)
- 你在哥大上課免費 （你知道這樣值多少錢吧)

## 聯絡方式

其他詳細內容以及履歷投遞請[點這裡](http://go.tc.edu/architect)
有問題歡迎私下詢問我 ryan.wu at tc.edu

**Comment by Rplus** [comment]
抱歉了～ 我們沒有 `年薪三百萬` 的 label  XDDD

**Comment by ryanhanwu** [comment]
🙏🙏🙏了

**Comment by ryanhanwu** [comment]
BTW, Backend 其實大多是 `Node.js`, 少數 `Django`

**Comment by Rplus** [comment]
嗯？我看標題是寫 Python Preferred

**Comment by ryanhanwu** [comment]
JavaScript & Python ... 或者我該寫 JavaScript + Node.js + Pyhon ？

**Comment by calpa** [comment]
哥大免費上課 lol

**Comment by ryanhanwu** [comment]
@calpa professional development 很重要啊 
公司內有人一邊工作一邊拿了 MS & PhD （當然我覺得他精通時間管理）

**Comment by gogobook** [comment]
哥大免費上課 lol
我會django, 和一些typescript。

**Comment by srehacks** [comment]
请问，有运维，数据库，运维开发相关职位吗？

**Comment by ryanhanwu** [comment]
目前沒有相關職位，我們年初才剛剛 Hire 一個 DevOp。
ᐧ

**Comment by aar0nTw** [comment]
哥大一年學費就 50000 刀了 賺賺賺

**Comment by sharils** [comment]
Hi @ryanhanwu Is this still open? Thanks.

**Comment by ryanhanwu** [comment]
@sharils it's closed, sorry about that
