### ISSUE TITLE
Doist - Front-end Engineer

### ISSUE THREAD

**Issue by stkao05** [f2etw/jobs#274]
## 團隊簡介/地點
Doist is a global, remote-first company and we believe that our way of working– independent of borders and time zones– is the future.

Our Products
- [Todoist](https://todoist.com)
- [Twist](https://twistapp.com)

At Doist, we strive to build not only amazing products but amazing groups of people. Our multidisciplinary teams are passionate about creating products like Todoist and Twist that improve people’s lives. 

## 工作內容
You’ll help improve Todoist by building useful and innovative features, building reusable libraries and tools, and improving our codebases with modern JavaScript tools such React and Redux. 

## 能力需求
The ideal candidate is a savvy JavaScript developer with a deep understanding of the latest Internet technologies, a keen engineering intuition, and outstanding communication skills. In addition, you should have:
- Experience building complex interactive web applications.
- Good computer science fundamentals, especially regarding your knowledge related to the web technology stack.
- Solid knowledge of modern JavaScript. You should have a substantial grasp of concepts like prototypes, closures, asynchronous programming and ES6.
- The ability to use and customize tools (i.e. Webpack, Gulp) to streamline your development/build process.
- Proven ability to work autonomously and stay self-motivated, or previous experience working in remote teams.
- Good level of written and spoken English.

### 加分
-  Experience working with React and Redux.

## 薪資範圍
1M+

## 工時/特休
- 40 hours per week, flexible schedule (remote work)
- 25 days paid vacation
- National holidays

## 福利/推薦項
- Flexible schedule and location
- Education stipends
- Hardwares/home office perks

...and many more :)

## 聯絡方式
steven@doist.com

**Comment by Rplus** [comment]
連結貼錯了唷  請附完整網址

**Comment by stkao05** [comment]
@Rplus 阿謝謝，已經更正。另外，我可以加一個”遠端工作“的標籤嗎？

**Comment by sharils** [comment]
I suppose this is closed as this is not list on https://doist.com/jobs/, am I right?

**Comment by sharils** [comment]
Hi @stkao05  - Is this still open?

**Comment by stkao05** [comment]
@sharils sorry for the late reply. The position is no longer available.
