### ISSUE TITLE
Frontend Engineer, Data Platform @ Machine Zone, Taipei, Taiwan

### ISSUE THREAD

**Issue by chenkuochen** [f2etw/jobs#29]
Introduction
====
Machine Zone設在矽谷新創公司中心地帶Palo Alto。目前一款遊戲在30個國家App Store Top Grossing排名第一，80多個國家排名前五，每日活躍玩家超過150萬人。

台灣辦公室的工作內容主要與 Data Infrastructure / BigData Analytics / Business Intelligence 相關，一開始會先到美國總部受訓，之後不定期需至美國出差。

公司簡介：Mobile gaming startup(待過Y Combinator) from 2008。公司文化年輕開放，重視Engineer的想法。(http://www.glassdoor.com/Overview/Working-at-Machine-Zone-EI_IE409080.11,23.htm)

相關報導：https://news.google.com/news/section?q=%22Machine+Zone%22

Responsibilities:
====
Work with backend engineers and product managers to deliver user-friendly, flexible and maintainable web services for our internal tools
Contribute creative ideas and insight for improving usability of our web tools
Build efficient and reusable front-end abstractions and systems
Participate in design and code reviews
Identify and communicate best practices for front-end engineering

Requirements:
====
BS/MS in Computer Science or a related field
3+ years of experience of building web applications
Experienced in JavaScript, including an understanding of Object Oriented Programming, AJAX, JSON, and object serialization
Ability to write readable, maintainable JavaScript, HTML and CSS
Experienced with at least one JavaScript framework such as jQuery, Backbone, AngularJS, and React
Passionate about communicating with users and building user-friendly user interface
Ability to rapidly prototype a tool and iterate effectively
Must have the ability to multi-task and work effectively in a fast-paced, highly data-driven and changing environment
English writing/reading and oral communication skill

Nice to Have:
====
Experienced in Git or similar version control systems, e.g. CVS, Subversion, or Perforce
Experienced in SQL
Experienced in Highcharts, D3.js, SVG
Expert knowledge in jQuery, AngularJS or Node.js
Having a sense of beauty :)
Some of your works that can be shown to us

Banana:
====
NT$ 65,000 以上
＊最高薪資面議

**Comment by ArvinH** [comment]
請問職缺還開著嗎？
