### ISSUE TITLE
[徵才] Eatgether - Front-End Engineer

### ISSUE THREAD

**Issue by SimonSun1988** [f2etw/jobs#304]
![eatgetger](https://www.eatgether.com/img/logo.png)

> 我們相信，一頓飯可以連結全世界。

## **【團隊簡介/地點】**
《食我餐飲顧問股份有限公司》是一個成立自2014年的新創公司，致力於透過網路科技創新應用服務，「創造更美好的用餐體驗」。分別於2014年與2016年完成種子與天使輪投資，分別來自於聯合報系與多位業界知名天使投資人。公司主要的產品為自2016年上線就獲得廣大好評的聚餐交友APP《Eatgether》。

目前團隊成員約十人，是個平均年齡近30歲，同時具備年輕活力與技能經驗的團隊。動靜分明是我們的團隊文化，彈性自律是我們的工作風格，在這裡沒有太多的規範，上下班不打卡，也可自行安排工作時間，高度的自律搭配目標導向的管理模式，成就了一個快而精實的新創團隊。目前整個團隊都聚焦在開發Eatgether，朝著打造一個來自台灣的國際化餐飲社交平台而努力。我們認為新創公司的人才就是一切，每個加入的人都會改變這個團隊與產品，非常期待有你的加入！

## **【相關報導】**

- [產品發表會](https://www.youtube.com/watch?v=rIxD2zYZoeo)

- [TVBS](https://www.youtube.com/watch?v=B2UBGYBNAQ4)

- [蘋果新聞](https://www.youtube.com/watch?v=boBn5vLGDhY&t=57s)

## **【工作內容】**
- 協助網站前端開發
- 臨時交辦任務

### **必備需求**
- Vue.js (使用過 react.js 或 angular.js 等前端 framework 也歡迎)
- HTML
- CSS
- JavaScript
- Git

### **加分條件**

- 使用過 `PHP (Laravel)` 或是 `Node.js (koa.js)`
- 使用過 `AWS`, `GCP`, `Azure` 任一服務
- 使用過任何一種 RDBMS
- 曾經自己創業過
- 良好的溝通
- 對自己的工作負責
- 活潑開朗，喜歡聊天打屁練瘋話
- 愛玩遊戲，愛吃美食

## **【薪資範圍】**
- 年薪60-100萬(12個月)
- 獎金依當年度營運狀況發放

## **【工時/特休】**
- 週休二日，表定10:00-19:00，午休一小時，彈性上下班不打卡 **(因應勞基法規定，今年這制度可能會有所調整)**
- 比照勞基法，國定假日見紅就放
- 工作滿一年後，依照勞基法核定特休

## **【福利/推薦項】**
- 合夥與配股機會
- 公假外部進修課程與購書補助
- 無限零食與咖啡
- 不定時聚餐

## **【聯絡方式】**

信件標題請輸入 `應徵 Eatgether 【Front-End Engineer】`。

請附上個人履歷 / Github / 個人網站等資訊在信件內，我們會盡快與您聯絡。

履歷請寄至 `jobs@eatme.tw`

**Comment by Rplus** [comment]
要不要先確認一下有沒有發過？
我剛搜了下 [Eatgether](https://github.com/f2etw/jobs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Eatgether)，還沒關的就有四篇哩
確定都是不同職缺嗎？

**Comment by Rplus** [comment]
若確定能關掉的話，麻煩到其它 issue 下留言，感謝～

**Comment by SimonSun1988** [comment]
@Rplus 已經留言了，再麻煩您了

**Comment by SimonSun1988** [comment]
@Rplus 此職缺麻煩先關閉，麻煩了
