### ISSUE TITLE
[徵才]均一教育平台 - 全端工程師 

### ISSUE THREAD

**Issue by JunyiHR** [f2etw/jobs#309]
## 身為工程師的你，也可以擁有另一種選擇——

> 你能夠讓程式不只是一串字碼，而是你引以為傲的專業技能，協助教育現場的老師教學、幫助學生快樂學習；你可以賦予程式溫度，成為讓你能夠挑戰自己的極限，為社會創造更多正向價值的舞台！

> **只要你願意，你，可以不一樣！**
> 在均一，用Coding譜寫出不一樣的改變，寫下與創造自己的未來！
> 加入均一，成為工程師界不可多得的改變力量吧！
　
## 均一平台教育基金會介紹

在這個快速迭代的時代，「均一平台教育基金會」看見了教育體制內環環相扣的問題，因此決定透過一場長穩的教育改革，與志同道合的夥伴一同改善台灣的教育環境。 均一期待透過科技，協助老師落實個別化教學，消弭學習弱勢；透過科學，提供孩子學用整合的機會，連結未來世界。

我們的產品，均一教育平台是一個線上學習平台，提供免費而優質的學習內容。利用科學與科技的力量，為老師與孩子，提供創新有效的「教」與「學」路徑，致力於達到「用科技，讓孩子擁有最適合的學習節奏」。

我們期許透過均一能讓孩子在學習中有更多主動權，以適合自己的方法與步調來學習，最終落實個人化學習；老師透過均一的協助，都能實現對教育的熱情，讓每個孩子發光發熱；而家長們也能夠陪伴著孩子快樂學習，探索未知的世界，最終幫助孩子找到自己的天賦。

**均一官網：https://goo.gl/k7uhu6
均一教育平台：https://goo.gl/wS5NFj**
　
## 均一團隊與工作地點
均一團隊目前有22位全職夥伴，其中有8位背景多元的軟體工程師，來自Garmin、Synology等。團隊成員懷抱著對改善教育的共同夢想一起來到均一，期待用自己的專業力量，共同為台灣下一代的教育努力！

工作地點：台北捷運善導寺站2號口，步行三分鐘，交通便利。
　
## 工作內容

- 網站功能全端開發與維護
- 對大量數據進行處理、分析，並根據分析結果做決策
- 與教育領域、教學現場溝通，並挖掘需求
　
## 能力需求

- 大學理工相關科系畢業，寫程式經驗至少2年
- 熟悉 Python、Javascript ，或有 Web 開發經驗者
- 對數字敏感、邏輯清晰，知道如何拆解問題，並樂於動手解決
- 對於教育有熱忱，具有同理心及反思能力
- 善於溝通，團隊合作能力佳
　
## 加分條件

- 熟悉 Restful API 或 React
- 使用者需求探索、介面設計與測試經驗
- 有教學經驗佳
　
## 工時/特休

- 每日工作8小時，彈性工時
- 若假日上班可申請補休

## 薪資與其他
- 42k-60k，年薪13個月，並含勞健保
- 與一群對教育充滿理想與熱忱、來自各個領域的多元化夥伴共同打造屬於自己心中的教育藍圖
- 接近同領域、同年資之薪資待遇，並含勞健保
- 不需打卡，可以彈性遠距離工作
- 合理的工作與休息，即便週末加班亦可排補休
- 時時自動補滿的零食區與咖啡，累了還有懶骨頭可以小憩 
- 這裡沒有條條框框，只要你能想到，就有機會將它實現 
　
## 應徵方式
將個人履歷（形式不拘）連同想加入均一的原因，寄至 hr@junyiacademy.org，若您通過履歷審核，我們將會儘速與您聯絡！以上職位徵滿即停止收件，有興趣的夥伴請不要錯過喔！

**Comment by Rplus** [comment]
呃…
我覺得 「週末加班亦可排補休」 好像並不算是福利吧…？

**Comment by JunyiHR** [comment]
謝謝你的建議，已經改為「其他」囉！
