### ISSUE TITLE
徵 React.js developer/Project owner

### ISSUE THREAD

**Issue by davidyu37** [f2etw/jobs#318]
遠端工作
時間彈性
屬於自己的專案

## 工作內容
全新專案，不需接手任何別人留下來的code
架設 React.js webapp 與 Firebase realtime database結合

## 能力需求
JavaScript, HTML, CSS, React.js, Redux, Firebase
至少有一個項目在production上
有團隊合作經驗

### 加分
對於學習充滿熱愛

## 薪資範圍
以時薪計算
NTD800~1000

## 聯絡方式
davidyu37@gmail.com

**Comment by calpa** [comment]
薪資範圍？
