### ISSUE TITLE
【徵才】Branch8 資深前端工程師 React

### ISSUE THREAD

**Issue by chunsli** [f2etw/jobs#340]
## 團隊簡介/地點
Branch8是一個幫助電商於多平台管理產品及訂單的網站，直接以API連接如亞馬遜，eBay和天貓等。主要客戶是來自香港的企業及品牌。公司同時亦在開發一個顧客管理系統，而在台灣招聘主要是為開發此產品。我們很自豪得到台灣之初創投(AppWorks)的支持及美國Y Combinator的投資，Y Combinator是一家矽谷基金，早年也曾投資Dropbox、Airbnb、Stripe、Docker等初創企業。我們的開發團隊成員有Facebook, Microsoft, Accenture等的工作經驗。

在台灣招聘是Branch8本年度的重點項目，雖然只在起步階段，但已成功在台北招聘到兩位資深的工程師，並計劃在未來二到個月最少再增聘一至二人。公司會在短期內在台北設立辦公室，我們希望台灣的開發員能計支持我們成為亞洲最強大的電商工具軟件。

## 工作內容
以下是我們目前使用的技術：
React、Redux、Node.js、Typescript、Flow、Jest、PostgreSQL、RabbitMQ、Redis、Docker、Kubernetes
1. RWD (Responsive-Web-Design) 網站開發。
2. 與後端工程師協同開發網站。
3. 與Product Manager 協調分配工作。

## 能力需求
1. 具前端Framework (eg. Angular, Vue, React) 開發經驗。
2. 熟悉 Git 操作。
3. 擅溝通協調，重視團隊合作。
4. 高自律性。

### 加分
1. 熟悉React, Redux, Node 及JavaScript。
2. 熟悉Test Driven Development。
3. 具全端能力。
4. 具架構設計能力。
5. 具領導開發團隊的能力或經驗。

## 薪資範圍
年薪 100 -150萬新台幣，具領導及架構設計能力者可另議。

## 工時/特休
1. 彈性上下班，一般10:00 至 19:00。
2. 週休二日，依國定假日休假。
3. 特休每年14天。

## 福利/推薦項
1. 可選擇遙距工作或在台北信義區上班。
2. 彈性工作時間 
3. 彈性工作地點 
4. 14天年假 
5. 按能力及頁獻分配年底花紅或股本

## 聯絡方式
matt@branch8.com

**Comment by alxtz** [comment]
好奇收到 Email 的標準 XDDDD
