### ISSUE TITLE
【徵才】媽咪愛誠徵 Front-End Developer

### ISSUE THREAD

**Issue by guAnsunyata** [f2etw/jobs#352]
## 團隊簡介/地點
媽咪愛團隊持續招募能自主學習、喜歡解決問題、喜歡團隊合作、喜歡和優秀隊友一起成長的 developers，歡迎與我們聊聊

媽咪愛是一間成長快速的新創公司，目前有超過 40 萬的用戶，是目前台灣最大的親子電商平台。我們的使命是利用網路的科技，幫助家庭解決生活中遇到的種種問題，陪伴家庭與孩子快樂地成長。
 
老闆之前在美國 Google 工作，很希望在台灣可以打造一個自己也認同和喜歡的公司文化，每天上班覺得和優秀隊友合作是件很值得期待的事。公司每年很穩健快速的成長，針對這些我們很努力的做到，也持續往更好的方向前進！

## 工作地點
台北市中正區南昌路二段222號10F (古亭捷運站 2 號出口步行三分鐘)
 
## 團隊文化
我們 Product/Engineering 的團隊文化： 
1. (真正的) 彈性工時與上下班時間，我們更重視的是你的產出和貢獻 
2. 扁平化的組織架構，能發揮自己對產品或技術的想法 
3. 執行 Code Review，交換彼此的意見一起成長 
4. 工程師參與 Design Review 給予意見及協調需求 
5. 每週五團隊技術分享 brown-bag session 
6. 每週四公司內部的分享會

我們希望你有的特質： 
1. 喜歡寫 code ，覺得在透過網路解決人們生活的難題是一件很酷的事 
2. 想挑戰自我的能力，願意嘗試在快節奏的公司工作 
3. data-driven，喜歡用數字來驗證工作的成效而不是只是憑感覺 
4. 溝通能力佳，喜歡團隊合作更勝一人球隊 
5. 你非常在乎使用者體驗和前端效能，希望提供使用者一流的體驗

## 工作內容
開發維護電子商務平台網站前端工程： 
  - Vue.js / Vuex / Vue Router 打造 Web Application 
  - 密切與 Product Manager / Designer 合作開發並可以參與設計流程 
  - 開發注重使用者體驗的 Desktop / Mobile Web App

如果你有興趣，歡迎你一起參與： 
  - 前端效能調教與網站最佳化 
  - 參與持續優化 SEO 的流程 
  - 對 UI/UX 有所要求而不斷追求進步 
  - 進行 User Behavior Tracking 和模型分析 
  - 開發 Accelerated Mobile Pages 
  - 持續導入 Progressive Web Apps
  - 維護系統健康 APM & Error Tracking : Sentry, New Relic 
  - GCP / AWS deployment

## 能力需求
- 有使用過 HTML、CSS、JavaScript 開發 Web Application 的經驗
- 有使用過 Sass/SCSS 或其他相關開發工具的經驗
- 對於 RWD 有基礎的認識
- 有使用過 Git 或其他程式碼本版控制的經驗
- 有串接後端 API 的經驗

### 加分
- 對於 JavaScript 語言本身有熱忱
- 具備 Vue.js 或任一前端架構的開發經驗或基礎認識
- 有使用過 webpack 或其他打包/任務工具的經驗
- 願意解決跨瀏覽器開發可能遇到的相容性問題
- 對於打造 mobile friendly 的行動版網頁有興趣
- 有使用 PHP 或任一後端語言的經驗

## 薪資範圍
50K ~ 70K/月，13個月 (視個人經驗和能力而定，若很有經驗薪資可談)

## 工時/特休
1. 彈性工時與上下班時間。
2. 週休二日，依國定假日休假。
3. 加入第一年即享五天特休，優於勞基法。

## 福利/推薦項
- 配備 MacBook Pro '13 電腦及螢幕，或自備電腦者每月有輔助金
- 提供相關課程或演講補助，期待你與公司一起成長
- 業績達標時有季獎金
- 每月一次公司買單的員工聚餐
- 不定期公司請客的下午茶
- 年度員工旅遊

## 聯絡方式
如果對我們公司有興趣，歡迎將履歷 email to: hr@upn.com.tw

**Comment by hsuchihting** [comment]
您好，已主動投遞履歷到指定信箱，再請您撥空看看，希望有機會可以面試，謝謝您。
