### ISSUE TITLE
[徵才] 優拓資訊 (Yoctol Info) 前端工程師

### ISSUE THREAD

**Issue by chentsulin** [f2etw/jobs#368]
## 公司介紹

優拓的軟體工程團隊專注於開發聊天機器人的開發框架，以及打造更容易使用的語意理解服務，協助團隊更快速地打造 Chatbot 並優化使用者體驗。

團隊組成扁平，沒有由上而下的指令，只有彼此間的緊密合作與溝通。同時，我們樂於擁抱新技術及各種嘗試，並鼓勵所有人在 Open Source 專案上一起留下努力的軌跡。
如果你和我們一樣樂於學習、擁抱開源、能夠自主的管理個人工作時程，並且喜歡在開放團隊裡一起努力，歡迎加入我們的行列！

公司官網 - https://www.yoctol.com/
GitHub - https://github.com/Yoctol
Medium - https://blog.yoctol.com/

## 工作內容

- 共同開發高品質的平台介面提升使用者體驗
- 評估需求並改善工作流程與效率

我們需要你不僅僅是個工程師，還要是一個好的聆聽者，永遠將使用者的感受當作第一位，並且有能力將使用者的需求轉化成乾淨且好維護的程式碼。
擅長使用 JavaScript 打造功能豐富的 Web Application，並且熱於發掘日新月異的 Front-End 新技術以及動手改改 CSS。

## 需求條件

- 熟悉 JavaScript (ES6+)、CSS 與 HTML
- React.js 使用經驗
- 熟悉 RESTful API
- 對 UI / UX 有所堅持

## 加分條件

- 有 Next.js 相關經驗
- 有 GraphQL 相關經驗
- 有 Unit Test 相關經驗
- 擁抱 Open Source 精神
- 喜歡學習，交流新事物

## 工作地點

台北市大安區信義路二段 74 號 4 樓
（近捷運東門站 3 號出口）

## 薪資範圍

NT$50K / 月以上 + 股票選擇權，視經驗與能力而定

## 公司制度

- 週休二日 / 休假優於勞基法
- 工時表訂 9:30 - 18:30，亦可彈性調整
- Remote 工作機制，分工完畢後可以遠端工作

## 公司福利

- 免費零食飲料生啤
- 定期出遊 / 聚餐 / 運動，不勝枚舉
- 每週 Happy Hour，輕鬆幽默的主題式分享
- 每週 Workshop，與強者同事交流尖端技術

## 聯絡方式

將您的履歷，及任何能讓我們眼睛為之一亮的資料，寄至 jobs@yoctol.com
（※ 別忘了在信件標題註明申請前端工程師！）

**Comment by xJkit** [comment]
大師徵才，還不快去 XD

**Comment by kunyaoxu** [comment]
請問 貴公司還有在徵才嗎?

**Comment by chentsulin** [comment]
@kunyaoxu 我們職缺一直都還開放 歡迎高手應徵

**Comment by jkfox67** [comment]
Vue比React熟練的可以嗎？@@?

**Comment by chentsulin** [comment]
@jkfox67 我們 team 也有很熟練 Vue 的工程師，不過會建議 React 還是要有一定程度熟練度喔
