### ISSUE TITLE
[徵才] MemePR 潮語傳媒誠徵 Frontend / Full stack developers

### ISSUE THREAD

**Issue by UniH** [f2etw/jobs#369]
## 團隊簡介/地點
MemePR 潮語傳媒是首家結合科技將行銷服務商品化的國際行銷平台,協助企業以更快、更具成本效益和高效率的方式，在大中華區和東南亞地區推廣其品牌和產品 。目前, 我們的辦事處位於香港和臺北, 擁有跨越十多個國家共1000多家的行銷合作夥伴。
公司利用最尖端的人工智能及Memebot技術幫助企業收集市場情報、擬定行銷策略建議、協助客戶主動出擊,快速累積知名度與增加業績。

 MemePR 認為共好所以多贏。我們相信即使各地的文化不同，依然可以透過 MemePR 的平台，減少企業與行銷端之間的溝通落差，節省二端的時間與成本，並讓全世界的消費者可以更快地接觸到好的產品/品牌/理念。 MemePR 喜歡多元文化交流激盪的火花，所以公司成員由多國組成。

我們找夥伴不找員工，絕對尊重公司的每個成員的話語權，鼓勵公司同仁們 Work hard, Play hard。所以即使對工作要求，該玩樂時也不手軟。 如果你正在找一個成長飛快並具有挑戰性的工作，如果你也喜歡一群人一起向前邁進的感覺，如果你也認同我們的理念，歡迎加入MemePR！

公司網站徵才說明：[https://www.memepr.com/career](https://www.memepr.com/career)
公司粉專：[https://www.facebook.com/memepr.news](https://www.facebook.com/memepr.news)
Medium :[https://medium.com/memepr](https://medium.com/memepr)

## 工作內容
    使用 React, Styled-component 的常見 Javascript Framework 開發網站 

## 能力需求
    1. 熟悉 React 
    2. 熟悉 Git 

### 加分
   1. 使用過 Node
   2. 有其他前端框架開發經驗 (e.g. Angular, Vue...)
   3. 有相關作品

## 薪資範圍
 基本有 NT$50K / 月以上 + 股票選擇權，視經驗與能力而定，若是好手一定不會虧待你。
 對 memepr.com 有興趣之 full stack 高手技術合夥人，同步招募中。

## 工作地點
台北橋捷運出口10秒到達（等電梯不算）

## 工時/特休
週休二日 / 休假優於勞基法
工時表訂 10:00 - 19:00，可自由彈性調整，只要上滿8小時即可
特殊情況可申請遠距工作。

## 福利/推薦項
1. 員工配股
2. 慶生會
3. 完整的教育訓練
4. 順暢的升遷管道
5. 週休二日
6. 女性同仁生理假
7. 結婚禮金

## 聯絡方式
請將您的履歷寄至：cs@memepr.com 標題註明 '[應徵] 前端工程師 XXX (你的姓名)'

**Comment by ymcheung** [comment]
- 經常拖欠薪水
- 勞健保以 22K 申報

**Comment by UniH** [comment]
@ymcheung Hi Yuming, 好久不見！

首先，issue 關閉不代表職缺已關閉，有興趣的求職者可以透過 email 詢問，issue 關閉是由於我已經不在此公司服務。

其次，由於我跟 Yuming 都已經離開這間公司了，我們並沒辦法知道公司現在的營運狀況為何，但若以離職的時間點來說，我應該可以稍作一些更為客觀的補充。

在我仍在職的期間公司發薪狀況確實不穩定，經常會延遲發薪，但通常會在一個禮拜內收到薪資，且若是公司真的遇到困難主管也會提早告知，主管也說過若有急用錢的狀況他會幫忙想辦法，我沒有找過主管幫忙，所以不知道解決方案是什麼，不過遲發薪水確實相當令人困擾。

至於勞健保的部分，由於我沒有實際查過，所以不清楚申報的級距，但從薪資預扣的勞健保是跟我的薪資級距對的上的。

**Comment by ymcheung** [comment]
陳述事實無關客不客觀。
欠薪協調會的開會通知就懶得貼了。

![log1](https://user-images.githubusercontent.com/4409977/44358292-2631d200-a4e7-11e8-949c-718f3cd19f6d.png)

![log2](https://user-images.githubusercontent.com/4409977/44358315-334ec100-a4e7-11e8-81cc-f72582ccef55.png)
