### ISSUE TITLE
[徵才] Picowork 香港商協作雲端 - Frontend Engineer

### ISSUE THREAD

**Issue by charlesPicowork** [f2etw/jobs#373]
## 團隊簡介
Picowork是協同式雲端操作系統技術和協同式雲端電腦產品及方案供應商。於2010年在香港成立，2012年5月於台北成立研發中心。團隊成員來自大中華區的IT菁英。通過對協同式雲端電腦（CCC - Collaborative Cloud Computer）和協同式雲端操作系統（CCOS - Collaborative Cloud Operating System）的研發，Picowork在雲系統架構技術上已經取得全球矚目的突破性進展, 成為物聯網、大數據、工業4.0及中國製造2025時代的系統核心科技。

公司里程碑：
2010年12月創立；
2015年2月 Picowork系統在台灣研發成功；
2015年2月-2017年2月 在港台超過一百家企業進行試用測試；
2017年2月 協同式雲端電腦CCC和協同式雲端操作系統CCOS正式發佈。
2017年3月 全球包含CNN、美聯社等200多家媒體爭相報導Picowork 協同式雲端電腦CCC和協同式雲端操作系統CCOS。
2017年4月 Picowork持續性的著手在全球展開專利佈局，數十項專利，已在美國、中國、台灣、日本、歐洲……等國家和地區審核中，部分核心專利已分別獲包括美國等不同國家核准並取得相關的專利證書。
2017年6月 Picowork於香港數碼港盛大發表協同式雲端電腦CCC和協同式雲端操作系統CCOS。並受到香港科技局及數碼港全力支持。

## 工作地點
台北市大同區

## 工作內容
1. 與設計師、後端工程師溝通並確認程式開發流程與細節。
2. 規劃功能架構及開發時程
3. 使用ReactJS開發與維護產品。
4. 必要時協助維護舊有程式架構(AngularJS 1)，從中尋找並修正問題。
5. 編寫開發技術文件。
6. 注重程式碼品質。

## 能力需求
1. 兩年以上Web (HTML5 + CSS + JavaScript) 開發及維護經驗。
2. 熟悉ReactJS，具備基礎AngularJS 1。
3. 熟悉Git版本控制及Git Flow。
4. 了解Grunt, Webpack等工具。
5. 了解Web前端效能優化。
6. 了解跨瀏覽器的相容性問題。
7. 了解CI/CD概念。

### Plus
1. 具備自動化測試(Auto-Testing)經驗。
2. 熟悉一種以上的設計模式(Design Pattern)。
3. 具備使用敏捷開發(Agile Development: Scrum, XP...)之經驗。

## 薪資範圍
TWD 800,000 至 TWD 1,400,000 / 12個月
根據面試的結果決定是Junior或是Senior來雇用

## 需求人數
3人

## 工時/特休
上班時間為 9:00 ~ 18:30，可彈性前後一個小時上下班。午休90分鐘，另外有30分鐘的下午茶時間。
週休二日。
特休規則與大部分外商相同：休當年，到職日即有特休。
特休天數則優於勞基法：第一年有10.5天，第二年有12天，第三年有14天，第四年有16天，第五年之後每年增加一天。

## 福利/推薦項
節慶禮物
不定時聚餐
享勞健保
勞退新制
員工旅遊
教育訓練
員工分紅

## 聯絡方式
請把履歷、作品集寄給Charles(charles@picowork.com)

**Comment by sharils** [comment]
Hi @charlesPicowork Is this still open? Thanks.

**Comment by charlesPicowork** [comment]
Sorry, it is closed.
