### ISSUE TITLE
[徵才] 公視軟體工程師

### ISSUE THREAD

**Issue by ptsnewmedia** [f2etw/jobs#377]
## 團隊簡介/地點
公共電視除了提供優質的節目與影音作品外，也在培養自己的技術團隊，主要任務是：
1. 改善目前網頁開發流程
2. 既有服務雲端化
3. 開發及維護影音服務

公視的目標是：建立公共服務媒體平台，看見台灣更美好的未來
不論是否有工作經驗，只要能認同公視的願景，都歡迎來信聯絡我們

地點：台北市內湖區康寧路三段75巷70號，康寧大學正門對面
## 工作內容
    1. 維護公視節目網頁
    2. 與團隊成員開發服務
    3. 擔任OTT專案的技術窗口

## 能力需求
    1. 熟悉 HTML 與 CSS
    2. 具備前端開發經驗並了解基本技術(e.g. ajax or RESTful API)
    3. 保持開放的態度與非技術人員溝通與合作
    4. 寫出易讀且適當的程式碼
    
## 加分條件
    1. 使用 ES6 或 JS packaging(e.g. webpack or gulp)的經驗
    2. 有任一前端 framework 的開發經驗
    3. 具備任一伺服器端腳本語言(e.g. php or python)的開發經驗
    4. 熟悉 Git 操作

## 薪資範圍
* 月薪40k~50k(有無經驗皆可)
* 太強者薪資低於您的要求，可以在履歷上附註期待薪資

## 工時/特休
* 彈性上下班，08:00 ~ 10:00 至 17:00 ~ 19:00
* 週休二日，依國定假日休假
* 特休同勞基法

## 福利/推薦項
* One for All(我為人人)的榮譽感
* 一個月的年終獎金
* 績效看表現
    
## 面試流程
1. 第一階段：團隊成員會主動電話聯絡適合的應徵者並進行訪談(15-20分鐘)
2. 若有通過第一階段，會在結束後三天內通知並送出面試確認信
3. 第二階段，邀請您來公視面談：
> 請您自我介紹與介紹我們給您認識(30分鐘)
> 技術的相關問答(2小時)
> 組長訪談(0.5小時)
> 您的提問時間(不限)
4. 若有通過第二階段，會在結束後一週內通知並送出第三階段面試確認信
5. 第三階段
> 主管面試與提問(1小時)
> 您的提問時間(不限)
6. 若有通過第三階段，會在兩週內通知面試結果

## 聯絡方式
* 請將履歷的電子檔發信到 ptsnewmedia@mail.pts.org.tw，標題請註明`[應徵公視軟體工程師]`
* 電子檔案請勿使用.doc或.docx，也盡量不要提供與學經歷無關的資訊

**Comment by ptsnewmedia** [comment]
修正面試流程排版和新增主要任務

**Comment by Rplus** [comment]
應來信要求，close issue.
