### ISSUE TITLE
【徵才】萊思特科技 - Senior Front-end Engineer

### ISSUE THREAD

**Issue by GaryChenTW** [f2etw/jobs#382]
## 團隊簡介/地點
萊思特科技成立於2017年中，專注提供Letstalk即時通訊服務，主打加密及保障客戶隱私。

目前提供iOS及android版本，現有同集團友好公司內部使用並以chatbot提供商業服務。

工作地點在台北內湖及新竹關埔。

## 工作內容
- Build our web-based desktop applications, including consumer editions and business editions.
- Build back office systems for our business users to manage their subsidiary accounts.
- Work closely with other mobile engineers, back-end engineers,  product owners and designers.
- More than welcome to bring in new flows and concepts.

## 能力需求
- Solid understanding of javascript and web development.
- Familiar with Git or other version control tools.
- Have the will to setup unit tests and automate testing flows.
- Good communication skills.

### 加分
- Experience of **PWA** (Progressive Web Apps).
- Experience of **Electron**, delivering signed applications to both windows and mac.
- Experience of NodeJS.
- Good utilization of React, Vue, Webpack, Angular.
- Experience of server side architectures and skills.
- Knowledge of cryptography.

## 薪資範圍
年薪 TWD 900,000 ~ 1,100,000

## 工時/特休
周休二日，每年享有12 天年假 + 10天全薪病假。
上班時間彈性，含午休一小時到班九小時，來的及參加11時日會即可。

## 福利/推薦項
公司全額補助參加課程及技術活動。
每季聚餐，辦公室供應飲料零食。

## 聯絡方式
gary.chen@letstalk.asia

**Comment by sharils** [comment]
Hi @GaryChenTW Is this still open? Thanks.
