### ISSUE TITLE
[徵才] 舒服美牙體科技 徵 前/後端工程師 (社會新鮮人亦佳)

### ISSUE THREAD

**Issue by jackypan1989** [f2etw/jobs#384]
## 團隊簡介/地點
團隊成立於 2014 年，專攻隱形牙套/數位矯正服務，工作地點在南京重慶交叉口(中山站附近)，目前公司成員已達40人，期待有興趣的新人加入。

## 工作內容
1. 維運/內控系統開發
2. 官網開發
3. 客戶端 app 開發

## 能力需求
1. 熟悉 Git
2. Javascript 基礎知識
3. 團隊合作能力

### 加分
1. 玩過 React (or Angular / Vue)
2. 對 fp 領域有熱情 (Haskell / Purescript)
3. 參加過 Hackthon

## 目前公司用到的項目
1. nodejs / reactjs / rxjs (with ES6)
2. styled-component / ant-design
3. webpack / babel / flow
4. elasticsearch / mongodb
5. CI/CD service / AWS / GCP
6. Socket.io
7. threeJS / 3d modeling
7. Purescript (歡迎一起來學)

## 薪資範圍
無經驗 4.5w / per month
Junior 6w / per month
Senior 8w / per month

## 工時/特休
1. 0930~1830
2. 特休依勞基法規定

## 福利/推薦項
1. 公司提供 MacBook Pro Retina + 29吋大螢幕
2. 免費隱形矯正(包含諮詢與療程)
3. 福委會定期活動
4. 絕不加班文化
5. 公司性別比例均衡
6. 部門定期吃大餐
7. 年度健檢
8. 員工旅遊 (前兩年分別去韓國看經典賽跟泰國)
9. 讀書會/外部課程補助
10. 吃不完零食跟咖啡機 (小心發胖)

## 聯絡方式
jacky@sov.dental (請附履歷/專案)

**Comment by LuHua10** [comment]
請問一年有保障幾個月嗎?

**Comment by jackypan1989** [comment]
保13

**Comment by jackypan1989** [comment]
目前 team 暫時收滿
