### ISSUE TITLE
文創電商 Fandora Shop 誠徵前端工程師

### ISSUE THREAD

**Issue by xpsteven** [f2etw/jobs#39]
## 公司介紹

Fandora Shop 繽紛生活，致力於用美好的圖像，讓生活中的各種用品，不再枯燥乏味，而是有靈魂，有故事，能夠傳遞幸福的存在。

成立兩年多來，作為消費者和創作者間的橋樑，已與 1,500 多位優秀插畫家合作免費協助開館，將美好的圖像創作，變成各式設計訂製商品，讓創作者能夠更瞭解市場的聲音，更便捷的打造插畫品牌，並實質回饋到默默耕耘的創作者們。今年，我們將進一步打造全球獨一無二的插畫商品百貨，網羅全球繽紛好物，讓每個人都能打造專屬的繽紛生活，享受幸福。

如果你也一樣充滿幫助創作者的熱情、有想法、有衝勁，信仰學習前進是永遠的課題，喜歡 Team work ; 能夠主動溝通跟大家打成一片，並願意與我們一起打造這樣一個幸福場域，Fandora Shop 誠摯邀請您加入成為我們的團隊夥伴 :)

## 主要產品

[Fandora Shop](http://fandorashop.com/tw/)

## 薪資條件

40K ~ 70K

## 必要技能

1. Javascript
1. CSS
1. HTML

## 加分技能

1. Backbone
1. SASS
1. Handlebar
1. Git/GitHub

## 工作內容

1. 網站前端開發
1. 我們採用前後端完全分離的開發方式，只要換串接後端工程師用 Node.js 開發的 HTTP API 就能上手了

## 連絡資訊

1. 請寄個人履歷到 admin-team@fandorashop.com 標題請用 *[應徵網頁前端工程師]-姓名*
1. 合適者將安排面試

**Comment by dca** [comment]
`新資條件` -> `薪資條件`

**Comment by xpsteven** [comment]
@dca 3Q

**Comment by Rplus** [comment]
後端用哪種的有需要幫忙加 label 嗎 ~？

**Comment by xpsteven** [comment]
@Rplus 後端用 Node.js 
感謝

**Comment by Rplus** [comment]
喔？ 徵到了嗎？ ：)

**Comment by xpsteven** [comment]
@Rplus 是的，感謝 F2E.tw 過程中帶來好幾封履歷

**Comment by Rplus** [comment]
:+1:

**Comment by dca** [comment]
@xpsteven 還有缺後端嗎XDDDD
