### ISSUE TITLE
[誠徵] IoT百萬年薪前端工程師/設計師

### ISSUE THREAD

**Issue by yutin1987** [f2etw/jobs#4]
![screen shot 2015-01-09 at 9 26 18 am](https://cloud.githubusercontent.com/assets/2505934/5674208/aa650252-97e1-11e4-81d0-c5b5d80f3a52.png)
目前主要服務：http://mcs.mediatek.com/

#**應徵條件**
我們需要你的作品集(PSD或GitHub...等)，希望能夠提高自己都感到滿意的作品。
對於做Web Application有高度熱誠，對於嵌入式系統(Linkit, Arduino, Raspberry Pi)有高度興趣。
已習慣團隊合作，願意分享技術，善於溝通討論。

#**工作模式**
使用標準的git flow，運作agile跑storyboard，使用全套Atlassian。
不惡性加班，遵守每月46小時上限（產品有興趣公司環境好，你會想急著回家嗎？）

#**工作地點**
新竹，平均6k以上即可住到10坪以上套房，14k上下可以租到高級套房或整層公寓。
離高鐵10min，台鐵新竹站(可搭輕軌轉乘)30min，南北來往方便，40min到台北。

#**應徵方式**
前端與移動應用工程師
http://careers.mediatek.com/eREC/Job?id=50778417&langKey=zh-TW
後端工程師
http://careers.mediatek.com/eREC/Job?id=50779610&langKey=zh-TW
使用者經驗設計師
http://careers.mediatek.com/eREC/Job?id=50779612&langKey=zh-TW

https://www.youtube.com/watch?v=_XoRJhJ6llA
https://www.youtube.com/watch?v=3s4QTGFomYE

**Comment by yutin1987** [comment]
後端不限語言 NodeJS, Python, PHP ...等

**Comment by yutin1987** [comment]
結束瞜！

**Comment by Rplus** [comment]
good!
