### ISSUE TITLE
[徵才] 樂傑科創 ReCactus - Backend Engineer

### ISSUE THREAD

**Issue by AlexandreHJE** [f2etw/jobs#402]
## 團隊簡介/地點
大家好，我們是ReCactus。

我們正積極尋找資深後端工程師夥伴加入我們的團隊。

ReCactus 是一個 錄製反應影片(Reaction Video)的社群平台。我們的團隊雖小，但我們的夢想很遠大，也
抱持著努力不懈的精神在國際舞台努力著，歡迎您一起加入我們！

經過 2017 AppWorks 創業加速器到產品發佈不到一年的時間，已募得美國、東南亞以及
台灣資金，且平台上用戶已錄製超過 150,000 影片，用戶數量也持續成長中！

獲得成就：

- 2018 日本知名科技展會 Infinity Ventures Summit 新創比賽冠軍 
(http://thebridge.jp/2018/06/ivs18s-launchpad-pitch-competition)
- 2018 亞洲最大科技展會 RISE Conference 冠軍
(https://international.thenewslens.com/article/99668) 

以下想再跟各位分享一下我們技術架構：

1. 我們使用Git/GitHub，並採用GitHub Flow，有良好的Bug fix, staging/production
deployment架構
2. 後端是採用Node.js開發，並使用Serverless framework搭配AWS Lambda，所以在Web
server層面來說，有近乎無限的scalability，不怕倒站，對於10 RPS到1 million RPS都
可採用相同架構。
3. 採用GraphQL API，相較於RESTful API，將資料存取細節交由client決定，
Introspection可直接當作文件，以及GraphQL種種優點，在此不一一列舉，相信GraphQL
會大幅取代RESTful。不過值得提的一點是，我們也花了很多心力在防範recursive query
和N+1 query的問題。
4. 使用ES6並搭配ESLint，尤其使用Async/Await，這能多大改善Developer Experience
(DX) 我就不再多言。不過很可惜還沒採用TypeScript是一大遺憾，但未來也是極有可能
採用的。
5. 使用AWS眾多服務：S3, CloudFront, Transcoder，而我們也擁有相當多AWS Credit，
想玩什麼新服務不用有壓力。其實我們也有GCP和Azure的Credit，目前也稍稍摸到一些
GCP。
6. 目前因為因應快速開發，沒有Testing/TDD，這的確是一大弱點，這個 trade-off 歡
迎大家討論。

另外附上一些採用的package：
1. sequelizejs：ORM、Database migration、防範SQL Injection等等
2. OneSignal：Massive push notifications、auto localization
3. Sharp：搭配serverless，最輕鬆完成縮圖任務

地點：台北市信義區（市政府捷運站旁）

## 工作內容
- 主要為 mobile API 開發與維護

## 能力需求
- 精通 Node.js/ES6、Express、GraphQL
- 熟悉 MySQL、Redis
- 熟悉AWS服務，包含 Lambda、API Gateway、CloudFront、CloudWatch、S3
- 熟悉 Git 和 GitHub
- 善於和 Android, iOS, Web Frontend 工程師溝通合作
- 能接受新創步調

## 薪資範圍
薪資: 年薪 800K ~ 1.2M 

## 工時/特休
每日工作時間: 10:00AM ~ 7:00PM (八小時), 中午休息(12:00 ~ 1:00)
加班與加班薪水: 遵守勞基法規定

## 福利/推薦項
- 不定期聚餐
- 有其他想法歡迎討論

## 聯絡方式
請 email 履歷至 alex.hu@recactusapp.com  Alex 收

**Comment by dca** [comment]
無前端職缺

**Comment by AlexandreHJE** [comment]
請問您想問的是前端Web的職缺嗎？

**Comment by osk2** [comment]
這裡只能發前端的缺，後端可以到隔壁棚

https://github.com/nodejs-tw/jobs/issues
