### ISSUE TITLE
[徵才] In Touch Games Ltd 誠徵前端遊戲開發工程師數名

### ISSUE THREAD

**Issue by tin80122** [f2etw/jobs#405]
## 團隊簡介/地點
獲獎無數的引達取有限公司是發跡於英國的線上遊戲開發與營運商。在數位娛樂（iGaming/ eGaming ）產業據重要地位，超過兩百萬的玩家活躍於旗下多個知名遊戲品牌。製作、發行與營運的遊戲相容於 iOS, Android 與 PC 系統，能支援近 99% 的硬體裝置。目前全球有近 300 位員工分據赫索溫（Halesowen, UK）布加勒斯特（Bucharest, RO）、吉隆坡（Kuala Lumpur, MY）與台北（Taipei, TW）。

- 工作地點近中山捷運站與台北車站

## 工作內容
- 根據遊戲設計文件開發遊戲
- 使用Typescript / Javascript 跟in-house editing tool開發遊戲
- 配合專案主管在時程跟目標上完成任務

## 能力需求
- 資訊背景或是相關的工作經驗
- 無工作經驗可, 有完整訓練課程

### 加分
- 具備遊戲開發經驗
- 具 Slot 或 Poker Game 經驗
- 熟悉Javascript / Typescript
- 熟悉物件導向程式設計
- 了解HTML5 / WebGL / Canvas
- 了解XML / JSON / REST APIs

## 薪資範圍
月薪可議（30K-50K)

## 公司資訊
- 具競爭力的年假制度（一年23天）
- 具競爭力的薪資制度（每半年Performance Review一次）
- 三節禮金
- 生日假
- 順暢的升遷管道 
- 不定期員工教育訓練 
- 免費下午茶、滿滿零食 
- 明亮寬敞的辦公環境 
- 咖啡機、微波爐、冰箱、飲水機等完善設備 
- 彈性上下班時間 
- 員工健康檢查 
- 員工團保
- 不定期康樂活動(受公司捐助社會福利單位為優先)
- 英國博弈外商公司、擁有英國合法執照 
- 'Top 1000 Companies to Inspire Britain'

## 聯絡方式
意者請直接投遞104履歷
https://m.104.com.tw/job/67z6j?jobsource=m104

**Comment by alvinnyen** [comment]
Hi @tin80122 ,

Is this position still is available?

thx
