### ISSUE TITLE
[徵才][Adenovo]  諦諾科技 徵求前端工程師

### ISSUE THREAD

**Issue by AdenovoTech** [f2etw/jobs#414]
## 公司簡介
Adenovo諦諾科技是一間AI金融科技公司，創立於2014年，以車聯網裝置整合數據實現無人化車隊管理作為創業開端，隨著資料累積與人工智慧模型逐漸成熟，我們實現全球第一個人工智能的汽車貸款風險評估及貸後風險控管的系統，能有效執行百萬件以上的貸款審核及風險管理，並與全球金融機構及租賃公司合作。

隨著技術日漸成熟穩定，業務夥伴逐漸增加並擴展其業務版圖，我們也開始為金融機構運用區塊鏈開發嵌入式金融服務，打造區塊鏈資產及智能債券平台並協助其銷售，透過智能合約的應用及技術整合，打造不同於以往的商業模式，提升資本運用率。我們在金融科技領域開發多樣的解決方案，期待能推動資金流動，打造普惠金融的環境，減少金融侷限，使更多人得到金融服務。 

網址：https://www.adenovo.com
Linkedin：https://www.linkedin.com/company/adenovo-tech

## 工作地點
台北市南港區忠孝東路六段21號8樓（遠雄國際金融廣場）

## 工作內容
- 設計Adenovo業務相關之系統平台，建立快速且具擴充性及高乘載之系統。
- 參與專案開發與程式碼審查。
- 維護且適時重構現有專案，並完成新專案。
- 與團隊成員協同合作，規劃並設計專案，並適時導入新技術。

## 能力需求
- 3年以上專業開發經驗。
- 精通JS與node.js，並且願意學習接觸多種程式語言。
- 具有React，Redux 和在SPA上的saga開發知識。
- 能以GitHub Flow之流程進行專案開發。
- 具有建立伺服器與系統之相關知識。
- 具有SQL，單元與負載測試之相關知識。
- 能撰寫模組化程式，以提升系統穩定度與擴展性。
- 對測試、撰寫文件及撰寫高品質程式碼有熱忱。

## 薪資範圍
- 月薪 60K 起跳（每年至少14個月）
- 另計 ESOP 員工股票選擇權

## 工時/特休
優於勞基法

## 福利/推薦項
- 生日慶生會 
- 下午茶點心零食櫃補到滿 
- 不定期Team Building活動 (春酒、尾牙、酒吧世足賽、KTV歌唱大賽、桌遊、蛋糕烹飪課、密室脫逃等) 
- 健身中心會員(強迫運動以便尾牙可以穿得下西裝) 
- 公司上市配股 
- 員工紅利/年終獎金 
- 定時技術分享會議 
- 技術書籍研討會輔助 
- 優秀的團隊夥伴 
- 最好的成長環境和舞台 
- 改變世界的機會

## 聯絡方式
請將個人之
- 中英文履歷(附照片)
- 自傳(中文即可)
- 作品集(i.e. github, marvelapp...)

寄至 cto@adenovo.com

**Comment by Rplus** [comment]
> 強迫運動以便尾牙可以穿得下西裝

wwww

**Comment by AdenovoTech** [comment]
其實公司是希望同仁們都能健健康康地與公司一同成長，因此會鼓勵大家培養運動的習慣。目前公司有人選擇上健身房、有人上瑜珈課、有人游泳也有人打泰拳。
