### ISSUE TITLE
[徵才][台中] 火箭科技有限公司 徵求資深前端工程師 

### ISSUE THREAD

**Issue by allxblue** [f2etw/jobs#426]
## 團隊簡介/地點
坐落於台中的〝遊戲〞產業公司，正在跨國南下發展，需要你的加入，
讓公司在時代洪流中能站穩腳步開疆闢土。

可參考公司於[104的介紹](https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=62684b73407451294060426e34463e67540424a733c3e466f444a42252525252534d52567503j50&jobsource=n104bank2)

## 工作內容
1.將PSD轉換成前端頁面製作，與動態效果呈現
2.協助修正網頁語法、版面問題
3.串接後端 API，開發 SPA 網站
4.優化網站效能及瀏覽體驗
5.後端功能協同開發

## 能力需求
1.資深前端該具備的技能
2.使用版本控制經驗
3.RESTful API 及 Route 概念
4.後端開發經驗 

### 加分
1.使用過前端框架(React、Vue、Angular皆可)於專案中
2.運用 flux flow 於開發項目
3.熟悉 ES6/ES7
4.前端部署環境建置
5.對於前端在 DevOps 自動化部分有實作經驗

## 薪資範圍
月薪NTD 55,000起，依能力調整

## 工時/特休
半責任制，但正常時間是早上10點前打卡，下午5點即可刷卡下班
特休比照勞基法

## 福利/推薦項
★ 甜點點心每日供應，咖啡任你喝。
★ 不定期舉辦戶外活動與餐會。 
★ 上班工時較短
★ 公司正在高速發展

## 聯絡方式
請提供線上作品集並將履歷寄至信箱
[lambert@rocketsz.com](mailto:lambert@rocketsz.com)

### 另有 Junior Frontend  及 Backend enginner 職缺請瀏覽
[https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=5c62456d3a6e4b233a5a3c682e40386193a3c446d363840693e443c1f1f1f1f1f2474c4c2a67j99&jobsource=n104bank2](https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=5c62456d3a6e4b233a5a3c682e40386193a3c446d363840693e443c1f1f1f1f1f2474c4c2a67j99&jobsource=n104bank2)

**Comment by ZhouHansen** [comment]
大陆的招么？

**Comment by allxblue** [comment]
> 大陆的招么？

查了一下台灣法規... 一年一簽啊，目前應該沒辦法

**Comment by ZhouHansen** [comment]
还好吧？有点麻烦而已

**Comment by dca** [comment]
關鍵是聘台灣人不麻煩啊



周汉成 <notifications@github.com>於 2018年9月19日 週三，上午8:30寫道：

**Comment by ZhouHansen** [comment]
嗯，谢谢你还去查了法规！

**Comment by allxblue** [comment]
> 还好吧？有点麻烦而已
應該要翻牆才能看的[法規看這裡](https://law.moj.gov.tw/LawClass/LawAll.aspx?PCode=Q0020006)

> 
聘僱期間：經許可受僱在臺灣地區工作之大陸地區人民，其受僱期間不得逾一年。（臺灣地區與大陸地區人民關係條例第11條第2項）並得申請在臺灣地區工作居留，居留期間最長為三年，期滿得申請延期。（關係條例第17條第2項）
（二）應備文件：僱用大陸地區人民在臺灣地區工作，應向主管機關申請許可（第11條）。申請許可應備文件，以下僅摘錄大專院校得邀請者。

就是我幫你申請了，主管機關也不一定會通過
北杭廣前端缺不少，待遇也比台灣高，其實不一定要來台灣的

**Comment by ZhouHansen** [comment]
哇哦💥谢谢你的提议，我知道北上广工资高..可惜不感冒

**Comment by allxblue** [comment]
@Rplus 麻煩協助關閉，謝謝
