### ISSUE TITLE
【徵才】AsiaYo - 前端工程師

### ISSUE THREAD

**Issue by Chelseaaaaa** [f2etw/jobs#428]
## 團隊簡介/地點
工作地點：台北市大安區敦化南路二段77號18樓之3
**我們的工程師文化：** 
- Technique enthusiasts：希望你熱愛技術，喜歡接觸與嘗試新知，在眾多的需求裡仍然可以不斷的精進自我。 
- Play fun：可我們相信每件事都需要熱情，希望你可以運用所學做出很酷又好玩的東西。 
- Problem solving：我們希望不只是看 spec 做事，而是作為一個 problem solver ，主動發現問題並提出解決問題的方法。 
- Team working：我們相信每個問題都有一種以上的解法，透過團隊集思廣益，選擇適當的開發語言，適當的系統架構才是最好的。 
- Give it a try：在這裡，錯誤並不可怕，怕的是因為害怕錯誤而不願意前進。擁抱改變，錯了就修正。 
[詳細職缺內容](https://pro.104.com.tw/vip/job/jobmaster?jobno=9329355)
## 工作內容
使用React開發，以最有效率的方式提供使用者方便好用的介面，踏入跨平台開發的領域。利用React Native在iOS、Android平台上開發Apps，讓使用者能在手機上享受即時、方便的服務。 
在工作中你將有機會接觸到: 
-- React Native Framework 
-- Payment, Authentication, Push notification, Tracking services
-- RESTful API, Service Oriented Architecture
## 能力需求
1. 熟悉Redux
2. 熟悉前端開發語言(JavaScript、HTML5、SASS..)，能熟練運用前端開發的工具、有RESTful API串接經驗。
3. 具相關工作經驗兩年以上(加分)
4. React Native實戰經驗，並有App上架(加分) 
5. 對UI/UX敏感度佳，能與PM、UX、UI設計溝通合作，開發出最酷的應用。對前端軟體開發的流程有清楚的了解認識。 
6. 喜歡跟不同團隊溝通，熱愛挑戰新事物。認為能做出使用者覺得好用、愛用的軟體，是件超酷、超有成就感的事
## 薪資範圍
年薪：700,000-無上限，依資歷給薪，有能力歡迎你來爭取。
## 工時/特休
工時：每周一至五, 9:00-18:00(含休息1小時)
特休：到職即享10 天(未滿一年按比例給)，第二年 11 天...(每增加一年多一天)
## 福利/推薦項
- 開放式的辦公空間、歡樂的大環境
- 彈性上下班時間 (只要確保所屬專案如期進行)
- 每月不必理由任選 2 天遠端工作，不必困在辦公室
- 員工專屬住宿優惠折扣！
- 每年20,000進修上課補助！
- 不定期 Workshop 邀請資深 Coder, PM, UX/UI Designer 交流增廣見聞
- 部門聚餐、不定期舉辦活動
- 吃不完的零食、放空專屬休憩區、與隨時能打開來玩的 PS4！
- 每月底周五下午 Happy Hour，免費供應下午茶 
- 三節禮金、生日禮金
- 員工團體保險
## 聯絡方式
hr@asiayo.com , 來信請附上履歷及應徵職缺名稱

**Comment by ZhouHansen** [comment]
大陆的招么？

**Comment by Chelseaaaaa** [comment]
> 大陆的招么？
不好意思, 因為大陸人士來台工作的可聘雇期間較短,不太符合公司所需, 所以目前沒有考慮喔！謝謝

**Comment by ZhouHansen** [comment]
可长期
