### ISSUE TITLE
【徵才】JUKSY捷喜多媒體 - 資深後端工程師

### ISSUE THREAD

**Issue by eveliao3** [f2etw/jobs#429]
## 團隊簡介/地點
JUKSY 捷喜多媒體是一個為引領趨勢而生的新媒體。透過連結不同領域的達人與創作者，為讀者打造出豐富、有趣且兼具價值的多元化內容，將玩娛樂、玩潮流、玩世不恭的新媒體品牌精神植入每位用戶心中。

工作地點：​台北市中正區羅斯福路二段9號5樓之-1

## 工作內容
1. 研究、開發、測試、維護電子商務網站及系統
2. 曾參與開發或執行O2O平台建置專案
3. 精通Javascript,PHP, Laravel，且具備跨瀏覽器相容性開發能力
4. 熟悉任一種API資料交換格式(ex: JSON,Aajax,XML)
5. 熟悉任一種前端框架(ex: Angular, React, Vue etc.)
6. 協助分析問題，並與團隊夥伴一同提出解決方案
7. 團隊有外籍人士，需具備基本英文溝通能力

## 能力需求
精通Javascript,PHP, Laravel

## 加分
1. 具備 MySQL/PostgreSQL相關知識
2. 具備 Google Cloud Platform架構規劃經驗
3. 擁有 EC電子商務網站開發經驗者佳
4. 擁有 APP 開發經驗者更佳

## 薪資範圍
月薪NTD 50,000-80,000，依能力調整

## 工時/特休
工時：每周一至五, 10:00-19:00(含休息1小時)
特休：比照勞基法

## 福利/推薦項
1. 很自由：享受新創團隊的扁平化組織管理、開放自由的工作氣氛，十點才上班，讓你睡好睡滿，不用擠通勤人潮，公司在古亭捷運站6號出口步行一分鐘，上班超便利。

2. 很好吃：無限量供應零食吧/膠囊咖啡暢飲/氣泡水，不定時發放廠商贈品、電影票券、展演票券、禮物包，公司每週贊助放縱下午茶，每月慶生會開心吃蛋糕。

3. 很好玩：絕對超值的員工度假(曾去過韓國釜山/泰國曼谷)，不定期大型聚餐(各大節慶歡慶)、電影日，壽星享有薪生日假，還有機會在公司撞見女神、藝人、名模、網紅。

6. 很好拿：員工專屬3C/APPLE產品特約商店，除了年終獎金、三節禮金爽爽拿之外，還有年年玩很大、送很大的華麗春酒派對

## 聯絡方式

歡迎將履歷寄到HR：
窗口：Eve
​eve.liao@juksy.com

**Comment by Rplus** [comment]
這是後端缺還是全端缺？

**Comment by eveliao3** [comment]
Hi Rplus ,

該職缺是後端缺(但會希望懂一點點前端方便溝通)，
我們也有開全端缺，若有相關職涯規劃也可以應徵喔 :)
公司招募頁：
https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=4f63456f595f425934353d6637413a1c95d63457143494224242424693c642928654j02&jobsource=n104bank1
很謝謝您的詢問！


best regards,


Eve


捷喜多媒體數位股份有限公司

*人資行銷專員*   *廖苡琇** Eve Liao*

T：02-7709-1777 <%2B886-2-7709-1777> 分機 121

F：02-2322-3999 <%2B886-2-2322-3999>

M：eve.liao@juksy.com

A ：台北市中正區羅斯福路二段9號5樓之-1
<https://maps.google.com/?q=%E5%8F%B0%E5%8C%97%E5%B8%82%E4%B8%AD%E6%AD%A3%E5%8D%80%E7%BE%85%E6%96%AF%E7%A6%8F%E8%B7%AF%E4%BA%8C%E6%AE%B59%E8%99%9F5%E6%A8%93&entry=gmail&source=g>


Rplus <notifications@github.com> 於 2018年9月20日 週四 下午11:58寫道：

**Comment by Rplus** [comment]
唔…
總覺得這後端工程師定義跟一般人認知不太一樣 XDD

**Comment by eveliao3** [comment]
Hi Rplus ,

感謝提醒！已再次跟內部同仁確認核心技能，
重新調整內容了，非常謝謝，也歡迎您加入我們 :)

Eve
