### ISSUE TITLE
[徵才][新竹][70K以上][Juiker] Senior Backend Engineer

### ISSUE THREAD

**Issue by shooding** [f2etw/jobs#431]
[徵才][新竹][70K以上][Juiker] Senior Backend Engineer
公司簡介
---------------------------
Juiker「揪科」是2015年從工研院獨立的新創公司，主要提供企業行動通訊解決方案，包含即時通訊、話務節費、雲端通訊錄等產品。
除了在台灣已佔有一席之地，更開始在多個國家 (例如越南 http://news.ltn.com.tw/news/business/paper/1188673) 提供在地化的服務。
更於2018年6月 與Yahoo!拍賣攜手推出「拍賣即時通」。
https://www.inside.com.tw/2018/06/26/yahoo-juiker

源思科技將以Juiker揪科成功經驗，持續朝向雲端資訊服務邁進，期望為OTT(over-the-top)服務產業注入動能，同時結合在地精神與國際接軌，推出國際化服務，展現台灣的軟實力。

主要商品/服務項目
------------------------------
Juiker雲端企業通訊服務

福利制度
------------------------------
<ul>
<li>提供 MacBook Pro + 外接27吋顯示器</li>
<li>公司提供免費咖啡、鮮奶</li>
<li>年終獎金保證 2 個月，以全薪計</li>
<li>年度健康檢查</li>
<li>不定期員工聚餐</li>
<li>每個月生日慶生或團康活動</li>
<li>電話費補助</li>

</ul>

工作內容
------------------------------
- Build world-leading Instant message and VoIP SaaS for corporate users
- Containerization of backend services for CI/CD and scalability
- Cowork with Client team to realize business logic
- Cowork with System-Assurance team to achieve automated testing
- Cowork with Operation team to provide highly reliable services

[Required]

- Heavy Instant Messaging/VoIP user like LINE, WeChat, Messenger, Skype, Viber and eager to build one of your own
- Git
- 2y+ experience in scalable service
- 2y+ Linux user knowing shell commands
- Knowledge of MVC/ RESTful API
- Familiar with either PHP or JAVA or Erlang

[Bonus]

- Experience in K8s/AWS/GCP/VMWare/Openstack
- Familiar with MySQL Query optimization
- Familiar with NoSQL DB like Dynamodb/Cassandra/MongoDB
- Familiar with unit testing tools like PHPUnit, JUnit, EUnit
- Familiar with load testing tools like JMeter, Tsung, Chaos monkey
- Experience in erlang

[Interview questions](https://github.com/shooding/interview/blob/master/backend/questions.md) 

In order to get the position, you must create a pull request with your answer.

**Comment by shooding** [comment]
@Rplus 
labels:
[B] JAVA
[B] PHP
GIT

**Comment by Rplus** [comment]
目前只收前端類的職缺唷
