### ISSUE TITLE
jobs on secure-scuttlebutt

### ISSUE THREAD

**Issue by caasi** [f2etw/jobs#432]
最近從 [pellaeon](https://social.slat.org/@pellaeon) 那裡看到 secure-scuttlebutt 這個分散式 SNS ，不同的應用程式可以在 feed 放自定義的資料，例如 [scat](https://github.com/stripedpajamas/scat) 就放了自己的 `scat_message` 。

要不要來把 jobs 放到上面（雖然我只會寫 js 0rz ）？這樣想做公開或私人 job 平台的人都可以利用～

protocol 介紹： [Scuttlebutt Protocol Guide](https://ssbc.github.io/scuttlebutt-protocol-guide/)

補充：這不是徵人，而是提議開發平台。

**Comment by yutin1987** [comment]
感覺放 jobs 的標題不是問題，但要放內容可能有難度。 話說 放上去的 好處是？

**Comment by caasi** [comment]
現在的 post feed 長這樣：

```
{
  "previous": "%XphMUkWQtomKjXQvFGfsGYpt69sgEY7Y4Vou9cEuJho=.sha256",
  "author": "@FCX/tsDLpubCPKKfIrw4gc+SQkHcaD17s7GI6i/ziWY=.ed25519",
  "sequence": 2,
  "timestamp": 1514517078157,
  "hash": "sha256",
  "content": {
    "type": "post",
    "text": "Second post!"
  }
}
```

content 的 type 和欄位可以按應用程式需要自訂，不支援的應用程式可以不顯示。

---

以前曾好奇，如果有人「不喜歡公開徵才或被徵才，求職時很吃小圈圈的信任關係，又希望資料可以帶著走」，可以用怎樣的軟體達成。那時想像的解法是把求才網站跑在 sandstorm 上（當時 sandstorm 除了資料帶著跑外，還強調一人多 identity ）。但開發 sandstorm app 其實沒有很方便， Meteor 也滿複雜的。

這次看了 Scuttlebutt Protocol Guide ，發現他在 LAN 可以自動探索其他節點，同步資料，在 WAN 上可以和任意 pub 連接，達成中心化 SNS 看到「朋友的訊息」與「朋友的朋友的訊息」的效果。

才想到要是 job 內容和現在 Scuttlebutt 的 about 或是 gather 一樣，大家可以附加訊息、標籤上去，那就同時達成「呈現小圈圈對求職或求才者的信任」與「大家擁有自己的資料」這兩件事。而且要公開徵才（public pub）或是私下徵才（LAN 或 privite pub），完全交由該圈圈自行選擇。

我想做的是：
  * 找個假日來 patch [Patchwork](https://github.com/ssbc/patchwork/) 這個 client ，
  * 按 f2etw 的需求，設計 job 欄位（畢竟這邊的欄位是被真實需求淬煉出來的），
  * 運作看看，再決定：
    * 在 scuttlebutt 詢問別人的興趣、
    * 將 repo 移到 f2etw 或其他適合的 org 下、
    * 是否做獨立的 client 、
    * 怎麼同步 GitHub 上的 issue 上去、
    * 台灣還有什麼樣的人或團體有興趣？

也許最後一般 post 或 gather 就能完成此事，不需要特別的 job feed 那也沒差。另外如果有人比我快開坑，我也希望能加入，一起填坑 XD

**Comment by caasi** [comment]
有人做了看來很酷炫的 [tale:net](https://t4l3.net/) ，我先關掉這個 issue 好了。
