### ISSUE TITLE
[短期專案] TaiBIF 徵 Vue.js 專家協助完成 API 串接

### ISSUE THREAD

**Issue by cjk-halodule** [f2etw/jobs#441]
(107 年 11 月 2 日更新)

## 團隊簡介
[TaiBIF](http://taibif.tw) 為全球生物多樣性資訊機構（GBIF）的臺灣節點，目前設立於中央研究院生物多樣性研究中心。我們積極配合 GBIF 的[工作計畫](https://assets.ctfassets.net/uo17ejk9rkwj/3Ua4cMwNawso46kMGisICM/31a4b0c3e0aee20d0954230b72bc405f/GBIF-Work-Programme-2018.pdf)推動臺灣生物多樣性數據資源的公開分享及研究單位資訊管理流程的研發及建設。生物多樣性資訊學為跨生物學及資訊學的新興領域，有許多令人興奮的專案正在進行，歡迎您的加入，和我們一起探索與開發！

### 專案說明
為了統整臺灣自動相機監測資料、照片及影片，TaiBIF 團隊今年起著手規劃及建置自動相機資料管理系統。目前已完成前端設計（見[暫時頁面](http://camera-trap.aja.com.tw/index.html#/)），使用 Vue.js 為前端框架，後端資料庫及 API 建置中，尚需完成前端與後端 API 之串接及資料交換，以完成系統開發。

## 工作內容
1. 瞭解專案概況；細讀設計線框圖瞭解功能項目。設計線框圖十分詳盡，可按圖施工，大部分 HTML 渲染已就位。
2. 與前端開發人員瞭解前端程式碼架構，著手開發。目前程式碼請見 [camera-trap-webapp](https://github.com/TaiBIF/camera-trap-webapp)（持續更新中）。
3. 與後端開發人員協調，確保串接正確、功能可驗證。
4. 維護程式碼品質及建立應用程式連續整合(integration)及部署(deployment)流程。

## 能力需求
1. 熟悉 Vue.js 及後端 API 串接。
2. 熟悉 git 操作。
3. 習慣跟隨 coding convention，並提供程式碼註解。

## 薪資範圍
**時程**：預計應可在三至四週內完成。
**待遇**：以時薪 NTD$800 計。
**有效時間**：即刻。 

## 聯絡方式
[柯智仁先生](https://www.linkedin.com/in/chihjen-ko-2096441/ 
) 
聯絡地址：[cjk@sinica.edu.tw](mailto:cjk@sinica.edu.tw)，主旨請註明「Vue.js API 串接熟手」確保收件，我們將儘速回覆。
聯絡電話：(02)27872220 ext.24 

### 應備文件： 
1. 個人在 github 的作品集，有實際 production 的案例（請提供 URL）尤佳。

**Comment by cjk-halodule** [comment]
@wangchou 是否可提示應加強說明的地方？

**Comment by wangchou** [comment]
Downvoted because this line.
```
以時薪 NTD$520 計（相當於年薪 1,081,600）
```
沒提供設備、沒有勞健保、沒有國定假日、沒有特休的年薪108萬?

**Comment by cjk-halodule** [comment]
謝謝 @wangchou 說明，已修改用字。

**Comment by cjk-halodule** [comment]
瞭解業界一般行情後調整時薪。

**Comment by cjk-halodule** [comment]
已徵得合適人選囉，謝謝。
