### ISSUE TITLE
[徵才] 集界科技 徵『UX 互動工程師』

### ISSUE THREAD

**Issue by yutin1987** [f2etw/jobs#444]
## 🍓 UX 互動工程師：

**職稱說明**
UX 互動工程師 就是在做互動流程時，已知悉常見基本應該避免的設計，且發現很不好的使用流程會忍不住把它改好的那種，而在迭代的開發過程中要知道如何做使用者經驗驗證。

**工作內容**
- 用 NodeJS or Python or Go 開發 server side
- 用 React and NextJS 或者更棒的架構開發 client side
- 用 Native 或 React Native 或者更棒的架構開發 mobile 端應用
- 用 Google Cloud 架設雲端環境（非必要）

**開發模式**
任務不依領域做切分，也就是不分前後端或營運。任務因需求而產生，解構需求小則 1 人大則多人合作，先找到出最適解後，再以敏捷方式共同完成任務。
延伸閱讀：

## 🥦 基本條件
熟悉 Slack 、 Docker 、 GitHub 與 Sketch。

## 🍖 加分項目
[資訊界連署挺同婚](https://github.com/RainbowEngineer/taiwan_love_wins/tree/master/signatures) 有簽名，穿搭有個性、玩音樂或滑板、騎單車、曾經出國旅遊、手做乾燥花、習慣用鋼筆寫字、喜歡喝飲料、等紅綠燈時吹口琴、聽烏牛欄大護法、玩 Switch 或 PS4、搭電扶梯都站左邊，而且反著站。

## 🍎 工時與休假
- 上下班時段，通常上午 10 點開始有人進公司，然後下午 5 點開始有人離開公司。
- 使用 https://geekbot.io/ 進行每日的站立會議 (asynchronous standup meetings)。
- 使用 https://www.attendancebot.com/ 進行自我工時管理。
- 工作不一定需要在辦公室（請在 `Slack` 透過 `AttendanceBot` 告知在何處工作即可）
- 週休二日，依國定假日休假（休假期間 `Slack` 與 `Email` 無需理會）
- 特休／病假／產假／生理假／失戀假／照顧家庭假 / 技術聚會假，不扣薪全年無上限（請在 `Slack` 透過 `AttendanceBot` 告知不想工作），如需長時間休假可討論留職停薪。

## 🍌 團隊準則

**異步的討論**  
- 除每兩週一次的 meetup 聊聊近況外，不會有全體會議
- Slack 為預設 Google Meet 為例外，必要時由 Owner 招集 2~3 人成組討論
- 善用非同步（Slack）方式進行討論，或過透 standup meetings sync 進度

**嚴謹的態度**
- 每個 Pull Request 都會經過至少 1 人以上的 Code Review 
- 寫測試是開發者最基本的必要習慣，後端 Jest 前端 TestCafe
- 發現 bug 不是用猜的來 fix 需有能力先找出問題的原因進而找出解法

**開放的文化**
- Slack 上討論 #general 是預設其他是例外，其他夥伴有興趣都可參與
- 每位夥伴的行事曆皆公開，沒有專屬的工作可自由協調資源
- 開發上優先考量開放且標準的架構，確保專案的延續與相容性

## 🍍 薪資
『月薪 50k x 13 個月 = 65w』當下被團隊成員**問倒**但有潛力
『月薪 60k x 13 個月 = 78w』當下被團隊成員**問不倒** 
『月薪 70k x 13 個月 = 91w』當下被團隊成員**問不倒**且提出厲害的見解

- 目前開發團隊成員：
前端、後端、手機應用、伺服器、硬體：2 名
前端、後端、手機應用、伺服器：2 名
後端、伺服器：1 名
前端：1 名

## 🍒 應徵步驟 1 2 3
1. 請寫 255以內的字 說明 自己與眾不同的地方，並附上常用的 Social Network 網址 (GitHub / Twitter / Linkedin / SlideShare / Instagram / Behance / Medium, etc)，Email 至 yutin_liu@tmotx.com 與 liting_hsu@tmotx.com（收到 email 後 3日內會與你聯繫）
2. 公司實體面談介紹公司產品與文化並討論公司福利等，並 Email 幾個問題於下次線上面談時聽你發表看法。
3. 透過 meet.google.com 線上面談，並與公司所有團隊成員聊聊天、談談公司工作習慣等。（結束後 3 日內會通知你結果並告知核可薪資）

## 🍣 公司簡介
Tmot 是我們的名字，代表的是 Together & Moment - 把握當下，珍惜人與人之間每次的相遇！
我們不喜歡官僚文化，崇尚開放、透明、簡約、效率。我們認為讀萬卷書不如行萬里路，出國、出差、旅行是公司成員們的習慣。海賊王裡的索隆說：「人生中有些事你不竭盡所能去做，你永遠不知道你自己有多出色」，Legends Never Die 只要我們存在著，正當我們揮霍生命像個孩子，留下的不只是回憶更該是歷史的創造者，歡迎加入生來顛覆的 Tmot 團隊。

## 🍰 產品簡介
- UniQR - https://tmotx.com/
- mutix - https://mutix.co/
- CHITOSE 千歲

**Comment by Rplus** [comment]
為啥 UX 要熟 Docker 呀？ XD

**Comment by yutin1987** [comment]
為什麼不要熟 Docker 呀？

**Comment by damody** [comment]
可以進你職缺的人可以進其它薪水高太多的大公司了，而且大公司還不需要會那麼多，這個薪水最多就是應屆國立碩練功仔的薪水。

**Comment by dca** [comment]
這個缺蠻厲害的，前端 & 後端 & App & UX

**Comment by hlbarbarian** [comment]
Full stack 加上會 Infra ，這樣的薪水可以找到人？

**Comment by duncanhsieh** [comment]
條件設太多只是會難找人，尤其要fullstack又devops又UI/UX，太奇葩了 XD

**Comment by joey3060** [comment]
要求基本上 從front-end , back-end , RN and mobile, 還要會部署 , docker。 然後用UX engineer的名義找人 給這樣的薪水?..，然後還很嗆的說 "為什麼不需要熟docker"?  我想貴公司真的很想紅 你的薪水是給你現在的薪水x5倍?

**Comment by david50407** [comment]
原來是 Universal eXpert 啊，我找錯職缺了

**Comment by BryanYu** [comment]
🍌🍌🍌🍌🍌🍌🍌🍌

**Comment by idiotize** [comment]
看起來很有趣呢，不過提醒一下，薪水的部份是不是標錯了？這大概是十年前畢業生的起薪哦！

**Comment by yutin1987** [comment]
『UX 為何需要 Docker』？ @joey3060 @david50407 
請各位要再認真看清楚 原文 有針對職稱說明，需要找的是 User Ex 不是 User Re ，簡白一段話就是『請在做前端時對 UX 有點基本的 sense ，不要犯了網路上文章裡常見的錯誤，如果發現有網路上提到的常見錯誤，請撥空修正或開發 issue 追蹤』
至於前端與 Docker ，近年來我有一個案子對方後端使用 RoR ，該架構對於系統原生套件的相依性太高，常增加不必要的開發時間成本，因此雖然我只做前端，但用 Docker 運作後端來幫助開發是一個不錯的解決方案。
當然不管是前端與否，Docker 都是重要的，目前走 k8s 架構每一個 commit 都會封裝成一個 Docker image ，不論你的任務是什麼，只能把 Docker run 起來對於開發、測試、驗收與討論都有很大的幫助。

『又 … 又 …，太奇葩了 』？ @dca @duncanhsieh 
不奇葩吧！這只是我的日常，還會玩玩直播、搞視覺互動設計(VJ)、有線無線網路建置、漏洞掃描、拉電路寫嵌入式系統、繪圖行銷小編與滑雪，上面原文大概只是我會的技能的三分之一左右。

『職稱改成一條龍』？ @osk2 
也許在你的習慣裡，已習慣一個人從頭做到尾，但在我們團隊裡的『開發模式』如原文所提，要會習慣將任務拆細，在單點目標上進行多人合作加快產品的進程，時而你可需要寫寫後端，時而你需要寫寫前端，老話一句『前後端分離是架構，別把前端分裂當習慣』。

『大公司還不需要會那麼多』？ @damody 
不確定你指的大公司有多大，目前我待過最大的公司是 1000+ ，我的經驗是不管大小，人與人團隊合作的人數極限是存在的，即便在扁平化的架構下，還是需要有虛級的小組存在，當小組的技能有限時，勢必就需要跨單位合作，就像公司去找外包商一樣，這時候各種職場小故事就不在此處多說了。

『薪水可以找到人』？ @damody @joey3060 @idiotize 
『５萬前端 + 5 萬後端』 vs 『10 萬前後端』我會選擇後者，但別忘了就算你會的技能再多，每個人都只有 24hr，在相同時間速度下每個人的產值是均等的，因此在團隊裡無論年齡、性別又或者工程師與設計師，領的薪資大同小異這是很重要的平等價值。當然而有些時候每個人的經濟壓力情況有所不同，盡可能讓每位成員沒有經濟壓力為優先考量。又或者如果你覺得你的速度堪稱奇耙，產值遠高出公司價值獲利的 N 倍時，想領 300 萬的薪資並將 200 萬的收入用在對社會有意義的事情給更需要的人時，薪資好談好談。

 『很嗆的說 "為什麼不需要熟docker”』？ @joey3060 
喔！因為他是我老朋友了～ 不嗆一下怎麼行。

<附錄>

前些日子去 TeamLab 辦公室觀光，還記得有段對話是這樣的：
Q: TeamLab 目前有哪些職缺？
A: 工程師與設計師 而已
Q: 這樣而已？但工作內容似乎不是常見大家對於工程師與設計師的認知
A: 加入後就要想辦法會瞜！但也許不適合會離開

前些日子路過 矽谷 一趟，問了幾個朋友現況，答案如下：
能力高與低依然落差很大，但近年開始找尋會多樣技能的人，因為這會提高效率，減少等待與溝通。
當然 技能多樣的極限在哪 有待討論，必定 Airbnb 表示 React Native 所需的技能所跨的領域之多，已造成找人困難。
然而最近我們團隊有個 App 的專案，負責的成員表示想用 React Native 施工，討論中我表示之後會有很多 Native 的串接需求這樣行嗎？找得到人嗎？他的回答是：『行啦！就這樣幹』，所以看樣子我們要找更多『行啦！就這樣幹』的人。

---
以上想法為個人價值觀，無關對錯與職涯規劃，你依舊可以堅持只寫前端 JS 又或者只玩 iOS ，然後跟出資者要求 300萬 年薪。只是不適合我們團隊而已，期待其他有趣的人加入。 😄

**Comment by yutin1987** [comment]
路過日本與矽谷找了朋友聊天後，
開始思考 **『職稱說明』『工作內容』『開發模式』** 的重要性，
因為這是一個合作上基礎態度的共識，
**這樣的職缺說明，大概已經擋掉本身就對自己設限又或者不勇於挑戰的人，**
 團隊裡在這個共識下，也許你會的不是那麼多，又或者只是皮毛，
但只要態度對了，有我在 要我把畢生所學與你分享又何是難事？又或者你自然就會成長不必我操心，
自信與決心是很重要的，別忘了公司不是付你錢來學習的地方，那是學校。

有些公司老愛看 KPI ，但我喜歡之前某公司的 HR 人事評比表，
主要 3 個問題『這 1 年做了什麼？』『下 1 年要做什麼？』『下 1 年要挑戰什麼？』
多麼熱血...

**Comment by tpai** [comment]
我是覺得啦... 大家不是不勇於接受挑戰，是不敢接受低薪。

**Comment by guAnsunyata** [comment]
基本上你所相信的價值與本篇求職被討論的地方沒有關係。「對自己不設限，勇於接受挑戰」的人是每一個追求成長的公司渴求的人才。公司會反過來說明你們會提供什麼樣的環境或資源給願意突破和貢獻一切的員工。
薪資的部份也是不合理的，你提到 5 萬、10 萬最後 300 萬

**Comment by smallseven1213** [comment]
我這些都ok
會UX，我也會做設計，後端也ok
年薪250萬ok嗎

**Comment by tpai** [comment]
「不扣薪全年無上限的休假」最近開出這種福利的公司好像變多了

不過個人還是認為沒有白紙黑字寫明有多少假來的踏實，所以我都會當作沒有

起薪不設上限的意思是因為這邊貼要給香蕉資訊，所以給個起薪當底嗎？

如果是這樣，那就祝福貴公司跟面試者能談好彼此都滿意的數字囉。

**Comment by caasi** [comment]
@yutin1987 大大考慮一下求職者的心情啦，不是每個人都能專心在專業上，也不是每個人都有機會看見你看到的世界。 0rz

**Comment by yutin1987** [comment]
@caasi 感謝!!! 了解你的意思~ 但我需要清楚解釋我們正在找尋的人，避免日後合作上認知的差異。

**Comment by dca** [comment]
其實很簡單，「月薪 4 萬 8 起」很容易有種預算大概就是 4 萬 8 上下的感覺。 

其他的沒什麼好戰的，不同團隊組成本來就會需要不同特性的人才，Ｔ型人才很難得的

**Comment by Negaihoshi** [comment]
對於職缺而言，工作內容就是能力要求，薪資就是對於這個能力要求給的，所以大家看到這個要求對薪資覺得不合理才會有這些反應，如果你多寫「 junior 可談」或是「能加更好，薪水另談」其實就會爭議比較少了，不然對於台灣的環境來說，大多數人可能只會覺得你想找給 4w8 想卻讓他做四份工的人

**Comment by tedshd** [comment]
小弟也粗淺地提供一下自己的看法
從上述的回覆
大致上了解 @yutin1987  對該職位的要求與看法
其實要求對大部分資深一點的工程師來說不算難
但是以有工作經驗的工程師一開始看到這 JD 中的薪資起點還是會有點害怕

接下來以下為個人看法

然後關於

> 新成員領的是 48k 代表『我認為你不會的還很多，但我信任你未來有機會達到因此歡迎你的加入』。

其實這很有難度

1. 這樣有潛力的新人(這裡我指的新人大多是指應屆畢業生)不多, 我也有見過很厲害的應屆畢業生

2. 對方是否願意來衝一把(當然是要看對方的心態是找份工作還是來把工作當成自己的生活中的一部分)

3. 新人的未來是否能達到你期望也是個未知數(每個面試時都自信滿滿, 但是最後沒達到期望...)

4. 依我慘痛的面試經驗, 在新人中有這種潛力的人不多(當然也可能是我面試過的人太少)

5. 我是覺得與其接納新人不如只專注在找真正有兩把刷子的人, 而且把薪資標準底線調高, 讓有興趣又有兩把刷子的人不會質疑或猶豫

以上是小弟的淺見

**Comment by SimonSun1988** [comment]
建議薪水上下限
起薪 48k ~ 150k (依能力面議)
這樣就不會起蒸液

**Comment by yutin1987** [comment]
@Negaihoshi 不好意思，我與你持有不同的看法，

### 『工作內容就是能力要求』這應該是近年來台灣職場上最大的誤會哩！
在勞動契約上『工作內容』指的就是報到後將要面對該做的事，會不會做與能不能做好無法在書面被定義，舉個例子`當你入取了早餐店，勞動契約寫煎蛋如果你不會，資深的人就會教你如何煎蛋，突然有一天增加了鐵板麵，依法你可以因與工作內容不符拒絕，當然多數企業會用一條萬用契約『任何主管交辦的事項』`，但基於道德還是求職時講清楚比較不會有爭議。另一個情況，`勞動契約如果寫 Excel ，當公司將系統從 Excel 2008 升級至 Excel 2010 時，是否可以依員工不履行工作內容而資遣？答案當然是不行，應該要優先考量做在職訓練，但成本之高也就造成多數企業不願意升級系統`，至於企業是否要付薪出錢做在職訓練？這又是另外一個議題了，我就不再多說

### 『薪資就是對於這個能力要求給的』在此我與多數人持不同的看法
個人不是從體制內成長的，並不喜歡資優生文化。如之前所提，就算人再厲害 1 天依舊只有 24 hr，在公司產品還沒轉虧為盈之前，優先考量的是個人經濟負擔，我需要確保所有成員不會為此挨餓，又需要將資源做最有效分配，然而公司開始轉虧為盈之後，優先考量的是產值、社會貢獻與承擔的責任，再者依舊是個人經濟負擔。當然而會有特例，當技術具稀有性時勢必就要談，但這件事在軟體開發上不常發生。

另有關建議：
「 junior 可談」<= 當寫 60k junior 可談，然後面試時說你是 junior 因此 48k ，這不是詐騙嗎？
「能力優，薪水另談」 <= 當寫 48k 能力優，薪水另談，我知道有些人會這樣寫，但有誰覺得自己能力不優？也就是大家都要另談？這跟『48k 起』的差異在？何不無關能力都可以提？且 『工作內容就是能力要求』『能力優，薪水另談』前後文好像矛盾。 

### @SimonSun1988 感謝建議，以依你的建議設定上限。
但我並沒有很認同此作法，雖然在此多數有這個習慣，且間距越來越大，難道沒有人懷疑過到底是誰領 150k 嗎？還是其實 48k ~ 150k = 48k？又或者有些公司依職等真的可以從 48k ~ 300k （我知道有） 那... 領 48k 的什麼時候會 300k ？

**Comment by yutin1987** [comment]
@tedshd 大大別這麼說，來聊聊吧！

### 『有工作經驗的工程師一開始看到這 JD 中的薪資起點還是會有點害怕』
所以我想... 會認真面試的大概是認同產品且 catch 到我的理念的人吧！而且看到『起』後願意提出期望薪資的人，應該是很有想法且不受限於框架的人，必定除了工作內容與薪資外，原文一大串都在講公司的文化與理念，而且多數是已經在執行的事。

另補充：目前的做法是不過問之前薪資，只問期望薪資，然後依期望薪資給與入取與拒絕的結果。

### 1. 2. 3. 4.
就如你所說是如此沒錯，但有幸的是目前團隊有不少『有潛力的人』，當然兒也是花了很常時間的累積，但我願意多花點內心做這件事，必定在我年輕時非常感謝許多前輩的提拔。

### 5.
就如同你說的『每個面試時都自信滿滿』，可能是我看人能力不佳，目前遇到的『說自己有兩把刷子的』然後給了高薪都是失望的結果，當然我還沒放棄期待在此貼文，離開同溫層下也有機會遇到，但目前比較頃向這類夥伴要用挖角的。

**Comment by yutin1987** [comment]
@guAnsunyata @CodinCat

這是 9 月 [徵才設計師的貼文](https://www.facebook.com/groups/TaiwanUIUXDesigners/permalink/1281687788640068/) ，
入門起薪 48k 幾乎每日 1 封 mail 持續約兩週，而在此 FED 的貼文目前 2 封 mail，
前些日子 #GoogleWalkout 目的在追求消除騷擾與歧視，這也是我追求的不論性別與職業（設計師 / 工程師），在 24hr 的架構下我會給平等的待遇。也許你的平等不等於我的平等，也許因此我會招募不到工程師，但... 價值不應利益或對象而妥協，就像當初 FED jobs 的版規認同且執行之後，即便離開此版我的徵才文依舊會附上薪資與休假資訊，然而也許明年會調薪那也是設計師與工程師同步。

cc. @Negaihoshi  打擾你了!!!

**Comment by jack45j** [comment]
聽起來根本就是不同工但又要人家同酬
因為每個人一天都是24HR 產值都差不多 高不了哪裡去
所以你過去花再多時間會再多技能跟專業你還是只有24HR 產值差不多 薪水大家也應該差不多
是這個意思吧? 是這樣理解吧?

**Comment by yutin1987** [comment]
更新資訊如下：

## 🍍 薪資
『月薪 50k x 13 個月 = 65w』當下被團隊成員**問倒**但有淺力
『月薪 60k x 13 個月 = 78w』當下被團隊成員**問不倒** 
『月薪 70k x 13 個月 = 91w』當下被團隊成員**問不倒**且提出厲害的見解

- 目前開發團隊成員：
前端、後端、手機應用、伺服器、硬體：2 名
前端、後端、手機應用、伺服器：2 名
後端、伺服器：1 名
前端：1 名

**Comment by yutin1987** [comment]
基本條件增加 必須在 [資訊界連署挺同婚](https://github.com/RainbowEngineer/taiwan_love_wins/tree/master/signatures) 有簽名。

**Comment by sharils** [comment]
@yutin1987 Is this still open? Thanks!

**Comment by yutin1987** [comment]
@sharils 感謝提醒 🙏，貼文後已徵得。
