### ISSUE TITLE
[短期專案] TaiBIF 徵 Node.js + Express + MongoDB 熟手協助 API 開發

### ISSUE THREAD

**Issue by taibifbrcas** [f2etw/jobs#449]
(107 年 11 月 7 日更新)

## 團隊簡介
[TaiBIF](http://taibif.tw) 為全球生物多樣性資訊機構（GBIF）的臺灣節點，目前設立於中央研究院生物多樣性研究中心。我們積極配合 GBIF 的[工作計畫](https://assets.ctfassets.net/uo17ejk9rkwj/3Ua4cMwNawso46kMGisICM/31a4b0c3e0aee20d0954230b72bc405f/GBIF-Work-Programme-2018.pdf)推動臺灣生物多樣性數據資源的公開分享及研究單位資訊管理流程的研發及建設，完全支持開源的開發模式。生物多樣性資訊學為跨生物學及資訊學的新興領域，有許多令人興奮的專案正在進行，歡迎您的加入，和我們一起探索與開發！

### 專案說明
為了統整臺灣自動相機監測資料、照片及影片，TaiBIF 團隊今年起著手規劃及建置自動相機資料管理系統。目前正在進行：
1. 前端開發（見[暫時頁面](http://camera-trap.aja.com.tw/index.html#/)），使用 Vue.js 為前端框架，接近完成，目前 API 介接工作亦正進行中，[專案位置](https://github.com/TaiBIF/camera-trap-webapp)；
2. 後端資料庫及業務邏輯開發，使用 AWS EC2 w/MongoDB, S3, Lambda, [專案位置](https://github.com/TaiBIF/camera-trap) ；
3. API 建置，採用 LoopBack (基於 Express) 連 Mongo DB 提供前端網頁接口，[專案位置](https://github.com/TaiBIF/camera-trap-api)。

本 part-time 徵才專注在第 3 項 API 建置。

## 工作內容
1. 瞭解 API 專案的開發情況，加入分工，協同開發。
2. 參考/修訂 branch strategy，建置 dev, uat, prod 伺服器環境。
3. 建立應用程式連續整合(integration)及部署(deployment)流程。
4. 程式碼 QA 工具及規則設置（如 eslint rules）。
5. 提昇程式碼的 test coverage。
6. 應用程式效能調校。
7. 清除已累積的技術債（趁還沒累積很多）。
8. Infrastructure as code.

## 能力需求
1. 瞭解 Node.js 生態系網站應用程式開發，有 benchmark Node.js 應用程式經驗。
2. 熟悉 MongoDB 的配置。
3. 有 API 的開發經驗，熟悉 Express，有意願瞭解 LoopBack。
4. 對 ES6 有很好的掌握。
5. 熟悉 git 操作。
6. 習慣跟隨 coding convention，並提供程式碼註解。
7. 有自動化與程式碼品質的 OCD :)

## 薪資範圍
**時程**：希望第一、二個月可較密集地協助，後續可視情況以不同的方式協議合作模式及費用。
**待遇**：以時薪 NTD$1,500 計，可議。
**有效時間**：即刻。 

## 聯絡方式
[柯智仁先生](https://www.linkedin.com/in/chihjen-ko-2096441/ 
) 
聯絡地址：[cjk@sinica.edu.tw](mailto:cjk@sinica.edu.tw)，主旨請註明「自動相機系統 API 開發」確保收件，我們將儘速回覆。
聯絡電話：(02)27872220 ext.24 

### 應備文件： 
1. 希望有在 github 的開發專案可分享。
2. 建議可指出目前 [camera-trap-api](https://github.com/TaiBIF/camera-trap-api) 可見問題並提出改善建議。
3. 有推薦者為佳。

註：對臺灣業界情況尚不熟悉，若內容有任何不合理的地方，請不吝指教，謝謝！

**Comment by dca** [comment]
這篇誠意滿點！

**Comment by appleboy** [comment]
@taibifbrcas vim 產生的 .bak 檔案? https://github.com/TaiBIF/camera-trap-api/blob/master/server/middleware.json.bak

**Comment by cjk-halodule** [comment]
@appleboy 不小心 commit 進去，感謝您的 pull request 啊！開源的好兆頭！
