### ISSUE TITLE
Vectr - Full Stack Javascript engineer

### ISSUE THREAD

**Issue by yurenju** [f2etw/jobs#45]
☞☞☞ 徵才網址（也有 designer 跟 marketing 的職缺喔！）： https://vectr.com/jobs

[English below]

我們相信每個人都可以成為設計師，為此我們正在使用 Javascript 全新打造一個向量圖形編輯器 — 內建設計作品發佈平台與設計團隊的協同設計工具來協助所有設計師們。

https://www.youtube.com/watch?v=CnSRzM91FYY
# 公司文化

所有團隊成員都是遠端工作且獨立作業。這代表你可以在你最愛的咖啡館喝著咖啡工作並使用 Slack 跟團隊成員溝通。由於我們開發的系統十分模組化所以每個人通常都主導系統中的部份模組並獨立作業。
# Tech Stack

我們幾乎從頭建造整個 stack 包含 framework 以及整個向量繪圖工具，所以我們尋找的團隊成員需要能夠樂意面對困難的問題，並且積極解決問題。相信你也可以想像 -- 使用 JavaScript 打造一個向量圖形編輯器並不是件輕鬆的工作。

我們使用的技術包含：
- Node.js
- [elem](https://github.com/em/elem) (web assets management)
- socket.io (socket.io 的作者也是 Vectr 的投資者與顧問)
- Javascript, JavaScript, JavaScript.

目前團隊成員：
- @em 
- @yurenju
- @EragonJ 
- @hychen
- @nickbuddendotcom
# 薪資

年薪約 1,250,000-1,600,000NT
# 聯絡方式

Please contact Nick by email in English. 如果你有任何問題也可以聯絡 Yuren (中文可！)
- Nick Budden: nick@vectr.com
- Yuren Ju: yurenju@gmail.com
# Company:

We believe everyone can be a designer. We’re building a 2D vector graphics editor in JavaScript, with a built in design assets marketplace and design team collaboration tools. https://www.youtube.com/watch?v=CnSRzM91FYY
# Company Culture

We work remotely, and extremely independently. You’ll spend your days drinking coffee  in your favourite coffee shop, using Slack to communicate with the rest of the team. The app’s very modular, and one person typically takes ownership of the module they’re working on from start to finish.
# Tech Stack:

We’ve built almost everything from scratch, so we’re looking for the type of person that gets excited by hard problems. As you can imagine building a vector graphics editor in JavaScript can be tough.
- Node
- elem (web asset mangement)
- socket.io
- JavaScript, JavaScript, JavaScript

The socket.io creator is also an investor in/advisor to Vectr.
# Current Team:
- @em 
- @yurenju
- @EragonJ 
- @hychen
- @nickbuddendotcom
# Salary:

1,250,000-1,600,000NT

**Comment by appleboy** [comment]
:+1:

**Comment by ShinyChang** [comment]
:+1:

**Comment by dca** [comment]
:+1:

**Comment by aminzai** [comment]
:+1:

**Comment by suensummit** [comment]
:+1:

**Comment by mjj2000** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by softcup** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by softcup** [comment]
:+1:

**Comment by floydsoft** [comment]
:+1:

**Comment by amidofu** [comment]
:thumbsup:

**Comment by EragonJ** [comment]
:+1:

**Comment by bcbcarl** [comment]
:+1:

**Comment by Neson** [comment]
:+1:

**Comment by touhonoob** [comment]
:+1:

**Comment by zorro0555** [comment]
好酷歐歐歐歐歐
超心動

**Comment by yurenju** [comment]
有興趣的可以在 Facebook Messenager 問我問更多資訊喔喔喔喔喔！

**Comment by Rplus** [comment]
喔喔喔喔
這個 issue 好多大拇指 XDDD

**Comment by yurenju** [comment]
仔細看裡面還有 team member 偷推 XDDD

**Comment by kvzhuang** [comment]
:+1:

**Comment by roadmanfong** [comment]
:+1:

**Comment by winwu** [comment]
:+1:

**Comment by killtw** [comment]
:+1:

**Comment by c9s** [comment]
ahah 居然在這邊看到 @EragonJ  XDDDDDDD

**Comment by yurenju** [comment]
@c9s 哈哈是啊沒想到吧， @EragonJ  你看看你～～～ 另外也歡迎各位參加這週日晚上的 [**Very** High Performance JavaScript with Mathias Buus](http://www.meetup.com/javascript-enthusiasts/events/223911537/) 可以當面跟我們聊聊我們正在做的東西！

**Comment by yurenju** [comment]
謝謝大家的幫忙，我們已經招募到新的員工了，先關閉這個 issue，如果之後 reopen 再通知大家！

**Comment by Rplus** [comment]
Good job!   
( 雙關耶~ XD )

**Comment by yurenju** [comment]
各位，我又把這條 issue reopen 啦，歡迎有興趣的來 apply，可以參考一下我們的徵才網頁 https://vectr.com/jobs

**Comment by yutin1987** [comment]
:+1:

**Comment by raymondyeh** [comment]
看到team member 先跪了

**Comment by jsleetw** [comment]
±1

**Comment by dreamline2** [comment]
:+1:

**Comment by sharils** [comment]
@yurenju Is this still open?

**Comment by nickbuddendotcom** [comment]
@sharils nope, it's not.
