### ISSUE TITLE
【徵才】未來數據股份有限公司 - 網頁設計前端工程師

### ISSUE THREAD

**Issue by hap0328** [f2etw/jobs#451]
## 團隊簡介
未來數據股份有限公司為國際人工智慧新創AISA Innotech Inc. 之台灣子公司
負責技術研發及東南亞相關業務運營，公司具備高成長性及前景，並給予員工
完善的獎勵、加薪及升遷制度。

## 主要開發項目
人工智慧演算法開發
企業合作AI專案開發
遊戲化人工智慧應用APP開發

## 工作地點
台北市信義區市政府捷運站1號出口附近

## 工作內容
協助企劃人員設計版形
將設計畫面切版供程式人員套版

## 能力需求
熟悉 HTML5、CSS3、SASS 網頁語法技術
熟悉 CSS Grid System 
可獨力完成HTML.CSS.與DIV切版
有 RWD WEB 或 MOBILE WEB 經驗 
能獨立作業並與企劃、程式設計等相關人員配合，協同執行專案

### 加分
略懂jQuery 前端程式語法 

## 薪資範圍
月薪 35,000元~50,000元

## 工時/特休
周休二日，上班時間AM 09：00～PM 06：00，含午休一小時到班九小時。
新入職即享有3天特休，滿半年未滿兩年則為7天，其餘比照勞基法。

## 福利/推薦項
到職即可享特休、完善加薪、升遷及獎勵制度。

## 聯絡方式
aisa.startup@gmail.com

**Comment by Rplus** [comment]
收履歷的信箱是 gmail 而不是公司信箱哩？
O w O
