### ISSUE TITLE
【徵才】RapaQ 羅百酷國際 - 前端工程師

### ISSUE THREAD

**Issue by cutedogspark** [f2etw/jobs#456]
## 團隊簡介

RapaQ 是一個創新的電子商務平台
首度在線上跨領域整合：好物、設群、創創三大平台功能
藉由平台串連，打造服務系統鏈，
提供給重視生活質感的消費者、設計師、創客、智能工廠 具有特⾊商品銷售/推廣平台建立產品⽣態圈
RapaQ提供設計師簡易上架及變現功能，賦予個⼈設計師創造⾃有粉絲的空間
「讓創意變成⽣意」是我們的共同目標，希望對此有興趣的夥伴我們歡迎您的加入 !

## 地點

台北市南港區三重路19之11號4樓

## 工作內容

RapaQ 電子商務平台 網站開發 與 維護  
時常與帥氣的後端工程師搭配合作
時常與美麗的UX搭配合作

## 能力需求
熟悉JavaScript、HTML及 CSS的程式設計與開發經驗
具備 React / Redux  開發技術經驗 與 後端 API 串接經驗
具網頁切版與版面組件規劃 具有備響應式設計 (RWD )實作經驗 亦能善用 jQuery 套件
良好的溝通能力，善於獨立完成工作，同時具備良好的團隊協作能力。 

### 加分

對於畫面的呈現方式有獨到的看法致力於 使用者體驗為需求

## 薪資範圍

NT$40K~60K / 月 (依照您的工作經驗及上述條件狀況決定)

## 工時及休假

- 工作時間彈性 ```09:00 am ~ 18:00pm  or   09:30 am ~ 18:30pm```
- 休假/特休依勞基法規定

## 環境及休閒
- 提供免費咖啡飲料及點心
- 提供 Mac 筆電 及 雙螢幕 進行開發

## 備註

務必請您重視團隊合作，能為了共同目標一起成長前進
不吝提出自己的想法與見解，提出更好的解決問題的方式
擁有自我學習的習慣，樂於分享技術資訊或生活趣事

## 聯絡方式

有興趣的夥伴請將您的履歷請寄至 garychen@rapaq.com

**Comment by Rplus** [comment]
工時的 markdown 格式需要修正一下唷
不然會變刪除號
