### ISSUE TITLE
[徵才]美商Synergies誠徵前端工程師

### ISSUE THREAD

**Issue by Olivia1015a** [f2etw/jobs#462]
## 公司介紹
美商訊能集思智能科技 Synergies Intelligent Systems, Inc.
致力於開發人工智能商業決策平台，透過洞察數據、預測行為與流程自動化，協助企業解決日常運營、產銷供應鏈、產品生產製造流程等問題，並透過數據賦能來實現智慧化管理。
網站:http://www.synergies.com.tw/

公司穩健成長中，業務量猛爆性增長，希望是較有經驗的前端工程師，能夠彼此切磋討論
## 工作地點
台北市中正區北平東路20號10樓
- 鄰近善導寺捷運站，只需5分鐘路程
- 附近有華山大草原､華山文創園區､全聯福利中心､手搖飲料店，生活機能齊全，寬敞的景觀露台，室內整齊乾淨，備有零食飲料、微波爐、咖啡機飲水機，特殊節慶活動可開伙，接受寵物｡

## 工作內容
- 專注於前端領域，負責網站及網路應用程式之開發、維護
- 與設計師、後端工程師及資料科學家合作，共同完成核心產品及專案
- 產品架構之設計，優化前端工具鏈 (for senior)
- 改進協作流程，創建技術標準與規範 (for senior)

## 能力需求
- 熟悉 JavaScript、CSS、HTML 
- 熟悉 AJAX、JSON、Restful API 及 DevTools 
- 前端 framework / library 的使用或開發經驗
- 熟悉版本控制工具Git 操作，了解多人協作開發流程
### 擁有以下條件更加分
- 熟悉 ES6+語法
- 擁有 CSS Pre / Pos-processors 開發經驗，如 SASS、PostCSS 等
- 擁有 JavaScript framework / library 的開發經驗，如 Vue、 Vuex、d3、echart 等
- 前端架構及模組分析設計經驗 (for senior)
- webpack / gulp 的深入使用經驗 (for senior)
- 擁有 TDD/BDD開發概念與實務經驗 (for senior)
- 具備後端知識與網站效能調校經驗 (for senior)
## 薪資範圍
月薪 NTD$ 40K - 80K + 年終，視經驗與能力而定
## 工時/特休
- 週休二日，國定假日、颱風假等，該放的假都一定會放到
- 表定上班時間為09:00~18:00，午休時間1小時
- 優於勞基法的休假制度，到職滿一年享10天特休假，每人每年10天全薪病假

## 福利/推薦項
- 好像會不定期舉辦workshop、慶生會及公司聚餐
- 美式風格管理，零食飲料齊全，超紓壓的日曬雨淋景觀大陽台
## 聯絡方式
相關履歷與作品寄至 olivia.yang@sis.ai

來信前請先確認一下您的基本條件是否符合以下幾點：
- 對AI、大數據、物聯網有興趣 (你應徵的是AI公司)
- 完整瀏覽過Synergies的網站至少一次
- 擁有自主規劃工作的能力，願意學習新技術並樂於分享

**Comment by aiko3310** [comment]
不好意思，信箱好像寄不進去
