### ISSUE TITLE
[徵才] Positive Grid - Staff/ Senior Front-end Engineer

### ISSUE THREAD

**Issue by AllieChen412** [f2etw/jobs#467]
## 團隊簡介/地點
想要再被程式碼包圍的工作氛圍下一起打造世界一流的高品質音樂產品嗎？
我們正在積極招募志同道合的你加入我們在台灣的技術團隊，
用你的能力，做出令人驚艷的產品
用你的創意，重新定義世界創作音樂的方式
和我們一起站上世界的舞台
驕傲地向全世界說：這是我做的產品！

辦公室據點：臺北市大同區 digiBlock 數位產業園區

## 你會在Positive Grid 做些什麼
- Webview 為介面的跨平台桌機軟體，以 Mac 與 Windows 為主
- 以前端技術實現音樂產品所需的複雜互動和動態效果
- 目前的前端 Tech Stack 如下。只要對團隊有好處，也歡迎導入新技術
- ES6+
- React / AngularJS
- Styled Components / SASS / Stylus
- Webpack / Gulp / Babel
- Jest

## 你會跟這樣的團隊一起工作
- 以 Scrum 執行專案，但不拘泥於形式，持續改進開發流程以找到最適合團隊的方法
- 熟悉 Git 操作，了解多人並行開發的流程
- 主動發掘工作上的問題，並提出解決問題的方法
- 良好的溝通合作能力
- 關注前端發展趨勢，樂於分享討論
- 每月一次的 Workshop 分享新知
- 舉辦讀書會一起來讀想看但看不完的書

## 我們需要這樣的你
- 至少一年以上前端開發相關經驗
- 精通 JavaScript、CSS、HTML 及瀏覽器渲染原理
- 熟悉 Angular、React 或 Vue 至少一項前端框架 
- 熟悉自動化單元測試、整合測試和 End-to-End 測試方法及相關工具
- 有能力設計效能與擴充性兼顧的 Component 結構和狀態管理系統
- 有能力將需求拆分成可使團隊成員順暢分工協作的任務
- 不只在乎使用者體驗，也重視開發者體驗。在滿足產品需求的同時兼顧專案的健康
- 不畏懼 Legacy Code，可以安全地重構專案，改善專案品質

### 加分但不是必須
- 精通 Canvas、SVG 或 WebGL 等前端技術 
- 開發過 WebView-based 的桌面程式
- C++ 開發經驗
- 有在彈電吉他

## 薪資範圍
840,000-1.7M

## 工時/特休
- 週一至週五，09:00-18:00 (彈性工作時間)
- on board第一天就有特休，每多一年加兩天

## 福利/推薦項目
自由靈魂的標準配備： 
- 蘋果咬一口-用了MacBook Pro，你就是Pro! 
- 咦？零食盒怎麼會自己裝滿？-上升的體重 上升的工作靈感 
- 誰喝咖啡這麼香？-無限供應的咖啡豆，我的一天，從喝了咖啡才開始 
- 零食配汽水才是王道？-冰箱的汽水啤酒給你最經典的搭配 
和Positive Grid一起對自己好一點： 
- 進公司第1天就有特休，每多一年加2天，絕對不會低於法令規定， 
還有給薪家庭照顧假&病假讓你運用 
- 留得青山在不怕沒柴燒-不定期提供健康檢查的服務．Positive Grid關心你． 
- 光找停車位就一肚子火了？-別怕！！我們有停車費補助讓你消消氣 
看不見但很重要的： 
- 溫馨的team building，開心吃喝，互相學習與成長 
- 上班氣氛很歡樂，吵鬧的辦公室也可能是你靈感的來源 
- 跟一群優秀的人一起工作是最棒的福利！其他還有更多，等你來體驗！

## 面試流程 (會在1-2週內結束)
1. 第一階段面試(線上) : 針對基本技術、工作規劃進行面談
2. 第二階段Manager & HR面試(到公司) : 聊聊工作期待&薪資期望
3. 第三階段CEO(線上) : 工作規劃、Culture Fit

## 聯絡方式
Allie Chen
allie.chen@positivegrid.com

**Comment by AllieChen412** [comment]
> 我是住在香港的developer，請問合適嗎？

嗨唷～感謝提問！
PG現在不主打remote工作囉！
主打一起到公司工作更開心！
但還是保有彈性空間:)

給你參考~

**Comment by milkmidi** [comment]
請問團隊是以 AngularJS 還是 React 為主呢?

**Comment by LiuTzuLing** [comment]
Hi,
我們都有使用喔。

請問您方便提供您的履歷表嗎以及email嗎？之後我們覺得有興趣會跟您約視訊通話的時間，謝謝您

Merry Christmas

Best,
Celine
[image: Valoso Inc.]
Celine Liu  Digital Marketing Specialist

Valoso Inc.
m: +8869 <+886937018294>*12005761*
w: valoso.com
e: celinel@valoso.com
Follow us:
[image: facebook] <https://www.facebook.com/valosovideos> [image: twitter]
<https://twitter.com/ValosoMedia> [image: linkedin]
<https://www.linkedin.com/company/6464584/>


ᐧ

**Comment by AllieChen412** [comment]
我們團隊 AngularJS React 都有使用唷！歡迎參考:)

**Comment by AllieChen412** [comment]
樓上是要搭版徵才？

**Comment by diabloevagto** [comment]
怎樣叫做保有彈性空間？

**Comment by AllieChen412** [comment]
應該是說我們已經不主打 remote 工作型態，但是有事情要先離開辦公室 (ex: 接小孩、避開塞車時段、短暫國外工作...) 都可以，也不會強迫你在辦公室待滿8小時
總之，有需求都可以提出來討論:)
