### ISSUE TITLE
[Frontend Developer] Nexusguard 禦騰科技有限公司

### ISSUE THREAD

**Issue by SteveTsai** [f2etw/jobs#47]
禦騰科技有限公司
求才內容說明
職務名稱：	Frontend Developer
需求人數：	1人
職務類別：	Internet程式設計師、軟體設計工程師
職務說明：	

1. Development of customer-facing web portals to include data from a variety of mediums displayed in a cohesive fashion.
2. Development of internal dashboards to show the current status of the operations and infrastructure to achieve business goals.
3. Research and develop innovative methods of presenting information in efficient, yet meaningful manners.
4. Work with operations teams to enhance and streamline workflows for portal and dashboard navigation.

Requirements :
CSS3, HTML5, RWD
Javascript, D3, ReactJS, AngularJS
Linux / Nginx
Node.js(io.js)
Gulp / Grunt / Browserify / Webpack
SPA(Single Page Application)

Plus :
Github Account
UI / UX
Unit-Test
Docker / CI(Continuous Integration) / Network Protocols
Open Source Contributor
More than 5 years’ experience in web development.

Salary:
50K~100K+   13 個月 + 績效獎金 (合適者不在此限)

公司簡介
成立於二○○八年，Nexusguard為對抗惡意網路攻擊的全球領導性廠商。保護客戶免受分散式阻斷服務(DDoS)攻擊及多種網路威脅，確保網路服務不受干擾。Nexusguard 致力為世界各地不同產業及規模的客戶提供全方位、高度客製化的網路安全解決方案，並且為網路服務供應商提供全面性DDoS防禦專案及支援服務。總部設立於舊金山，Nexusguard 之安全專家網絡正快速地拓展全球。了解更多請造訪網站 www.nexusguard.com

福利制度
公司採人性及自主化管理, 我們視所有同仁為公司最重要的資產，重視員工的需求與發展。
1.具競爭力的整體薪酬制度
a.依個人能力及工作職掌提供具競爭力的薪資
b.每年依據個人績效及公司整體營運狀況發放具激勵性紅利和績效獎金/調薪/升遷
c.保障年薪13個月
d.三節獎金(端午、中秋、春節)。 
2.福利制度
a.具健全之勞保、健保、勞退金制度，並提供員工免費之團體保險(含壽險、意外險、醫療險)、海外旅遊保險、癌症保險、職業災害保險等保障。 
b.完善的員工教育訓練及在職進修補助
c.絕佳之辦公環境
d.生育、傷病、住院、急難救助、婚喪禮金補助。 
e.定期提供同仁免費健康檢查。 
f.介紹獎金制度
g.休假制度
-周休二日(輪班人員之休假依公司制度)
-優於勞基法之年假休假制度 - 第一年即享有16天年假 (年假天數將按照到職日當天依比例計算)
-陪產假
-不扣薪病假(14天)
-女性同仁生理假
h.休閒活動
-公司聚餐
-公司郊遊
-Christmas Party
-年度尾牙

還有 Backend 及 Full Stack 程式職缺，請參考 104.

管理責任：	無
上班地點：	台北市內湖區瑞光路413號8樓
出差外派：	無需出差
職務聯絡人：  Steve Tsai
email : steve.tsai@nexusguard.com

**Comment by ArvinH** [comment]
請問已經徵到人了嗎？

**Comment by SteveTsai** [comment]
Yes, thanks
Steve

On Thu, Oct 15, 2015 at 9:43 PM, ArvinH <notifications@github.com> wrote:

> 請問已經徵到人了嗎？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/f2etw/jobs/issues/47#issuecomment-148390961>.
>



-- 
*Steve Tsai*

P : [886] 2 2658 8278
F  : [886] 2 2658 6978
Skype: steve.nxs

*NEXUSGUARD*
www.nexusguard.com
LinkedIn <https://www.linkedin.com/company/nexusguard> • Twitter
<https://www.twitter.com/nexusguard> • Facebook
<https://www.facebook.com/nxg.pr>

Disclaimer: This e-mail message contains information intended solely for
the intended recipient and is confidential or private in nature. If you are
not the intended recipient, you must not read, disseminate, distribute,
copy or otherwise use this message or any file attached to this message.
Any such unauthorized use is prohibited and may be unlawful. If you have
received this message in error, please notify the sender immediately by
email, facsimile or telephone and then delete the original message from
your machine.

San Francisco  |  San Jose  |  Los Angeles  |  Miami  |  London  |  Hong
Kong  |  Beijing  |  Taipei  |  Manila

**Comment by Rplus** [comment]
@SteveTsai 
那還有徵才的需求嗎?
如果沒有的話，就把它關掉吧～

**Comment by SteveTsai** [comment]
Hi:

I have problem login the account. could you close it from me, Please?

thank you.
Steve

On Fri, Oct 16, 2015 at 10:49 AM, Rplus <notifications@github.com> wrote:

> @SteveTsai <https://github.com/SteveTsai>
> 那還有徵才的需求嗎?
> 如果沒有的話，就把它關掉吧～
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/f2etw/jobs/issues/47#issuecomment-148583392>.
>



-- 
*Steve Tsai*

P : [886] 2 2658 8278
F  : [886] 2 2658 6978
Skype: steve.nxs

*NEXUSGUARD*
www.nexusguard.com
LinkedIn <https://www.linkedin.com/company/nexusguard> • Twitter
<https://www.twitter.com/nexusguard> • Facebook
<https://www.facebook.com/nxg.pr>

Disclaimer: This e-mail message contains information intended solely for
the intended recipient and is confidential or private in nature. If you are
not the intended recipient, you must not read, disseminate, distribute,
copy or otherwise use this message or any file attached to this message.
Any such unauthorized use is prohibited and may be unlawful. If you have
received this message in error, please notify the sender immediately by
email, facsimile or telephone and then delete the original message from
your machine.

San Francisco  |  San Jose  |  Los Angeles  |  Miami  |  London  |  Hong
Kong  |  Beijing  |  Taipei  |  Manila

**Comment by SteveTsai** [comment]
Thank you very much.
Steve

On Fri, Oct 16, 2015 at 11:48 AM, Chen-Heng Chang <notifications@github.com>
wrote:

> Closed #47 <https://github.com/f2etw/jobs/issues/47>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/f2etw/jobs/issues/47#event-437126690>.
>



-- 
*Steve Tsai*

P : [886] 2 2658 8278
F  : [886] 2 2658 6978
Skype: steve.nxs

*NEXUSGUARD*
www.nexusguard.com
LinkedIn <https://www.linkedin.com/company/nexusguard> • Twitter
<https://www.twitter.com/nexusguard> • Facebook
<https://www.facebook.com/nxg.pr>

Disclaimer: This e-mail message contains information intended solely for
the intended recipient and is confidential or private in nature. If you are
not the intended recipient, you must not read, disseminate, distribute,
copy or otherwise use this message or any file attached to this message.
Any such unauthorized use is prohibited and may be unlawful. If you have
received this message in error, please notify the sender immediately by
email, facsimile or telephone and then delete the original message from
your machine.

San Francisco  |  San Jose  |  Los Angeles  |  Miami  |  London  |  Hong
Kong  |  Beijing  |  Taipei  |  Manila
