### ISSUE TITLE
中央研究院生物多樣性研究中心 TaiBIF 誠徴前端工程師一名

### ISSUE THREAD

**Issue by taibifbrcas** [f2etw/jobs#474]
# 中央研究院生物多樣性研究中心 TaiBIF 誠徴前端工程師一名

(108 年 1 月 28 日更新)

前端工程師可以有不一樣的職涯發展！您在乎自然生態保育嗎？您知道您的開發專業對臺灣生態的研究與保育可以有很大的影響力嗎？

## 工作內容
1. 參與使用者需求分析，根據分析結果及設計建議，評估實作可行性，並規劃前端的實作架構及開發排程。
2. 接手設計端提供的切版及動態，介接資料及完成互動功能開發。
3. 協調外部工程師執行開發工作，推動專案進程。
4. 協助網站使用情形的資料分析(Google Analytics)，並據以規畫功能修正。

### 職缺說明
我們希望能找到在業界有前端 UI/UX 設計、開發經驗及熟悉開源方法的工程師，能根據設計主導資訊服務前端的實作架構，並能在開發過程協同外部人力一起開發，同時與後端工程師保持密切互動，釐清功能實作時的分工。這是一個相對穩定且能兼顧職涯發展的工作機會。

## 應徵資格
1. 非資訊相關科系畢業可，曾參與資訊服務網站前端的開發工作。
2. 熟悉 Vue.js 或 ReactJS 等前端框架，及與後端 API 串接。
3. 熟悉 Nodejs 生態系工具。對 ES6 有良好的掌握。
4. 熟悉 git 操作。
5. 不畏懼英文溝通與書寫（工作中有大量國外同儕的開發資訊），想提昇自己的英文能力。
6. 細心、能有效率地獨立作業；能與團隊其它角色溝通合作。

**加分關鍵字**：Python, R, D3.js, Data visualisation, Dashboard design, Open Streep Map, Leaflet, MapBox, CartoDB, Coding convention, CI/CD, test coverage.

因為是前端開發，我們希望您有一雙對視覺細節及色彩平衡十分敏感的眼睛，能忠實呈現設計，甚或加強設計。由於此領域技術推進快速，我們也期待您積極求知，主動提出想法、擔負責任，在瞭解生物多樣性資訊的同時，也能持續參與技術社群的活動，汲取業界新知，保持自己的競爭力。

## 待遇
**薪資**：試用期間（三個月）新台幣 68,712, 過後則為 71,411，隨考績調整。對於提供的工作範圍及內容有想法，可進一步面議。
**加班費**：每週工作40小時，加班費按月支單一薪酬除以240為每小時支給標準。
**工作支持**：工作期間提供一台 MacBook Pro 便利開發工作進行。
**職涯發展**：支援參加與工作相關或能力養成之國內外訓練及研討會（每年至少一次國外行程與同儕交流）。
**休假**：週休二日，依國定假日休假。
**福利**：年終獎金 1.5 個月。院內健檢補助及設施優惠，及週邊電影娛樂優惠。
**特休**：按勞基法規定。

工作時間：彈性上下班，表訂每日 09:00 至 18:00，午休一小時。按需求可遠端工作。
工作地點：中央研究院生物多樣性研究中心 跨領域大樓
到職時間：農歷年後、3 月 1 日或依個案處理。
職缺有效時間：有合適的人選即截止。

## 聯絡方式
[柯智仁先生](https://www.linkedin.com/in/chihjen-ko-2096441/) 
聯絡地址：[cjk@sinica.edu.tw](mailto:cjk@sinica.edu.tw)，主旨請註明「TaiBIF 前端工程師」確保收件，我們將儘速回覆。
聯絡電話：(02)27872220 ext.24 

### 應備文件：
1. 個人在 github 的作品集，有開源合作專案或實際 production 的案例（請提供 URL）尤佳。
1. 建議可指出目前 [camera-trap-webapp](https://github.com/TaiBIF/camera-trap-webapp) 可見問題並提出改善建議。
1. 兩位推薦人的電子郵址或電話，一位過去的同事，一位主管。請事先徵詢推薦人。我們將視情況連繫。

註：對臺灣業界徵才佈告的規則尚不熟悉，若內容有任何不合理的地方，請不吝指教，謝謝！

## 團隊簡介
[TaiBIF](http://taibif.tw) 為全球生物多樣性資訊機構（GBIF）的臺灣節點，目前設立於中央研究院生物多樣性研究中心。我們積極配合 GBIF 的[工作計畫](https://assets.ctfassets.net/uo17ejk9rkwj/3Ua4cMwNawso46kMGisICM/fcc5c802058a44ca64922d53c15f147d/GBIF-2019-Annual-Work-Programme-APPROVED.pdf)推動臺灣生物多樣性數據資源的公開分享及研究單位資訊管理流程的研發及建設。生物多樣性資訊學為跨生物學及資訊學的新興領域，有許多令人興奮的專案正在進行，也有許多與國際同儕協同開發的機會。此職缺包含與全球生物多樣性資料應用領域的交流及海外職缺機會，歡迎您加入探索！

目前團隊內部的主要技術堆疊為 Vue.js, Node.js, LoopBack/Express, MongoDB，另有 PHP, Drupal + MySQL 及 .NET VB + MSSQL 的歷史專案等待更新。

**Comment by Rplus** [comment]
發現你們開了很多個徵才 issue 耶
好奇都是仍在應徵中的不同職缺嗎？
https://github.com/f2etw/jobs/issues?utf8=%E2%9C%93&q=is%3Aissue+TaiBIF

**Comment by taibifbrcas** [comment]
@Rplus 不好意思 #472 是用錯帳號的結果，所以先 close 掉了。希望沒造成困擾。

**Comment by taibifbrcas** [comment]
更新部分資格文字。有興趣歡迎談談。

**Comment by taibifbrcas** [comment]
更新說明內容，請大家告訴大家！
也可以參考我們另一個[後端職缺](https://github.com/nodejs-tw/jobs/issues/139)喔。
