### ISSUE TITLE
【徵才】iStaging 前端工程師 (Front-end Engineer)

### ISSUE THREAD

**Issue by jason90929** [f2etw/jobs#479]
工作內容
* Good knowledge of HTML, Javascript(ES5, ES6) and CSS 
* Know how to structure containers, components, flows by using Vue.js / React.js. Cross browser support experience or RWD design is big plus. 
* Experienced in Aframe, Web AR/VR application 
* Detailed understanding of front end performance best practices: build processes, code organization, lazy loading 
* Understanding of Functional Programming paradigms 
* Effectively and efficiently communicates both written and verbal issues to peers, partners and management 

Other Requirements: 
‧ MUST HAVE SAMPLES or GITHUB (banner placed on website, sample code, current school projects, freelance) to show 

- Responsible to develop and maintain the new front-end system for the SaaS platform using the latest front-end technology 
- Work with Backend Engineers to build features and ship experiments. 
- Build efficient and reusable front-end systems and abstractions. 
- Collaborate with colleagues including product managers, designers and other engineers assigned to your project(s). 

iStaging frontend product：https://livetour.istaging.com/a4fa9a67-5f65-4b10-8169-dd9ea269b9c1/yung-ching

工作待遇：
月薪 55,000~80,000元 (*14)

上班地點：
台北市松山區南京東路4段2號2樓（小巨蛋南區入口處） 

語文條件：
英文 -- 聽 / 中等、說 / 中等、讀 / 中等、寫 / 中等

公司福利
正職員工享有以下福利： 
【薪獎假勤類】 
. 具市場競爭力的薪資 
. 年特休假10-30天 
. 三種彈性上班工時選擇 
. 享額外健康及全勤津貼每月$4,000元 
. Employee Stock Option(員工認股權) 
. 分紅獎金 
. 業務業績獎金 

【娛樂類】 
. 供應健康美食：新鮮水果、湛盧咖啡、有機豆漿、鮮奶、麥片等；也供應療癒系美食：好吃零食、每周手搖飲料 
. 好躺好睡的午覺柔軟沙發 
. 不定時員工聚餐 
. 年度團體活動 (Team Building, 旅遊等) 

【其他】 
. 到職滿三個月提供團體保險 
. 優質辦公環境（咖啡機、電冰箱、微波爐、午睡沙發、按摩椅、健身器材 等） 

iStaging提供國際舞台，與不同國籍同事溝通的工作環境 
擁有積極挑戰的企業文化 
定期也會有產業知識分享會 

辦公環境寛敝，開放式的工作環境，採光充足，交通便利 
鄰近松山運動中心，午休或下班後運動都很方便喔 
快來加入我們吧!

聯絡方式
HR: rachel@istaging.com
Frontend developer: jason@staging.com.tw

**Comment by Rplus** [comment]
`試用期`???

**Comment by diabloevagto** [comment]
`試用期滿提供團體保險`
這意思是不是第一天就有勞健保？？？

**Comment by jason90929** [comment]
團體保險不是勞健保
