### ISSUE TITLE
[擴大徵才] 舒服美 徵 Front End Developer (Senior / Junior / Intern) 歡迎新鮮人！

### ISSUE THREAD

**Issue by jackypan1989** [f2etw/jobs#493]
## 團隊簡介
https://sov.dental
舒服美數位隱形矯正 (SOV) 是目前台灣本土市占第一的年輕隱形矯正團隊，藉由電腦軟體輔助3D診斷、設計、製造等系統，生產專屬於客戶的隱形矯正牙套，團隊平均年齡為25歲(目前共45人)，歡迎你一起加入。

## 工作內容 (目前均用 React)
1. 公司內部後台系統 (ERP)
2. 診所醫生端牙技平台 (CRM)
3. 官網/牙套分享平台/產品頁面 (SITE)
4. 病患端手機應用程式開發 (APP)

## 能力需求
1. 熟悉 Git 
2. 玩過 ES6
3. 玩過 Vue, Angular, React 其一
4. 對電腦視覺 / 生醫工程 / 3D 建模 有興趣者
5. 對 Functional Programming 有興趣者

## 技術 Stack
1. Nodejs
2. React / NextJS / Electron
3. Typescript
4. Webpack
5. Apollo / Graphql
6. MongoDB / Elasticsearch

## 薪資範圍 (全年保證13個月)
1. Freshman ~ Senior
年薪 65 ~ 104 萬起 (有實力可再往上談)
2. Intern
時薪 200

## 工時 / 特休
彈性上下班 (0930~0630)
其餘依勞基法規定

## 福利 / 推薦項
1. 生日禮金 / 生日假
2. 三節禮金
3. 吃不完的零食
4. 配全新 Macbook + 29吋寬螢幕
5. 健康檢查補助
6. 員工旅遊
7. 尾牙
8. 每月公司福委活動
9. 公司男女比均衡
10. 講座/論壇等公出補助
11. 部門無加班文化 (近一年僅一次上線前加班)
12. 部門讀書會 (Haskell/Purescript)
13. 帶薪參加學校課程 (去年是上台大的 Flolac 暑期學分班)

## 聯絡方式
學經歷請寄 
jacky@sov.dental

官網
https://sov.dental
<img width="1422" alt="2019-03-06 10 33 03" src="https://user-images.githubusercontent.com/1138803/53851954-a216e600-4003-11e9-82e6-a907d9c16044.png">
去年泰國員工旅遊
<img width="749" alt="2019-03-06 10 34 28" src="https://user-images.githubusercontent.com/1138803/53852020-d4c0de80-4003-11e9-9303-59cc5cd7dc76.png">

**Comment by Haruka1120** [comment]
請問還有在徵人嗎？

**Comment by jackypan1989** [comment]
你好，目前暫時滿編
預計六月底會再度徵才
