### ISSUE TITLE
【徵才】Pelith - Frontend Developer

### ISSUE THREAD

**Issue by artistic709** [f2etw/jobs#496]
## 公司簡介

Pelith 沛理科技股份有限公司

Pelith 是一個充滿活力的年輕團隊，成員平均年齡 24 歲，專攻以太坊智慧合約以及區塊鏈相關應用開發。2018 年已經成功開發三個成熟的區塊鏈產品，撰寫與稽核超過十個運作中智慧合約，並與 ACCUPASS 活動通合作新平台 EvenToken，發行了專用的實體卡片。

## 工作職缺
- 前端工程師

## 工作內容：

身為前端工程師，你必須對技術有很高的熱情，能快速學習新技術，並能夠在非常新、變動頻繁（如 web3) 的框架下獨立開發、解決問題。

### 徵求條件

- 基礎
    - HTML5 搭配 Vanilla JS
    - RWD/mobile-first layout
    - CSS/SASS/SCSS
    - JS(ES2015), Promise, async/await
    - CommonJS/ES modules
- 前端框架
    - 至少熟悉 Vue.js, React/Redux, Angular 任一項
    - 熟練使用 Bootstrap 4/Material component web 等樣式為主的框架任一
- 打包工具
    - Browserify/webpack
    - rollup/parcel
- (加分) 區塊鏈相關
    - 在網頁端或伺服器端串接 web3.js (v1.0+) 並與鏈上合約互動
    - 曾經使用過其他替代框架如 ethereumjs / ether.js / parity-JS

## 工作地點

捷運東門站附近

## 工作時間

- 全職
    - 彈性上下班：核心時間 13:00 - 15:00
    - 星期一必須出席
- 學生兼職
    - 每週 20 小時，工作時間另議
    - 星期一必須出席

## 公司福利

- 制度類：週休三日、真．彈性上下班
- 健康保險：勞保、健保、勞工退休金 6％ 提撥
- 請／休假：就職即享一年十日優於勞基法之特休
- 娛樂福利：每月團隊 team building 活動（吃大餐）、零食、飲料無限供應
- 獎金禮品：尾牙抽獎人人有獎
- 健身房補助：沒有，老闆是肥宅

## 薪資範圍 

- NTD 50,000 - 75,000
- 績效獎金、配股

## 需求人數

-  1 人

## 聯絡人/連絡方式

- 陳品
- ping@pelith.com

**Comment by Rplus** [comment]
週休三日耶 好酷 ：P

**Comment by jkfox67** [comment]
請問可否遠端（Remote）上班？

**Comment by artistic709** [comment]
目前沒有規劃 remote 的職缺喔

**Comment by jkfox67** [comment]
> 目前沒有規劃 remote 的職缺喔

😞  謝謝回覆.

**Comment by kunyaoxu** [comment]
請問這個職缺是偏向資淺還是資深呢?

**Comment by artistic709** [comment]
> 請問這個職缺是偏向資淺還是資深呢?

沒有特定的年資限制，不過希望具備獨立作業/解決問題的能力

**Comment by kunyaoxu** [comment]
> > 請問這個職缺是偏向資淺還是資深呢?
> 
> 沒有特定的年資限制，不過希望具備獨立作業/解決問題的能力

了解, 我寄信應徵了 :D
