### ISSUE TITLE
【徵才】Victor Tech 資深產品前端工程師

### ISSUE THREAD

**Issue by vincentkan0701** [f2etw/jobs#498]
## 團隊簡介/地點
台北市_台北車站
## 工作內容
1.參與前端框架的構建和優化； 
2.制定前端開發規範，負責前端的代碼結構設計和實施； 
3.負責公司移動端H5產品的開發反覆運算； 
4.負責公司PC端Web產品的開發反覆運算； 
5.負責公司小程式產品的開發反覆運算； 
6.瞭解iOS（OC/Swift）、Android(Java/Swift)、WEB前端且至少精通其中一項，並能根據需求進行排期； 
7.與UI設計師及產品經理合作，根據切圖、原型圖及產品設計文檔，完成頁面交互效果及控制項製作。 

---------------------------------------------------- 
★薪資依照過去經驗、能力及擅長工具面談；只要您值得，我們絕不吝嗇。 
---------------------------------------------------- 
★我們是新創手遊APP遊戲科技產業，歡迎新夥伴加入 ; 簡單一句話，我們選擇將目光與資源先放置在工作夥伴身上，我們相信唯有讓夥伴過得更好，我們公司才會擁有更優質的團隊，一起共創更豐富的職涯！
## 能力需求
5年以上Web前端開發經驗； 
2. 扎實的前端基礎，包括但不限於HTML/CSS/JavaScript等相關知識，熟悉http，並有自己的瞭解； 
3. 熟悉前端性能優化，熟練使用各種調試工具； 
4. 有Vue.js/React/AngularJS等前端MV*框架實踐經驗，並瞭解其中原理； 
5. 有webpack/Gulp/Grunt等前端工具使用經驗； 
6. 有複雜使用者介面與交互應用開發經驗，注重介面細節； 
7. 有Git使用經驗，理解Git workflow； 
8. 有良好的代碼風格和程式設計習慣； 
9. 有良好的學習、溝通及解決問題能力； 
10. 對使用者體驗、交交互操作流程、及使用者需求有一定瞭解； 
11. 積極樂觀，責任心強，工作認真細緻，具備良好的服務意識，具有良好的團隊溝通與協作能力，並富有工作激情、創造力和責任感，能承受高強度的工作壓力，必要時候接受公司的加班安排； 
12. 相關互聯網產品經驗優先，有參與開源和個人作品優先。 

## 福利/推薦項
五節獎金 
婚喪補助 
生育禮金 
餐費津貼 
全勤獎金 
開工禮金 
聚餐費 
推薦獎金 
不扣薪病假 

◆完善的保險福利 
1.勞保 
2.健保 
3.退休金提撥 

◆優美的上班環境 
1.無限零食飲料咖啡區 
2.交通便利 
3.週五下午茶 
4.每月慶生會 
5.優質的工作環境
## 聯絡方式
Email: vincentkan.work@gmail.com 來信請付上履歷及聯絡方電話，謝謝。

**Comment by sharils** [comment]
請問是博弈產業或產品供博弈產業使用嗎？

**Comment by vincentkan0701** [comment]
> 請問是博弈產業或產品供博弈產業使用嗎？
此職缺是協助產品開發，服務產業是博奕沒錯。

**Comment by sharils** [comment]
Thanks @vincentkan0701
