### ISSUE TITLE
[徵才] 加拿大新創 Sinitic.ai 誠徵 Senior Frontend Developer 90k-140k (VueJS, 可遠距) 

### ISSUE THREAD

**Issue by iamalbert** [f2etw/jobs#502]
## 團隊簡介/地點

Sinitic is a Canadian startup that helps businesses automate multilingual customer support with our conversational AI technology.

We're recruiting a Front-End Developer with an eye for good UX to work on a key component of the Sinitic Plaform: our Visual Bot Designer.

Our frontend is a Vue2 SPA which communicates with the backend through REST services and Websocket. One of our key advantages is that non-technical users can easily configure their bots by assembling a few blocks using our Visual Bot Designer.

You can work either remotely or in our Taipei office.

## 工作內容

You will be responsible for maintaining the Visual Bot Designer, our Webchat component, as well as the rest of the Sinitic Platform, troubleshooting performance problems, maintaining good compatibility across evergreen browsers and improving the UX.

## 能力需求

Ideally, you can offer these skill sets:

   -  Able to organise its own schedule based on management's priorities.
   -  3+ years experience as a javascript developer.
   -  2+ years experience in role with a big UX/Design component.
   -  Sound knowledge of Webpack and Vue2.
   - Able to troubleshoot performance problems and memory leaks using Chrome/Firefox's developer tools.
   - Effective communication with all levels of our company.
   - Able to communicate in verbal and written in English

### 加分

   - Excellent knowledge of SVG. Experience in D3 is a plus.
   - Excellent knowledge of ES6 or more recent, knowledge of TypeScript is a plus.

## 薪資範圍

NTD 90,000 - 140,000 / month 

## 工時/特休

- 20 vacation days
- Flexible working hours

## 福利/推薦項

- Relocation to Canada after 1 year.
- Sick and compassionate leave
- Gym membership & team activities
- Multicultural work environment

## 聯絡方式

Please send your CV/resume to albert@sinitic.ai
Or apply online: https://secure.collage.co/jobs/sinitic/10482

**Comment by Rplus** [comment]
Is this same with #577 ?
