### ISSUE TITLE
[徵才] SurveyCake - Front-End Developer 前端工程師

### ISSUE THREAD

**Issue by wubaibai** [f2etw/jobs#503]
> SurveyCake 同時提供 SaaS 與企業版，於 SaaS 主要進行功能開發，企業版部分打造客製化模組，在這裡你可以體驗到更多單純前端開發以外的經驗，適合對於多專案同時進行有興趣的你來加入。

## 團隊簡介/地點
我們是 25sprout ，一間年輕正發新芽的公司，
SurveyCake 是由我們打造的行動雲端問卷平台，
協助用戶輕鬆打造線上問卷並即時追蹤統計回覆資料，
我們也藉此得到服務眾多大型知名企業的機會！
   
我們熱愛且相信自己所做的工作，
也期望能將這樣的熱情分享給我們的身邊的每一個人。
   
地址：105 台北市松山區南京東路五段1號12樓

## 工作內容

- 負責專案前端開發，與後端串接 API
- 協助專案除錯與修正

## 能力需求

- 充滿創意、主動積極，有捲起袖子什麼都願意試試看的熱情
- 熟悉使用 JavaScript, CSS3, HTML5 開發網站和網路應用程式
- 有 React 相關開發經驗
- 有 Redux 或 Flux 或 Mobx 相關開發經驗
- 使用 CI/CD 優化部署流程經驗
- 喜歡學習最新前端技術 Pug, PostCSS, ES6, ES7, css-in-js
- 解決跨瀏覽器相容性問題經驗(IE11)

### 加分

- 使用 Webpack 優化開發環境經驗
- 有 Vue 相關開發經驗
- 有 RxJS 相關開發經驗
- 有 Flow 或 Typescript 相關開發經驗
- 有 rollup, gulp 相關經驗
- 有使用 Jest, nightwatch, cypress, puppeteer 相關測試經驗

## 薪資範圍
NT$ 500,000 - 750,000 (年薪)

## 工時/特休

- 彈性工作時間，每日工作八小時
- 12 天年假，每滿 1 年加 1 天，未滿一年依比例計算
- 10 天 Remote Work Day，可自由選擇工作時間和地點，巴黎跨年京都賞櫻不是夢

## 福利/推薦項

- 免費美味員工午餐，零食咖啡永遠充足
- 一年兩次海內外員工旅遊
- 電影之夜，每季一次，可攜伴參加
- Workshop，每月一次，課程內容開放大家提議
- 社團活動與不定期 Team Building 活動
- 運動 / 健身補助
- 全身健康檢查補助
- Keep Learning Project，鼓勵自主學習，包含購買書籍、課程等皆可申請補助
- 尾牙不用表演，專心享用美食即可
- 充分享受在 Spotify 音樂與垃圾話穿插夾雜的團隊合作樂趣
- 接觸各領域的領導品牌客戶，參與超過上萬人使用的產品專案

## 工作環境
- 一流的網路新創公司工作環境 
- 每人配備獨立大桌面 與 23" DELL 螢幕 
- 正職員工提供 Mac 公司機 
- 面對臺北 101 整排落地玻璃 
- 餐桌與吧檯。 
   餐桌是暢快聊天的午餐午茶區域，落地窗吧檯是伸展筋骨的站立工作空間 
- 沙發休閒區、42" LG 電視搭配 MOD 
- 獨立會議室和投影設備、兩大面白板牆 

## 聯絡方式
如果你對我們的工作有興趣，請將你的履歷 / 作品集 / 網站 一併提供：
https://www.surveycake.com/s/w4Nzq

**Comment by kunyaoxu** [comment]
有興趣, 已填問卷 ~

**Comment by wubaibai** [comment]
已徵得，感謝大家。
