### ISSUE TITLE
【徵才】Heroic Faith 後端工程師

### ISSUE THREAD

**Issue by hfhrsl** [f2etw/jobs#506]
## 團隊簡介/地點
聿信醫療囊括急重症醫師及專科護理師、資深軟硬體工程師、生技商業開發與投資經理及醫工跨領域專才，且與台灣大學生醫電資所合作、與國內知名醫學中心均有學研與臨床試驗合作。

聿信醫療自設立以來，針對生理音訊(ex.心音、呼吸音等)收集與分析之議題，研發出多通道陣列聽診器，並且已經完成了種子輪階段所設立之里程碑。
工程設計部門配合臨床使用者體驗，經數次改版後，完成了通過台灣大學醫學院醫工部安規及電信安全等認證。目前已投入觀察型臨床研究，於2018年12月推展臨床進行呼吸聲音之收音計畫。
我們也在全球最大生醫投資論壇 JPM Healthcare Conference之活動 RESI 取得 Innov我ation Challenge 第二名之殊榮。

## 工作地點
新北市中和區連城路258號16樓之5

## 工作內容
1. Build a flexible framework to help the development process of AI training models with the help of massive clinical data 
2. Turn solid AI prototypes/ideas into clinical decision service in the edge and in the cloud
3. Develop next-generation AI backend systems related to large-scale real-time data access, collection, analytics and monitoring 
4. Continuously improve the quality of AI production systems in the cloud
## 能力需求
- Familiar with Linux operations and basic concept for Linux network stack/utils/config
- Familiar with RESTful API design
### 加分
- Better to have Docker experience
- Better to have cloud platform experience（such as Azure, AWS, GCP） 
- Better to have Node.js, Go , Python development experience, or willing to learn
## 薪資範圍
NTD 70K ~ 100K (Depend on skills)
## 工時/特休
●平日平均工時 8 ~ 9 小時
●週休二日
## 福利/推薦項
1. 週休二日 
2. 勞保、健保、勞退金 
3. 員工分紅/配股 
4. 年度評核績優員工獎勵 
5. 完善考核、專利獎勵制度 
6. 健全的升遷管道 
7. 三節獎金或禮券
8. 婚喪喜慶補助
9. 不定期聚餐與紅酒品酒會
10.年終尾牙晚會
11. 免費零食、咖啡
## 聯絡方式
請將您的簡歷或作品資料寄至 fjtsai@heroic-faith.com (English resume must attach into email) 或是上 104 投遞

**Comment by dca** [comment]
但這裡是前端場，要不要考慮一下 [Node.js Jobs](https://github.com/nodejs-tw/jobs)

**Comment by hfhrsl** [comment]
謝謝提醒
