### ISSUE TITLE
中央研究院生物多樣性研究中心 TaiBIF 誠徴全端工程師一名

### ISSUE THREAD

**Issue by taibifbrcas** [f2etw/jobs#508]
(108 年 4 月 14 日更新)

還想做電子商務嗎？網站工程師可以有不一樣的職涯發展…
您在乎自然生態保育嗎？您知道您的開發專業對臺灣生態的研究與保育可以有很大的影響力嗎？

## 工作內容
1. 參與使用者需求分析，根據分析結果及設計建議，評估實作可行性，並規劃前後端的實作架構及開發排程。
2. 接手設計端提供的切版及動態，介接資料及完成互動功能開發。
3. 實作資料庫建置及業務邏輯。
4. 協調外部工程師執行開發工作，推動專案進程。
5. 其他團隊開發合作項目。

### 職缺說明
我們希望能找到在業界有前後端網站開發經驗及熟悉開源工具、協同開發方法的工程師，能根據設計主導規畫資訊服務前後端的實作架構，並能在開發過程中協同外部人力一起進行。這是一個相對穩定，工作節奏舒適且能兼顧職涯發展的工作機會。

## 應徵資格
1. 非資訊相關科系畢業可，曾參與資訊服務網站前後端的開發工作。
2. 熟悉 Vue.js 或 ReactJS 等前端框架，及與後端 API 串接。
3. 熟悉 Nodejs 生態系工具。對 ES6 有良好的掌握。
4. 熟悉任一資料庫的選擇和操作，能進行基本的索引設定及效能調校。
5. 熟悉 git 操作及社群貢獻慣例。
6. 不畏懼英文溝通與書寫（工作中有大量國外同儕的開發資訊），想提昇自己的英文能力。
7. 注意細節、能有效率地獨立作業；能與團隊其它角色溝通合作。

**加分關鍵字**：MongoDB, Cassandra, DynamoDB, Solr, ElasticSearch, Python, R, Java, AWS, serverless, D3.js, Data visualisation, Dashboard design, Open Streep Map, Leaflet, MapBox, CartoDB, Coding convention, CI/CD, test coverage.

因為包含前端實作，我們也希望您有一雙對視覺細節及色彩平衡十分敏感的眼睛，能忠實呈現設計，甚或加強設計。由於此技術領域推進快速，我們也期待您積極求知，主動提出想法、擔負責任，在瞭解生物多樣性資訊的同時，也能持續參與技術社群的活動，汲取業界新知，保持自己的競爭力。

## 待遇
**薪資**：新台幣 60~75K，按能力及經歷面議。
**加班費**：每週工作 40 小時，加班費按月支單一薪酬除以 240 為每小時支給標準。
**工作支持**：工作期間提供一台 MacBook Pro 便利開發工作進行。
**職涯發展**：支援參加與工作相關或能力養成之國內外訓練及研討會（每年至少一次國外行程與同儕交流）。
**休假**：週休二日，依國定假日休假。
**福利**：年終獎金固定 1.5 個月。院內健檢補助及設施優惠，及週邊電影娛樂優惠。
**特休**：按勞基法規定，可視需求面議。

工作時間：彈性上下班，表訂每日 09:00 至 18:00，午休一小時。按需求可遠端工作。
工作地點：中央研究院生物多樣性研究中心 跨領域大樓
到職時間：面議。
職缺有效時間：有合適的人選即截止。

## 聯絡方式
[柯智仁先生](https://www.linkedin.com/in/chihjen-ko-2096441/) 
聯絡地址：[cjk@sinica.edu.tw](mailto:cjk@sinica.edu.tw)，主旨請註明「TaiBIF 全端工程師」確保收件，我們將儘速回覆。
聯絡電話：(02)27872220 ext.24 

### 應備文件：
1. 個人在 github 的作品集，有開源合作專案或實際 production 的案例（請提供 URL）尤佳。
1. 建議可指出目前 [camera-trap-webapp](https://github.com/TaiBIF/camera-trap-webapp) 及 [camera-trap-api](https://github.com/TaiBIF/camera-trap-api) 可見問題、架構缺失並提出改善建議。
1. 兩位推薦人的電子郵址或電話，一位過去的同事，一位主管。請事先徵詢推薦人。我們將視情況連繫。

## 團隊簡介
[TaiBIF](http://taibif.tw) 為全球生物多樣性資訊機構（GBIF）的臺灣節點，於 2004 年起設立於中央研究院生物多樣性研究中心。我們積極配合 GBIF 的[工作計畫](https://assets.ctfassets.net/uo17ejk9rkwj/3Ua4cMwNawso46kMGisICM/fcc5c802058a44ca64922d53c15f147d/GBIF-2019-Annual-Work-Programme-APPROVED.pdf)推動臺灣生物多樣性數據資源的公開分享及研究單位資訊管理流程的研發及建設，過去也累積完成許多公部門生物多樣性資料相關專案。生物多樣性資訊學為跨生物學及資訊學的新興領域，有許多令人興奮的研究開發正在進行，也有許多與國際團隊工程師協同合作的機會，與世界接軌！歡迎您加入探索職涯發展的可能性！

目前團隊內部目前主要的技術堆疊為 Vue.js, Node.js, Express, MongoDB，期待您來強化及演進。

**Comment by Rplus** [comment]
update from #474

**Comment by taibifbrcas** [comment]
Looks similar but it's actually a different setup.

**Comment by taibifbrcas** [comment]
Thanks to the board, we've got the right person.
