### ISSUE TITLE
【徵才】方格子vocus - 資深前端工程師

### ISSUE THREAD

**Issue by david32510** [f2etw/jobs#509]
## 公司簡介

平台網址：（https://vocus.cc/）

方格子vocus （原SOSreader） 是一個新型態的寫作與出版平台，我們提供一個全無廣告、易於上手的書寫空間，適合深度寫作、分享與交流。同時也支援讀者付費訂閱的金流功能。目前已經有超過14萬會員、8500位以上的作者加入，並且有30%以上的讀者來至海外，我們希望能維持寫作與出版的多元生態，透過新的模式創造新選項，讓優質的創作者、內容及出版品被更多人看見，並進一步讓創作者獲得合理的報酬，不再吃土啃草、煮字療飢。

隨著科技的演進，閱讀習慣的改變，數位內容產業的黃金時代正在到來。在此之中，方格子（vocus）致力於嘗試、實踐一種新的方式，讓寫作者能夠在此自由表達、書寫、交流，甚至不再處於整個內容產業鍊的底層，能夠透過我們的平台獲得公平且合理的報酬。讀者也不再只是作為一個讀者，而是成為這個內容生態系的另一個關鍵角色，變成與通路商、經銷商甚至出版商平等的地位，因為讀者能直接面對作者，能在這裡存粹享受閱讀的樂趣，並且進一步分享、消費，為了自己所喜愛的作者或內容合理的付費。  

我們是一家正在邁入第5年的新創公司，歡迎一起加入我們，在改變、創新、調整的過程中，沿途的風景與經驗絕對讓你獲益良多！

## 工作內容
-負責開發維護產品前端功能與版面
-以前端專業和PM、同仁討論新功能開發方向與可行性
-與UI、UX設計師與後端工程師合作開發

## 能力需求
-Javascript、ReactJS、Redux 程式設計
-CSS3 / HTML5 開發
-CSS Framework: SASS開發
-RWD開發
-熟悉 Git / GitHub的操作
-具備call後端API基本知識

### 加分
-能用CSS做出簡單的動畫效果
-擁有組織大型專案結構的技巧及經驗
-具備或了解後端程式運作且有開發經驗
-樂於加入新創團隊，樂於面對挑戰、具抗壓性、企圖心強
-過往工作經驗或作品與內容產業相關

## 薪資範圍
-70,000–90,000（視工作經驗與能力而定，若能力超過歡迎面議）

## 工時/特休
-週一至五每日9hr，午休1hr（9:30-11:00為彈性上班時間，每月可選一天remote工作）
-有自我管理能力可申請彈性上下班

## 福利
-每年享有15天的特休假
-女性同仁每月生理假1天
-內部不定期教育訓練、進修補助
-每月歡樂聚餐

## 聯絡方式
請將履歷及作品集寄至 joinus@vocus.cc （主旨請附上申請職稱與姓名）

**Comment by Rplus** [comment]
官網網址的括號影響到連結囉~

**Comment by diabloevagto** [comment]
每日九小時？中間自己扣掉一小時午休？

**Comment by david32510** [comment]
扣掉一小時午休，已經修改囉，謝謝！
