### ISSUE TITLE
Java工程師

### ISSUE THREAD

**Issue by GraceChien** [f2etw/jobs#526]
// 以下是建議填寫項目，可自由增刪排序~
// 也建議標註團隊目前技術框架，標籤有前端&後端的語言
// ^ 上面的看完就可以刪了~

## 團隊簡介/地點
台北市南港區

## 工作內容
1.	依據產品需求進行系統分析、系統設計、程式開發。
2.	進行軟體之測試與修改。 
3.	研發軟體新技術與新工具，持續提升程式碼品質，及投入創新技術和解決方案。

## 能力需求
1.	三年以上Java開發經驗，一年以上大流量網站開發經驗尤佳。
2.	熟悉Java語言及版控Git Flow及Jenkins.。
3.	熟悉Spring、Mybatis、Hibernate、Memcached等常見開源架構。
4.	熟悉MySQL、Redis等數據庫，能熟悉解決資料庫負載的方法。
5.	精通Linux 操作系統，熟悉Shell script及常用的Linux操作指令。
6.	對技術有熱情，喜歡研究，並具有良好的學習能力。
7.	具備系統分析和設計能力，具有良好的編碼風格和習慣。
8.	具備良好溝通能力以及團隊合作精神。
9.	熟悉scrum，且精於開發工作中使用。

### 加分
主動、積極、有自信

## 薪資範圍
（依經驗及能力決定）

## 工時/特休
週休二日
9：00-18：00（有彈性時間）
依照勞基法享有所有權利

## 福利/推薦項
◆ 保險類
勞保、健保、勞退
團保意外險
◆ 休閒聚餐類
每月部門聚餐
尾牙活動
◆ 請休假制度
週休二日
依法享有各種法定假別
◆ 獎品禮金類
三節禮金(年終、中秋、端午)
生日禮金
## 聯絡方式
104應徵(https://www.104.com.tw/job/6molc?jobsource=hotjob_chr)
E-mail : jobanya010@gmail.com

**Comment by slouchy** [comment]
似乎沒看到前端缺
