### ISSUE TITLE
[徵才]全台最大的線上直播平台 資深前端工程師 年薪80-120萬

### ISSUE THREAD

**Issue by peter80713** [f2etw/jobs#53]
如果你是這樣的人，請趕快聯絡我們： 你習慣在開發之前，從任務背後的商業邏輯出發，思考開發的目的和價值，以尋求更簡潔的實現方式。你習慣在參與的過程中觀察、思考並發掘別人沒有注意到的問題，並熱衷主動嘗試解決。你希望能找到一群厲害的同儕繼續切磋、一起開發具有挑戰性和影響力的產品。你喜歡在開放文化的工作環境裡工作：沒有規定上下班時間、可以在家工作、能夠安排自己的學習進度，享受與團隊一起完成專案的成就感。

工作內容： 直播平台開發。
與系統前後端開發人員、網站設計師、及使用者體驗研究員協同合作，參與大型分散式網站之系統設計、開發、維護與資訊安全環境建置，打造高品質、高效能且能負載高流量之系統。

技術必要條件

※　熟悉 JavaScript、HTML5、CSS3，並具 Coffee/LiveScript、SASS/LESS、Bootstrap 開發之經驗
※　熟悉 AngularJS or ReactJS，並具開發其 extension/plugin 之經驗
※　熟悉 BDD/TDD 概念與任一測試框架 (Mocha/Jasmine etc.)，並具豐富測試撰寫之經驗
※　熟悉 Git & Gitflow，可自在運用 rebase & cherry-pick 等指令
※　熟悉 Linux 開發環境與系統基本操作
※　熟悉物件導向程式設計概念與重構技巧，並有實際進行重構之經驗
※　熟悉任一後端 MVC framework，可獨自從無到有建構全端含資料庫存取之網站

其他加分條件

※　熟悉 Ruby on Rails
※　RESTful API 開發經驗
※　IaaS 雲端架構管理經驗 (AWS/GCE etc.)

應徵請將履歷寄至:
peter@recruitexpress.com.tw  Peter 收

**Comment by appleboy** [comment]
@Rplus 能不能建議 Head Hunter 給個公司名稱？台灣應該沒有這麼隱秘吧？

**Comment by Rplus** [comment]
他不附我也很無奈呀...

**Comment by dca** [comment]
都號稱是「全台最大」，為什麼不能說公司名稱呢？

這樣是公認最大還是號稱最大

**Comment by Rplus** [comment]
issue closed...
