### ISSUE TITLE
[徵才] 艾西斯資訊 徵 前端工程師 (Vue/Angular)

### ISSUE THREAD

**Issue by DerikLu** [f2etw/jobs#547]
## 團隊簡介/地點
艾西斯資訊有限公司 55643294
台北市大安區敦化南路二段 182 號 5 樓

獨立專案公司，進行平台與產品的開發。
團隊文化開放多元，嘗試將靈活快速的工作模式注入長期獲利的產業之中。 
良好工作環境之外、也提供學習及成長的空間，歡迎優秀的朋友一起加入。

我們正尋找新的前端成員，一起參與新的產品開發、功能設計，後續會持續優化其功能及系統架構。
歡迎你加入我們，一同打造從使用者角度出發、符合需求、使用輕易上手的服務！  

## 工作內容

- 維護並優化現有產品
- 開發設計介面、串接 API

## 能力需求

- 熟悉 Vue / Angular 任一框架開發
- 熟悉 RWD
- 串接 API 以及讀、寫文件能力
- 熟悉 CSS pre-processor
- 熟悉 Git 以及 Git 開發流程

### 加分

- 曾經帶領團隊完成具體專案 
- 有良好的測試習慣 
- 靜態網站架構經驗 CDN 運用 
- 熟悉 CI / CD 
- 喜歡學習新知，並能夠應用在工作上

## 薪資範圍

65K ~ 90K
保障年薪 14 個月 ( 含獎金）

## 工時/特休
10:30 ~ 19:00 中午休息 12:30 ~ 13:30 (工時 7.5小時)
每周工作時間 7.5 * 5 = 37.5
優於勞基法的休假制度，第一年 12 天特休 ，入職滿三個月即按比例計算，滿三年 18 天 

## 福利/推薦項

- 團建補助，每人每月 NTD 2,000，由部門統籌運用                                                                          
- 零食餅乾許願池，想吃什麼自己許願 
- 每週下午茶，我們努力餵飽同事 
- 每月團隊聚餐公司買單 ，想吃米其林再也不是夢 
- 優於勞基法的休假制度，第一年 12 天特休 ，入職滿三個月即按比例計算，滿三年 18 天 
- 友善的工作夥伴、追求卓越的軟體開發團隊 
- 彈性工作時間，10:30 前進辦公室即可，每天都可睡飽飽再來 
- 人性化管理，我的快樂來自於給你自由
- 社團經費補助，喜歡打電動、打桌遊、打籃球、健身......都有夥伴可以同樂 
- 配備高階筆電，開發者搭配兩個 24 吋 螢幕 (可依職務需要, 要求直立螢幕) 
- 保障年薪 14 個月 ( 含獎金）

## 聯絡方式
derik@icsgame.com
https://www.yourator.co/companies/icsgame/jobs/7942
更多職缺歡迎來看看

**Comment by diabloevagto** [comment]
菠菜？

**Comment by DerikLu** [comment]
> 菠菜？

是的，歡迎各路好手來聊聊～
如果有違反規定請告知，謝謝

**Comment by kunyaoxu** [comment]
請問前端工程師目前有考慮資歷淺的嗎 ?

**Comment by DerikLu** [comment]
> 請問前端工程師目前有考慮資歷淺的嗎 ?

@kunyaoxu 有的，歡迎來聊聊～
https://www.yourator.co/companies/icsgame/jobs/7997
