### ISSUE TITLE
【徵才】eGroupAI 徵 React 前端工程師

### ISSUE THREAD

**Issue by a6091731** [f2etw/jobs#551]
## 團隊簡介/地點
eGroupAI 台灣人臉辨識技術研發團隊，專注於人臉辨識引擎設計，從2017年銷售至今，已經成功讓許多Partner整合至既有系統、擁有刷臉服務，廣泛應用在生活各種領域，我們期待未來能提供更多人臉辨識產品，讓人臉辨識應用快速普及。
公司 : 益群健康(股)
公司地址 : 台北市大安區辛亥路二段47號(近台大側門)
官網 : www.egroup.com.tw

## 技術介紹
- 設計
    - 軟體 : Sketch、Adobe Photoshop、Adobe Illustrator、Adobe XD
    - 風格：material design
- 程式語言
    - 前端 : Javascript、HTML5/CSS、React
    - 後端 : Java
- 框架
    - 前端 : react + redux
    - 後端 : spring maven
- 資料庫
    - DynamoDB
    - RDS
    - MySQL
- 雲端平台
    - AWS
- 深度學習
    - 臉部辨識
    - 語意分析
    - 物件辨識
    - 影/圖像處理

## 工作內容
- 使用 react 開發網站
- 使用 redux 和 redux-observable 處理資料流
- 使用 react-material 套 UI 介面
- 和後端工程師協同作業串接 API

## 經歷需求
- 應屆畢業生

## 能力需求
- 熟悉 HTML5、CSS、JavaScript
- 熟悉 React 與 React Ecosystem
- 基礎 UX 流程設計

### 加分
- 作品集

## 薪資範圍
- 35~70k，依能力面議決定(薪資)

## 工時/特休
- 責任制。
- 彈性工時。
- 週休二日，依國定假日休假。
- 特休優於勞基法規定。

## 福利/推薦項
- 勞健保
- 季遊
- 零食隨便你吃
- 供晚餐
- 彈性出遊/吃美食

## 面試流程
Team-> Chairman

## 聯絡方式
履歷請寄至egroup.daniel@gmail.com 主旨請備註 #前端社群

**Comment by shihKaiHung** [comment]
25k - 35k???????

**Comment by gocreating** [comment]
朝聖

**Comment by shihKaiHung** [comment]
25K太讚了
想應徵

**Comment by sky172839465** [comment]
要求會 `console.log` 都嫌太過份

**Comment by alanchuangi** [comment]
25k都開得出來
台灣的資方簡直不要臉到極點了

**Comment by Larry850806** [comment]
25K 要會 redux-observable？

**Comment by a-ken** [comment]
朝聖
好吸引人啊

**Comment by shihKaiHung** [comment]
朝聖

**Comment by chongruei** [comment]
朝聖

**Comment by nelsliu9121** [comment]
@shihKaiHung 我來朝聖你的

**Comment by dca** [comment]
台北市應屆畢業生沒有 30k 應該是略低於行情。

**Comment by vocolboy** [comment]
單位是人民幣的話好像可以😆

**Comment by jason90929** [comment]
朝聖

**Comment by sharils** [comment]
@a6091731 請問薪資的部份是不是打錯了？
