### ISSUE TITLE
【徵才】 Aegis Custody - Frontend/Backend Engineer

### ISSUE THREAD

**Issue by Aegis-Custody** [f2etw/jobs#564]
## 團隊簡介

Aegis Custody是專為企業機構設計的數位資產管理解決方案，目前正在台灣聘
請經驗豐富的工程師。Aegis Custody藉由結合多重簽名硬體錢包與多層雲架構，提供
金融機構級的安全性。工程師團隊負責設計易於使用的產品和服務，使機構能夠安全
地使用區塊鏈技術和數位資產。

## 上班地點

台北市信義區松仁路101號12樓

## Frontend Engineer 工作內容

- 實作設計、編寫可測試的程式碼。
- 從事區塊鏈服務平台、相關應用和智能合約的研究與開發。
- 研究主流的企業級區塊鏈平台開發，開發、維護並優化我們的平台。
- 將產品功能轉移至前端，協助開發網頁應用程式，並支援多種裝置和瀏覽器。
- 能兼顧開發進度與維護測試。
- 學習、實踐和審查程式碼規格，與工程團隊合作以維護高品質的前端程式碼。

## Frontend Engineer 能力需求

- 學歷要求：大學以上。
- 科系要求：資訊管理、資訊工程、其他軟體工程及電算機科學相關。
- 擅長工具：TypeScript、Linux。
- 具備至少一項JavaScript框架經驗(例如React、Angular、Vue、Ember等)。
- 熟悉HTML5、CSS3、JavaScript (ES6+)與Webpack。
- 熟悉版本控制系統Git。
- 熟悉HTTP Request、Response 和Restful API (須了解RFC)。
- 熟悉整合式開發環境VS Code、JetBrains IDE及Visual Studio IDE。
- 熟悉CSS樣式。
- 熟悉RESTful API與WebSocket串接。
- 熟悉node.js與npm。
- 具備區塊鏈技術實際專案經驗者優先。
- 熟悉Solidity等常用智慧合約語言者優先。
- 具備建立營銷等網站經驗者優先。
- 注重編碼品質與基礎架構的設計和測試。
- 英文聽說讀寫能力精通，能自主學習新技術。
- 工作積極主動、責任心強、擅於溝通、具問題解決能力，具有良好的團隊合作精神。

### 具備以下加分項目者優先

- dApp、web3.js 經驗
- Web UI/UX design 經驗與美感
- Reactive programming、RxJS 經驗
- SVG、canvas API graphics、D3.js 經驗
- React Native、Chrome Extension、Firefox Addon 經驗

## Backend Engineer 工作內容

- 實作設計、編寫可測試的程式碼。
- 從事區塊鏈服務平台、相關應用和智能合約的研究與開發。
- 運用分散式系統協助開發高品質(quality)、並發(concurrency)、可用性(availability)與可擴展性(saclability)的後端API。
- 能兼顧開發進度與維護測試。
- 參與討論與設計架構，協助開發新組件以及優化現有系統。

## Backend Engineer 能力需求

- 學歷要求：大學以上。
- 科系要求：資訊管理、資訊工程、其他軟體工程及電算機科學相關。
- 擅長工具：Python、Go、TypeScript、Julia。
- 熟悉版本控制系統Git。
- 熟悉整合式開發環境VS Code、JetBrains IDE、Visual Studio IDE。
- 熟悉HTTP Request、Response和Restful API (須了解RFC)。
- 能夠自主學習後端堆疊架構。
- 具備建構分散式系統的實作經驗。
- 具備區塊鏈技術實際專案經驗者優先。
- 熟悉Solidity等常用智慧合約語言者優先。
- 注重編碼品質與基礎架構的設計和測試。
- 英文聽說讀寫能力精通，能自主學習新技術。
- 工作積極主動、責任心強、擅於溝通、具問題解決能力，具有良好的團隊合作精神。

## 薪資範圍

Total compensation $2,000,000+ including base and stock options (compensations can be adjusted according to experience)

## 工時/特休

表定 09:00 ~ 18:00

## 福利/推薦項

- 彈性上下班，再也不用擠電梯擠車位了
- 不打卡，不簽到
- 員工配股/員工認股
- 每月點心櫃補到滿，想吃什麼自己點
- 每位員工皆配備apple筆電，可自由選配工作用的電腦與螢幕
- 每天例行歡樂午餐時光，午餐都由公司供應，各種知名餐廳與美味餐點等著你
- 每月數次不定時聚餐

## 聯絡方式

請將CV寄至下列信箱：aegis-career@aegiscustody.com

**Comment by Rplus** [comment]
> 零食飲料經同意可由公司支付

這句的意思是不定時`公司下午茶`嗎？
