### ISSUE TITLE
[徵才] 永豐商業銀行 - 前端工程師

### ISSUE THREAD

**Issue by ayuha406645** [f2etw/jobs#566]
## 團隊簡介
永豐商業銀行
誠徵 前端工程師
本部門擁有設計團隊，前端工程師就隸屬於設計組，負責與設計師和 PM 溝通專案細節與需求，完成各種專案需求。
 
## 地點
南京復興站附近
 
## 需求人數
2 人
 
## 工作內容
- 平常做的事情就是把設計師設計出來的 PSD 檔或 AI 檔轉成 html web，然後依設計師或 PM 要求，需要在頁面上做點 css3 動畫，不致於讓頁面太死板。
- 某些專案有使用 Angular 與 Vue，如果有能力處理的話會更好！
- 我們前端有使用 Prepros 進行製作，所以也需要對 Pug.js 熟悉，對於 html 很熟悉的人來說 Pug.js 學一天應該就可以上手了。
- 專案有分行銷活動頁類的與產品類（網路銀行），產品類會需要切完版後給資訊處同仁套版，有時候需要跟資訊處同仁協作處理套版畫面。
- 專案上有使用 git，在公司內有自架 gitlab，所以也得需要熟悉 git。
- gitlab 是用 VirtualBox 開一台虛擬機，OS 是 CentOS 7，如果有後端經驗會操作 Linux 的大加分！
- 前一位離職的前端，有用 Laravel 和 Joomla 寫一些上稿小工具，會 LAMP 的也是大加分！
- 基本上就是完成主管交付的專案事項。
 
## 能力需求
1. HTML5、CSS3、Javascript、jQuery、Ajax、CSS Animation
2. Photoshop 操作/切版、Illustrator 操作/切圖、Sketch 操作/切圖
3. Pug.js(Prepros)、Fire.app (舊專案有使用，新專案都用 Prepros 了)
4. SCSS
5. RWD、SVG
6. Highcharts、Highstock
7. git
 
### 加分
1. Angular 8、Vue.js
2. Pixi.js/TweenMax
3. icon font
4. WebAPI 串接
5. 習慣用 Visual Studio Code 開發
6. Google Analytics、Google Tag Manager (會基本操作即可)
7. Linux、Apache、MySQL、PHP
8. ASP.NET 或其他相關後端經驗(跟 IT 會比較好溝通)
9. 會使用 Linux、會操作 VirtualBox
 
## 薪資範圍
年薪600K~900K (大概範圍，依能力可再談更高)
 
## 工時/特休
周一至周五每天 8 小時，每週 40 小時
見紅就休，五一勞動節也有放假
上班時間：8:45 ~ 17:45 (中午休息時間一小時)
特休假制度與勞基法相同
 
## 福利/推薦項
薪獎設計：每位新進同仁皆依個人學經歷核薪，另視個人績效與當年度營運發放績效獎金與紅利。
各類保險：所有金控同仁都享勞保、健保、團保，同仁眷屬亦可加入團保。
年度健檢：同仁的健康就是永豐最大的資產。定期辦理同仁健檢，使同仁可以定期檢視個人健康狀況。
補助項目：同仁生日、三節、年終時，提供年節獎金或舉辦活動。此外，同仁婚、喪、喜、慶或住院時，公司也提供補助金或慰問金。
優惠貸款：所有金控同仁都享有優惠房貸與信貸，協助同仁在理財規劃上能作更好的運用。
休假制度：提供同仁優於勞基法的給假制度，新進同仁到職，就享有依年度比例的年假，另隨年資與職等的晉升年假也隨之增加，讓同仁在工作與生活中取得平衡。
環境設施：為讓同仁們擁有舒適的辦公環境，在金控總部設有員工休憩中心、藝文表演廳等休憩空間，並提供各式茶飲，讓同仁在緊湊繁忙的工作中適度調劑。
==== 以上是公司 104 上的資訊，額外資訊如下 ====
- 福委會不定期的哈根達斯兌換券，與威秀電影票。
- 福委會不定期的員工自強活動，今年已經去過六福村了。
- 公司有社團，如果對戰鬥有氧有興趣的，每個禮拜三晚上都有開課！
- 公司社團還有桌球社、藍球社等等社團可以加入。
- 至於外傳的優存13%，本公司已經取消多年。
- 本單位有提供免費咖啡機，咖啡可以喝到飽！
 
## 聯絡方式
有興趣者麻煩請將履歷（cakeresume 或其他）寄至：kai@sinopac.com
或直接以 104 應徵：https://www.104.com.tw/job/6p7eu?jobsource=company_job

**Comment by caasi** [comment]
推會有用不完的衛生紙（？）👍

**Comment by ayuha406645** [comment]
> 推會有用不完的衛生紙（？）👍

沒那麼佛心啦XD

**Comment by hsuchihting** [comment]
您好，已寄信到指定 email 喔~ 104 也投遞了，希望有面試機會!

**Comment by viacharles** [comment]
您好  已email 署名吳昌霖 ～ 希望能有面試機會～

**Comment by ayuha406645** [comment]
@viacharles 抱歉，目前已找到人囉~ 職缺已關閉。
