### ISSUE TITLE
[徵才] 轉轉創意 - 前端工程師

### ISSUE THREAD

**Issue by whalesingswee** [f2etw/jobs#58]
![tenten recruit](https://s3.amazonaws.com/f.cl.ly/items/0Y1a3h0V2C2s3v2k1s3v/tenten-recruit-github.jpg)
## 工作內容

大型電子商務網站開發與維護、內部創業產品開發、創新技術研發
## 工作需求
- 具備前端基礎開發 HTML5/CSS3/Javascript/Git
- 懂基礎的 Linux
- 需有基礎英文能力，能自行研讀英文技術文件，協助導入解決方案
- 願意學習新技術並樂於與團隊合作及共同分享技術新知
- 具有 UX 的思維, 對Web 開發及使用者經驗有高度的熱誠
### 加分
- 用過 PostCSS / Mustache, Handlebar, 或 Jade 等 Javascript Template
- 用過 Module Loader 等例如：Webpack, Browserify
- 製作過 SVG 動態
- 具有使用任一 MVC Framework 的開發經驗
- 擅長下列任何一個前端框架 Angular / React / Ember
- Linux server administration
- 能快速學習並運用新技術者尤佳
- 具有 Amazon Web Services 管理與操作實務經驗
- 曾自行架設並使用過 WordPress, Ghost, Jykell 等
### 超級加分
- 逛 reddit
- 愛玩鍵盤
- 爬山踏青戶外
- 愛裝愛用些自己不熟習的東西來實驗
- 會找很多方式來提昇自己的效率
## 薪資範圍

**Junior** 約 36,000 ~ 以上 **Senior** 約 45,000 ~ 60,000
## 工作流程
- Jira
- Confluence
- HipChat
- BitBucket Server
## 福利與發展機會
- 每年海外員工旅遊補助 (第一年即有)
- 舒適的工作環境
- 充足的吧台點心
- 保障 13 個月年薪
- 書藉與線上學習平台提供：購買工作相關書藉，或是國外數位學習平台服務（可申請公費，我們非常鼓勵學習新事物）
- 我們鼓勵混合型的專業人才，透過與不同專業的團隊合作學到新的知識與視野
- 開放自由的工作環境 (像 Coffee shop 一樣的工作空間)
- (Lean & Agile!) 靈活敏捷的團隊，歡迎每個人在團隊中尋找自己發揮價值的定位
- 熱愛敏捷開發，深信 Pivot 的精神，透過反覆快速的測試、驗證，一起讓產品變得更好
- 週休二日
## 地點

[轉轉創意 - 台北市東區（忠孝復興站步行 5 min，微風廣場對面）](https://www.google.com.tw/maps/place/%E8%BD%89%E8%BD%89%E5%89%B5%E6%84%8F+Tenten+Creative/@25.0454128,121.5404003,17z/data=!3m1!4b1!4m2!3m1!1s0x3442a8159b3982f9:0xabeca8cf0a9bdfe0)
## 其他

歡迎參考 [加入轉轉介紹頁面](https://tenten.co/tw/five-reasons-why-you-should-work-at-tenten)
意者請投履歷至 [jobs@ten2.tw](mailto:jobs@ten2.tw)

**Comment by haway** [comment]
每年海外員工旅游補助 (第一年即有)

發救生圈自己游出去嘛 :-)

**Comment by jf423** [comment]
請問還有junior的職缺嗎？
