### ISSUE TITLE
[徵才] YTML 台灣台北 - Junior Front-End Developer

### ISSUE THREAD

**Issue by PhoebePan** [f2etw/jobs#581]
## 團隊簡介/地點  
YTML Group - Information Technology and Service.Sydney 即將來台擴點，主要工作地點以大台北為主，擁有適合的技能、資歷的夥伴歡迎來信詳談噢！
https://ytml.com.au/
https://www.linkedin.com/company/ytmlgroup/

We are seeking multiple Front End Developer with strong JavaScript experience to lead the development of web and mobile applications for the client's range of high-profile clients. 

## 工作內容  
Building and maintaining web sites and web apps based on proprietary technology solutions. Transform business requirements into well-designed, testable, efficient code (HTML/CSS/JavaScript).

### Details:   
- Front-end development includes building responsive websites and website templates on ASP.NET by using HTML, CSS, and JavaScript.
- Building and testing web applications with backend developers on RESTful APIs by using HTML, CSS and JavaScript.

## 能力需求  
• HTML5, CSS3, JavaScript
• JavaScript Frameworks/jQuery
• Responsive Design/Bootstrap
• Worked within an agile/scrum environment

### 加分  
• UI/UX Experience
• Git
• C# or any backend experience

## 薪資範圍  
Up to TWD 600K/year

## 工時/特休  
• 15 vacation days
• Flexible working hours

## 聯絡方式
Please email me a CV if this is a suitable opportunity.
Phoebe Pan
phoebe.pan@ytml.com.au

**Comment by ryrocks** [comment]
噓不怕耶，在Facebook F2E社團被噓後，還封鎖人，心虛嗎。
[FE Taiwan](https://www.facebook.com/groups/f2e.tw/permalink/2343529215684430/)
說你不把好的文化帶進台灣就算了，結果帶你的老闆來台灣低薪找人，現在還心虛還封鎖人。

這次怎麼不敢寫薪水寫清楚
要找senior跟jr
senior要求3年還要會後端，才開50,000~60,000
jr要2年是吧42,000
都幫你列出來了

你再刪文沒關係啦，反正有截圖
