### ISSUE TITLE
[徵才][台北][45K-80K][台灣牙e通] Frontend / FullStack 前端/全端工程師

### ISSUE THREAD

**Issue by victorfu** [f2etw/jobs#582]
## 團隊簡介/地點
台灣牙e通，是全台灣最大的資訊整合平台，目前會員人數超過4,500人，約佔全台灣牙醫師人數35%，和學會、公會、廠商配合舉辦課程和產品推廣。每年超過500場以上的課程，超過1000種的牙科材料及設備，推薦給台灣牙醫師最實用且高品質的資訊。目前主要開發項目為牙科病歷系統，預計2019就會擴展到海外市場

我們尋找對產品設計有熱情，願意跟團隊起成長的你! 這是一個開放包容，又充滿挑戰跟熱血精神的地方。 我們希望的夥伴跟我們一樣永遠充滿好奇心，嘗試改變世界。 我們不怕犯錯，但是我們會一起學習如何正確地犯錯，一起成長向前邁進。

你可以接觸到什麼:
1.    第一線醫療科技及健康科技產品
2.    前端系統架構及軟硬整合
3.    人工智能技術
4.    國際市場開拓

你的起點是什麼:
1.    公司新專案的醫療資訊系統軟體開發設計
2.    逐步了解公司發展方向，及投入公司主力產品開發

你能夠得到甚麼?
1.    你可以接觸專業的軟體開發過程, 配合版本控制, 你將學會如何多人一起開發一個軟體
2.    你可以接觸到如何開發一個最小的可行性產品, 如何從使用者意見修正自己的產品
3.    你可以接觸到各種有趣的技術, 包含區塊鏈, AI, 數據分析, 網路協定…等
4.    你可以接觸到無比的工作熱誠, 讓你能夠發掘自己想要走的路

這是一個起點，希望藉由這個機會，讓我們更加認識彼此，我們也讓你更加認識市場與產品設計，成為團隊的核心份子，一同打拼。

## 工作內容
1. 協同一起設計後端架構
2. 根據標準及規格, 在時限內完成專案或功能程式開發
3. 撰寫技術規格文件

## 能力需求
1. 有開發前端經驗 React Framework
2. 能夠使用 git 做版本控制管理 
3. 有一個熾熱不怕失敗的心 

### 加分
1. 表達能力好，擅長溝通 
2. 有後端開發經驗
3. 有產品UI/UX相關開發經驗 
4. 有開發過醫療健康領域產品經驗

## 薪資範圍
40K - 80K

## 工時/特休
10AM - 7PM (彈性工時)

## 福利/推薦項
1. Mac筆電
2. 免費零食
3. 工作自由可遠端
4. 彈性工時
5. 技術團隊交流頻繁, 共同學習, 共同打造產品

## 聯絡方式
hi@dentall.io

##其他資訊請參考:
https://www.cakeresume.com/companies/e-e99e93/jobs/node-js-81bd7a

**Comment by Shawnfoto** [comment]
請問目前前端/全端人數？

**Comment by victorfu** [comment]
> 請問目前前端、全端人數？

目前研發團隊人數
前端: 4
後端: 2
設計: 3
