### ISSUE TITLE
[徵才]VIST Research 徵求網頁遊戲前端工程師/Web Game Frontend Engineer

### ISSUE THREAD

**Issue by xinwen5523** [f2etw/jobs#586]
## 團隊簡介/地點
VIST Research是一群相信區塊鏈技術和虛擬貨幣經濟能顛覆很多產業既有規則，為新進者帶來機會和希望的新創團隊。在這條偉大的航道上，我們已經做了很多嘗試。我們的團隊和產品也分別得到了幣安Binance的投資及TRON Accelerator第一名的殊榮。

雖然在鏈圈和幣圈取得了初期的成績，但是我們知道區塊鏈技術和虛擬貨幣經濟要能帶來革命，區塊鏈技術、虛擬貨幣經濟、和我們都需要能夠走進一般大眾的生活裡。我們不想只是乘著浪頭順著風勢前進，還期許自己能成為起風造浪的一份子。

在和矽谷的科技新進們討論各種想法後，我們找到了在區塊鏈和虛擬貨幣裡適合我們的角色和機會。所以決定要來尋找更多和我們有著同樣願景和能一起起風造浪的夥伴。期待想跟我們一起在這個新世界冒險的夥伴加入！
## 工作內容

- 依照設計師提供的設計檔，切出和刻出精準且高效的HTML及CSS。
- 熟悉HTML5/CSS/Javascript，打造全新和調整現有的遊戲畫面和邏輯。
- 和區塊鏈工程師及後端工程師溝通，完成專案需要的前端、後端、區塊鏈間的整合。
- 能自主解決技術問題，也能和團隊討論架構，並樂於持續精進程式效能和自身的技術能力。
- 能適應新創的步調和變化。

## 能力需求

- 熟HTML5、CSS、Javascript
- 一年以上網頁遊戲開發經驗
- 兩年以上工作經驗
- 熟任一網頁遊戲開發框架尤佳，如Phaser、Cocos2d、Construct 2等。

## 薪資範圍
70000~100,000 NTD/Month

## 工時/特休
公司不用打卡，可遠端工作，必要時配合專案進度進辦公室Sync
工作時間彈性，無固定特休

## 福利/推薦項

- 定期員工聚餐，今年為止摘了兩顆星。
- 專案獎金。

## 聯絡方式

- https://www.cakeresume.com/users/sign_up?job=7d513d
- roxy.chang@gmail.com

**Comment by jkfox67** [comment]
請問現在是否仍有缺？是否支持完全遠端工作呢？以及、若沒有 Phaser、Cocos2d、Construct 2 等框架經驗可嗎？

**Comment by xinwen5523** [comment]
> 請問現在是否仍有缺？是否支持完全遠端工作呢？以及、若沒有 Phaser、Cocos2d、Construct 2 等框架經驗可嗎？

每週至少需進辦公室一天，若你有興趣的話，請將履歷跟作品寄給我
