### ISSUE TITLE
25sprout Back-End Developer 後端工程師

### ISSUE THREAD

**Issue by 25sprout-HR** [f2etw/jobs#596]
### 

> 後台工程師就像高譚市的蝙蝠俠，從黑暗中帶出黎明
> 又堪比一個打十個的葉問，默默付出但充滿勇氣與爆發力
> 我們需要沈穩可靠的你，作為各個專案最堅強的後盾
> 讓我們的產品充滿魅力，並面對各種無法預期的變化
> 最重要的是，新芽的後台工程師的重要性眾星拱月
> 經常是看板人物，帥度一百！

## 團隊簡介/地點
我們是 25sprout ，一間年輕正發新芽的公司，
SurveyCake 是由我們打造的行動雲端問卷平台，
協助用戶輕鬆打造線上問卷並即時追蹤統計回覆資料，
我們也藉此得到服務眾多大型知名企業的機會！
   
我們熱愛且相信自己所做的工作，
也期望能將這樣的熱情分享給我們的身邊的每一個人。

地點：台北市松山區南京東路五段 1 號 12F

## 工作內容
- 負責合作產品資料處理，維護管理後台，開發後端 API
- 協助合作產品除錯與修正
## 能力需求
- 擁有 Hack Everything 的駭客精神
- 樂於自動化的工作流程，testing/CI/CD
- 我們使用 PHP / Laravel / JavaScript 混合前後端開發環境
- 一年以上協同工作經驗，熟悉 Git
## 加分
- 樂於學習矽谷最新的網路技術，了解 AWS、Docker、Serverless
## 薪資範圍
NT$ 700,000 - 800,000 (年薪)
## 工時/特休

- 彈性工作時間，每日工作八小時
- 12 天年假，未滿一年依比例計算，每滿 1 年加 1 天
- 10 天 Remote Work Day，可自由選擇工作時間和地點，巴黎跨年京都賞櫻不是

## 福利/推薦項
- 彈性工作時間，每日工作八小時
- 12 天年假，未滿一年依比例計算，每滿 1 年加 1 天
- 10 天 Remote Work Day，自由選擇工作時間地點
- 免費美味員工午餐，零食咖啡無限補充
- 一年兩次海內外員工旅遊
- 電影之夜，每季一次，可攜伴參加
- Workshop，每月一次，課程內容開放大家提議
- 社團活動與不定期 Teambuilding 活動
- 運動 / 健身補助
- 全身健康檢查補助
- Keep Learning Project，鼓勵自主學習，
   包含購買書籍、課程等皆可申請補助
- 尾牙不用表演，專心享用美食即可
- 充分享受在 Spotify 音樂與垃圾話穿插夾雜的團隊樂趣
## 聯絡方式
麻煩至 https://www.surveycake.com/s/7ny41 投遞職缺 ：）

**Comment by zxp86021** [comment]
之前投過一次，無聲無息，然後職缺開開關關的，不知道怎麼回事

**Comment by 25sprout-HR** [comment]
> 之前投過一次，無聲無息，然後職缺開開關關的，不知道怎麼回事

您好，因新芽有分兩個不同的事業體，所以各部門會各自招募後端人才，抱歉造成您的疑惑！
職缺招募完畢就會關閉，有新的職缺會再開一個新的招募資訊。
關於您提到投遞過我們的職缺，所有的求職者，我們盡可能會發送通知信，偶有特例狀況還請見諒，未來我們會更注意通知信無一缺漏，也歡迎未來有合適的機會再與您聯繫交流。
