### ISSUE TITLE
[徵人] 資深前端網頁工程師 @ 遠傳電信 影音串流資訊部

### ISSUE THREAD

**Issue by htchien** [f2etw/jobs#6]
徵求資深前端網頁工程師一名來我們 遠傳電信 在台北市內湖區 的 影音串流資訊部。需求資格如下：

* 三年以上相關工作經驗
* 熟悉（但不限於）HTML5 / CSS3 / JavaScript / AJAX / jQuery 等前端網頁技術
* 對網頁 UX 設計有基本概念
* 能包容他人意見，善於溝通

以下為加分項目：
* 有處理多媒體網頁的經驗
* 熟悉 SEO / RWD 等網頁優化技術
* 對不合理的 UX 設計能勇於提出意見、據理力爭（因為我是這樣的人，所以我希望你也是）
* 喜歡 Open Source 開源技術，並喜歡嘗試新技術

有興趣的人歡迎寄履歷到 htchien AT fareastone DOT com DOT tw 給我。

電信業薪資待遇在台灣資訊產業中應該還算不錯（礙於公司規定無法公開提供詳細數字，不過薪資水準應該算業界前半段，且保證年薪 14 個月以上），還有每年旅遊補助等大企業該有的員工福利我想應該是不用擔心。

今年已成為台灣 4G 元年，電信業在今後這幾年會是變動最大，變化快速的產業，會有很多事情可做，也會讓你很有成就感。如果你可以進來遠傳，我也會努力滿足你在工作上的需求。如果你也認同遠傳「開口說愛，讓愛遠傳」的品牌理念，歡迎你來遠傳看看！

**Comment by htchien** [comment]
已找到人，感謝各位。

**Comment by Rplus** [comment]
恭喜～
加冕已求得的頭香
