### ISSUE TITLE
[徵才] AHEAD 徵 Data/Backend Engineer

### ISSUE THREAD

**Issue by abawchen** [f2etw/jobs#603]
### 關於我們
您好，我們是來自臺大醫院及清大電機系 BIIC 研究室合作的新創團隊 AHEAD，目前開發血癌自動化辨識系統，已獲得多項肯定，包括參加 2018 年未來科技展、加入台灣代表團進軍CES 2019/2020，更入選多項創新創業計畫。歡迎有熱情想挑戰新創的軟體工程師加入我們，參與團隊及醫院討論，一同打造輔助血癌診斷的最佳軟體服務。

### 媒體報導
- ithome: https://tinyurl.com/y5nzm2xf
- digitimes: https://tinyurl.com/yxcjar3e
- 非凡新聞: https://tinyurl.com/y2aprnty
- EE Times Taiwan: https://tinyurl.com/y2uxmlgq, https://tinyurl.com/y2qnyzey

### 工作內容
- Data Engineer 1~2 （Backend 背景欲挑戰亦可）
- 處理/清理各種類性與非結構性的資料。
- 設計並最佳化機器/深度學習所需要的 data pipeline architecture。
- 與 data scientists 合作以最佳化機器學習的實驗/訓練流程。
- 開發/訂定 data profiling 的流程與工具。
- 設計資料存取權限。

### 條件
- 2 年工作經驗以上，資訊、統計相關背景科系畢業為佳。
- 以 Python 為主要開發語言 1 年以上

### 加分或進來後必須熟悉的:
- Unit test & Code Review。
- SQL/NoSQL
- Data pipeline and workflow management tools: Luigi, Airflow, etc.
- AWS 相關服務(EC2, S3, EMR)
- 系統設計

### 希望具備的人格特質
- 熱情、具良好溝通與學習能力，樂於分享，願意 Open mind 接受任務與挑戰。
- 我們希望除了完成工作之外，能透過互相學習讓開發團隊實力一起成長。

### 薪資福利 & 其他:
- 工作待遇：月薪 6萬元 至 10萬元(13 個月)
- 工作性質：全職
- 工作地點：台北
- 休假：比照勞基法

### 聯絡方式
- 履歷請用 pdf 格式寄到: abaw.chen@aheadmedicine.com
- 提供 Git 帳號或 code snippet 者優先面試

**Comment by virus-warnning** [comment]
地點在台北的那裡呢？

**Comment by abawchen** [comment]
會先在小巨蛋的 TTA 半年，之後會評估其他地點（目前選定雙連附近）

**Comment by virus-warnning** [comment]
附近方便停機車或重機嗎？還是只能搭綠線？

**Comment by abawchen** [comment]
我不清楚 .... Orz
https://www.arena.taipei/cp.aspx?n=459956E830D4A8BB&ccms_cs=1
^ 這個不知道有沒有幫助

**Comment by virus-warnning** [comment]
感謝
