### ISSUE TITLE
[日本]代徵赴日IT工程師（SE、PG、PM）

### ISSUE THREAD

**Issue by KanglinJP** [f2etw/jobs#604]
## **團隊簡介/地點**
「以客戸為中心」是我們的企業哲學。
我們的IT服務知識與經驗已成功支援眾多客戸與合作夥伴，現今已成為亞洲市場上的領頭羊。
身為立於世界頂端的國際IT服務提供者，我們是受全球客戸信賴的夥伴，於美國、歐洲、大陸、韓國都有據點。

**工作地點**：東京、大阪、廣島、九州（可自行選擇）

## **工作內容**
1、對第一線各項需求、異常進行分析、偵錯、改良以確保系統順暢運行。
2、概要設計、程式設計、綜合檢測、系統運用、開發業務、專案主導。
3、定義要件、製成設計圖，並根據設計圖進行系統開發、測試等與程式設計相關事務。
4、技術調查、主導網路基礎架構設計、規劃及實施、根據業務及管理需求改善網路基礎架構。
5、管理團隊、客戶、專案、程式企劃提案、獨立作業參與專案業務。

## **能力需求**
日文可溝通（無須檢定）
SE或程式設計師系統開發經驗1年以上

### **加分**
以下任意能力尤佳：C、C++、Java、firmware、COBOL、.NET（ASP、VB、C#）、SAP、ORACLE、BSE、SAP S/4 HANA、VB.NET、pathyon、salesforce、iOS、android、PHP、PL/SQL

## **薪資範圍**
20～80万（考量經驗、能力）

## **工時/特休**
（コアタイム）9:00～18:00

## **福利/推薦項**
社會保險完善（雇用、勞災、健康、厚生年金）
加班津貼、出差津貼、職務津貼、職能津貼、幹部津貼
海外研修制度、國内外員工旅遊、全額補助交通費

## **聯絡方式**
Email: sharon9@KL0800.com
Line: black012601
Tel: (04)2202-6799 #25
https://kanglinglobal.wixsite.com/taiwanjinzai
有任何疑問都歡迎尋問哦!!

**Comment by alvinyen** [comment]
請問日文是必要的嗎？英文是可以流利溝通的程度符合資格嗎？謝謝

**Comment by KanglinJP** [comment]
> 請問日文是必要的嗎？英文是可以流利溝通的程度符合資格嗎？謝謝

您好，日文需要可以溝通的程度，不用考檢定也可以哦！
