### ISSUE TITLE
Job opportunities for HK companies, based in Taipei!

### ISSUE THREAD

**Issue by Kevin-Glints** [f2etw/jobs#606]
大家好，有好幾個香港公司可遠端工作的機會，有興趣可私訊：

1) [TW$30K/month up] 找前端工程師，可遠端工作，是一家來自香港的零售科技初創，技能需求主要是react和搭API，找1年相關工作經驗

2) [面議] 找CTO，可遠端工作，是一家在香港業務正快速增長的酒店較價平台，技能需求主要有AWS／Azure經驗，並有5年以上帶領科技團隊的工作經歷，有做過Web及App development兩者的優先

3) [TW$50K/month up] 找前端工程師，可遠端工作，同樣是在香港業務正快速增長的酒店較價平台，找3-4年相關工作經驗人才，會React JS, SEO, WordPress，並有一點 UI/UX背景

4) [面議] 找前端工程師，台北工作，是一家專門幫跨國公司建payment solution和電子錢包的香港Fintech初創。3-4年相關工作經驗，對英語要求高。最好懂ReactJS，但非必須。主要工作為建web components 和 implement UI/UX。

5) [面議] 找後端工程師，台北工作，同樣是一家專門幫跨國公司建payment solution和電子錢包的香港Fintech公司。3-4年相關工作經驗，對英語要求高。必須懂Docker, Kubernetes, 及有AWS 或Google Cloud 經驗，懂Golang的優先，主要工作為 distributed micro-services

**Comment by Rplus** [comment]
GitHub 是要怎麼私訊啦 XD

**Comment by Kevin-Glints** [comment]
Contact me from:
WhatsApp: +62 822 8495 8354
Line ID: the_yoseph
Linkedin: https://www.linkedin.com/in/kevin-wijaya-a23ba411a/
e-mail: kevinwijaya@glints.com

**Comment by Kevin-Glints** [comment]
Please contact me through:
e-mail: kevinwijaya@glints.com
WA: +62 822 8495 8354
Line ID: the_yoseph
Linkedin: https://www.linkedin.com/in/kevin-wijaya-a23ba411a/
