### ISSUE TITLE
[徵才][年薪 160 - 200 萬] Botrista 飲品自動化 徵全端工程師 

### ISSUE THREAD

**Issue by botrista** [f2etw/jobs#609]
## Botrista簡介/地點
Botrista專注於開發智能自動化設備，服務橫跨全美及亞洲，所設計的產品和應用專為全球連鎖餐飲集團、以及茶飲品牌使用，目前正在打造全球第一台自動現調飲品設備，期待能夠顛覆過往飲品產業服務方式，讓新鮮現作能夠透過自動化的方式兼具客製化及標準化。如果您也認同我們的理念，那我們急需你這樣的夥伴加入，協助我們開發出世界級的產品服務。

## 工作內容
1. 開發商家智慧設備管理平台。
2. 開發智慧調理設備雲端架構系統及各項串接。
3. 規劃文件化功能規格與系統設計。
4. Linux 應用程式開發經驗，並指導同仁、解決問題。

## 能力需求
1. 相關科系畢業，三年以上全端經驗， 一年以上前端及ReactJS開發經驗。
2. 良好的軟件開發素養，能貫徹實施敏捷、測試驅動和持續集成的開發模式。
3. 曾使用過AWS, Node, Containers, ELK stack / elastic, SQL以及NoSQL資料庫系統, REST APIs, Microservices和敏捷開發流程。
4. 熟悉大型資料庫的API撰寫開發串接、經驗。
5. 熟悉金流串接的API撰寫開發串接、經驗。
6. 與UX設計師合作設計好的體驗應用。

## 薪資範圍
1. 起薪$ 80,000 - $150,000，面議爲主，依照能力與經驗調整，歡迎自薦爭取更高的價值與報酬。
2. 基本勞健保。

## 工時/特休
彈性的工作時間：表定是9點到6點上下班。
特休：服務滿半年7天特休起算，滿一年即10天特休。

## 福利/推薦項
寬敞及明亮的辦公環境，並備有完整廚房，每天現作手搖飲喝到飽。
公司位置超級方便，交通四通八達，近迪化街南西商圈，附近美食吃不完。

團隊成員大多都是工程師，機構工程師人數居多，軟體工程師團隊正在擴編中，公司正在產品測試及市場驗證階段，很多設計會需要快速調整，會接觸到許多軟硬體整合的地方，
也有機會和第一線使用者接觸。除了很偶爾特殊狀況發生之外，都正常上下班。目前台灣團隊有近20人，氣氛融洽，積極徵才中！

1. 良好的升遷制度與職涯成長機會。
2. 定期內部員工訓練以及外訓課程，提供全額學習補助
3. 定期與公司創辦人1對1談話，共同討論公司未來方向。
4. 彈性上下班時間。
5. 手搖飲料喝到飽。
6. 不定期聚餐及出遊。
7. 辦公室備有健身器財、桌球桌，一起運動同樂。

## 聯絡方式
請以標題“【全端工程師】_你的名字” ，並附上以下資料以及問題寄到：hr@botrista.io 
1.  英文履歷 & Cover Letter
2. Github連結
3. 作品集
4. 其他你認爲能幫助我們更了解你的資料

**Comment by dca** [comment]
前端的版，後端工程師的缺
技能要Nodejs ， 應徵的卻是 python 工程師

botrista <notifications@github.com>於 2019年11月8日 週五，下午10:13寫道：

**Comment by botrista** [comment]
感謝指正，已更新為全端工程師
