### ISSUE TITLE
公視新媒體部 徵求前端工程師 / 後端工程師

### ISSUE THREAD

**Issue by liaodolphin** [f2etw/jobs#611]
## 團隊簡介
**公共電視 新媒體部 互動媒體**
公共電視近年來積極迎接新媒體，成立了公視+ OTT影音平台，搭配各部門推出各種互動網站，更努力佈署雲端建置，希望能讓公共電視快速轉型，以面對新媒體的挑戰。

公視的目標是：建立公共服務媒體平台，看見台灣更美好的未來
**歡迎有能力又能認同公視願景的你，來信與我們聯絡**

公司地址：台北市內湖區康寧路三段75巷70號，康寧大學正門對面
環境優、空氣佳、捷運直達，超優質環境。

## 工作內容
- 開發及改善目前網頁開發流程
- 既有服務雲端化
- 打造技術團隊的知識共享

 **1. 前端工程師一名：**
- [x] 整合API與後端資料串接
- [x] 活動網頁切版及開發網頁前端互動功能(如互動圖表呈現等)
- [x] 跨平台web服務與前端程式調校
- [x] 釐清企劃需求，與後端工程師協作
- [x] 分析設計前端架構以提升UI質感與UX體驗

 **2. 後端工程師一名：**
- [x] 後端系統的研發和維護工作
- [x] 網站的前後端及相關API開發與串接
- [x] 管理維護網站
- [x] 釐清企劃需求，與前端工程師協作
- [x] 規劃及進行現有服務雲端化

## 能力需求
 **1. 前端工程師：**
- [x] 熟 HTML、CSS、JavaScript、AJAX、jQuery 等前端技術
- [x] 至少熟悉一種JS Framework 如：vue、react
- [x] 了解SASS/LESS
- [x] 熟悉Git
- [x] 熟悉 SEO 及各瀏覽器相容性
- [x] 熟悉跨裝置與跨瀏覽器相容技術
- [x] 熟悉RWD網站開發技術
- [x] Photoshop 基本操作
- [x] 具有高度溝通能力，並樂於技術分享者

 **2. 後端工程師：**
- [x] 熟Laravel框架，但必須不使用Framework也能開發
- [x] 熟悉Git
- [x] 熟悉MySQL語法，有獨立資料庫作業能力
- [x] 了解LAMP (Linux + Apache + MySQL +PHP)開發環境
- [x] 了解HTML5/CSS/JavaScript/jQuery
- [x] 具RESTful API開發經驗
- [x] 具有高度溝通能力，並樂於技術分享者
- [x] 熟悉任一雲端技術發展，並會使用者(加分)
- [x] 有使用 Docker 的經驗(加分)

## 薪資範圍
月薪 40,000-70,000 

## 工時/特休
- 彈性上下班，08:00 ~ 10:00 至 17:00 ~ 19:00
- 週休二日，依國定假日休假
- 特休同勞基法

## 福利/推薦項
- One for All(我為人人)的榮譽感
- 一個月的年終獎金
- 績效看表現

##  面試流程
- 第一階段：團隊成員會主動電話聯絡適合的應徵者並送出面試確認信
- 第二階段，邀請您來公視面談 (本團隊人員進行訪談)
  若有通過第二階段，會在結束後一週內通知並送出第三階段面試確認信
- 第三階段
  主管面試與提問
  **若有通過第三階段，會在兩週內通知面試結果**

##  聯絡方式
請將履歷的電子檔發信到 liaoj@newmedia.pts.org.tw
liaoppj@gmail.com
liaoj@mail.pts.org.tw，
標題請註明[應徵公視軟體工程師]

**Comment by timtorChen** [comment]
你好 你們提供的信箱主機似乎有問題  寄信會被退件
伺服器回應
```
500 5.0.0 Service unavailable
```

**Comment by liaodolphin** [comment]
Sorry,已修正

**Comment by timtorChen** [comment]
不好意思 我使用 Gmail 信箱依然無法成功傳送郵件

**Comment by liaodolphin** [comment]
謝謝告知，我們查詢一下，請先郵寄到liaoppj@gmail.com
