### ISSUE TITLE
【徵才】[台北中山] ACCUPASS活動通 徵  React前端工程師

### ISSUE THREAD

**Issue by Ling422** [f2etw/jobs#655]
## 團隊簡介/地點
「ACCUPASS 活動通」是亞太地區具備影響力的活動SaaS平台。除了為各式活動主辦單位與個人提供辦活動及售票的服務，也有完善的行銷推廣及展會科技可供主辦單位使用，深受各界客戶信賴。
我們接下來將整合多方資源，快速擴展到亞洲各國，這是一段艱辛及困難的旅程，我們需要更多的夥伴，在這條路上和我們一起奮鬥。
現在就加入ACCUPASS活動通，和我們一起為人們創造更多故事與回憶！讓每個人的生活都能因活動而生動！

## 工作內容
負責依照產品需求開發ACCUPASS平台網頁，並且根據視覺設計需求完成CSS切版，搭配完成體驗、質感、性能等兼備俱佳的網頁。

## 能力需求
1. 1+年軟體設計開發工作經驗，實做產品，且有網站專案上線經驗
2. 熟悉React, Redux框架
3. 熟悉javascript, ES2015+語法
4. 熟悉git
5. 熟悉Babel, Webpack等JavaScript開發工具
6. 擅長切版、熟悉CSS3, RWD

### 加分
1. 擅於和Designer溝通
2. 熟悉GA, GTM, Facebook pixel及SEO等行銷工具
3. Vue開發上線經驗
4. 後端開發經驗

## 薪資範圍
月薪 35K-50K

## 工時/特休
週一至週五，09:30-18:30 (彈性上下班)
特休依勞基法規定

## 福利/推薦項
活力滿滿的充電假(到職滿一年即享有一年2天)
參加各式活動的機會
開放的辦公環境
輕鬆活潑的上班氣氛
吃不完的零食、飲料

## 聯絡方式
Yourator：https://www.yourator.co/companies/Accupass/jobs/10352
CakeResume：https://www.cakeresume.com/cr/accupass-dc49d3/accupass-front-end-engineer-f35409
HR ：lingwang@accuvally.com

**Comment by Rplus** [comment]
舊的記得關一關唷~
https://github.com/f2etw/jobs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ACCUPASS

**Comment by Rplus** [comment]
「徵 React 開發者，但是熟 Vue 者有加分」
好奇這是因為想往 Vue 遷移嗎？
