### ISSUE TITLE
【徵才】【50K~120K+】【台北】Xfers 新加坡商迅星金融科技有限公司徵Junior前端/前端工程師

### ISSUE THREAD

**Issue by logan-lo** [f2etw/jobs#658]
## **團隊簡介**
Xfers Mission
Xfers believes in financial inclusion. We abstract away regulatory and compliance responsibilities, making it easy for Fintech and digital businesses to accept payments, store and disburse funds.

In Singapore, we are a Widely Accepted Stored Value Facility alongside only 4 other companies, namely Capitaland, Ezlink, Cashcard, and NETS.
In Indonesia, we are a registered payments gateway licensee. We work closely with regulators to ensure that our services are compliant.

## **上班地點**
台北市中山區

## **工作內容**
As a Junior Software Engineer, Frontend at Xfers, you will be working extensively on the Dashboard revamp project. The Dashboard revamp project is part of the initiatives to improve both our external users experience, and the internal operation team experience. You will be exposed to all the exciting cutting-edged technology as we revamp our front-end stacks. Besides that, you will also be supporting the enhancements and upgrades to our Javascript SDK.

## **能力需求**
- Bachelor's degree in Information Systems, Computer Science or related field, or equivalent practical experience (preferred)

- You understand the fundamentals of Web application, including HTTP requests, API usage, HTML, CSS, and Javascript

- Prior working experience is not required, but you have displayed ownership in your own learnings in other aspects of your life

### **加分**
1.團隊合作精神
2.表達能力好，樂於溝通
3.自我學習能力強
4.金融科技相關經驗

## **薪資範圍**
Junior前端工程師 50K-80K/月薪
前端工程師 70K-120K+/月薪
年薪13個月來計算

## **工時/特休**
週一～週五，10:00~18:00 (彈性上下班)，實際工作 7 小時
試用期過後14天特休

## **福利/推薦項**
1.免費零食
2.彈性工作時間
3.有事情可以在家工作
4.200新幣補助看醫生/年
5.英文進修補助費
 
## **聯絡方式**
請將英文履歷投遞下方其中一個方式
HR: logan@xfers.com
其他職缺：https://www.cakeresume.com/companies/xfers

**Comment by alvinnyen** [comment]
@logan-lo dear Hiring Manager,

Does this position still open?
Just wondering it's still open or not cause the position is not on cakeresume.

thanks,

**Comment by logan-lo** [comment]
> @logan-lo dear Hiring Manager,
> 
> Does this position still open?
> Just wondering it's still open or not cause the position is not on cakeresume.
> 
> thanks,

Hello @alvinnyen ,
This position close.
