### ISSUE TITLE
徵才 - 美商安邁尋求一同以JavaScript征服世界的勇者

### ISSUE THREAD

**Issue by finchen-ami** [f2etw/jobs#66]
美商安邁科技股份有限公司台灣分公司 AMI Taiwan
https://www.104.com.tw/job/?jobno=353yi&jobsource

NTBU是AMI裡的新創部門，目前致力於數位看板軟體系統開發。Tech stack 以 Javascript 為主，後端有 nodejs 軟體端有 nw.js，目前還處於開發階段因此需要更多有經驗的同伴一起讓產品更為完整。

<Salary Range>
50~90k * 14

<Job Description>
• Work as part of software team to develop product’s key component: web-based management portal.
• Build prototypes based on requirements.
• Implement prototypes into robust product features.
• Optimization, monitoring and maintenance of website.

<Requirements>
• Understanding of HTML5, CSS3, JavaScript and DOM.
• Basic knowledge of GIT & GITHUB.
• Familiar with web application concepts such as AJAX, RESTful, HTTPS, …
• Team player & problem solver.

<Bonus>
• Have concepts on user experience (UX).
• Experience in mobile & cross-browser web application.
• Experience with developing a whole website using SPA frameworks like Angular, React, etc.

contact us: finchen@ami.com.tw

**Comment by gwokae** [comment]
我我我我我我我我我我我我我我我我我我我我我我我我我
