### ISSUE TITLE
【徵才】【台北】Xfers 徵 Junior & Senior 區塊鏈工程師

### ISSUE THREAD

**Issue by logan-lo** [f2etw/jobs#664]
**## 團隊簡介**
At Xfers, we believe in financial inclusion. As South-East Asia stands on the cusp of being an economic powerhouse in the coming years, there is a need to enable many individuals to step out of their marginalized financial environments. In empowering a speedier entry by digital financial service providers into these markets, we aim to bring equal financial opportunities to all, in the hope of alleviating financial hardship.

We strive for a place where everyone should be able to reach out to trusted digital financial service providers with ease and convenience. However, establishing a business of any scale with a transparent and secure regulatory-compliant payment infrastructure can be challenging, complex and time-consuming.

By enabling and accelerating the setting up of digital financial businesses in this region through the Xfers API platform, these businesses will now be able to focus on their core function of providing financial services, in the shortest possible time, even in the most remote places, and all individuals will be able to access these services towards financial betterment.

**##工作地點**
台北市中山區

**## 工作內容**
As a Blockchain Engineer at Xfers, you will be responsible for working on our suite of financial integrations tools and core Xfers banking systems. You will be involved in leading or supporting the design, architecture and implementation of these systems. More specifically, you will be involved in cutting edge design and implementation of compliant stablecoin(s) for South East Asia under Project StraitsX.

**## 能力需求**
Junior 
- Bachelor's degree in Information Systems, Computer Science or related field, or equivalent practical 
   experience (preferred)
- At least 1 - 3 years of relevant engineering experience
- Knowledge of Web3 architecture
- Experience with at least one smart contract programming languages, Solidity or Scilla preferred

Senior
- Bachelor's degree in Information Systems, Computer Science or related field, or equivalent practical 
   experience (preferred)
- At least 2 - 4 years of relevant engineering experience
- Knowledge of Web3 architecture
- Experience with at least one smart contract programming languages, Solidity or Scilla preferred
- Experience with MVC frameworks such as Ruby on Rails

**### 加分**
- Experience with MVC frameworks such as Ruby on Rails a plus
- Experience with maintaining blockchain node(s) and microservice(s) a plus
- Experience with smart contract development environment such as Truffle a plus
- Experience in managing Linux servers a plus
- Experience working with open-source projects a plus

**## 薪資範圍**
Junior 50K~80K/month
Senior 70K~120K+/month，可和創辦人談薪水上限。

**## 工作時間**
10:00 am - 6:00 pm (工時7小時)

**## 福利**
- 14天特休
- 零食
- 英文進修補助
- 200新幣補助看醫生

**## 聯絡方式**
請將英文履歷寄至 logan@xfers.com

**Comment by logan-lo** [comment]
您好，請問一下為什麼會被關閉呢？

從我的iPhone傳送

**Comment by Rplus** [comment]
非前端職缺而關閉。

另外，提問前建議你開啟 GitHub issue 確認 issue 狀態，
我想這麼一來你就不會提出這麼容易回答的問題了 ：）

**Comment by logan-lo** [comment]
您好，

不好意思我了解了，下次會注意。
