### ISSUE TITLE
[徵才] H2 Inc. 前端工程師 Front-End Developer (內湖科技園區)

### ISSUE THREAD

**Issue by hanksudo** [f2etw/jobs#68]
https://gist.github.com/hanksudo/5dd6acbf6d116e0898f7

Android Developer
iOS Developer
前端工程師 Front-End Developer
後端工程師 Back End Engineer
UI / UX Designer 界面與使用者體驗設計師
Marketing Specialist/Manager 行銷專員／經理

# We are H2 Inc,  we are hiring!

https://www.health2sync.com

We are Health2Sync, we help Diabetics improve blood sugar control with technology.

應徵請寄至: hr@health2sync.com

## 公司介紹

H2 Inc. 是一間新創公司, 成立于2013年6月, 目前成員有18人, 目標是提供一系列結合行動/數位醫療及雲端服務的健康照護平台。第一個產品為協助糖尿病管理的方案「智抗糖」，包含了Mobile App、 Web App，及方便病患同步血糖機數據的傳輸線。病人可以更容易追蹤、管理血糖、家人與醫療單位可以透過雲端平台更即時瞭解狀況並提供關懷。歡迎對我們公司產品有興趣的人加入，一起努力！

### 相關報導:

- [H2 Launches Health2Sync, A Tech-Savvy Way To Help Diabetics Manage And Track Their Glucose](http://goo.gl/wlUVxd)
- [Health2Sync - CES 2014 Hardware Battlefield Video](http://youtu.be/j83BSoowEIo)
- [長庚醫院血糖量測 連上雲端](http://www.chinatimes.com/newspapers/20140818000112-260204)
- [慧康進軍醫療 開花結果](http://www.chinatimes.com/newspapers/20150330000066-260204)
- [[Meet創業之星]血糖監控+雲端照護，慧康科技打造全方位醫療管理平台](http://www.meetclub.tw/article/view/id/35775)
- [醫療分配不均怎麼解？Health2Sync 的糖尿病照護平台或許有答案](http://punnode.com/archives/30018)
- [手機APP監控血糖　比傳統衛教更有效！](http://www.appledaily.com.tw/realtimenews/article/new/20150602/621166/)

### 為何加入H2?

全世界有將近10%的人口是糖尿病的病患，這個比例逐年增加。你身邊很有可能就有一位病患或潛在病患。我們希望H2的服務可以幫助病患控制他們的血糖，減少糖尿病導致的問題，也想幫助全世界的醫療機構提升他們給予病患的醫療品質。

### 工作內容

- 協助開發給病患及醫護人員使用的Web App
- 持續優化網站

條件:

- Experienced in responsive web development
- Familiar with JavaScript, HTML5, CSS3, and AJAX
- Familiar with frameworks such as Bootstrap, Backbone, AngularJS, React

加分條件:

- Development on Mac OSX or Linux
- Github
- UI / UX Design Sense
- NodeJS
- SEO

### 其他資訊

薪資: 40k ~ 70k 
工作地點: 內湖科技園區 (西湖站)
做喜歡的事, 做拿手的事, 做幫助人的事，誠摯邀請您加入我們當我們的夥伴！
應徵請寄 Email 至 hr@health2sync.com

附上:

- 履歷
- 作品 (非必要)
- GitHub (非必要)

**Comment by Shyam-Chen** [comment]
前端職位的薪資是 40K ~ 70K (14個月) ?

**Comment by hanksudo** [comment]
@Shyam-Chen Yes, 謝謝。

**Comment by Rplus** [comment]
@hanksudo ，請問是已徵得嗎？

**Comment by hanksudo** [comment]
@Rplus Yes, 已徵得，暫時此職缺已滿，謝謝。
