### ISSUE TITLE
25sprout 2020 實習生招募計畫 正式啟動！！！

### ISSUE THREAD

**Issue by 25sprout-HR** [f2etw/jobs#683]
📢 25sprout 2020 實習生招募計畫 正式啟動！！！
   
實習生計畫已來到第七屆了！真的非常開心每一屆都有優秀的實習生加入，為我們團隊帶來源源不斷的熱情還有衝勁!
期待今年能有機會邀請更多充滿創意與活力、樂於享受團隊合作和願意學習與分享的小幼苗加入我們，一起冒險、一同成長 🚀🚀

We are looking for
． Back-End Developer - 後端工程實習生
． Front-End Developer - 前端實習生
． Project Management - 專案管理實習生
． Account Management - 客戶管理實習生
． UI/UX Designer - UI/UX 設計實習生
． Marketing - 行銷實習生
． Customer Success - 客戶成功實習生
． Business Development - 商業開發實習生
     
  2020 25sprout Intern 限時招募中，實習計劃詳情請見：https://www.25sprout.com/intern/
         
**貼心提醒**
🌱 投遞職缺一律至實習生計畫網站透過問卷申請！！！
🌱 本次招募採先到先審的機制，會需要一段時間篩選履歷，後續會再以 Email 和各位聯繫，招募到適合的人選即關閉職缺，歡迎大家儘早投遞履歷給我們唷!!

## 團隊簡介/地點
我們是 25sprout ，一間年輕正發新芽的公司，
SurveyCake 是由我們打造的行動雲端問卷平台，
協助用戶輕鬆打造線上問卷並即時追蹤統計回覆資料，
我們也藉此得到服務眾多大型知名企業的機會！
   
我們熱愛且相信自己所做的工作，
也期望能將這樣的熱情分享給我們的身邊的每一個人。

地點：台北市松山區南京東路五段 1 號 12F

## 薪資範圍
時薪：$160 元起，將視實際能力與貢獻增加

## 工時/特休
彈性工作時間、實習周數與每週上班天數

## 福利/推薦項
- 彈性工作時間、實習周數與每週上班天數
- 免費美味員工午餐，零食咖啡永遠充足
- 電影之夜，每季一次，可攜伴參加
- Workshop，每月一次，課程內容開放大家提議
- 不定期 Teambuilding 活動，也可自發發起社團活動喔！
- 運動 / 健身補助
- 充分享受在 Spotify 音樂與垃圾話穿插夾雜的團隊樂趣
- 接觸各領域的領導品牌客戶，參與超過上萬人使用的產品專案
- 實習期間表現優異，我們將誠摯地歡迎您成為我們的正職夥伴

## 聯絡方式
麻煩至 https://www.25sprout.com/intern/ 投遞履歷！

**Comment by 25sprout-HR** [comment]
Back-End Developer 後端工程實習生 及 Marketing 行銷實習生 
已徵得！

**Comment by 25sprout-HR** [comment]
UI/UX Designer UI/UX 設計實習生 
已徵得！

**Comment by 25sprout-HR** [comment]
Front-End Developer - 前端實習生 
已徵得！

**Comment by 25sprout-HR** [comment]
Account Management 客戶管理實習生及 Customer Success 客戶成功實習生 已徵得！

**Comment by 25sprout-HR** [comment]
Project Management  專案管理實習生 已徵得！

**Comment by Rplus** [comment]
那個…
前端實習已徵到的話
就不要一直留言了
看是要去改內文，還是在同一留言區塊裡註記都好

不然我一直會收到通知…

**Comment by diabloevagto** [comment]
刷存在感的概念嗎？
