### ISSUE TITLE
[徵才] BLOOMON - Front-End Developer (React)

### ISSUE THREAD

**Issue by touhonoob** [f2etw/jobs#70]
## 公司名稱

BLOOMON 
http://www.bloomon.co.uk/

## 公司介紹

Bloomon是一家藉由線上訂閱服務為歐洲花卉產業
帶來革命性影響的新創公司，我們在一年內成長
至10000名用戶，擴張到4個歐盟國家，並在台北
成立RD Center。除此之外，我們在第一輪募資就
獲得了1.4億台幣的資金。

## 薪水

60k ~ 80k

## 休假資訊

- 見紅就休
- 有薪病假

## 工作需求

- Required
  - 合理的英文程度 (不用很流利，但至少能在工作上溝通無礙)
  - 熟悉React

- Bonus
  - React Native
  - Angular.js
  - Webpack/Require.js 等module管理工具
  - Gulp/Grunt
  - SCSS/SASS
  - Node.js

# 福利

- 每週免費Company Lunch
- 不定期Company Drinks
- 獲得與多個歐洲國家合作的經驗

# 工作地點

捷運台北橋站 (Innosqaure)

# 應徵方式

請附上英文簡歷+作品集或是Github帳號

- tom.medema@bloomon.nl
- https://www.linkedin.com/in/tommedema
- https://www.facebook.com/tommedema

**Comment by yutin1987** [comment]
nice service :+1:

**Comment by touhonoob** [comment]
@yutin1987 已補休假資訊

**Comment by Shyam-Chen** [comment]
如果不會 React 就不能，對嗎?

**Comment by Rplus** [comment]
@touhonoob 你好，請問 BLOOMON 是已徵到前端同事了嗎？
如果是的話我會幫忙加的 `已徵得` 的 label 來恭喜 XD

**Comment by touhonoob** [comment]
@Rplus 因為需求和工作地點都改了，所以就重開一個issue
