### ISSUE TITLE
[求職][台北] 前端工程師 Front-End Web Developer

### ISSUE THREAD

**Issue by mingjunlu** [f2etw/jobs#709]
## 簡介
自學網頁前端開發約一年半，喜歡寫跟生活有關的作品，偶爾會在部落格記錄自己學到的東西。

履歷好讀版：
https://www.cakeresume.com/mingjunlu

### TOEIC 多益英語聽讀測驗（新制）
- 得分：925/990
- 日期：2019.05.26
### TOEIC 多益英語聽讀測驗（舊制）
- 得分：900/990
- 日期：2012.08.26

### Website Layout
- Semantic HTML
- CSS
  - Flexbox & Grid
  - Media queries
  - BEM naming convention
  - SCSS
### JavaScript
- ES6+ syntax & features
- React
- React Hooks
- Redux / React Redux (synchronous data flow only)
- Node.js + Express (for building simple APIs)
### Tools
- ESLint
- Git
- Parcel
- Photoshop (with no design skills)

### [使用 WebP 格式減少圖片載入時間](https://medium.com/@mingjunlu/image-optimization-using-webp-72d5641213c9)
整理出幾種將圖片轉換為 WebP 格式的工具，並記錄在網頁中載入 WebP 圖片的不同方法。
### [透過 lazy loading 延遲載入圖片](https://medium.com/@mingjunlu/lazy-loading-images-via-the-intersection-observer-api-72da50a884b7)
描述當網頁有大量圖片時，如何利用 Intersection Observer API 動態載入部分圖片。

### [口罩咧？](https://www.findmasks.tw)
前後端分離的口罩地圖，前端使用 React，後端使用 Node.js、Express。資料來源為健保署提供之開放資料。

![findmasks_RWD_TEMPLATE](https://user-images.githubusercontent.com/40516784/83398623-491a4580-a432-11ea-877c-b5af7147ec1b.png)

網址：https://www.findmasks.tw
原始碼：https://github.com/mingjunlu/findmasks-frontend

- Responsive web design (RWD)
- Single-page application (SPA)
- 作品列於健保署「[口罩供需資訊平台](https://mask.pdis.nat.gov.tw)」的地圖應用清單
- 2020 年 4 月平均每日將近 500 人造訪，日瀏覽量約 5,100 次

### [Furnit](https://furnit.herokuapp.com)
前後端分離的電商網站模型，前端使用 React，後端使用 Node.js、Express、Mongoose。

![furnit_RWD_TEMPLATE](https://user-images.githubusercontent.com/40516784/83399508-ecb82580-a433-11ea-91b8-af7a1a370812.png)

網址：https://furnit.herokuapp.com
原始碼：https://github.com/mingjunlu/furnit-frontend

- Responsive web design (RWD)
- Single-page application (SPA)
- 實作簡易會員登入功能

## 社群參與
- 零時政府 g0v 口罩地圖專案協作
  - 作品列於健保署「口罩供需資訊平台」
- F2E & RGBA Meetup - Light 八月號 2019
  - 參加講座主題：React function component
- F2E & RGBA Meetup 五月號 2019
  - 參加講座主題：如何打造 UX 設計師的影響力
- F2E & RGBA Meetup - Light 五月號 2019
  - 參加講座主題：關於 React Pattern 的那些大小事

### 2017.03 - 2018.07 專任研究助理 @ 國立陽明大學 公共衛生研究所
- 負責科技部研究計畫的問卷施測收案
- 與同事共同制定、撰寫收案流程 SOP 文件
### 2011.08 - 2015.06 教育心理與諮商學系 @ 國立新竹教育大學
- 2015 年透過 Coursera 修習 Python 入門課程
- 2012 年起擔任計網中心工讀生，協助宿舍網路簡易問題排除、電腦維修等

## 期望薪資
扣除勞健保後，實領月薪 38 ~ 42 K

## 聯絡方式
contact@mingjun.lu
歡迎來信聯絡 ✉️

**Comment by caasi** [comment]
請問您是 F2E & RGBA 那三場的講者嗎？

**Comment by mingjunlu** [comment]
> 請問您是 F2E & RGBA 那三場的講者嗎？

啊啊不是的，我是去聽講座的與會者 😅
我這樣寫的確容易讓人誤會，來調整一下，感謝提醒！

**Comment by mingjunlu** [comment]
已找到工作，感謝所有聯繫我的朋友們 🙇‍♂️
