### ISSUE TITLE
【Lane Crawford Joyce Group】Backend developer

### ISSUE THREAD

**Issue by noragao** [f2etw/jobs#733]
> ## WHO ARE WE?

Are you a passionate talent who can think out of the box to help driving the business with a new approach? ImagineX Group is a premier retail, brand management and distribution company. We build luxury, designer and premium contemporary fashion, beauty and lifestyle businesses with an entrepreneurial approach and the passion and flair of a brand owner. 
 
We are now inviting a self-motivated, creative and talented Backend developer to join our Beta Labs.
 
Beta Labs is a new data science initiative from The Lane Crawford Joyce Group maximizing the value of the Group’s assets across its retail and distribution businesses, Lane Crawford, Joyce, Pedder Group and ImagineX.
 
The Group is Asia’s pre-eminent luxury lifestyle Group, with more than 450 points of sale and 1.5 million active luxury customers across Greater China and online. Its companies are internationally recognised as benchmarks for retail innovation and creativity.
 
Beta Labs aims to support the paradigm shift in retail by driving business insights through data solutions. We are looking for data scientists, engineers, and digital domain experts to join us to explore the potential value and possibilities to innovate personalisation and customer experience. You will have access to our assets and analyse on top of Hadoop and Spark.
 
If you thrive in a fast-paced environment, possess an entrepreneurial spirit and are passionate about data analysis with a focus on the end user, we’d like to hear from you.
 

> ## WHAT YOU WILL BE DOING?

•	Develop and design cloud native applications
•	Build and design database systems across SQL and NoSQL
•	Integrate with various data management platforms
•	Write readable and quality code with unit testing

> ## YOU NEED TO BE…

•	Bachelor's degree in computer science or relevant discipline
•	Hands-on experience in SQL and NoSQL database
•	Hands-on experience in Restful API
•	Hands-on experience of Docker and Kubernetes is a plus
•	Knowledge in HTML and CSS is preferred
•	Knowledge in React, Vue or any JavaScript frameworks is preferred

> ## Salary range
NTD$ 1,000,000~1,500,000 / Annual salary

Information provided will be treated in strict confidence and only be used for recruitment purpose. The Company may refer suitable applicants to other vacancies within the associated Group of companies

Please send your full CV, present and expected salary, and your availability to alanyu@lcjgroup.com, kennethshek@lcjgroup.com

`SQL`
`NoSQL`
`Restful API`
`Docker`
`Kubernetes`
`HTML`
`CSS`
`React`
`Vue`
`Javascript`

> ## WORKING ENVIRONMENT

![IMG_3135](https://user-images.githubusercontent.com/69784143/90363539-8be4d480-e095-11ea-86b0-2d39d37df436.JPG)
![IMG_9428](https://user-images.githubusercontent.com/69784143/90363552-8e472e80-e095-11ea-96b3-d0112fc8f07d.JPG)
![59261c6b-5560-4698-9754-fb22619e2cee](https://user-images.githubusercontent.com/69784143/90363580-930be280-e095-11ea-88a7-4453f0496b95.JPG)
![Beta Labs_Office](https://user-images.githubusercontent.com/69784143/90363589-943d0f80-e095-11ea-89b8-7d99022b8149.jpeg)
![d8220f3e-1276-4b4d-a2e9-840b343e16f6](https://user-images.githubusercontent.com/69784143/90363593-94d5a600-e095-11ea-9f69-d320f8bb79ec.JPG)

**Comment by tpai** [comment]
Backend engineer...?
