### ISSUE TITLE
【徵才】 Dcard 徵求前端工程師 Web Frontend Developer 

### ISSUE THREAD

**Issue by ariayann** [f2etw/jobs#740]
## 團隊簡介/地點
致力於打造一個讓每個人都可以放心分享的場域，創造讓平凡人分享不平凡故事的新世代社群服務。我們的使用者來自世界各地，除了既有社群服務與版圖，我們也正全力擴張發展新型業務及跨國市場。

面對快速變化的社群生態與公司的成長，我們期待更多優秀的人才加入 Dcard。為了讓 Dcard 能為全世界的使用者提供更好的服務，我們需要 Web Frontend Developer 加入我們的團隊，一同在瞬息萬變的前端領域學習成長、擁抱挑戰，一起打造被這個世代所喜愛與使用的產品。

## 身為我們的夥伴⋯
你所製作的產品將能立刻接觸到龐大的使用者，並在他們的生活中創造一個美好的驚喜。

Dcard 的開發團隊組織扁平，開發時程皆可討論，上班時間也十分彈性。我們主要使用 React.js, Redux，工作內容從切版、刻元件，到改架構、調效能、SEO 都會碰到。除此之外，我們會嘗試不同的新技術，團隊內部會定期舉辦讀書會互相交流。

### 日常挑戰
・加入不同 delivery team，和 PM、engineer 和 designer 合作，打造社群、電商、廣告等不同領域的跨國市場產品
・在兼顧設計、體驗與效能下，追求每個元件的最佳實作
・思考如何在多語系、多地區的條件下，穩健優化整體網站的 SEO
・考量跨裝置、跨瀏覽器與向下相容，提供給使用者順暢穩定的瀏覽體驗
・最大化地共用程式，開發出所有 2C、2B 與 MIS 的網站
・專注於優化開發者體驗與架構，並評估導入新的技術

### 技術現況
・主要使用 react、nextjs、typescript、redux，沒事就升到最新版本
・用 yarn-based monorepo 整合開發所有內外部網站，元件、工具、資料流、中間層、框架皆共用

### 工程文化
・YAGNI
・Boy Scout Rule
・追求程式品質 (stability、performance、maintainability、reusability)

### 工作流程
・github flow
・PR 需要被 reviewed 才能 merge
・每隻 PR 創建後，CI 會自動生成該 PR 的測試環境 (包含 staging、production、storybook...)
・平均一天 release 3~4 次，週五不 release

### 團隊現況
・10+ 位 frontend developers
・每週一次 frontend 週會
・每兩週一次讀書會
・每月一次全工程團隊的 seminar

### Fun Facts
・在 Slack 上做了「發射」按鈕，沒事就按，就 release
・自建訂便當、按摩預約...等系統

## 工作內容
・支援產品團隊專案開發
・持續迭代系統架構與效能
・在各種裝置上為使用者提供一流的網站體驗
・與一群成長心態、喜歡挑戰並樂於學習新技術的同伴們一起幫助公司及自己成長

### 必備條件

・3 年以上 web 開發經驗，擁有優秀的架構設計能力、良好的程式撰寫風格
・有深厚的 troubleshooting 功力
・熟悉 react、redux、ES6、typescript
・開放心態，有團隊精神，協作經驗豐富，技術討論順暢
・樂於學習新知，與團隊一同快速成長

### 加分條件

・對 UI/UX 敏感度佳
・優化過大型網站架構的效能
・深刻了解 Web Vitals 與改善技巧
・熟悉安全性議題
・有後端開發經驗

## 薪資範圍

- 年薪 NTD 900,000 ~ 1,600,000，或依經驗與能力面議

## 工時/特休

- 彈性上下班，優於勞基法的年假

## 福利/推薦項

- 重視夥伴成長：講座、語言課程、不限國內外的 Conference 補助、讀書與購書補助，時時刻刻和 Dcard 一起學習成長。
- 彈性工作環境：彈性上下班時間，還有一週一次 Remote Day ，自主運用自己的時間及空間。
- 舒適工作配備：Macbook + 24 吋大螢幕、一週一次的按摩時間，除了自己的座位，更可以在站桌、吧台、沙發上舒服工作。
- 溫馨員工活動：每個月慶生會、午餐日、水果日、尾牙、運動團課，我們重視每個相聚的時光。
- 吃不完點心吧：無限量零食飲料、膠囊咖啡機、氣泡水機，堅持午後紅茶等級的飲食標準。
- 年假與勞健保：優於勞基法的年假、優於產業的團保，體貼每一個重要的需求。

## 面談方式 & 流程
請至官網 [職缺連結](https://grnh.se/313965b61) 投遞履歷。如果團隊覺得有機會合作，一起讓 Dcard 往更高的目標邁進，我們會儘速聯絡你。

為了確認我們是否為適合彼此的夥伴，接下來會有幾個面談階段，包含 Take Home Test 和 Web Team, HR Team 與 CEO 的面談，時程預計將會在兩週至一個半月左右完畢。

## 關於團隊
如果對團隊不太熟悉，可以 聽聽 [CEO 對團隊的想法](http://bit.ly/2Bzz974) 或是 閱讀[ iThome 的 Dcard 專訪 ](https://www.ithome.com.tw/people/136905)。

希望有機會能邀請優秀的你，成為我們的夥伴！

## 聯絡方式

請前往官網 [職缺連結](https://grnh.se/313965b61) 提交你的履歷申請。

**Comment by Rplus** [comment]
跟舊的 #610 比起來
勞方開發經驗需求多一年，但資方給付年薪下限減 100k XDDD
