### ISSUE TITLE
「求職」Martin：工作或接案

### ISSUE THREAD

**Issue by youjenli** [f2etw/jobs#746]
# 自介與履歷下載點

您好。我是個目標導向、精益求精的工作者。為順利達成任務目標，實現特定的理想，我能主動發展新技能、學習新事物並自行判斷和安排待辦事項，從不將侷限自己在所屬崗位的職責範圍內。

過去在國內電子產品貿易商的資訊部門先後負責實作基於 Web 的內部資訊系統、為公司物流團隊整合並研發混合式行動應用程式（hybrid mobile app）的架構和功能、為開發團隊探索、建置、檢驗與選用持續整合系統，以及導入應用程式效能監控系統。

平時除經常參與技術社群的討論以學習處理各類事務的策略，還會主動探索與學習有用的新語言、新工具、新框架、新架構設計思想，然後視需求將它們介紹給同事和朋友，使大家以更有生產力、有效率、有彈性、更少錯誤的方法完成工作。

我關心系統、產品或服務之存在意義與其獨特之處，願意推廣自己認同其意義的東西，或是鑽研方法改善、增強其表現，亦或機動地支援諸如前端、後端、自動化測試或維運等工作。

希望有機會進一步了解您的目標、理想，以及我能夠效勞之處。

歡迎下載履歷進一步了解我的狀況：
https://drive.google.com/file/d/1bWdfZuXFyiKWXHUfLbk_h1SUK6IgK4C3/view?usp=sharing  
或是線上查看我在 cakeresume 的履歷：  
https://www.cakeresume.com/s--A_RcRjGTWXCvnIMjS-YOKg--/youjenli-developer  

履歷內容包含技能概述、工作經歷、學歷、自傳與修習過的資訊工作相關知識。  

## 參考作品
因為從前一份工作離職後心力憔悴，身心陷入生涯低潮與嚴重的自我懷疑，同時缺乏生活目標又迷失職涯發展方向，所以近兩年多在消忱的心情下在家調養身心、整頓個人環境、完成過去想做的事並且複習部分學科，並未求職。  
在透過一些探討大腦運作和拖延心理的書藉破解自己的迷思，並且在處理事情的過程中更了解自己之後，現在我重新找回了生活的目標以及職涯發展方向，準備再次出發。

在此期間與工作相關的重要事務是自學了 React.js、TypeScript 和 wordpress 系統開發了 SPA 架構、RWD 設計的個人網站以證明自己。歡迎藉此前端評斷我是否有您需要的切版能力與前端功能實作能力。

### 個人網站
https://youjenli.site/
### 原始碼
https://github.com/youjenli/youjenli-s-website-front-end

#### 此前端的架構設計
此前端實現 SPA 架構與 RWD 設計的作法是先用 navigo 函式庫委派對應的功能處理使用者發送給各頁面的請求，然後等各功能透過  axios 函式庫向 wordpress 的 rest api 取得各頁面的資訊後，再用 react 函式庫根據螢幕尺吋產生對應的畫面內容並為元件設定合適的尺吋。

產生此畫面樣式的做法是先撰寫 SCSS 再整併轉譯後的 css 檔案。  
建置此專案的作法是自行整合 browserify、cleanCSS 等函式庫開發專用來建置 wordpress 場景的 gulp 指令稿。  
  
#### 架構設計的考量與檢討
使用 navigo 而非react router 委派對應模組實現 SPA  原因是我認為不應採用 jsx 這樣的宣告式語法表達委派處理請求的對象，而且也應該盡可能把 react component 當成單純的畫面樣板而不要在取得畫面內容之前就先啟動元件的生命週期，因此用 navigo 委派其他單純的 javascript 模組處理請求是較合適的安排。  
另外，我沒有使用 redux 那類工具管理應用程式的狀態，原因是我認為各功能所管理的狀態之間關係沒有複雜到一定程度之前不需要使用這些工具，這樣有點像用大砲打蒼蠅，因此各功能使用幾個變數各自管理其狀態即可。

然而，事後檢討發覺採用 SPA 架構有點像是為了用 react 而用 react，未必是當時最適當的設計。儘管 Google 宣稱他們已開發出可以解讀 SPA 內容的爬蟲，但他並不保證會等前端程式多久，因此網站的 SEO 表現有可能不夠理想。再說，內容網站的介面互動程度相對較低、功能較少 ── 其實用經典的 unobstusive javascript 滿足需求應該就綽綽有餘。  
雖然這問題可以運用立基於 node.js 的 server-side rendering 工具提早產生部分請求的回應畫面來緩解，但這樣做又有伺服器端整合不同平台（node.js、php）的問題，系統或許就不便部署在一些划算可靠的主機租賃服務上。因此未來我會考量主機租賃服務的狀況研究實現 SEO 的適當做法。若到時要繼續採用 SPA 架構，那我還會一併嘗試整合 GraphQL 和 next.js。

另外，當初因為擔心效能與維護問題，所以不但沒有採用 Styled Component 產生樣式，還將樣式表分拆至許多 scss 檔案中，事後發覺這是非常愚蠢的決定。當畫面的結構已經因為採用 react 而在一個一個 js 檔案中設定完畢時，分開撰寫樣式反而非常不便查找與修訂。這降低了我的工作效率，未來我一定會抽空解決這個問題。

最後，之所以自行開發建置指令稿，而非使用目前流行的 webpack 或 create-react-app，原因是我認為那些工具只有在開發者願意一切照其安排時才好用，否則複雜的運作機制加上講得不夠清楚的文件往往令我傷腦筋，再加上我的專案是一個 wordpress 的場景而非典型的應用程式前端介面。有些額外的事情得在建置時一併處理，因此最後還是透過 gulp 指令指令稿安排建置作業。

### 我具備的知識
以下文件包含我了解的軟體執行環境、前後端程式語言、框架與函式庫，以及會使用的開發工具、系統和服務，還有我讀過的學科。  
https://docs.google.com/document/d/1tA8mo0llYUCjTo9DY6CJ5I4KnUgVnXYe5FyI7L68E2I/edit?usp=sharing  
寫在 google doc 是為了運用它比 markdown 更完整的排版能力。  

## 願意考慮的工作地點和語言
國內國外，遠端或進辦公室都可。  

2019 年報考 TOEIC 口說和寫作測驗，兩項分別得到 150 / 200，170 / 200 分。我樂於藉工作繼續磨練與精進英文聽說讀寫能力。

## 期望待遇
每間公司對其工作崗位各有規劃與安排，我應該多能理解，因此不管願意提供的待遇多少都歡迎您找我討論看看。  
只是若薪資越低，那我會更在意公司和我未來的成長與發展議題，例如業務是否有成長潛力？系統的發展藍圖？個人在開發功能過程中可以累積什麼經驗？可以學到哪些東西？…等等。  

### 作息與出勤
由於我剛吃飽很難馬上睡著，因此希望午休時間可以有點彈性。  
例如中午原本一小時的午休可以讓我只休息半時吃飯就開始工作，但是等到下午兩點到三點間沒有活動時，可以趴下來小睡半小時。  
若上下班時間也能有一點彈性更好，早到早走，晚到晚走。

希望可以加入採用 scrum 等敏捷方法工作的團隊。雖然我沒有相關經驗，但因為聽完簡介後就直覺它非常適合我，所以曾買書看過入門觀念。  

### 服儀
上班便服、制服都好。  
希望會客、會議、重要面談以外的情況可以穿拖鞋。

### 配件
希望上班可以視情況自備電腦週邊，例如在公配螢幕以外還可以自備螢幕，可以帶慣用的滑鼠與鍵盤…等等。  

希望可以戴耳機聽音樂。  
我不會總是聽音樂沉浸在自己的世界中，只是當壓力大，或是有令人煩躁的問題時，若能聽音樂可以讓自己心情平緩一點而不那麼厭世。希望您可以諒解。  

## 聯絡方式
youjenli1124@gmail.com

**Comment by caasi** [comment]
您的個人網站 502 了，是不是打錯網址？

**Comment by youjenli** [comment]
> 您的個人網站 502 了，是不是打錯網址？

網址沒有錯喔~
剛才也有其他人跟我反應相同問題，我想或許是主機商的系統出錯，不好意思。

**Comment by youjenli** [comment]
網址沒有錯喔~
剛才也有其他人跟我反應相同問題，我想或許是主機商的系統出錯，不好意思。

**Comment by youjenli** [comment]
幾經思考覺得不想當前端工程師了，因此關閉此串
