### ISSUE TITLE
[徵才] Kono - Full Stack Web Developer

### ISSUE THREAD

**Issue by yu-liang-kono** [f2etw/jobs#75]
## 公司簡介

[Kono](https://www.thekono.com) 成立近6年，創辦團隊來自史丹佛校友，總部在全球最大創新基地矽谷，致力打造全球最好閱讀平台，團隊成員來自矽谷、臺北、馬來西亞、香港等。推出 Kono 線上電子雜誌平台、App，吸引台港日數百知名雜誌出版社合作上架、日本最大的雜誌電商合作，我們歡迎對新創/APP/閱讀有興趣的人加入，將您的專長應用在跨國市場，在這您可與跨國人才一起合作、了解矽谷創新思維，歡迎加入 Kono，一起成就理想未來！

iOS：[http://itunes.apple.com/tw/app/id477224666](http://itunes.apple.com/tw/app/id477224666)
Andorid：[https://play.google.com/store/apps/details?id=com.kono.reader](https://play.google.com/store/apps/details?id=com.kono.reader)
Facebook: [https://www.facebook.com/thekono/timeline](https://www.facebook.com/thekono/timeline)
## Requirements
- Thorough knowledge of CSS 3, JavaScript, jQuery and HTML 5
- Familiar with HTTP and basic networking concepts
- Familiar with unit test framework
- Experience with single page app (SPA)
- Experience with responsive web design (RWD)
- Experience with at least one JavaScript framework, such as **Angular** or **React**
- Experience with at least one backend programming language, such as **Node.js** or **RoR**
## 薪資福利

Kono 以人為本，重視每位使用者、每家合作夥伴，更重視每位員工。因此，我們不僅持續打造以用戶為主的服務，更在乎每位一起努力的同仁，我們致力創造多元環境，擁有不同國籍的夥伴、不同看世界的角度，更鼓勵員工學習成長，幫助您成就自己。加入 Kono，一起讓好的內容被世界看到，也一起成就理想的自己！

- 月薪 **NT$ 60,000** 起，依能力經驗面議
- 彈性工時
- 支持員工依照專長與興趣，進行職務調整
- 鼓勵學習成長，補助海內外研討會、進修課程
- 優於勞基法，就任即享 12 天特休假，年資多一年加 1 天
- 女性長達3個月產假
- 矽谷總部工作機會
- 每月點心與零食
- 週五中餐補助
- 生理假、病假
- 週休二日
- 方便、舒適的工作環境
- 提供完善的保險制度
- 不定期聚餐活動

## 其他
- 台北市信義區，捷運 101 站附近
- 有意者，請來信至 **yu.liang[at]thekono.com**
- 來信請盡量附上
  - resume (required)
  - github (required)
  - websites you built (optional)
  - blog (optional)
  - stackoverflow (optional)

**Comment by Rplus** [comment]
@yu-liang-kono 需要幫忙加 「已求得」 的 label 嗎？

**Comment by yu-liang-kono** [comment]
可以，謝謝你！
