### ISSUE TITLE
Perpetual Protocol 徵求前端工程師 

### ISSUE THREAD

**Issue by yurenju** [f2etw/jobs#752]
最新職缺資訊將會在我們 [官方的職缺網站](https://jobs.perp.fi/f2e) 上更新，這邊我也會不定期更新，但請以官方職缺網站上面的為準。

## 簡介
你將成為 PERP Team 的一員，負責與團隊一起完成 Perpetual Protocol 的介面開發及其他相關網站的前端工作。

Perpetual Protocol 為目前 DeFi 世界中，交易量最大的衍生金融商品去中心化交易所 (Decentralized Derivative Exchange)。PERP Team 於 2020 發表首創的 vAMM 虛擬造市機制，將去中心化永續合約 + 自動造市商的協議建構在以太坊 (Ethereum) 與 xDai/Arbitrum 網路上，除了提供低手續費永續合約（Perpetual Contract）交易介面外，也讓其他金融服務可以基於此 Protocol 建置 DApp，衍伸出更多樣的 DeFi 服務。

更多介紹請見：

* [Perpetual Protocol 介紹](https://medium.com/@perpetualprotocol/what-is-perpetual-protocol-36db9db89169)
* [vAMM 介紹](https://medium.com/@perpetualprotocol/a-deep-dive-into-our-virtual-amm-vamm-40345c522eeb)
* [Litepaper](https://docs.perp.fi/library/litepaper)

## 工作內容 Responsibilities

團隊的主要目標為設計與實作永續協議，工作包含撰寫但不限於：

- 撰寫銜接整合 Perpetual Protocol DeFi 協議的網站介面
- 研究並整合其他的 Dapp 如 Uniswap v3 或 balancer 等
- 撰寫 Perpetual Protocol 除了核心業務外的其他網站介面如 landing page, DAO (Decentralized Autonomous Organization) 頁面等

團隊成員需要能撰寫高品質且可測試的程式碼，並對相關的金融知識有興趣深入學習。

## 必備條件 Basic Qualifications

對於技術的要求，我們並不侷限於單一程式語言或是框架。由於區塊鏈以及其他新科技日新月異，熟悉團隊已經在使用的技術固然加分，但我們相信樂於學習新技術的工程師能夠自我學習新的框架、程式語言以及區塊鏈技術。

以下為應徵條件：

- 對 DeFi (Decentralized Finance) 與區塊鏈充滿熱情
- 熟悉 Javascript 或 Typescript 語言，工作上將會使用 TypeScript
- 熟悉 React 或其他框架，工作上將會使用 React
- 擅長溝通
- 樂於學習新技術
- 熟悉你慣用語言的自動化測試方式
- 深入了解自身學習的語言與該語言相關的開發環境、Framework 與工具

## 加分條件 Preferred Qualifications

- 擁有區塊鏈底層技術知識
- 熟悉不同區塊鏈的異同
- 熟悉 Layer 2 solution

## 薪資範圍

年薪 182 萬～ 350 萬台幣，以美金加密貨幣 [USDC](https://www.circle.com/en/usdc) 支付。另外如果你認為你是敝公司不可或缺的人但薪資不符，我們的薪資還有彈性空間，歡迎來信洽詢！

## 關於 PERP Team

我們有超過十年的創業經驗，多次成功出場。Perpetual Protocol 投資人包含世界上最大的虛擬貨幣交易所幣安（Binance）及其他知名投資機構，遠大的願景是成為 DeFi 金融衍生商品的核心模組，發展更好的 DeFi 生態系。

我們總是對技術充滿好奇心，願意嘗試新事物，並且不停修正與改進。團隊協作風格為透明開放，自由當責，主動積極，鼓勵創意。工作的形式為 4/5 的時間遠距工作，1/5 在辦公室上班，公司提供螢幕與設備，私人筆電每年固定提供補助金。若你想要更深入的了解加密貨幣／區塊鏈產業，一起建構獨一無二的去中心化 DeFi 金融服務，歡迎加入 PERP Team！

## 聯絡方式

投稿履歷請至 [官方的職缺網站](https://jobs.perp.fi/f2e) 應徵該職位，需要更多資訊請在底下留言或寄信至 hiring@perp.fi 聯絡或至 [Facebook 貼文](https://www.facebook.com/groups/f2e.tw/posts/4775136495857011/) 詢問！

**Comment by satsuya0114** [comment]
@yurenju 請問有機會全遠距嗎？

**Comment by yurenju** [comment]
@satsuya0114 你好，全遠距是可談的，你可以在 apply 時附註，我們會一併考量。

**Comment by yurenju** [comment]
感謝各位的協助，我們已經陸續找到了一、二位適合的工程師。我們預計還要找一名工程師，但是就會轉成比較長期的尋找方式，所以如果有興趣的朋友還是可以來信，如果覺得適合的話會再邀請進行面試。

另外如果不是前端工程師也可以 apply。我們主要開發是圍繞前端、serverless 的後端以及 Smart Contract，如果你不是前端工程師但也對這樣的專案有興趣也歡迎寄信給我們！

**Comment by yurenju** [comment]
嗨各位，我們目前從前端工程師這個角度找工程師的事情到了一個段落，不過如果你對於區塊鏈與 DeFi 有興趣還是可以聯絡我們，我們還是有在找工程師喔！

**Comment by yurenju** [comment]
re-open ticket 再招募囉！

**Comment by yurenju** [comment]
感謝各位的幫助，目前這個職位的招募已經到一個段落，不過有興趣的朋友還是可以聯繫 hiring@perp.fi ，如果你非常適合我們公司，我們會再討論一下是否額外開個職缺 :D

**Comment by yurenju** [comment]
各位，我又來 re-open ticket 啦！！

**Comment by hanamizuki** [comment]
快來當我同事！
