### ISSUE TITLE
[徵才] Umbo CV - Backend engineer interns

### ISSUE THREAD

**Issue by pinglin** [f2etw/jobs#76]
Umbo CV (https://www.umbocv.com) is looking for solid backend engineer interns. Please send your resume to the only email shown inside the container:

`docker run umbocv/internapp`

Thanks.

**Comment by pinglin** [comment]
Our recruiting style seems to violate the rule of this job board. So I would close the ad by myself.

**Comment by twxia** [comment]
雖然不是前端, 但這徵才方式頗有趣 :smile:
