### ISSUE TITLE
[徵才] VerdantSparks | Full-Stack Software Engineer

### ISSUE THREAD

**Issue by ferrywlto** [f2etw/jobs#761]
We are a software startup company located in Taipei with Hong Konger founder. We treasure professional talents who with passion. We focus on your proven skills more than academic results. If you are passionate in technology, enjoy non-traditional working environment and want to improve animal welfare, **this job is for you**.

### Tasks:
- Full-stack Software development.
- Participate in UX design.
- On-site support in exhibition booth may required.
- Meeting clients.
- Remote working.

### Education background and work experience required:
- Degree of Computer Science or equivalent qualification from the world's top 200 universities and working experiences from Fortune 500 companies.
- **Fluent English is a must.**
- You have at least one mobile App under your name deployed in production Apple App Store/Google Play Store. 

### Technical requirement:
- VueJS, JavaScript, TypeScript, NativeScript, C#, .NETCore, Python.
- MongoDb, MS-SQL Server, Firebase and other SQL/NoSQL vendors. 
- GitHub, Docker, webpack, npm, yarn, DevOps, Cloud Computing.
- Slack, WebAPI, Cybersecurity concepts.
- Implementation experience of Blockchain and Machine Learning.

- You have good understanding and passionate in writing clean and performant code.  That means:
  - You write tests.
  - You know OOP and design patterns well.
  - Your code don't smell.
  - You write documentations about your code.
  - You write code with plan. 
 
### Personal characteristics required:
- You able to work under pressure and tight schedule.
- You will proactively contribute to the company.
- You demonstrates phenomenal problem solving skills. 
- You are honest with the company, the clients, and yourself.
- You take responsibility for your own mistakes.
- You work as a good team player.
- You love technology and programming.
- **You own and love your pets and care about animals welfare.**

### Extras
+ Cantonese language skill will be a big plus. 
+ Contributions in open-source world is appreciated.

### Remuneration package
- Annual salary: 1M - 1.5M+ NTD (Labor Insurance & National Health Insurance included).
- National Health Insurance, Labor Insurance and Labor Pension as required from Taiwan government.
- Working hours and annual leaves: Follow [Labor Standards Act](https://law.moj.gov.tw/ENG/LawClass/LawAll.aspx?pcode=N0030001)

### Apply information
1. Send your CV/resume with title "Apply for Full-stack Software Engineer" to [here](mailto:apply@verdantsparks.io).
2. Your should include your Linkedin/StackOverflow profile url in your resume.
3. You **MUST** have portfolio for referencing your previous work. 
    - GitHub/GitLab or equivalent public repository of your previous work/personal projects/contributions to open-source community. 
    - **We discard application without portfolio directly.**
4. Shortlisted candidate will be invited for coding test.
5. There will be a casual face to face interview If you pass the coding test.
6. Although we located in Taipei, you can work in anywhere. We will happy if you live around Taichung area.

**Comment by hunterliu1003** [comment]
請問月薪大約只有 26000 嗎
390000 / (12 + 3)

**Comment by ferrywlto** [comment]
> 請問月薪大約只有 26000 嗎
> 390000 / (12 + 3)

不是啊，最高會是 480000/(13+3) 喔。

**Comment by noel77543** [comment]
天啊…全端月薪三萬…

Ferry To <notifications@github.com> 於 2020年10月16日 週五 上午12:20 寫道：
