### ISSUE TITLE
【徵才】GoSky 誠徵前端工程師 Front-End Engineer

### ISSUE THREAD

**Issue by JerryLiao-GoSky** [f2etw/jobs#773]
![](https://user-images.githubusercontent.com/69893031/98499125-9e7d3d00-2283-11eb-90cf-c16eab004895.png)

## 團隊簡介、工作內容
GoSky 目前正尋找優秀的開發者一起加入聊天機器人行銷科技的團隊中，我們致力於發展適合 不同產業型態、不同客戶規模的解決方案。你將經手聊天機器人前後台介面開發，提供全球不同市場企業主優質的服務體驗，期待你的加入！

## 公司文化
- 重視工程師自我提升，不時會提供講座、研討會的資訊及補助。
- 良好的業務端、產品端關係，工程師能夠得知自己的努力在市場上的價值是如何。

## 能力需求
- 2 年以上前端開發經驗，熟悉 HTML、CSS、JavaScript 知識。
- 熟悉 React 及 Hooks API、Custom Hooks 觀念和實作方式。
- 確保 UI/UX 技術可行性，及網站支援跨裝置。
- 具模組化觀念，開發重用性高、易維護的程式碼。
- 熟悉 Git Flow 及 git 操作指令。
- 前後端分離開發經驗。

### 加分
- 熟悉 GraphQL
- 熟悉 SEO 優化。
- 具建構 CI/CD 經驗。

## 薪資範圍
NT$ 800,000 - 1,200,000 (年薪)

## 工時
9:30 至 18:30，中午休息 2 小時(12:00 ~ 14:00)

## 福利
加入GoSky，以下等你來享受：

1. 有假就能請，絕對放得到：
    - 上工後即享特休 10 天，依年資調休。每兩個月享帶薪病假，女性同仁享每月帶薪生理假。
    - 2020 新試驗：開放申請遠端工作，疫情間遠端工作測試中。
2. 剛吃飽就開工？別開玩笑了：
    - 兩小時整午休時間 (12pm - 2pm)，隔壁人氣壽司店要排隊也吃得到！（懶得排也有熱心同仁幫你排）
3. 有想法不敢大小聲？
    - 團隊組織平行，溝通流暢，夥伴尊重一切前衛想法，只怕你沒有，不怕你不說。
4. 職場還能當學校，每月為腦加點料：
    - 定期舉辦 Workshop，學海無涯。學生是你，老師也是你！
    - GoSky 圖書館，每月添購書目，想讀新書就把連結貼過來！
5. 好啦！吃喝玩樂的福利來了：
    - 不定期 Team Building，人家在上班，你可能在破關。
    - 開心揪一下 Happy Hour，進對了公司，Happy Hour 天天都有！
    - 季節性按摩折扣券發放，累了就去鬆一下！三不五時還有電影首映會
    - 上班可以小酌，真的可以，杯子我們準備好了。（零食氣泡水茶飲咖啡的當然是什麼都有）
    - 55 吋超大螢幕，午休想看 NETFLIX 還是 Apple TV 都可以。
6. 放眼世界的 GoSky 國際化團隊：
    - 提供成員調職海外市場機會(北美/東南亞)。

更多你想要的福利，快進來幫同事爭取！

## 聯絡方式
透過 Email 投遞：jerryliao@goskyai.com 
或透過 Yourator 投遞：https://www.yourator.co/companies/GoSky/jobs/11507

**Comment by CaitlinGosky** [comment]
推！
