### ISSUE TITLE
【徵才】Shypyard.io  資深後端工程師

### ISSUE THREAD

**Issue by spchuang** [f2etw/jobs#792]
## 公司介紹 

Shypyard.io 是一個iPaaS平台,幫助公司串連不同的API介面來自動化資料的處理。我們提供一個可以在瀏覽器上開發node.js軟體的平台，並提供便利的方式串聯其他平台的API. 我們非常的初期，今年7月才開始。目前在[參加哈佛的新創加速器](https://entrepreneurship.hbs.edu/programs/mba/Pages/rock-accelerator.aspx)。

看我們的demo video: https://tella.video/shopify-task-automation-platform-0djt

Shypyard makes it super easy for developers to integrate any system with Shopify and automate mundane tasks so your team can focus on whatever matters most for your business. Never again worry about managing infrastructure, monitoring for crashes, or dealing with API changes. We are started in July of this year so we are still very early as a startup. Currently we're part of Harvard Business School's Rock Accelerator. 

## 團隊簡介
這個產品是今年7月才開始，目前主要是兩位創辦人: [Sam](https://www.linkedin.com/in/sampingchuang/) & [Dan](https://www.linkedin.com/in/li-dan/). Sam是前臉書資深工程師，之後開發了一個[熱門的Shopify套件](http://kiwisizing.com/)。Dan是前Linkden資深產品經理人，目前在讀哈佛MBA. 

## 上班地點
遠端/台北

## 工作內容
Day to day responsibility includes but not limited to..
- Building server endpoints for Shypyard app
- Continuously add new integrations to the platform
- Managing AWS resources
- Involved in core product planning with the founders
- Assist clients on building automation on Shypyard
- Improving the reliability and quality of the overall system

## 能力需求
We are looking for someone who is passionate about problem solving and obsess over code quality. While having experience with all the requirements we listed are ideal, we strongly believe the passion and ability to learn is more valuable than anything else. 

- more than 2 years of software engineer experience 
- Fluent English is a must
- Experience with AWS (cloud formation, s3, lambdas, kinesis, sqs, sns, etc)
- Proficient in Nodejs
- Kubernetes
- API integrations (Oauth2/API/Webhooks)
- Oauth2
- Databases: MySQL, Elastic search, Redis

### 加分
- have experience working with e-commerce related applications
- Many hackathon experiences and are excited about coming up with ideas to solve real life problems.

## 薪資範圍
- 年薪80-120萬。開始以contractor的形式，以2個月試用期開始。

## 工時/特休
- 每週40小時。可彈性調整上班及休息時間
- 每年14天特休
- 每個禮拜會有固定的遠端會議
- 每半年至一年薪資績效考核一次

## 福利/推薦項
- 每個月團隊聚餐
- 每個月1000NT 健身使用補貼

因為公司尚未在台灣設立分公司，故簽約會使用「外國公司的Contractor」的模式。

## 聯絡方式

If you are interested, please email me at sam@shypyard.io and we'll set up some time to chat.  Please include your resume in the email.

**Comment by Rplus** [comment]
可以左轉 https://github.com/nodejs-tw/jobs/issues
