### ISSUE TITLE
[徵才]百睿達新創科技公司誠徵軟體測試工程師（Junior Software QA Engineer）

### ISSUE THREAD

**Issue by ellie5011** [f2etw/jobs#795]
## 團隊簡介
Botrista是來自矽谷的現調飲品新興品牌，專注供應新鮮現作的酒精/無酒精雞尾酒飲品，並結合智慧自動化飲料機器人技術實力，服務全球連鎖餐飲集團以及知名飲料品牌，提供最完整的新鮮飲料調理配套及原物料供應鏈服務。

團隊正積極招募軟體測試工程師，身為軟體測試工程師，您將會協助建立自動化測試流程並參與機台軟體各個階段的實驗測試，確保產品在營運服務時穩定無虞，提供使用者最高品質的產品體驗，歡迎優秀的您一同加入我們的行列！

## 工作內容
1. 負責軟體發佈前測試。
2. 依照產品功能與相關文件撰寫項目列表，建立測試項目及測資。
3. 測試中給予研發部門改善項目及優化項目之回饋。
4. 協助了解業務及應用工程師回報之問題，並優化測試項目。

## 能力需求
1. 一年以上產品測試相關經驗。
2. 擁有以下其中一項Python, JavaScript (Node.js/Vue.js) Unit Test 經驗。
3. 善於設計極端測資。
4. 良好英文讀寫能力。
5. 對於技術問題的研究意願高與學習能力強。
6. 善溝通協調，具良好的分析能力，工作主動積極，解決問題能力佳。

## 薪資福利
NT$45,000~ NT$60,000/ 月

1. 擁有優於勞基法的休假制度及帶薪事假病假。
2. 彈性上下班，彈性的午休時間。
3. 慰勞辛苦的員工，每週一次Happy Hour餐點。
4. 供應零食還有各式飲品。
5. 擁有明亮舒適的空間，有開放式廚房可烹飪亦使用。
6. 提供學習補助，鼓勵同仁進修交流。
7. 有健身器材、桌球桌，可以一同運動同樂。
8. 員工活動春酒、年終尾牙等。

## 聯絡方式
請將您的履歷及優秀的作品集寄到 elliewang@botrista.io, 標題打上[GitHub] 軟體測試工程師＿你的名字

**Comment by Rplus** [comment]
可以去測試社團問問唷~
https://www.facebook.com/groups/1014390405245535

**Comment by ellie5011** [comment]
@Rplus 感謝您的意見！
