### ISSUE TITLE
[徵才] 映瀚科技 誠徵 全端工程師

### ISSUE THREAD

**Issue by Falldog** [f2etw/jobs#80]
關於我們
--------------

我們是一個B2B的SaaS (Software-as-a-Service)新創團隊，成立於2014年底。提供美國進出口貨物承攬公司 (Freight Forwarder & NVOCC)所使用之貨物運輸管理(Freight Management)的SaaS服務，處理客戶包括海空運運輸排程、流程操作、貨物追蹤、電子報關、CRM、會計、物流管理在內的各大功能。簡單來說，就是將傳統產業的流程電子化和網路化，徹底改善使用者體驗以及提高客戶效率，並同時減少人力成本及人為錯誤。未來目標為開發全球供應鏈的SaaS服務平台。

貨物承攬產業的市場目前已經達到每年1600億美元的規模，並持續成長，連Amazon都在今年初宣布投入這個市場!   但是這個產業絕大部分仍然使用古老的科技在進行日常的作業: 訂單大部分使用電話、傳真來下單，使用Excel檔案來更新追蹤再email給客戶等等。我們的目標是帶領這個不太使用科技的傳統產業進入網路的時代，用新創思維來創造傳統產業的高規格產品，替客戶創造獨特的商業模式。

從2014年開始，美國創投已投入超過10億美金進入貨物承攬這個產業，這個金額是之前五年總和的兩倍。這是一個連Paypal創始人Peter Thiel以及Google Ventures都已經投資的產業! 我們的優勢在對美國該產業市場的了解、穩定的客戶和已經上線的產品，加入這個團隊可以讓你擁有替一個廣大的市場打造SaaS產品的機會，運用科技的力量讓這個產業更進步!

目前團隊成員有八位，之前曾服務於台積電、訊連科技、趨勢科技、晨星半導體。我們花了一年多的時間發展出有效率的工作模式以及良好的團隊文化，期待你/妳一起加入我們!

職缺
--------------
  Web Developer / Software Developer
  (包含前後端 == 全端)

必備條件
--------------
  熟 Python或其他web開發程式語言(PHP/.Net/Java, etc.)
  熟 MySQL 或其他關聯式資料庫
  熟悉 Web Framework MVC or MTV 架構
  熟悉 CSS / Javascrip / jQuery
  熟悉 Git or SVN 任一版本控制工具
  熱愛程式設計，喜歡學習新技術與高度重視程式開發品質

加分條件
--------------
  有 Django / Flask / Pyramid 等任一Web Framework開發經驗
  有 AngularJS 開發經驗
  有 RESTful API 開發經驗
  懂 bootstrap
  有 Unit-Test 相關經驗
  有參與 Open Source 開發經驗

可附上github或其他作品

目前公司是以Python Django為主要開發語言，如果只是略懂Python，但是對其他Web Framework有經驗的話，我們也歡迎進來再學習。

非常歡迎各位高手過來談談，讓你們了解我們的理念與執行力，我們想做的不只是一個簡單的Web網站，期待完成第一版後，可以讓我們做出更獨特且走在市場前端的產品出來，所以我們非常要求code的品質、可讀性與架構，在這邊絕對可以學習到很多新東西，如果你也認同我們的理念，請加入我們！

公司福利
--------------
  舒適的高級人體工學椅，讓你coding一秒10行 XD
  良好的工作環境，扁平的組織。
  上班時間彈性，不需要加班給主管看，能有效率處理完公事準時下班最歡迎。
  不定時公司聚餐，慰勞辛苦的大家。
  常常有吃不完的飲料點心，兩台會自動長出膠囊的咖啡機。

薪資範圍
--------------
  NT$ 50,000 ~ NT$ 80,000 + 技術股
需求人數
--------------
  正職 1人

工作地點
--------------
  在台北市松山區，離小巨蛋捷運站約一分鐘，交通方便。

工作時間
--------------
  日班、10:00~19:00 週休二日

應徵方式
--------------
  寄履歷到bruce@hardcoretech.co
  請註明 GitHub - Web Developer徵才

**Comment by Rplus** [comment]
@Falldog 請問是已徵得嗎？

**Comment by Falldog** [comment]
@Rplus 抱歉 忘記comment了
已徵得 
謝謝
