### ISSUE TITLE
[台北] [950k~2m/yr] (遠端) InfuseAI / Frontend Engineer

### ISSUE THREAD

**Issue by catcatcatcat** [f2etw/jobs#801]
## 公司名稱
InfuseAI 工合股份有限公司

## 公司地址
遠端工作

## 公司網站
https://www.infuseai.io/ 
公司產品：加速你的 AI 開發流程： https://www.infuseai.io/primehub 

## 公司介紹
InfuseAI 提供 AI 研發及佈署平台「PrimeHub」，協助企業 10 倍加速 AI 發展進程，解決商務上的挑戰。

PrimeHub 協助團隊在實現 AI、深度學習(Deep Learning)的過程中，共享運算資源、開發環境、研發成果，並且加速模型部署，更快創造價值。透過我們的軟體平台，可以大幅縮短建置時間、降低管理與維護的成本。

InfuseAI 工合股份有限公司成立於 2018 年 6 月，目前台灣人工智慧學校、玉山金控、中央研究院，以及其他知名金融業、製造業、教學醫院、研究機構等等皆採用 PrimeHub 做為加速 AI 發展的平台。

我們的創辦人與夥伴都是長期在 Open Source 與 g0v 社群活躍的夥伴，習慣開放、透明的公司文化，
相信快樂的工作夥伴才有最好的產出，重視工作與生活的平衡。
想更了解我們的工作氣氛，可以上[粉專](https://www.facebook.com/InfuseAI)看小編發的廢文，或是看看上次我們 COO 在台中敏捷社群分享遠距工作經驗的[投影片](https://docsend.com/view/pexhw3uszfjcc3ww)喔

## 職缺與薪資範圍
是以美國舊金山工程師相同職位的薪水為 base 再乘上當地生活物價指數
USD$72K ~ 170K * COL factor (Cost of Living indices based on San Francisco)
(e.g. TWD$950,000 ~ TWD$2,000,000 if based in Taiwan)

## 職務說明
InfuseAI is a remote-friendly company based in Taiwan. Our mission is to fuel the future of AI adoption across industries. Our product PrimeHub is a deep learning platform to streamline AI workflow and supercharge productivity for data scientists.

We are looking for software engineers who are passionate about building productivity tools for ML practitioners.

## 職缺要求
We are looking for both junior and senior:
### Responsibilities:
* Develop features and improvements to the InfuseAI Product in a secure, well-tested, and performant way.
* Develop new user-facing features.
* Write, test, maintain, and document reusable code.
* Participate fully in code reviews and work with internal designers, developers, and QA to ensure quality code.
* Ensure the technical feasibility of UI/UX design.
* Collaborate with other team members and stakeholders.
#### Senior Responsibilities
* Provide mentorship for Junior and Intermediate Engineers on your team to help them grow in their technical responsibilities and remove blockers to their autonomy.
* Working with other developers to design, code, and implement performance and scalable solutions.
* Ensure quality and security.
* Ability to influence others and negotiate the best solutions among many stakeholders.
* Ability to break down and communicate complex issues, ideas, and solutions.
* Establish and track metrics related to key performance objectives and service levels.

### Requirements:

* Computer Science fundamentals in object-oriented design, data structures & algorithm design, and complexity analysis.
* Software development fundamentals, including testing, troubleshooting, and using version control (Git).
* 3+ years of professional development experience with ES6.
* 2+ years of experience in various JavaScript frameworks, such as Node, ReactJS, Vue, and Angular.
* Proficient understanding of web markup, including HTML5, CSS3, integrated Web development using REST, GraphQL and JSON.
* Experience with continuous integration workflows.
* Demonstrated capacity to clearly and concisely communicate about complex technical, architectural, and/or organizational problems and propose thorough iterative solutions.
* Familiarity with Linux.
* Outstanding analytical and problem-solving skills.
* Proficient written and verbal communication skills in English.
* Self-motivated in a fully remote working environment.

#### Nice to Have
* Good understanding of client-side scripting and JavaScript frameworks, including Babel, ReactJS, Ant Design, Webpack.
* Good understanding of server-side scripting and JavaScript frameworks, including GraphQL, apollo, koa.
* Good understanding of Test-driven development, including Unit, Application, and integration testing.
* Good understanding of TypeScript.
* Familiar with and/or have experience with Agile development under the SCRUM methodology.

## 工作福利
- 彈性的工作時間
- 個人零用金津貼
- 全職同仁每年特休 15 天
- 每年全薪病假 14 天
- 健康檢查補助
- 辦公用品補助
- 工作津貼
- 員工旅遊
- 團保
- 研討會門票補助

## 聯絡方式
直接透過連結投遞：http://bit.ly/3cpfQkJ 
如果你覺得你有其他想發揮的長才但沒有列在 job list 上，可以 email 到 apply@InfuseAI.io 聊聊喔～

**Comment by caasi** [comment]
可以不應徵但是幫忙 "provide mentorship for junior engineers" 那塊嗎🙃️😂😂

**Comment by Wizardgreen** [comment]
foc Attachments    This email is delivered by CINNOX
