### ISSUE TITLE
[徵才] Dcard 誠徵 Web Developer (Junior/Senior) 

### ISSUE THREAD

**Issue by brucehsu** [f2etw/jobs#81]
![](https://join.dcard.today/img/logo_joinus_s.png)
## 關於 Dcard
- Dcard 的目標：打造出百萬人關注，影響世代交流、思考，甚至累積知識的社群平台。
- Dcard 的現況：每個月五百萬不重複訪客、雙位數的月成長曲線、數億次文章閱讀。
- Web team 團隊現有成員： github 上有著 8687 stars 專案的大大、多名才氣洋溢的開發者。
## 工作目標
- 在各種裝置上為使用者提供一流的網站體驗
- 設計並打造兼俱效能、彈性的百萬人等級後端系統
- 與一群成長心態、喜歡挑戰並樂於學習新技術的同伴們一起幫助公司及自己成長
## 薪資範圍
- Senior: 60,000 - 100,000，或依經驗與能力面議
- Junior: 40,000 - 60,000，或依經驗能力面議
## 員工福利

![](http://i.imgur.com/6lDf32i.png)
## 必要條件
- 對於學習新技術充滿熱情，並且喜歡與人合作，分享自己的經驗，成為團隊成長的催化劑
- 熟悉 `Node.js`、`Express`、`Koa` 等後端技術
- 熟悉 `React.js`、`AngularJS` 等前端框架
## 加分條件
- 熟悉 `HTML5`、`CSS3`
- 熟悉 `ECMAScript 6` 規範
- 網頁速度最佳化經驗
- 懂得 `Chrome DevTools` 或類似功能的相關工具
- 豐富的 Mobile Web 經驗
- 熟悉 `WebSocket` 運作
- 對 UI/UX 敏感度佳
- Unit Testing 經驗
- DevOps 經驗
- 熟悉 CI, CD 概念
- 熟悉資料庫效能調校
- 樂於參與開源社群

履歷投遞及更多職缺（UI、UX、Android、iOS），請造訪 https://join.dcard.today 。
期待您的來信 :-)

**Comment by Shyam-Chen** [comment]
徵的似乎是全端工程師?
