### ISSUE TITLE
[求才] [台中/西區] 前端工程師 | Front-End Developer |  JavaScript / Html / CSS

### ISSUE THREAD

**Issue by sharlenechou** [f2etw/jobs#834]
![fb cover](https://user-images.githubusercontent.com/83001129/115678610-485d0b80-a384-11eb-9b62-72ceb01c6eb8.jpg)
## 團隊簡介/地點
**【關於緯雲】**
緯雲有限公司成立於2021年，由一群曾在知名遊戲公司的核心人才和技術菁英，帶著對夢想的追求組成，集Fantasy Sports(夢幻體育)遊戲平台研發，以及數據深入分析研究於一體的軟體新創公司。

**【主力產品】**
Fantasy Sports夢幻體育－為近年興起之運動經營遊戲，遊戲內容將讓玩家扮演球隊經理，分析評估球員能力，挑選喜愛的球員組織球隊， 並與全球同好共同競賽。而我們將致力為球迷打造多元、豐富且卓越的平台體驗，讓玩家能更深度投入於所喜愛的運動項目中。

**【加入我們】**
我們重視每一位員工，公司提供具前瞻性的產品開發思維，具競爭力的薪酬、良好的工作環境以及學習成長空間，誠摯歡迎優秀人才加入新創團隊的行列！
## 工作內容

我們正在尋找對於軟體技術領域充滿熱情的前端工程師，歡迎您成為團隊一份子！

• 以 Vue.js 設計與撰寫網頁（含單元測試）
• 串接後端 API
• 公開 Review 同事的程式
• 對現有功能中可改善的設計提出改善意見
• 自動化部署與維護

## 能力需求
• 一年以上軟體開發經驗
• 熟悉 JavaScript 與 CSS
• 有單元測試基礎，例如 Jest
• 有閱讀官方技術文件的能力
• 可獨力解出如 https://leetcode.com/problems/two-sum/ 難度的問題
### 加分
• 使用過 Docker
• 使用過 CI/CD工具，例如Drone、Jenkins
• 讀過 Clean Code 或 Extreme Programming
• https://cantunsee.space/ 7000 分以上
### 專業素養
在快速迭代的過程中，仍然對品質有堅持
專注於客戶的需求，而不只拘泥於符合規格
能獨立思考，而不只是聽命行事或照抄過去的 Solution
面對複雜需求，也能堅持依「簡單原則」設計程式
能自主學習專業技能
## 薪資範圍
月薪NTD 47000~73000元（薪資保障14個月）

## 工時/特休
• 表定為AM10:00~PM18:00，可視個人狀況彈性調整
• 新人到職即享有7天特休假
• 其餘假別均依勞基法規辦理

## 福利/推薦項
**【給力的薪酬制度】**
我們依據公平的原則，提供優於市場的待遇與績效獎金，讓員工除了穩定的收入之外，還能藉由展現個人績效得到更好的回饋。
• 每位員工均保障14個月年薪
• 年終獎金、中秋、端午節獎金
• 視個人表現發給之績效獎金
• 優於勞基法，到職即享有7天特休
• 彈性且人性化的出勤管理

**【貼心的福利措施】**
除法律規定的雇主義務之外，我們更貼心依據員工需求設計：
• 工作日享有免費午餐
• 無限零食、咖啡及飲料暢飲
• 生日禮金
• 年終尾牙餐會
• 定期聚餐及公司活動
• 定期員工健康檢查補助
• 婚、喪、喜、慶補助及急難救助

**【全方位的訓練體系】**
除既有團隊多年累積下來的專案實務經驗與技術，使人才可以站在巨人的肩膀上看世界；並提供相關補助措施，讓員工可於內外部環境及課程中持續學習：
• 各部門年度教育訓練規劃
• 每年三萬元之外部教育訓練學費補助 (另有交通食宿補助)
• 書籍採購補助

**【人性化的管理模式】**
我們提供員工暢通的溝通管道、公平合理的發展空間，讓員工個人的職涯發展與公司的業務目標相互結合，創造出員工與公司的無限可能。

## 聯絡方式
可直接將履歷表寄至：hr@cloud-latitude.com（標題格式：應徵_「前端工程師」_您的姓名）
或至104投遞履歷：tinyurl.com/3773pbty

**Comment by xeriok18600** [comment]
您好請問可接受 部分遠端 的工作模式嗎? 
謝謝

**Comment by sharlenechou** [comment]
您好，我們目前尚無開放遠端工作模式，若您仍對我們的職缺有興趣，歡迎投遞履歷至hr@cloud-latitude.com，謝謝！
