### ISSUE TITLE
[徵才] [台北/大安] 優拓資訊 (Yoctol Info) 前端工程師

### ISSUE THREAD

**Issue by wtflink** [f2etw/jobs#847]
我們需要你不僅僅是個工程師，還要是一個好的聆聽者，永遠將使用者的感受當作第一位，並且有能力將使用者的需求轉化成乾淨且好維護的程式碼。
　
### 【工作內容】
- 評估需求並改善工作流程與效率
- 共同開發高穩定度的系統與服務
- 優化前端效能及使用體驗
- 維護及疊代 Design System

### 【工作地點】
- 台北市大安區信義路二段 74 號 4 樓（近捷運東門站 3 號出口）
　　　
### 【薪資範圍】
- 60K ~ 100K TWD / 月+ 股票選擇權，視經驗與能力而定

### 【在 YOCTOL.AI 的生活】
- 彈性上下班時間
- 每週有 Happy Hour 
- 每月有運動日及聚餐
- 每季有 Outing 及 Team Building
- 零食飲料每月許願，讓你上班吃飽飽
- Remote 工作機制，分工完畢後可以遠端工作
- 特休優於勞基法，每月照比例分配特休時數，到職滿四個月累計三日特休時數、到職滿一年累計十日特休時數
- 技術團隊有每週 Tech Workshop，同時鼓勵大家參加公司內外技術交流活動

### 【技術分享簡報】

最近幾次 tech workshop 的分享簡報
- [esbuild](https://hackmd.io/@B6Kj_5a8QMSCqxeT7yA71Q/Bk3LPbtOO)
- [Web Push Notification](https://hackmd.io/@B6Kj_5a8QMSCqxeT7yA71Q/HyjOvWtO_)
- [Revisit data sources & data loader](https://hackmd.io/@B6Kj_5a8QMSCqxeT7yA71Q/rkzWLmpHd)

#### 【需求條件】
- 熟悉 JavaScript、CSS 與 HTML
- 熟悉 TypeScript
- 熟悉 React.js
- 熟悉 React Hooks 並能撰寫 Custom Hooks
- 對 GraphQL 有基本的瞭解
- 熟悉 Git / GitHub 操作
- 良好的測試習慣
- 良好的溝通技巧

#### 【如果有這些更好】
- 熟悉 RESTful API
- 熟悉 Next.js 及 SSR 運作原理
- 熟悉 Apollo GraphQL 以及其 Ecosystem
- 熟悉 Babel 與 Webpack
- 使用 Jest 及 React Testing Library 的相關經驗
- 能夠解決跨瀏覽器的使用體驗
- 善用 DevTools 調校效能
- 擁抱 Open Source 精神
- 對 UI 與 UX 有所堅持
- 喜歡學習，交流新事物

#### 【第一階段】
- 面試第一階段主要專注在專業技術上，由工程團隊成員參與共同面試
- 首先請您介紹自己，我們也會自我介紹，也簡單介紹公司狀況
- 技術的考評主要是就履歷或未來工作上相關的技術問題作簡單問答
- 可以利用你習慣的方式協助表達：紙筆、白板、電腦投影等等
- 過程中有任何不清楚或是需求釐清都非常歡迎提問
- 最後也請您對公司或是未來的工作提問，減少資訊不對稱
- 我們討厭未知的等待，也尊重彼此的時間，第一階段面試結束之後約一兩周內會盡快送出後續通知

#### 【第二階段】
- 通過第一階段之後，會再與公司 CEO 和產品經理分別面談
- 這個階段專注在檢視人格特質、工作態度、合作流程、企業文化等等雙方期待是否一致
- 薪資及福利待遇也會在這個階段進行討論，歡迎提出你所期待的待遇
- 這也是面試的最後一關，同樣會在兩週內發出正式的 offer

### 【產品開發流程細節】

- 可以自由選擇遠端工作或是進辦公室工作，也會隨著疫情狀況調整開會形式
- 利用 Jira 跑為期兩週的 sprint，sprint 間每日自主列出工作項目供團隊成員同步，增加效率
- sprint 中間有一個例會了解大家工作狀況和同步團隊成員進度，有需要幫助或來不及做完原定 ticket 也可以尋求援助
- 團隊小而快速，常有機會直接與設計或 PM 溝通調整

### 【技術開發流程】

- 公司專案版本控制使用 GitHub 來管理，使用 Slack 來做溝通，採用 Git flow / GitHub flow
- 發 Pull Request 請 assign 適當人選進行 review，approve 後即可 merge，維護程式品質是團隊成員的共同責任
- 在開發中遇到問題可以向其他同事尋求協助，也可以發起文字或口頭甚至是會議形式的討論，以便資訊流通、團隊合作順暢
- 系統架設在 Azure 上使用 Kubernetes 來管理容器，以微服務架構組成我們的 SaaS 服務，透過 CI/CD 加速部署、確保系統穩定

### 【聯絡方式】

將您的履歷，及任何能讓我們眼睛為之一亮的資料，寄至 jobs@yoctol.com
（※ 別忘了在信件標題註明申請前端工程師！）

**Comment by lu7766lu7766** [comment]
想請教關於Remote 工作機制，所以分工還是必須到現場分工嗎?還是也可以遠端完成?

**Comment by wtflink** [comment]
目前由於台灣疫情嚴重，團隊都是全遠端狀態，所以分工可以透過遠端達成；不過，常態下工作分配是每週三在公司開會，還有週五下午的 tech workshop 也是線下活動，我相信人與人的連結還是相當重要的。
