### ISSUE TITLE
【徵才 | 在家工作】 iHerb 資深前端/後端工程師(年薪100萬-200萬) | Frontend/Backend Developer(Middle/Senior) 

### ISSUE THREAD

**Issue by GabyChen0617** [f2etw/jobs#864]
## 團隊簡介/地點
美國知名iHerb保健食品網購平台要在台灣建立開發團隊囉，需求人數持續增加中!!!
擁有超過1,500個品牌、30,000項產品到全球150個國家
平台系統皆由內部開發人員開發，擁有厚實的開發資源與環境
歡迎想要更多發展空間的你!

## 工作內容

- 進行軟體分析、代碼分析、需求分析、軟體評審、代碼度量識別、系統風險分析，以及軟體可靠性分析
- 專案規劃與專案管理，團隊合作順暢同時可獨立完成工作任務
- 物件導向設計與分析 (OOA和OOD)
- 軟體性能調整、改進、平衡、可使用性、再使用性以及自動化

※前端
1. 參與整個週期的應用開發，需要與產品經理、專案經理和後端程式開發員密切合作，共同開發公司產品(iHerb.com)
2. 使用如ReactJS、Typescript和ES2016+等技術，在Kubernetes或Docker的環境中工作

※後端
1. 使用新技術如React Docker/Kubernetes，以及NET Core 微服務技術，同時還使用雲技術將流程自動化，為公司不斷增加的客戶提供支援

## 能力需求

※前端
1. 需要有3年以上的前端開發經驗
2. 熟悉掌握 React.JS / RESTful API 且有實際專案經驗
3. 了解 TypeScript 並有使用經驗
4. 了解 HTML5 / CSS3 / Javascript (ES5/6/7)
5. 具有 Git 經驗

※後端
1. 需要有3年以上的後端開發經驗
2. 熟悉C# 或 .Net 
3. 了解前端React加分

### 加分

※前端
1. 熟悉ReactJS以外的前端框架如 Vue.JS 或 AngularJS
2. 有後端開發或UI/UX經驗者加分

※後端
1. 了解前端React加分

## 薪資範圍
1. 依能力核薪，有紮實全端經驗者/電商開發經驗者/管理經驗者待優
2. 年薪100至200萬元，12個月發放

## 工時/特休
1. 一週40個小時
2. 視工作sync的團隊所在地(上海或加州)彈性調整上班時間

## 福利/推薦項
1. 年假15天
2. 到職即配一台 16吋 Macbook Pro
3. 遠端工作模式，可在家工作，節省交通時間，或使用共享辦公室WeWork的空間與資源
4. 美商人性化管理、工作表現與生活並重的企業文化
5. 勞保、健保、退休金提撥

## 聯絡方式
歡迎透過填寫表單上傳履歷 :  https://forms.gle/C9nNrbEtoz4taVqE9
關於iHerb徵才的任何問題，歡迎與我們聯繫 (主旨請註明《iHerb徵才》)，我們將於一個工作天內回覆!
聯絡信箱 :  gabriella.chen@manpowergrc.tw

**Comment by timoyan** [comment]
@Rplus 
Hi Rplus, I am Timo in iHerb Taiwan. 
Could you close this issue since it was created by hunter agency but iherb is not in cooperation with the agency anymore. 
Thanks!!

Here is my linkedin profile to prove my ID
https://www.linkedin.com/in/timo-yan-07750b77/
