### ISSUE TITLE
[徵才][遠端工作] iHerb Mid / Senior Frontend Developer (十二個月發放 , 年薪 TWD 1M ~ 2M)

### ISSUE THREAD

**Issue by timoyan** [f2etw/jobs#869]
## **公司介紹**

iHerb 創立於 1996年, 總部位於美國加州 Pasadena 和 Irvine, 是全世界最大的保健食品跨境電商平台.

[https://tw.iherb.com/](https://tw.iherb.com/)

2021 年開始積極的在台灣尋找優秀的人才, 預計會在 2022年6月成立台灣分公司.

## **在 iHerb 你會有**

- 優於市場水準的行情, 按十二個月發放 , 年薪 TWD 1M ~ 2M
- 全額的勞健保
- 15天年假
- Work & Life Balance
- 自由選擇在台灣的工作地點
- 彈性工作時間, 依團隊情況調整
- 可申請學習經費
- 一年一次的 performance review 以及薪資調整機會
- 每個月實體聚餐活動

## **工作模式**

- 分公司成立之前, 會以 Contractor 合約附屬在台灣合作的 Agency
- 全遠端, 可到 [台北WeWork](https://www.wework.com/zh-TW/l/office-space/taipei--TPE) (09:00 ~ 18:00)
- 公司提供 Notebook, 16吋 Macbook Pro

## **工作內容**

- 依業務需求進行分析以及實現
- 協助設計師完成 UI 技術評估
- 參與 Peer Code Review
- 技術調研以及落地
- 協助並指導 junior 同事完成任務

## **基本條件**

- 3年以上的 F2E 經驗
- 近 1 年有 React Application 開發經驗但不包括 個人 Side Project 或 Campaign Site
- 熟悉 HTML5, CSS, JavaScript
- 熟悉 React
- 熟悉 Redux 及相關 Libraries, 如 Redux-Observable, Redux-Thunk
- 熟悉 CSS in JS 相關 Libraries, 如 Glamor, Emotion, Styled Components
- 熟悉 Unit Test 相關 Libraries, 如 React Testing Library, React Hooks Testing Library
- 熟悉 TypeScript
- 熟悉 RESTful API 風格的架構
- 了解 Webpack 以及常用的參數配置
- 熟悉 Git 版本管理
- 熟悉敏捷開發模式
- 良好的英文讀寫能力

## **加分條件**

- React SSR 的使用經驗
- 中大型系統 React Application 開發經驗
- 0 到 1 搭建 Scaffolding Project 的經驗
- CI / CD 使用經驗
- K8S & Docker 的經驗, 可以做到基本的服務狀態排查
- E-Commerce System 開發經驗
- Web Performance Tuning 經驗
- GraphQL 相關經驗, 如 Apollo, Relay
- E2E Testing Framework 相關經驗, 如 Selenium, Cypress
- Web 監控經驗, 如 Datadog RUM, LogRocket, Sentry, NewRelic
- 後端開發 及 資料庫 相關經驗
- 樂於嘗試新技術
- 良好的英文聽說能力

如果你有意願, 歡迎投遞履歷 到 timo.yan@iherb.com

郵件標題格式為 APPLY-TW-F2E-中文名字, 例: APPLY-TW-F2E-王大明

##

**Comment by satsuya0114** [comment]
iHerb在台灣並無創另公司，所以這個職位是約聘職 (名義上雇主並非iHerb)，對嗎？

**Comment by timoyan** [comment]
> iHerb在台灣並無創另公司，所以這個職位是約聘職 (名義上雇主並非iHerb)，對嗎？

Yes, `2021 年開始積極的在台灣尋找優秀的人才, 預計會在 2022年6月成立台灣分公司.`

So far iHerb do not establish official branch office yet in Taiwan.

**Comment by timoyan** [comment]
Closed due to no headcount.
