### ISSUE TITLE
【徵才】大千雲端事業股份有限公司 - Front-end Engineer ( 台中 / Junior / Senior )

### ISSUE THREAD

**Issue by osakihsieh** [f2etw/jobs#87]
## 公司簡介

新創公司，致力開發良好使用者經驗的客服系統
## 工作地點

台中
## 薪資範圍

Junior : 40000 以上 ( base on 13 Month )，或依經歷及實力論薪
Senior : 50000 以上 ( base on 13 Month )，或依經歷及實力論薪
## 工作時間

09:00 ~ 18:00 彈性工時
## 休假
- 依照人事行政局發布行事曆休假
- 遇到彈性休假不需補班
- 特休依照勞基法規定
## 公司福利
- 員工午餐
- 年終獎金
## 職缺職務內容
- Isomorphic web application framework
- UI Implementation
- 開發可重複使用的前端程式系統
- 依據產品規格、設計與計畫，開發 Web 前端使用者介面或原型
- 研究跨平台的 RWD 前端解決方案
## 技能需求
- 瞭解 UI / UX 設計概念，能與 UI 設計師良好溝通
- 熟悉 Html / CSS
- 熟悉 SCSS、Compass
- 擁有 JavaScript、GraphQL、Angular.js / React.js 的專業知識，懂 React flux 架構。
- 瞭解跨平台程式開發流程
- 良好的程式寫作習慣
- 熟悉 Git，有自己的 Github
## 加分項目
- 用過 CoffeeScript 或 TypeScript
- 瞭解 C#
- 熟悉前端測試工具
- 瞭解 Scrum 流程
- 有過Node.js開發經驗者佳
- 有過Flux架構開發專案經驗者尤佳

**Comment by Rplus** [comment]
應徵方式麻煩再補一下唷~

**Comment by osakihsieh** [comment]
@Rplus 已補上，感謝提醒 :smile:
