### ISSUE TITLE
【台北｜中山區】奧特技術－JAVA軟體工程師 (年薪80萬～180萬) 

### ISSUE THREAD

**Issue by st9360606** [f2etw/jobs#890]
## 團隊簡介/地點
奧特技術秉持「服務」的宗旨，為打造未來金融服務，投入區塊鏈技術研發，具有降低成本與提升效率的潛力，重塑商業流程，加強資安技術，以多樣化金融科技運用、數位行銷應用、多元支付整合導入，透過雲端大數據的分析，以科技實現更美好的金融交易體驗。

## 工作內容
1.依據專案需求進行系統架構設計與功能規劃
2.與前端/APP工程師配合，負責後端API開發與維護
3.後台系統功能開發、維護
4.系統執行效率及客戶體驗優化
5.代碼品質控管
6.線上問題解決
7.開發環境伺服器搭建與維護

## 能力需求
1.大學以上學歷，資訊管理或資訊工程相關科系畢業
2.2年以上Java開發經驗
3.曾使用過Spring, Mybatis , Maven, 當前主流框架；
4.進行代碼編寫及系統異常化解經驗；
5.有經驗使用MySQL, Oracle SQL指令
6.有經驗使用Git / Git Flow版本控制工具
7.具備良好的溝通能力與團隊合作精神
8.對工作積極主動，能有條理的完成工作任務
9.邏輯思考能力強且具解決問題的獨立思考能力
10.具備正面且專業的態度及強烈的責任心

### 加分
優先條件：
1.知道開發主要使用技術 Spring Mybatis Boot Redis 經驗
2.知道後台系統開發用Free Marker一種Template Engine經驗
3.有RESTful API 經驗

加分條件：
1.有spring boot經驗
2.有Oracle DB 經驗

## 薪資範圍
年薪80~180萬 （視能力調整） ＋ 保障14個月

## 工時/特休
10:00~19:00 (中間休息1hr) 週休二日、首年10天特休

## 福利/推薦項
【具競爭力薪資】
＊保障年薪14個月 ，薪資優於市場水平
＊員工保險制度，足額勞保、健保、勞退、公司團保
＊優於現行法規的休假制度(首年10天特休,依在職比例計算)

【津貼獎金】
＊三節禮金(中秋、端午、生日) ＊婚喪喜慶禮金 ＊人才推薦獎金 ＊伙食交通津貼

【福利活動】
＊員工年度旅遊/旅遊金補助 ＊員工年度健檢
＊不定期各類活動自由參與、社團&部門活動補助、員工餐敘、年終尾牙餐會..等
＊能量補充點心下午茶

## 聯絡方式
104 :https://www.104.com.tw/company/1a2x6blnft

履歷寄至：kurt@uttech.com.tw

**Comment by Rplus** [comment]
same with #889
