### ISSUE TITLE
【徵才】DingTaxi - React Engineer

### ISSUE THREAD

**Issue by yutin1987** [f2etw/jobs#90]
DingTaxi叮叮包車: 全球包車旅遊, 機場接送, 一日遊線上預訂
https://www.dingtaxi.com/

尋求react工作夥伴, 所需技能 React

履歷：請提交 github 有關 react 的 repository.
年薪：66～96萬
休假：見紅就放外, 特休7天, 其實沒有很嚴謹的休假制度, 有事告知就好. 工作愉快最重要.
風格：覺得對的事情就去做, 提milestones然後就go, 跑kanban. 解決問題最重要, 用什麼語言/方法不重要.

Email：yuting1987@gmail.com

**Comment by Rplus** [comment]
是不是 remote 的啊？

**Comment by yutin1987** [comment]
想 remote 也可. 但應該要先習慣如何網上協作

**Comment by yutin1987** [comment]
已找到
