### ISSUE TITLE
【臺北 / 遠端】方格子 vocus - 前端工程師 (React)

### ISSUE THREAD

**Issue by kusakawazeusu** [f2etw/jobs#901]
方格子近期釋出**前端工程師**的職缺，如果各位對於內容平台的前端開發有興趣，歡迎投遞您的履歷到我們的公司徵才信箱（joinus@vocus.cc），以下是工作詳細內容：

### 薪資、福利與工作地點
**薪資範圍：**
800K ~ 1.2M TWD / 年

**工作地點：**
目前採全遠端協作模式，實體公司在中藥香香的迪化街！

**公司福利：**
- 彈性上班時間，9-10 點自主管理
- 每年享有 15 天的特休假
- 女性同仁每月生理假 1 天
- 內部不定期教育訓練、進修補助
- 不定期聚餐
　　
### 關於方格子
我們相信，內容的力量是無遠弗屆的。vocus 致力於幫助創作者實踐夢想。無論是被看見的機會、或是合理的報酬。我們期望能夠持續幫助創作者創造價值，讓更多不同的思想在此激盪、交流。

更詳細的公司文化，[讓我把麥克風遞給文筆很好的老闆](https://vocus.cc/article/5f990d39fd89780001b94981) 👇

### 工作內容
- 負責開發 vocus 前端功能，提供流暢且豐富的服務體驗
- 撰寫易維護、高可讀性的程式碼，並參與工程團隊的 Code Review
- 以前端專業和 PM、同仁討論新功能開發方向，並評估可行性
- 與 UI/UX 設計師合作開發適用於主流平台的前端頁面
- 前端頁面的效能、Accessibility、Web Vitals 調校
- 全站 SEO 調校，體驗火箭升空般的曝光數字
- 與工程團隊一同優化系統架構與開發流程（監控、報錯、Issue Tracking ⋯⋯）
- 與後端工程師協作開發 DAPP 相關功能

### 希望你具備 ⋯⋯
- 熟悉 JavaScript、ReactJS、Redux、NextJS
- CSS Framework：SASS、styled components
- 有獨立切版能力、開發適用主流平台的 RWD 頁面
- 熟悉前端測試架構如 Jest、Mocha，或是 cypress
- 熟悉 Git 的操作與 GitFlow 流程
- 能夠透過 Swagger 文件串接後端 API

**擁有這些會很加分：**
- 熟悉 CI/CD 建置流程
- 擁有 SEO 調校經驗
- 能用 CSS 做出簡單的動畫效果
- 擁有組織大型專案結構的技巧及經驗
- 能夠調校、最佳化前端程式效能
- 具備或了解後端程式運作且有開發經驗
- 樂於研究、學習與分享，樂於面對挑戰、具抗壓性、企圖心強
- 擁有主動提出並解決問題的能力
- 過往工作經驗或作品與內容產業相關

**另外：**
平常前端會針對近期開發的新功能進行站內大內宣，我們會撰寫[工程獅開發誌](https://vocus.cc/user/@rdlion)，來紀錄平台的開發的勵志故事。

### 更多詳細說明，歡迎來這裡
請將履歷及作品集寄至：joinus@vocus.cc（主旨請附上申請職稱與姓名）
[深入了解方格子的公司文化與福利](https://vocus.cc/recruiti/home?articleId=5f990d39fd89780001b94981&nav=60880852fd89780001317f5e&fbclid=IwAR1ngR2I2dA-JfSYVrHt4FQWIoxZ9IbnfGpIALKpYNESD48W5cp_IBBZGPg)
[方格子工程師開發誌](https://vocus.cc/user/@rdlion)

**Comment by kusakawazeusu** [comment]
大家好，方格子再次徵才，JD 也有調整，歡迎大家參考，謝謝！

**Comment by Rplus** [comment]
或許你可以考慮關掉舊的
重開一篇新的~

**Comment by kusakawazeusu** [comment]
好 ～ 謝謝
