### ISSUE TITLE
【徵才】痞客邦 PIXNET - 前端工程師

### ISSUE THREAD

**Issue by afutseng** [f2etw/jobs#92]
![PIXNET Logo](https://pixnethackathon2015.events.pixnet.net/img/co-pixnet.png)

# 公司名稱
PIXNET DIGITAL MEDIA (痞客邦)
https://www.pixnet.net/

# 公司介紹
「痞客邦 PIXNET」為台灣社群第一品牌，匯聚全台最多原創內容，儼然已是全民生活的資料庫平台。藉由長期觀察多樣化內容，深度了解社群行為面貌後，於2012年憑藉創新技術，開發全新社群媒體平台 7Headlines，並延伸 7Headlines 語意分析技術，將雲端海量資料分析（Big Data）導入社群服務，於2014年成就全新口碑行銷數據系統【PIXinsight】聚合轉化社群口碑影響力！

身為台灣網路產業第一領導品牌，「痞客邦 PIXNET」掮負著本土網路業界領導者的使命，痞客邦相信創作是不會停止的，痞客邦 PIXNET 長期的提供創造更好更多贏的創作環境！向下紮根網路未來發展的基石，期盼帶領台灣網路的優質服務走向海外，成為台灣的數位之窗！

# 日常工作內容
- 開發與維護痞客邦 PIXNET 產品，您的研發成果可讓每日 770 萬名不重複訪客體驗
- HTML5 / CSS3 Layout / Performance tuning
- jQuery/AngularJS/React.js/Node.js 應用程式開發維護
- 與前端組同事共同引入新技術或工具，持續改良工作流程跟產品
- 鼓勵員工學習，會定期舉辦技術分享會，歡迎對技術學習有熱情的朋友加入

# 基本要求

- 二年以上網站前端工作經驗，可獨立作業。
- 熟悉 HTML/CSS/JavaScript
- 熟悉任一前端框架（AngularJS, React.js etc.)
- 具備 Bootstrap/jQuery 使用經驗
- 具備 RESTful API 介接經驗
- 具備 Git / SVN 版本控制系統使用經驗

# 加分項目

- 具備跨瀏覽器相容性開發能力
- 具備 Responsive Web Design 網站製作經驗
- 具備 Sass/SCSS/PostCSS 開發經驗
- 具備前端效能調校經驗 (RAIL model, DevTools, etc.)
- 暸解 Web Security
- 具備任何一種後端語言開發經驗 (PHP/Node.js/Python/Golang 等，PHP 尤佳)

# 薪資獎金

- 月薪 NTD $50,000 ~ $75,000 
- 績效獎金依每年兩次績效考核發放

# 休假
- 試用期滿即享有特休年假 12 天，逐年遞增一天
- 半薪病假

# 公司福利
- 員工旅遊 (2014-上海杭州、2015-馬來西亞、2016-越南)
- 國內外技術研討會門票、機票住宿補助
- 三節獎金
- 旅遊暨健康檢查補助
- 每週三免費下午茶點心
- 威秀電影票優惠
- 城邦集團旗下出版刊物優惠

# 需求人數
2 人

# 工作設備
- 任選 iMac 27" / Macbook Pro / Macbook Air / Ubuntu Desktop / Windows 電腦
- DELL 可直立旋轉螢幕 22" x 1

# 工作時間
09:00 - 18:00

# 工作地點
台北市中山區民生東路二段 149 號 3 樓
行天宮捷運站 1 號出口左轉步行約 300 公尺

# 應徵方式
請將履歷與作品集寄到 techjob AT pixnet.tw，並附上常用的網路服務帳號 (GitHub/Twitter/LinkedIn/SlideShare/Speaker Deck, etc)

**Comment by goden** [comment]
請問是否已經徵到人了！

**Comment by afutseng** [comment]
@goden 
您好，尚未徵到～

**Comment by lincecumHao** [comment]
好夢幻 想去 XD

**Comment by afutseng** [comment]
謝謝大家，已經完成招募，未來有新的員額會再張貼職缺。
