### ISSUE TITLE
[全遠端][百萬年薪][❤️ 開源] InfuseAI 尋找前端夥伴

### ISSUE THREAD

**Issue by catcatcatcat** [f2etw/jobs#950]
嗨，前端社群夥伴大家好～歡迎大家有興趣直接透過系統投遞履歷，或者是把資訊分享給你們的朋友唷！

### 公司名稱
InfuseAI 工合股份有限公司

### 公司地址
遠端工作

### 公司網站
https://www.infuseai.io/
公司產品：[PipeRider](https://www.piperider.io/)

### 公司介紹
We build MLOps tools to streamline ML workflows for the entire organization

我們的創辦人與夥伴都是長期在 Open Source 與 g0v 社群活躍的夥伴，習慣開放、透明的公司文化，
相信快樂的工作夥伴才有最好的產出，重視工作與生活的平衡。
想更了解我們的工作氣氛，可以上[粉專](https://www.facebook.com/InfuseAI)看小編發的廢文，或是看看上次我們 COO 在台中敏捷社群分享遠距工作經驗的[投影片](https://docsend.com/view/pexhw3uszfjcc3ww)喔

### 職缺與薪資範圍
TWD$1,260,000 ~ TWD$1,764,000 if based in Taiwan 

### 職務說明
InfuseAI is on a mission to revolutionize how AI is built and operated. We are the team behind PrimeHub, the open-source pluggable MLOps platform that allows data scientists to work more effectively with the tools they already use while adopting new data and model tools.

We are looking for software engineers with frontend application development expertise who are passionate about building state of art productivity solutions for machine learning practitioners. You will dive in at any level of depth in the web stack, and help to make it happen.

This position is 100% remote.

### 職缺要求
**Responsibilities:**

- Write, test, maintain, and document reusable code.
- Develop new user-facing features and improvements.
- Ensure the technical feasibility of UI/UX design.
- Participate fully in code reviews and work with internal designers, developers, and QA to ensure quality code.
- Collaborate closely with other developers to contribute to the InfuseAI products in a secure, well-tested, and performant way.

**Requirements**

- 3+ years of experience in web application development.
- Computer Science fundamentals in object-oriented design, data structures & algorithm design, and complexity analysis.
- Proficient in one of any popular web framework (Vue, Angular, React, Emotion, antd, chakra-ui, etc.).
- Proficient in modern frontend application architecture.
- Strong experience in web security and performance best practices.
- Excellent understanding of web markup, including HTML5, CSS3, integrated Web development using RESTful or GraphQL with JSON structured data.
- Working in a Unix environment.
- Working knowledge with one of any CI/CD solution (GitHub, GitLab, or CircleCI preferred).
- Intermediate level of written and spoken in English.
- Self-motivated in a fully remote working environment.

- Extra points for

- Familiarity with TypeScript.
- Experience in machine learning, productivity, or B2B application development in commercial products.
- Full-stack engineering experience in Python, JavaScript, or Go.
- Familiar with and/or have experience with Agile development under the SCRUM methodology.

### 工作福利
彈性的工作時間
全職同仁每年特休 15 天
每年全薪病假 14 天
健康檢查補助
辦公用品補助
員工旅遊
團保
研討會門票補助

### 聯絡方式
直接透過連結投遞：https://jobs.infuseai.io/o/frontend-engineer-2
對職缺有任何問題可以透過 comment 詢問 ^^

**Comment by regchiu** [comment]
要時常用英語溝通嗎?

**Comment by catcatcatcat** [comment]
要的唷，我們有國外的同事，文件跟開會會用英文~但可以溝通即可

**Comment by sharils** [comment]
Hi @catcatcatcat - Is this still open?

**Comment by cshif** [comment]
@catcatcatcat want to know is this still available, too! Thx!

**Comment by catcatcatcat** [comment]
Sorry, I forgot to close it. It's not available now. Thank you for asking.
