### ISSUE TITLE
[徵才] commandp Inc. - 前端工程師(Junior / Senior)

### ISSUE THREAD

**Issue by gogojimmy** [f2etw/jobs#96]
職缺名稱：前端工程師 Software Engineer（Frontend）
公司名稱：我印網路科技股份有限公司
公司網站：https://commandp.com
工作地點：台北市南京東路五段 16 號
薪資(Junior)：TWD: 35,000 ~ 60,000 月，14 個月
薪資(Senior)：TWD: 60,000 ~ 100,000 月，14 個月
休假：週休二日以及國定假日，其餘假日比照勞基法規定

## 關於 commandp:

我印網路科技 commandp Inc. 結合傳統的數位印刷與最新的網路技術，為一跨國定制化移動電商平台，讓冰冷的數位影像可以輕鬆並且快捷的將為有溫度的實體產品。目前正積極拓展台灣、日本與中國三大市場，國際化視野，真正走出台灣的網路公司。

2014 年 11 月，正式與日本 Capsule Inc. 達成獨家合作。為 commandp Inc. 深耕日本市場。
2014 年 12 月，成立 commandp Inc. Samoa，作為全球運營總部。
2015 年 1 月正式成立上海分公司，登記名稱為优印（上海）信息科技有限公司。座落於漕河涇軟件開發園區。
2015 年 4 月獲得中國 A 股上市公司千萬人民幣投資，進行中國市場佈局與開發。

## Junior 前端工程師職缺內容及要求

**職缺要求：**

1. 1 年以上的前端開發經驗(PC / Mobile )，了解基本的 HTML/CSS/Javascript. 
2. 至少使用過 jQuery, 可以依循文件來打造自己需要的效果。
3. 有使用過任何的 CSS Grid System 例如 Bootstrap / 960, 如果自己做過更好。
4. 強烈的學習動力，你需要在完成工作項目的過程中學習很多東西。

**職缺內容：**

1. 依照 UI 設計要求，使用 React JS 打造 Pixel-perfect 的手機端的 React Native 界面，以及網站端各種 campaign 頁面。
2. 與 Senior 工程師配合，學習現代化開發技巧，打造高可用性的 UI Component.

## Senior 前端工程師職缺內容及要求

**職缺內容：**

1. 依照產品規格要求打造前端工程化架構，針對不同平台體驗來設計高可用且彈性的框架。
2. 與設計 / UI / PM 團隊在工程角度持續溝通使用者體驗的精進。
3. 與成員一同制定前端團隊工作流程，從開發到部署到監控的持續精進。

**職缺要求：**

1. 精通各種前端技術，除了基本的 HTML, CSS 之外，希望你也玩過 Gulp, Grunt, Webpack, CoffeeScript, SASS 等熱門工具。
2. 具備跨終端的開發能力，在 Web (PC+Mobile) / Nodejs / React Native App 三個方向上至少精通一個方向，具備多者更佳，鼓勵在 Native 和 Web 技術融合上的探索。
3. 對前端工程化開發有一定了解並有開發經驗，至少使用過兩種以上的前端現代化框架，例如 Flux / Redux / Backbone / Angular 類。
4. 強悍的 Javascript 技能，了解 Javascript 的各類開發觀念，例如 Promise, Reactive Programming.
5. 良好的團隊溝通能力，因為我們是個團隊。

應徵方式：歡迎來信至 jobs@commandp.com, 附上你的 CV 以及過去作品。

**Comment by goden** [comment]
請問有徵到人了嗎?

**Comment by gogojimmy** [comment]
@goden 我們還在徵人哦！歡迎隨時寄履歷來~

**Comment by demiurga** [comment]
請問接受remote work嗎?

**Comment by fredchen90** [comment]
@gogojimmy 請問徵到人了嗎?

**Comment by jf423** [comment]
請問還有junior職缺嗎？

**Comment by gogojimmy** [comment]
已經找到人嘍，暫時關閉職缺

**Comment by Rplus** [comment]
恭喜~
