### ISSUE TITLE
[徵才] Carousell 旋轉拍賣 - 前端工程師 

### ISSUE THREAD

**Issue by Carousellhr** [f2etw/jobs#992]
## 關於公司

**Carousell 旋轉拍賣**是讓網路買賣跟拍照聊天一樣簡單的手機 app。目前已拓展至亞洲的 8 個市場，擁有超過千萬使用者、超過2.5億的上架商品，是全球最大且成長最快速的社群拍賣平台之一。去年我們拿到一筆新的資金，目前估值11億美元，已經成為獨角獸公司！🎉（詳細資訊請參考[此連結](https://pse.is/3rf2q3)）

Carousell 的技術團隊是**global feature team**編制，在台灣/新加坡/印度三個國家的開發團隊都是負責全區域的功能/產品開發。我們的產品每月為數千萬活躍用戶提供服務，所以在Carousell的台灣團隊，你一樣有機會接觸大型架構的服務開發！

## 關於團隊 
而這個職缺會加入我們的**Buyer Experience Team**， BX Team的使命是協助買家輕鬆找到他們想買的商品，並且順利的完成交易。只要是買家「逛街」時會經歷過的地方，從首頁 (Home Screen)、分類瀏覽 (Category Browse)、地點篩選 (Location filter)、搜尋條件 (Search Filter)、商品卡片(Listing Card) 到商品頁面 (Listing Page)，都是這個團隊負責的領域。

## 工作地點/ Location
我們的辦公室在捷運中山站附近，同時我們也提供彈性遠距工作型態選擇，想待在家工作ok，想進辦公室也很歡迎！

## 工作內容 
Homescreen, Search Browsing, Location Filters and Listing Details Page are critical parts of various user journeys in Carousell, and we are building the next generation technology to power our business.

We are always improving our buyer platform that powers most of these flows and our challenge is that it needs to cater to tens of millions of users and billions of listings. Isn't it exciting? Become part of this growing team and have a phenomenal impact by helping users easily find what they are looking for and engage and retain users by making content browsing on Carousell a habit. You can breathe the innovation and excitement of a startup, working alongside some of the most talented engineers!

How can you participate? We're looking for a talented backend engineer willing to make a huge impact in a fast growing company, leader in SouthEast Asia. Come and join our Engineering Team based in TW!

**You Will:**

- Work closely with the product and design teams across multiple locations to build exciting and innovative features for the Carousell web platform
- Build high-performance, dynamic web applications and platform technologies
- Take full ownership of projects from design, to implementation, and deployment
- Write clean, testable and maintainable code
- Participate in design discussions and code reviews to evolve Carousell’s web platform and maintain a high-quality code culture

## 能力需求

**You Have:**
- User obsession and empathy.
- Drive and resourcefulness to persevere and overcome obstacles achieving challenging goals.
- Focus on impact and results. You work on the right things and get them done.
- High integrity and ability to positively collaborate with others
- 2+ years of experience building production-level, modern web apps
- Strong command of JavaScript and associated technologies (ES6+, Node, etc.)
- Experience with modern web technologies and reactive frameworks like React, Angular or Vue
- In-depth knowledge of web frontend, including the DOM, browser APIs, modern CSS, responsive/mobile web, and components
- Proven ability to ship beautiful, stable and high-performance desktop and mobile web applications from start to finish

**Nice To Have:**
- Degree in Computer Science, Software Engineering, or equivalent
- Built and shipped production- level web apps using Express, React, Redux and Webpack
- Experience with multi-language, multi-country, and multi-currency web apps

## 薪資範圍
年薪: 1.2M至1.8M，依經驗及能力討論。另有員工股票選擇權。

## 除了基本的福利外我們還提供...  

- 配備全新 MacBook Pro & 辦公室有一個外接顯示器
- 彈性remote，想待在家工作ok，想進辦公室也很歡迎！(捷運中山站附近)
- 年假14天起跳，另有15天全薪病假＆1 天生日假，針對育嬰/產假/照顧假也有完善的規劃
- 身心健康定額補助，健身房、心理健康相關費用公司來出！
- LinkedIn Learning帳號公司幫你買好了，讓你隨時可以自主進修
- 每月一天沒有會議、訊息的Blue Sky Friday，讓你專注在自己的工作上，也可以趁機清年假！
- 電話費補助、每年一次健康檢查
- 辦公室提供健康零食、咖啡、飲料
- 每月一次 Together Thursday 提供免費午餐，同時會由新加坡總部進行全球同步連線，分享最新動態

## 應徵方式 / How to apply
請準備英文履歷至Carousell官網投遞 - [職缺連結](https://careers.carousell.com/job-posting/?gh_jid=3731901)

**Comment by domark0721** [comment]
請問職缺是不是已經關了？

**Comment by sharils** [comment]
Hi @Carousellhr ,

Is the [職缺連結](https://careers.carousell.com/job-posting/?gh_jid=3731901) expected to look blank?
<img width="1552" alt="Screenshot 2022-10-01 at 09 43 33" src="https://user-images.githubusercontent.com/3063067/193378265-f08e6aae-20ed-4e0f-9ec4-7c3b8c2501ab.png">

Thanks.

**Comment by Carousellhr** [comment]
Hi @sharils ! Thanks for the reminder, the link is not working as this role was closed already. I've marked this issue as closed. Thanks again 👍 :) !
