### ISSUE TITLE
【徵才】資深前端工程師 | Miso Technologies | 全遠距 | 年薪 100-150 萬

### ISSUE THREAD

**Issue by ddio-miso** [f2etw/jobs#997]
## 團隊簡介

Miso Technologies 是間在 2017 成立美國新創公司，專注提供易用、精準而且保護隱私的個人化搜尋與推薦服務，希望協助企業，使用和科技巨頭同等級的技術，為終端客戶提供更好的個人化服務。

我們的成員主要來自美國、台灣，所有人皆為遠距工作，工程與資料團隊則分散在台灣各地，透過各式協作工具以及兩週一次循環的軟體開發節奏，一起讓個人化引擎的管理與訓練，成為方便易用的網路服務。

歡迎認同以下文化的前端工程師，一起加入我們的行列：

1. 喜歡在新創的環境裡，一起創造符合公司文化的制度與流程
2. 理解遠距工作的優劣，除良好的自我管理之外，也能適時互相補位，降低遠距的溝通成本

## 職位說明

作為 Miso 的資深前端工程師，你將和創辦人、PM、設計師、後端、SRE、機器學習團隊一起，打造協助顧客使用核心服務的各式工具，包含：
- 核心服務管理界面： [Dojo](https://docs.miso.ai/dojo/overview)
- 官方文件站台： [docs.miso.ai](https://docs.miso.ai)
- 官方網站： [miso.ai](https://miso.ai)

在核心產品之外，因應不同的銷售方向，我們也將利用核心產品提供的服務，製作適用於不同領域的個人化服務範例網站，例如電商平台、內容平台。

## 工作內容

1. 與創辦人、PM、設計師共同釐清使用情境，並實做出實用的網頁界面
2. 與後端工程師、資料工程師共同找出滿足發佈時程的 API 設計，讓客戶順利使用 Miso 的服務
3. 維護風格一致且高品質程式碼，確保團隊工作效能以及降低維護成本

## 能力需求

1. UX/UI 的理解能力，能夠從 wireframe / mockup 裡，了解使用情境，並核對技術相關的設計細節
2. 熟悉 CSS ，能夠不用現成套件，製作好維護的 HTML 與 CSS 架構
3. 熟悉 Vue 相關解決方案
4. 熟悉 ES6
5. 基本的 API 設計能力，能夠從使用情境與設計文件中，找出需要新增或調整的 API 們
6. 熟悉 Git 與 Git workflow ，例如 Github flow 或 Gitlab flow
7. 基本的工程領域英語讀寫能力，能夠有效率地閱讀產品設計文件，以及和同事文字討論設計、工程事務
8. 樂於學習與分享新知，和 Miso 一起找出橫跨前後端、資料工程，以及各產業適合的個人化服務方案

### 加分

1. 具備遠距工作經驗，例如非同步溝通、理解不同協作工具的使用情境
3. 具備閱讀 Figma ，轉為可維護網頁的經驗
4. 具備 Nuxt 2 的開發經驗
5. 具備 Vue 2 相關的測試經驗，如 Jest、Vue Test Utils
6. 具備 pug / scss / [Tachyons](http://tachyons.io/) / [BEM](http://getbem.com/) 的使用經驗
7. 具備使用 [Bulma](https://bulma.io/) 以及客製化元件的經驗
8. 認同新創工作特性，即時滿足產品需求的同時，也能協助建立可持續發展的工作文化
9. 具備推薦系統、自然語言處理、機器學習等領域的基本知識
10. 基本的英語聽說能力，能夠和創辦人、PM、設計師以英語討論設計細節

## 薪資範圍

全職年薪 1,000,000 - 1,500,000，分別在每月中、每月底平均發放

## 工時/特休

1. 每年 10 天特休
5. 每年 3 天帶薪病假
6. 生理女性每月 1 天帶薪生理假

## 福利/推薦項

1. 運動補助每月 $2,100 
5. 遠距工作補助每月 $2,400
3. 健康檢查補助
4. 研討會門票補助

## 應徵流程

1. **填寫[此份表單](https://airtable.com/shrkCbEXcwxaGHBKA)**，我們會在一週內回覆是否進行進一步面試
2. **視訊面試**，在第一次的面試中，將由 Miso 的前端工程師負責，了解你的經驗、技能與工作習慣，是否達到我們的要求
3. **技術測驗**，在技術測驗中，我們將請你實做一個前端的功能，了解你的開發風格，以及對設計的理解程度。此測驗預計會花費你 4 ~ 8 小時的時間
4. **測驗回饋面談**，在通過測試後，Miso 的前端工程師將與你一起討論開發過程中的想法，以及是否有覺得可以改進的地方
5. **創辦人面談**，在通過 Miso 前端工程師的測試後，你將與 Miso 的創辦人面談，確認彼此都能接受對方的工作要求以及文化。在這階段面試結束後，我們會在兩週內通知最後面試結果。

## 聯絡方式

若有其他問題想詢問，請聯繫本次招募窗口 ddio （他也是日後和你一起工作的前端工程師），或在此留言，他會在一個工作日內回覆。

- 信箱： `ddio _at_ askmiso.com`
- 相關資訊： [LinkedIn](https://www.linkedin.com/in/kuan-chun-chuang/) / [Github](https://github.com/ddio/) / [Gitlab](https://gitlab.com/ddio.io)

**Comment by ddio-miso** [comment]
不確定標籤是否需要我這邊提供，以下是我覺得合適的標籤，再麻煩 @Rplus 斟酌，感謝！

- [F] Vue.js
- [F] Jest
- GIT
- Flexible working time
- senior
- Work Remotely
- Working Out Of The Office
- 年薪百萬
- 求才

**Comment by sharils** [comment]
Hi @ddio-miso - Are you hiring als backend developers? What's the job description if you are hiring? Thanks.

**Comment by ddio-miso** [comment]
@sharils , 

Thanks for asking, but the backend developer position is not opened for now.

**Comment by ddio-miso** [comment]
Close as this position has been filled.
